### ISSUE TITLE
Mouse click signals don't register 0.11.dev branch 

### ISSUE THREAD

**Issue by sharon92** [pyqtgraph/pyqtgraph#1001]
I am working on a PyQt5/Pyqtgraph based GUI. And I am using the 0.11 dev version of Pyqtgraph since it can create and update legends correctly. I have noticed that the mouse click signals stopped working correctly. It only updates when I zoom/pan the plot window.

`graphicsItem.scene().sigMouseClicked.connect(myfunction) `

**Comment by 2xB** [comment]
Hello @sharon92, I failed trying to reproduce this with an own minimal working example. Could you please quickly provide the information that is asked from the issue template (the default text you see when creating a new issue), including the example code? That massively helps tracking the error down. Thank you!

**Comment by 2xB** [comment]
For reference my testing:

### Tested code (does not reproduce)

```python3
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui

pg.mkQApp()

def myfunction():
  print("Hey")

win = pg.GraphicsLayoutWidget()
win.show()

graphicsItem = win.addViewBox()

graphicsItem.scene().sigMouseClicked.connect(myfunction)

if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()
```
### Tested environment

 * PyQtGraph version: `pyqtgraph/develop`, commit ad7453c
 * Qt Python binding: PyQt5 5.11.3 Qt 5.11.2
 * Python version: 3.6.8
 * NumPy version: 1.16.3
 * Operating system: Ubuntu 18.04 LTS
 * Installation method: pyqtgraph: from repository (no installation); dependencies: pip; python: system package

**Comment by sharon92** [comment]
@2xB So I tried it with a minimal example and it seems to be working fine. I will re-evaluate the source of this is in my main code later, perhaps its originating from other things being plotted in the script.

The issue I had was also on developer branch. I have a plot widget on which there is a plotted line, and I use a highlighter function which highlights or de-highlights the line when a mouse click signal is emitted on the plot window. And nothing would happen on mouse click, but when I zoom in or out, it would refresh and highlight with the right color. 

Meanwhile the following code works as expected.

```
from PyQt5 import QtGui, QtCore, QtWidgets
import pyqtgraph as pg
import sys

class MainW(QtGui.QMainWindow):
    
    def __init__(self):
        QtGui.QMainWindow.__init__(self)
        self.setMinimumSize(QtCore.QSize(640, 440))    
        
        view = pg.GraphicsLayoutWidget()
        self.setCentralWidget(view)
        
        self.graphics = view.addPlot()
        self.graphics.scene().sigMouseClicked.connect(self.highlight)
        self.color = 'b'
        self.ax = self.graphics.plot(x=[0,1],y=[0,1],pen=self.color)
        
    def highlight(self,evt):
        if self.color=='b':
            self.ax.setData(pen='y')
            self.color='y'
        else:
            self.ax.setData(pen='b')
            self.color='b'

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    mainWin = MainW()
    mainWin.show()
    sys.exit( app.exec_() )
```

Tested environment
PyQtGraph version: '0.11.0.dev0'
Qt Python binding: PyQt5 5.9.2
Python version: 3.6.7
Operating system: Windows 10
Installation method: pyqtgraph: from repository (no installation)
