### ISSUE TITLE
ParameterTree always reports default sizeHint instead of content dependent sizeHinte

### ISSUE THREAD

**Issue by Aikhjarto** [pyqtgraph/pyqtgraph#1006]
### Short description
I tried to resize a window to fit to a ParameterTree. However, the sizeHint() of the ParameterTree always reports the default of 256 x 192, regardless of its conentet.

### Code to reproduce
```python
from pyqtgraph.parametertree import Parameter, ParameterTree
from pyqtgraph import QtGui, QtCore
import sys

# new QtApp
app = QtGui.QApplication([])
    
t = ParameterTree()
print('sizeHint of empty ParameterTree', t.sizeHint()) #  PyQt5.QtCore.QSize(256, 192)

# add lengthy parameter
t.addParameters(Parameter(name='This is a very, very long name to make the Widget expand.',
                         value=0.0,
                         default=0.0))

print('sizeHint of ParameterTree', t.sizeHint()) #  PyQt5.QtCore.QSize(256, 192), but should be larger

# spawn a window
win = QtGui.QMainWindow()
win.setCentralWidget(t)
win.show() # still 256 x 192

if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
    QtGui.QApplication.instance().exec_()
```

### Expected behavior
The window spawned by the example should math the size of the ParameterTree, i.e. should receive a sizeHint() corresponding to the content of the ParameterTree.

### Real behavior
The windows spawned by the example is sized to a default/empty ParameterTree.

#### Windows test system
* PyQtGraph version: 0.11.0.dev0+g51b3201
* Qt Python binding: PyQt5 5.9.2 Qt 5.9.6
* NumPy version: 1.16.3 
* Python version:  3.7
* Operating system: Windows 7
* Installation method: develop branch from git via pip
#### Linux test system
* PyQtGraph version: 0.10.0
* Qt Python binding: PyQt5 5.13.0 Qt 5.13.0
* NumPy version: 1.17.0
* Python version: 3.6.5
* Operating system: openSUSE Leap 15.1
* Installation method: pip

**Comment by 2xB** [comment]
If this is a bug, it is a bug in PyQt5:
With the following code, you can reproduce the same effect without PyQtGraph.
```python3
from PyQt5 import QtWidgets, QtCore
import sys

# new QtApp
app = QtWidgets.QApplication([])
    
t = QtWidgets.QTreeWidget()
print('sizeHint of empty ParameterTree', t.sizeHint()) #  PyQt5.QtCore.QSize(256, 192)

# add lengthy parameter
item = QtWidgets.QTreeWidgetItem(['This is a very, very long name to make the Widget expand.',''])
root = t.invisibleRootItem()
root.addChild(item)

print('sizeHint of ParameterTree', t.sizeHint()) #  PyQt5.QtCore.QSize(256, 192), but should be larger

# spawn a window
win = QtWidgets.QMainWindow()
win.setCentralWidget(t)
win.show() # still 256 x 192

if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
    QtWidgets.QApplication.instance().exec_()
```
