### ISSUE TITLE
Export to matplotlib and csv fails

### ISSUE THREAD

**Issue by Axel-Jacobsen** [pyqtgraph/pyqtgraph#1007]
### Short description
Exporting a BarGraphItem in a pyqtgraph.plot() fails for the format above (but succeeds for the SVG, image formats).

### Code to reproduce

`xs` and `ys` are both `np.array`s.
```python
import pyqtgraph as pg
import numpy as np

win = pg.plot()
win.setWindowTitle('Booga Booga Booga')

vs = np.random.rand(10,)
xs = np.asarray([i for i in range(len(vs))])

width = self.bin_edges[1] - self.bin_edges[0]
bg = pg.BarGraphItem(x=xs, height=ys, width=width)
win.addItem(bg)
win.setXRange(xs[0], xs[-1], padding=0.05)
win.setYRange(np.amin(ys), np.amax(ys), padding=0.05)
```

### Expected behavior
Right-click on the plot, click export option, choose format and export.

### Real behavior
- When exporting to a MatPlotLib object, a matplotlib graph window opens with no content
- When exporting to a CSV, you get the error that occurs below:
```
Traceback (most recent call last):
  File "C:\Users\axel\Desktop\pyqtgraph\pyqtgraph\exporters\Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "C:\Users\axel\Desktop\pyqtgraph\pyqtgraph\exporters\CSVExporter.py", line 62, in export
    numRows = max([len(d[0]) for d in data])
ValueError: max() arg is an empty sequence
```

After poking around the CSVExporter.py file, `self.item.curves` the object is empty. I am not sure what is responsible for giving that object data, so that is as far as I got debugging.

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0
 * Qt Python binding: PyQt5 5.11.3 Qt 5.11.2
 * Python version: Python 3.7.4
 * NumPy version: 1.16.4
 * Operating system: Windows 10 Pro Verison 1803
 * Installation method: Initially Pip, then I forked the branch to investigate and had the same issues

### Additional context

Working on a larger set of graphing software. In this particular case, I am creating a histogram from a set of sample data. `vs` are the histogram counts (normalized or not), and `xs` are the bin edges. Both are calculated in an earlier step and saved in an object  

Thanks in advance!

EDIT 1: After fixing an import in the CSVExporter test (pyqtgraph\exporters\tests\test_csv.py), all the tests pass. My best guess is that the plot item is not properly being passed to the Exporter object on initialization. I would love some input from the developers!

EDIT 2: I believe that the issue (at least for the CSV export) is due to incorrectly adding the BarGraphItem to the pg.plot() object. This occurs in the [PlotItem.addItem(...) method](https://github.com/pyqtgraph/pyqtgraph/blob/ad7453c7818eddb3b18354c65370f416cb668b29/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L475-L523). Since a CSV export is occurring, we have to select the PlotItem part of the plot and export that (reinforced by [CSVExporter.py's lines 25, 26](https://github.com/pyqtgraph/pyqtgraph/blob/ad7453c7818eddb3b18354c65370f416cb668b29/pyqtgraph/exporters/CSVExporter.py#L25-L26)). [PlotItem.addItem(...)](https://github.com/pyqtgraph/pyqtgraph/blob/ad7453c7818eddb3b18354c65370f416cb668b29/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L475-L523) then checks the item that it is being passed for several attributes.

So, in the code example above, we create a PlotItem (`win = pg.plot()`) and then use the `win.addItem` method to add the BarGraphItem to the PlotItem. `win.addItem` fails to add `curves` to the PlotItem, and therefore, the export fails. This raises several questions:

1. Are we supposed to be able to export a BarGraphItem? I can not imagine a reason why this would be invalid. If it is invalid, then the `Export to CSV` option should be removed from the BarGraphItem's export menu. 

2. If we are supposed to be able to export a BarGraphItem, what other checks can be made so this doesn't occur?

EDIT 3: After implementing the missing methods in BarGraphItem, exporting to CSV works as expected. Exporting to images still does not work. I will implement these methods, and add them to a forked repository that I will link once I complete them. If there is a specific reason to not export to CSV, let me know. If you would like me to create a pull request, also let me know. I will close this issue for now.

**Comment by Axel-Jacobsen** [comment]
After fixing an import in the CSVExporter test (pyqtgraph\exporters\tests\test_csv.py), all the tests pass. My best guess is that the plot item is not properly being passed to the Exporter object on initialization. I would love some input from the developers!

**Comment by j9ac9k** [comment]
A pull request would definitely be appreciated. We're gearing up for a new release so I'm not sure how long it would take to get to reviewing it.

**Comment by Axel-Jacobsen** [comment]
@j9ac9k Dope! I'll open one sometime soon.

**Comment by Axel-Jacobsen** [comment]
@j9ac9k #1010 solves this issue as well as the image export
