### ISSUE TITLE
SciPy in requirements in README but not in install_requires

### ISSUE THREAD

**Issue by MikeFalowski** [pyqtgraph/pyqtgraph#1026]
Hey!
I'm wondering why SciPy is listed as a requirement in README but not in setup.py install_require argument.

Cheers,
Mike

**Comment by j9ac9k** [comment]
Hi Mike,

Thanks for opening the issue.  The scipy requirement is not a hard requirement, it's only used by some portions of the library, specifically image related component.  I agree we can be more explicit about that in `README.md`, but I'm not of the mindset of changing `setup.py` to reflect this, as there are other dependencies of pyqtgraph that are not covered in `setup.py` (specifically the Qt bindings of your choice).

If you would like to submit a pull request modifying `README.md` to reflect where `scipy` is used, we would be thankful!

Thanks!

**Comment by ksunden** [comment]
`setup.py` includes the ability to have optional dependencies (most often used for dev dependencies, but perhaps we wish to add a way of specifying what scipy enables within pyqtgraph)

**Comment by j9ac9k** [comment]
We could certainly include `extras_require` field; suppose `pyopengl` would go there as well.

We would need to come up w/ names for these extras that make sense.

**Comment by MikeFalowski** [comment]
Thanks for explanation!
Now I'm not sure if the pull request is still actual as I don't know what is the conclusion.
