### ISSUE TITLE
Suggestion: datetime axis support, like in matplotlib

### ISSUE THREAD

**Issue by kangalioo** [pyqtgraph/pyqtgraph#1032]
Hi,
I'm currently in the process of shifting my application to PyQtGraph because of performance. First off: PyQtGraph seems great! Really fast and straightforward to use. Coming from matplotlib, I've noticed that there's unfortunately no built-in support for datetime axes.

While it's not hard to implement a basic custom AxisItem implementation yourself, making it work as seamlessly as in matplotlib is hard. For example, matplotlib automatically adjusts the datetime detail depending on zoom level: when zoomed out you only get year and month on the axis, when zoomed far in you see year, month, day, hour and minute.

Also, matplotlib ensures that there are no irregular gaps on the axis. Example screenshot of that happening with my custom implementation:

![Example screenshot](https://user-images.githubusercontent.com/21220820/64198054-ce62d080-ce87-11e9-998c-5866eda02927.png)

It would be great if PyQtGraph had an implementation like matplotlib's one out of the box, because datetime-based plotting is relatively common I think. A robust implementation of it is not that easy to code up quickly, so it would be nice not having to worry about it.

**Comment by j9ac9k** [comment]
Thanks for the feature request.

I agree with you this would be a great addition to the library.  I'm not sure who will get to it when, we would gladly review any kind of pull request that incorporates this.

**Comment by ixjlyons** [comment]
There's the [customPlot example](https://github.com/pyqtgraph/pyqtgraph/blob/develop/examples/customPlot.py), but it has similar issues. If you know you want ticks to be in increments of 1 day, you can set the tick spacing:

```python
import time
import numpy as np
import pyqtgraph as pg

app = pg.mkQApp()

sec_per_day = 3600*24

class DateAxisItem(pg.AxisItem):
    def tickStrings(self, values, scale, spacing):
        return [time.strftime('%Y-%m-%d', time.localtime(x)) for x in values]

axitem = DateAxisItem(orientation='bottom')
axitem.setTickSpacing(major=sec_per_day, minor=sec_per_day/4)

pw = pg.PlotWidget(axisItems={'bottom': axitem})

x = np.arange(7) * sec_per_day
y = np.array([0.1, 0.2, -0.5, 0.8, -0.1, 0.7, 0.3])
pw.plot(x=x, y=y, symbol='o')

pw.show()
app.exec_()
```

A more robust solution would require overriding `tickValues` so the spacing is always some multiple of the number of seconds in the relevant unit of time (years, days, minutes, etc.) and more sophisticated handling of the string representation of the day/time based on the tick spacing (the customPlot example is a start).

I agree that it'd be cool to be able to just hand pyqtgraph some form of timestamp and automatically get date/time tick strings that just work with any range, zoom level, etc.

**Comment by 2xB** [comment]
There is a pull request for exactly this issue, namely PR #74.

**Comment by j9ac9k** [comment]
Nice find, should we add that PR to the 0.11 milestone?

**Comment by 2xB** [comment]
Okay, done!

**Comment by axil** [comment]
This has been implemented now, see https://github.com/pyqtgraph/pyqtgraph/pull/1154

**Comment by 2xB** [comment]
The corresponding PR #1154 is now merged to `develop` and will be part of the next version, `0.11.0`!
