### ISSUE TITLE
 pyqtgraph/examples/VideoSpeedTest.py type float has missing variable mx

### ISSUE THREAD

**Issue by wagenrace** [pyqtgraph/pyqtgraph#1038]
## Short description 
Running  pyqtgraph/examples/VideoSpeedTest.py and setting data type to float crashes the GUI for missing variable "mx"

### Tested environment(s)

 * PyQtGraph version: 0.10.0

**Comment by ixjlyons** [comment]
This was actually just fixed with #356, though I don't think there was ever an issue pointing out the bug. Thanks for reporting.

**Comment by j9ac9k** [comment]
@wagenrace just to follow up, a way to install the current `develop` branch is to run the following command:

`pip install git+https://github.com/pyqtgraph/pyqtgraph@develop`
