### ISSUE TITLE
exportDialog looses the exporter parameters

### ISSUE THREAD

**Issue by jkotan** [pyqtgraph/pyqtgraph#1047]
### Short description
The `exportDialog` widget looses the exporter parameters. 
It is quite annoying. 

### Expected behavior
I provide PR  #1023 with which `exportDialog` keeps the exporter parameters in a dictionary.

### Real behavior
Already set parameters disapprear.

### Tested environment(s)

 * PyQtGraph version:  '0.10.0'
 * Qt Python binding: 'PyQt4 4.11.4 Qt 4.8.7'
 * Python version: '3.5.3'
 * NumPy version: '1.12.1'
 * Operating system: debian9
 * Installation method: system packages

**Comment by j9ac9k** [comment]
#1023 was merged, thanks for the issue and following PR!
