### ISSUE TITLE
Bug Exporting ScatterPlotItem

### ISSUE THREAD

**Issue by JohnLunzer** [pyqtgraph/pyqtgraph#105]
ScatterPlotItem are not in the correct location when exporting using the export tool or export API.

I don't believe this bug is represented in other bug reports.

See this post for more details: https://groups.google.com/forum/?fromgroups#!topic/pyqtgraph/n-Ho-h5FYfM

**Comment by bergerspencer** [comment]
I just want to comment that I see this in 0.9.10 but not in 0.9.8. It definitely depends on the output size, it only displaces slightly when exported at the original size but if I absurdly expand the output size the scatter plot is much smaller than it should be and is displaced very far from where it should be. If you need details feel free to contact me.

**Comment by j9ac9k** [comment]
Fixed with #88 being merged
