### ISSUE TITLE
Flowchart context menu shows redundant submenu.

### ISSUE THREAD

**Issue by wuyuanyi135** [pyqtgraph/pyqtgraph#1059]
### Short description

The flowchart widget's context menu shows some useless submenu. It is caused by 
https://github.com/pyqtgraph/pyqtgraph/blob/ed6586c7ddd3ad95eadd40cb8fda7c4c1d4c746b/pyqtgraph/flowchart/Flowchart.py#L837-L838

![image](https://user-images.githubusercontent.com/11760870/67123142-74ab3100-f1bd-11e9-8d09-911a758b40c5.png)

### Expected behavior

The submenus should not be created.

### Real behavior

The submenu is not created. Only the actions should show.

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0+g4b8f56b
 * Qt Python binding: PySide2 5.13.1 Qt 5.13.1
 * Python version: 3.7
 * NumPy version: 1.17.1
 * Operating system: 
 * Installation method: pip install git+https://github.com/pyqtgraph/pyqtgraph

**Comment by isgursoy** [comment]
"Add Node" option is doubled everytime after I click "Options" custom action.
Action added in this way:
```
 class NodeAppearance(NodeGraphicsItem):
            def __init__(this, node):
                super(CustomWidget.AugmenterDiagram.NodeAppearance, this).__init__(node=node)
                this.minPixmap = QPixmap()
                this.maxPixmap = QPixmap()
                this.minPixmapPlace = QRect()
                this.nameItem.setTextInteractionFlags(Qt.NoTextInteraction)
                this.getMenu().addAction("Options", this.node.optionsWanted)
                this.setupDrawing()
```
![bug](https://user-images.githubusercontent.com/2170245/67627054-af683580-f85d-11e9-8717-d3ad491eb043.png)
