### ISSUE TITLE
PlotWidget squashed

### ISSUE THREAD

**Issue by p4r4noj4** [pyqtgraph/pyqtgraph#106]
I just came upon a problem, which was reported on StackOverflow as well, but apparently it was not posted as an issue here. I am using MacBook Pro with Retina display (running os X) and I have problem with all plots (e.g. the example ones) are very small in top-right corner. In addition they are not resizing when I am resizing window (but I am not sure if PlotWidget should resize what's inside automatically or not).

Anyway, link to related StackOverflow topic with screenshots: http://stackoverflow.com/questions/25520108/pyqtgraph-with-pyside-producing-tiny-squashed-graphs-including-the-example-cod

**Comment by j9ac9k** [comment]
Following up on an ancient issue, I feel confident in saying this has been addressed at this point (and this specific issue was likely addressed long ago).  Qt's support for hidpi monitors has gotten better in recent versions.  Sorry it's taken so long to follow up!
