### ISSUE TITLE
AttributeError: module 'pyqtgraph.widgets' has no attribute 'RemoteGraphicsView'

### ISSUE THREAD

**Issue by rwalroth** [pyqtgraph/pyqtgraph#1061]
### Short description

Trying to use RemoteGraphicsView throws an error, says there is no RemoteGraphicsView module
### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np

view = pg.widgets.RemoteGraphicsView()
```

### Expected behavior

Create a RemoteGraphicsView object
### Real behavior

```
>>> view = pg.widgets.RemoteGraphicsView()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyqtgraph.widgets' has no attribute 'RemoteGraphicsView'
```

### Tested environment(s)

 * PyQtGraph version: 0.10.0
 * Qt Python binding: PyQt5
 * Python version: 3.7.4
 * NumPy version: 1.16.4 
 * Operating system: Windows 10
 * Installation method: pip

### Additional context
If I look in the site-packages folder for pyqtgraph, I can see the RemoteGraphicsView file in the widgets folder, and other widgets load normally

**Comment by ixjlyons** [comment]
You should be able to import it with `from pyqtgraph.widgets.RemoteGraphicsView import RemoteGraphicsView`. We could implement some imports in `widgets/__init__.py` to make this a bit less of a hassle -- maybe that should be a separate issue.

**Comment by rwalroth** [comment]
That works! I would vote for implementing this into the __init__.py to make it more consistent with other widgets, but closing this now.

**Comment by j9ac9k** [comment]
Going to re-open so we remember to submit a PR for this fix.

**Comment by j9ac9k** [comment]
Looking at `widgets/__init__.py` I saw some commented out code

```
#importAll('widgets', globals(), locals(),
          #excludes=['MatplotlibWidget', 'RawImageWidget', 'RemoteGraphicsView'])
```

Looks like there was some intention to not have this guy be included right off the bat.

I'll make a PR with the change and see if anything breaks.
