### ISSUE TITLE
Plotting an array with bool or numpy.bool_ fails with TypeError: numpy boolean subtract deprecated in ViewBox

### ISSUE THREAD

**Issue by UsYer** [pyqtgraph/pyqtgraph#1070]
### Short description
Plotting an array containing bool or numpy._bool_ fails with a TypeError in ViewBox.
This relates to #692 which was falsely marked as fixed even though the related PR did not fix this issue.

### Code to reproduce
```python
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import pyqtgraph as pg

app = QtGui.QApplication([])

win = pg.GraphicsLayoutWidget(show=True, title="Basic plotting examples")
win.resize(1000,600)
win.setWindowTitle('pyqtgraph example: Plotting')

p1 = win.addPlot(title="Basic array plotting", y=np.random.normal(size=100))

p1.plot([bool(var) for var in range(0, 20)], pen=(255,0,0), name="Red curve")


## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()

```

### Expected behavior
The array should be plotted as zeros and ones

### Real behavior
Exception:
```
  File "PlottingBoolBug.py", line 23, in <module>
    p1.plot([np.bool_(var) for var in range(0, 20)], pen=(255,0,0), name="Red curve")
  File "C:\develop\gitRepos\livetrace\third_party\pyqtgraph\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 608, in plot
    self.addItem(item, params=params)
  File "C:\develop\gitRepos\livetrace\third_party\pyqtgraph\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 485, in addItem
    self.vb.addItem(item, *args, **vbargs)
  File "C:\develop\gitRepos\livetrace\third_party\pyqtgraph\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 410, in addItem
    self.updateAutoRange()
  File "C:\develop\gitRepos\livetrace\third_party\pyqtgraph\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 862, in updateAutoRange
    childRange = self.childrenBounds(frac=fractionVisible)
  File "C:\develop\gitRepos\livetrace\third_party\pyqtgraph\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 1355, in childrenBounds
    bounds = QtCore.QRectF(xr[0], yr[0], xr[1]-xr[0], yr[1]-yr[0])
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0, commit: 6848824
 * Qt Python binding: PySide2 5.12.3 Qt 5.12.3
 * Python version: 
 * NumPy version: 1.15.3
 * Operating system: Windows 10 1709
 * Installation method: clone from github repo

**Comment by ixjlyons** [comment]
[The docs](http://pyqtgraph.org/documentation/graphicsItems/plotdataitem.html#pyqtgraph.PlotDataItem.__init__) actually specify x/y are expected to be numeric:

> x and y values may be any sequence (including ndarray) of real numbers

But I can see how upgrading numpy causing an application to break isn't great. I suppose we can explicitly cast bool input data to int in `PlotDataItem.setData`.

**Comment by j9ac9k** [comment]
I just tested this with 0.13.1, and this plot was rendered without error

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/646398/193376828-5bb0f91a-e2cd-407e-a8fd-ab9ca2e097b7.png">
