### ISSUE TITLE
how to add a ray to viewbox

### ISSUE THREAD

**Issue by AndyYangjd** [pyqtgraph/pyqtgraph#1084]
Hi,
How can a add a ray to viewbox except using QGraphicsLineItem.
I can only  find any option in InfiniteLine.

Thanks for your amazing module.

**Comment by j9ac9k** [comment]
The relativity example uses `QGraphicsLineItem`, you can see it being added here: https://github.com/pyqtgraph/pyqtgraph/blob/3d3d0a24590a59097b6906d34b7a43d54305368d/examples/relativity/relativity.py#L676-L703

**Comment by AndyYangjd** [comment]
ok， thank u.
