### ISSUE TITLE
Symbols scale with window aspect ratio if `pxMode==False`

### ISSUE THREAD

**Issue by paulmueller** [pyqtgraph/pyqtgraph#1086]
When exporting a ScatterPlotItem with `pxMode=False`, the scatter symbols are scaled with the window's aspect ratio.

### Code to reproduce
```python
import pyqtgraph as pg
import numpy as np
from pyqtgraph.exporters.ImageExporter import ImageExporter
from PyQt5 import QtGui

if __name__ == '__main__':
    app = QtGui.QApplication([])
    win = pg.GraphicsWindow("title SVG Exporter bug")
    win.resize(1000, 600)
    p1 = win.addPlot()
    p1.plot(x=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], y=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    scatter = pg.ScatterPlotItem(pen=(200, 200, 200),
                                 symbolBrush=(255, 0, 0),
                                 symbolPen='w',
                                 size=1,
                                 pxMode=False,
                                 )
    p1.addItem(scatter)
    scatter.setData(np.arange(10), np.arange(10))

    QtGui.QApplication.processEvents()
    QtGui.QApplication.processEvents()

    pngexp = ImageExporter(p1)
    pngexp.export("test4.png")
```

### Expected behavior
The symbols should not be stretched.

### Real behavior
![test4](https://user-images.githubusercontent.com/2853022/69549791-36faae80-0f9a-11ea-8796-de2ff64b0071.png)

### Tested environment(s)
 * PyQtGraph version: develop (19c9e5460c4e04a6f31e0c2d7fd7e39dcc0e062c)
 * Qt Python binding: 'PyQt5 5.12.3 Qt 5.12.4'
 * Python version:  3.6.8
 * NumPy version: 1.16.4
 * Operating system: Ubuntu 18.04.3
 * Installation method: pip+git

**Comment by lidstrom83** [comment]
I don't think this is a bug. The purpose of `pxMode` is to allow the spots to ignore the `ViewBox` transformation. By setting it to `False`, you're explicitly saying that you want the behaviour you've described here. To get the behaviour you desire, you'd set it to `True` and choose a desirable `size` in pixels.

**Comment by paulmueller** [comment]
I see. The documentation at https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/scatterplotitem.html?highlight=scatterplot#pyqtgraph.ScatterPlotItem says:
`If True, spots are always the same size regardless of scaling, and size is given in px. Otherwise, size is in scene coordinates and the spots scale with the view. Default is True`

I don't remember why I stumbled across this. Maybe it's because I just didn't see any use-case for this behavior...

Thanks!
