### ISSUE TITLE
makeARGB  does not work with float RGB images anymore 

### ISSUE THREAD

**Issue by jkotan** [pyqtgraph/pyqtgraph#1099]
### Short description

After #406, which introduces nice floating-point masking, `ImageItem.paint()` crashes with  float RGB images. I fixes it by PR #1098

### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np

img = np.ones(shape=[3,3,3], dtype='float')
img[0,0,0] = np.nan
pg.makeARGB(img, levels=[0,3])
```

### Expected behavior

for float RGB images  makeARGB does not create mask or creates it according to NAN values.

### Real behavior
`ImageItem.paint()` crashes with  float RGB images

```Traceback (most recent call last):
  File "/home/jkotan/ndts/lavue/lavuelib/imageDisplayWidget.py", line 64, in paint
    _pg.ImageItem.paint(self, p, *args)
  File "/home/jkotan/testinst/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 439, in paint
    self.render()
  File "/home/jkotan/testinst/lib/python2.7/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 431, in render
    argb, alpha = fn.makeARGB(image, lut=lut, levels=levels)
  File "/home/jkotan/testinst/lib/python2.7/site-packages/pyqtgraph/functions.py", line 1186, in makeARGB
    imgData[nanMask, 3] = 0
IndexError: too many indices for array
```

### Tested environment(s)

 * PyQtGraph version: 0.11.rc0
 * Qt Python binding: PyQt5
 * Python version:  python2.7
 * NumPy version: 1.12
 * Operating system: debian stretch
 * Installation method:  system packages and git

**Comment by j9ac9k** [comment]
I think this may have been fixed as part of #1131 ...will verify

**Comment by ixjlyons** [comment]
#1098 will fix it

**Comment by ixjlyons** [comment]
#1152
