### ISSUE TITLE
pyqtgraph.Qt.loadUiType broken for PySide2 >= 5.14

### ISSUE THREAD

**Issue by ixjlyons** [pyqtgraph/pyqtgraph#1102]
https://dev.azure.com/pyqtgraph/pyqtgraph/_build/results?buildId=557&view=logs&j=1d023af0-a188-58ef-16b4-2e987dd32dd1&t=addebc46-66b7-583c-f559-d6f453020f3e&l=308

There's a note here, though I'm not sure what it means precisely: https://wiki.qt.io/Qt_for_Python_Development_Notes#24._October_2019

Location of the issue for reference: https://github.com/pyqtgraph/pyqtgraph/blob/6e9a48558c010803883f0f83a7170581098b978a/pyqtgraph/Qt.py#L91

**Comment by j9ac9k** [comment]
I'll take a look later this evening to see what the qtpy library does.

**Comment by j9ac9k** [comment]
Here is the relevant bit on qtpy's repo:

https://github.com/spyder-ide/qtpy/blob/d53db43e11200ee9324f399504c8a97d2432658c/qtpy/uic.py

I've been wondering if we should consider migrating qtpy as a dependency (and migrate some of the specific Qt.py content to pyqtgraph into the the qtpy library.

**Comment by j9ac9k** [comment]
After talking w/ @campagnola the two suggested ways to fix this is 

* precompile the exampler loader .ui file for pyside2
* raise a useful error message when attemping to use loadUiType on pyside2 5.14+

**Comment by j9ac9k** [comment]
Looks like this was "fixed" upstream: https://bugreports.qt.io/browse/PYSIDE-1223

Versions of PySide2 5.14.2.2 and 5.15.0 have restored this functionality and our example app is able to run w/o issue now.  Huge thank you to @cmaureir for getting this feature re-implemented in the PySide2 library!

**Comment by cmaureir** [comment]
My pleasure! let me know if we can provide other functions to help pyqtgraph :)

**Comment by j9ac9k** [comment]
@cmaureir only other upstream issue we've identified with certainty is #1095 reported as QTBUG-80937 (I know this isn't a PySide specific issue) ...We'll be sure to reach out if we identify anything else!

**Comment by j9ac9k** [comment]
Pre-maturely closed the issue, should have waited until we got the PR merged :|
