### ISSUE TITLE
development version on conda

### ISSUE THREAD

**Issue by half-adder** [pyqtgraph/pyqtgraph#1107]
### Short description
I am using conda to manage the dependencies for my project, but require features from the develop branch of this project. Is it possible to have a development version on conda-forge or something? Sorry I'm not super familiar with packaging and how hard this would be.

Thanks!

**Comment by j9ac9k** [comment]
Hi @half-adder  I'm not sure what all is entailed in getting the package on conda-forge, but I see little benefit at this point, as to install a Qt of 5.12+ (which is what we recommend) you have to use `pip` as it stands as `conda` does not distribute newer versions of Qt for reasons that are complex.

Can you elaborate on how having pyqtgraph installable via conda be beneficial for you?

**Comment by half-adder** [comment]
Thanks for the quick response. I'm developing a scientific application for members of my lab who are not technically literate. 

To that end, I had hoped to distribute a single conda environment specification file which they can use. Right now I have docs that instruct installing packages with conda, then pyqtgraph-develop with pip. Every extra step is something that might go wrong with people who are not comfortable with terminals, so having the develop in conda would make the installation process more robust.

It is not dire, though, and as I said I'm not sure what is entailed with getting the development branch up and separate either. So if it's too much work don't worry about it. Just thought I'd ask!

As an aside, is there a release schedule planned for master releases? Or do you know when develop will be merged?

The only reason I'm using develop is #1016

**Comment by j9ac9k** [comment]
I too have end users of various technical abilities and can completely appreciate the desire to remove any unnecessary steps from a setup process.

You'll be happy to know we have v0.11-rc0 on pypi (which has the fix you referenced), so you should be able to specify that version explicitly in your `environment.yml` file:

https://pypi.org/project/pyqtgraph/#history

**Comment by ksunden** [comment]
It's not that hard to get a package on conda-forge, I maintain a few of my other packages on there (though I was not the one to originally submit them).

Mixing conda and pip can lead to unintended side effects (mostly by trying to re-install dependencies), though it _can_ work, it is not generally recommended (that said, I've certainly found myself doing it). 
I only personally use conda on Windows (as installing binary dependencies without a package manager is a nightmare, and conda handles what I need). In particular Qt was one of the more important binary dependencies I needed for my python programs.

I believe the decision to make it a final release is largely down to reviewing over open issues/PRs and seeing if any of them are important enough to hold up release.  [This Milestone](https://github.com/pyqtgraph/pyqtgraph/milestone/3) is a list we thought at one point should be done before final release, though it is subject to change.

**Comment by ksunden** [comment]
I looked again, and there already is a feedstock for conda-forge, submitted a PR to provide 0.11.0rc0, though I do not have merge rights on the feedstock, so dependent on one of the current maintainers

**Comment by j9ac9k** [comment]
Also looks like `environment.yml` supports pip installed packages from github:  https://berkeley-stat159-f17.github.io/stat159-f17/lectures/06-conda-pip-environments..html

```
name: example-environment

dependencies:
  - python==3.4
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - pip:
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
    - jupyterlab
```

you can likely put under the `pip` section

```
pip:
  - pyqtgraph==0.11.0rc0
```

or 

```
pip:
  - git+https://github.com/pyqtgraph/pyqtgraph.git@develop
```

**Comment by half-adder** [comment]
This is all very helpful. Thank you!

**Comment by j9ac9k** [comment]
@ksunden you're going to have to mix conda and pip sooner or later if you're using pyqtgraph and use conda at any other point; as conda won't be distributing qt 5.12+ versions of pyqt for some time ... which means you'll have to get them via pip...

**Comment by ksunden** [comment]
@j9ac9k https://anaconda.org/conda-forge/qt

Conda forge has Qt (and pyqt) 5.12, may not be in the default repo, but conda forge is very commonly added

**Comment by j9ac9k** [comment]
huh! that's new!  Last I was reading they needed to compile Qt from source with some older compiler that Qt didn't support...didn't look like it was going to get solved anytime soon...

**Comment by ksunden** [comment]
Conda forge may have/allow a newer compiler than anaconda/main (the default repo)

**Comment by marcelotrevisani** [comment]
conda-forge has ``qt`` ``5.12.5`` , so that is completely fine
and pyqt is using that ``qt`` on ``conda-forge`` channel

**Comment by ksunden** [comment]
@half-adder `pyqtgraph` `0.11.0rc0` has been released on `conda-forge`

As it is a pre release build, I believe you have to specify the version number, as it will default to the latest stable release.

```
conda install -c conda-forge pyqtgraph=0.11.0rc0
```

**Comment by j9ac9k** [comment]
@ksunden did you do the release? if so, thank you!!!! if not, and you know who did, pass along my thanks (or link me to the PR, and I'll comment there myself)

**Comment by ksunden** [comment]
I did make the PR https://github.com/conda-forge/pyqtgraph-feedstock/pull/13
@marcelotrevisani Merged it.

I am now on the maintainers list for the feedstock, and can do future releases as we push them to PyPI (there is also a bot that does automatic updates to packages, which just require pressing the big green merge button most of the time, but does not automatically do pre-release, it seems)
