### ISSUE TITLE
Suggestion: Export TableWidgetItem along with TableWidget

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#1115]
pg's `TableWidget` is great for my use case. However, it would be nice to override some default behaviors of the `TableWidgetItem`, such as minor characteristics during the `edit` role. This is difficult as-is, since `TableWidgetItem` is not exported and therefore can't be subclassed.

**Comment by ixjlyons** [comment]
I don't see a reason it shouldn't available in the `pyqtgraph` namespace. Note that it is possible to import though:

```python
from pyqtgraph.widgets.TableWidget import TableWidgetItem
```

**Comment by ntjess** [comment]
You're right. When I used this module, I thought __all__ specified importable objects, not just wildcard imports. I know more now 🙂

**Comment by SohamMane19** [comment]
Is this issue still open or closed? @ixjlyons

**Comment by ntjess** [comment]
Probably OK to close since as ixjlyons pointed out it is still possible to do what the issue requests. If someone desires in the future, they are welcome to submit a PR to update `__all__`.

**Comment by ntjess** [comment]
If you'd like to make a contribution, I'd be happy to review it! This is a good first issue.

You can create a fork of the repository, change that line of code, and submit a new pull request if you wish

**Comment by SohamMane19** [comment]
That would be great, thank you!
I'll try it tomorrow itself 👍
