### ISSUE TITLE
How to use BarGraphItem in a GraphicsLayout

### ISSUE THREAD

**Issue by ValeKnappich** [pyqtgraph/pyqtgraph#1129]
I got a GraphicsView with a GraphicsLayout as central item like
```
graphics_view = pg.GraphicsView()
layout = pg.GraphicsLayout(border=(100, 100, 100))
graphics_view.setCentralItem(layout)
```
I currently have 2 plots in the layout. To add them to the layout I used ```layout.addPlot()```. Now I want to change one of them to a bar chart. 
Apparently the ```layout.addItem``` method does not accept a BarGraphItem since it is not an instance of ```QGraphicsWidget```. 

So how can I create a window containing a line graph and a bar graph?

**Comment by liangshanbovsluomio** [comment]
`            self.frame = QFrame(self)
            self.frame.resize(300, 300)
            self.frame.move(10, 200)
            self.frame.setFrameShape(6)
            self.frame.setFrameShadow(QFrame.Plain)
            self.frame.setStyleSheet("background-color:rgb(0,255,255);")
            verticalLayout = QVBoxLayout(self.frame)
            p = pg.plot()
            verticalLayout.addWidget(p)`
try it

**Comment by ValeKnappich** [comment]
I don't see how that is supposed to answer the question. My Question is about BarGraphItem ...

**Comment by ixjlyons** [comment]
One way to do it would be to add an empty `PlotItem` to the layout then add the `BarGraphItem` to that:

```python
import pyqtgraph as pg

app = pg.mkQApp()

graphics_view = pg.GraphicsView()
layout = pg.GraphicsLayout(border=(100, 100, 100))
graphics_view.setCentralItem(layout)

p1 = layout.addPlot(x=[0, 1, 2], y=[1, 2, 3])

p2 = layout.addPlot()
p2.addItem(pg.BarGraphItem(x=[0, 1, 2], height=[1, 2, 3], width=0.1))

graphics_view.show()
app.exec_()
```

It's definitely not obvious based on the way things are named. Suggestions for clarifying the docs welcome, though `BarGraphItem` isn't currently in the docs at all (#686) :sweat_smile:

**Comment by ixjlyons** [comment]
Going to close this . Feel free to re-open if you're still having issues with BarGraphItem.
