### ISSUE TITLE
Pyqtgraph `pg.viewbox` renders ` widgets`  poorly -- Font blur?

### ISSUE THREAD

**Issue by 625781186** [pyqtgraph/pyqtgraph#1132]
### Tested environment(s)
- PyQtGraph version: '0.10.0'
- Qt Python binding: 'PyQt5 5.14.1 Qt 5.14.1'
- Python version: 3.6
- Installation method: pip
### Question
```python
        ## ------------------------------
        self.win = pg.GraphicsView()

        vb = pg.ViewBox()
        vb.invertY()

        frame = QWidget()
        layout = QHBoxLayout(frame)
        web = E5EngineView(self)
        web.page().load(QUrl("http://www.baidu.com"))
        layout.addWidget(web)
        self.frame = frame
        frame.setFixedSize(600,800)

        prox = QGraphicsProxyWidget()
        prox.setWidget(frame)
        prox.setPos(100, 0)
        vb.addItem(prox)
        
        # self.win.setCentralWidget(prox)
        # self.win.setCentralItem(vb)
```
-  If I use `self.win.setCentralWidget(prox)`  , the font is normal , but item can't be move: 

![image](https://user-images.githubusercontent.com/30521429/75628635-f607db00-5c15-11ea-89d7-9b08626c4caa.png)

- But if I use `self.win.setCentralItem(vb)` , the font is blur : 

![image](https://user-images.githubusercontent.com/30521429/75628636-f7390800-5c15-11ea-9e93-d5a6b404d957.png)

Is that right?

@campagnola 
@ixjlyons

**Comment by ixjlyons** [comment]
Notice if you zoom on one axis only (e.g. hold right click and move right) or resize the window, the aspect ratio of the item will change. Setting `lockAspect` for the `ViewBox` might be helpful, e.g. `vb = pg.ViewBox(lockAspect=True)`.
