### ISSUE TITLE
pyqt5 can not use pyqtgraph

### ISSUE THREAD

**Issue by Hung-Hsiang-617** [pyqtgraph/pyqtgraph#1137]
### Code to reproduce
import pyqtgraph.examples
pyqtgraph.examples.run()

Traceback (most recent call last):
  File "C:/Users/vision/Desktop/patient/pyqtgraph.py", line 2, in <module>
    import pyqtgraph.examples
  File "C:\Users\vision\Desktop\patient\pyqtgraph.py", line 2, in <module>
    import pyqtgraph.examples
ModuleNotFoundError: No module named 'pyqtgraph.examples'; 'pyqtgraph' is not a package

### Tested environment(s)

 * PyQtGraph version:0.10.0
 * Qt Python binding: PyQt5 5.11.2
                                   PyQt5-sip 4.19.19
                                   PyQt5-tools 5.13.0.1.5
 * Python version: anaconda python 3.7.4
 * NumPy version: 1.17.4
 * Operating system: Win10
 * Installation method: pip install pyqtgraph

**Comment by ixjlyons** [comment]
Try renaming your script to something other than `pyqtgraph.py`. That should fix the problem.

**Comment by j9ac9k** [comment]
I'm going to close out this issue (I've also fallen victim to this) @Hung-Hsiang-617 if you're still having problems after renaming your script, post here and I'll re-open.
