### ISSUE TITLE
Plots after event loop has started does not update axes immediately

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#1144]
### Short description

When plotting data after the event loop has started, the axes are not updated immediately.

Results of git bisection:
d77ad273c71870881c3fda3d2b49d3488f100425 is the first bad commit
commit d77ad273c71870881c3fda3d2b49d3488f100425
Author: 2xB <31772910+2xB@users.noreply.github.com>
Date:   Sat Aug 17 20:52:45 2019 +0200

### Code to reproduce

```python
import pyqtgraph

QtCore = pyqtgraph.Qt.QtCore
app = pyqtgraph.mkQApp()

plotwgt = pyqtgraph.PlotWidget()
curve = pyqtgraph.PlotCurveItem()
plotwgt.addItem(curve)

def draw_later():
    curve.setData(list(range(100)))
        
timer = QtCore.QTimer.singleShot(0, draw_later)
plotwgt.show()
app.exec_()
```

### Expected behavior

![plot_good](https://user-images.githubusercontent.com/2657027/77027654-d15f8180-69d1-11ea-80a6-c0889f1b930b.PNG)

### Real behavior

![plot_bad](https://user-images.githubusercontent.com/2657027/77027662-d58b9f00-69d1-11ea-857d-72fd4a78fabf.PNG)

### Tested environment(s)

 * PyQtGraph version: 0.11.0rc0
 * Qt Python binding: PyQt5 5.9.2 Qt 5.9.6
 * Python version: Python 3.7.6
 * NumPy version: 1.18.1
 * Operating system: Windows 10 64-bits
 * Installation method: extract to local directory

**Comment by ixjlyons** [comment]
Thanks for reporting. I'm thinking this is something we should fix for next release. @2xB any insight would be appreciated.

**Comment by 2xB** [comment]
@pijyoi Can you please check whether the Pull Request #1159 fixes the issue?

**Comment by pijyoi** [comment]
@2xB Yes, it fixes the minimal example above as well as a slightly less minimal example. Thank you.
