### ISSUE TITLE
ErrorBarItem does not plot for values smaller than 1e-12

### ISSUE THREAD

**Issue by jaxankey** [pyqtgraph/pyqtgraph#1149]
### Short description
When I try to plot with error bars having values smaller than 1e-12, they do not show up. No error or warning.

### Code to reproduce
```python
import pyqtgraph, numpy

ey = numpy.array([2e-12, 1.1e-12, 1e-12, 0.9e-12])
p = pyqtgraph.plot()
p.addItem(pyqtgraph.ErrorBarItem(x=[0,1,2,3], y=[0,0,0,0], top=ey))
```

### Expected behavior
We should see 4 bars of diminishing height.

### Real behavior
We see only the first two.

### Tested environment(s)

 * PyQtGraph version: 0.10.0
 * Qt Python binding: PyQt5 5.9.2 Qt 5.9.6
 * Python version: 3.7
 * NumPy version: 1.15.4
 * Operating system: Linux Mint 19
 * Installation method: conda

### Additional note
PlotCurveItems appear with crazy small values, well below 1e-12, but their error bars don't. This confused me for a long time!

Thanks in advance, and sorry if this issue is fixed in 0.11 already.

**Comment by ixjlyons** [comment]
Seems to be on the Qt side -- here's a pure Qt example with the same problem:

```python
from PyQt5 import QtGui, QtWidgets

y = 1.0e-12  # set to 1.1e-12 and all three lines show up

app = QtWidgets.QApplication([])

win = QtWidgets.QMainWindow()
scene = QtWidgets.QGraphicsScene()
view = QtWidgets.QGraphicsView(scene)
win.setCentralWidget(view)

view.scale(10, -10/y)

for i, yval, color in zip(range(3), [y, 1.1*y, 1.2*y], ['red', 'green', 'blue']):
    path = QtGui.QPainterPath()
    path.moveTo(i, 0)
    path.lineTo(i, yval)

    item = QtWidgets.QGraphicsPathItem(path)
    pen = QtGui.QPen(QtGui.QBrush(QtGui.QColor(color)), 0)
    item.setPen(pen)
    scene.addItem(item)

win.show()
app.exec_()
```

**Comment by jaxankey** [comment]
Surprising, because the regular PlotCurveItems do work for small numbers. Can pyqtgraph simply switch the way it draws ErrorBarItems to match the way it draws PlotCurveItems?

**Comment by ixjlyons** [comment]
That's a great point. `PlotCurveItem` uses `arrayToQPath` to generate the `QPainterPath` -- I quickly hacked in usage of that function (with `connect='pairs'`) for `ErrorBarItem` instead of `moveTo`/`lineTo` calls and your example now works. It's not immediately obvious to me why that'd be the case, but at least there's a potential workaround.

**Comment by jaxankey** [comment]
Great. Hope this will be in the conda release of v0.11
________________________________

**Comment by imLew** [comment]
I am experiencing a similar issue with `InfiniteLine`. 
For a horizontal line when `setValue(x)` is called with the absolute value of x<1e-12 the line is moved to 0.
When the line is movable it can be set to values less than 1e-12, but afterwards it will no longer be moveable.

**Comment by j9ac9k** [comment]
I just ran into this issue while replicating issue #1457 this is only an issue on older Qt versions, if you use the conda version of pyside2, you get Qt 5.12.x; which is not susceptible for this issue.

That said, we should consider using `connect='pairs'` for drawing anyway...

**Comment by j9ac9k** [comment]
Confirming this issue is still present in Qt6

**Comment by j9ac9k** [comment]
And here is the issue reported in the Qt BugTracker: https://bugreports.qt.io/browse/QTBUG-75630

**Comment by pijyoi** [comment]
>It's not immediately obvious to me why that'd be the case, but at least there's a potential workaround.

In ```QPainterPath::lineTo```, there's a test to see if the new point is "equal" to the previous point.
https://code.woboq.org/qt5/qtbase/src/gui/painting/qpainterpath.cpp.html#810

However ```QPointF::operator==``` is defined to use ```qFuzzyCompare```:
https://code.woboq.org/qt5/qtbase/src/corelib/tools/qpoint.h.html#352

**Comment by j9ac9k** [comment]
> > It's not immediately obvious to me why that'd be the case, but at least there's a potential workaround.
> 
> In `QPainterPath::lineTo`, there's a test to see if the new point is "equal" to the previous point. https://code.woboq.org/qt5/qtbase/src/gui/painting/qpainterpath.cpp.html#810
> 
> However `QPointF::operator==` is defined to use `qFuzzyCompare`: https://code.woboq.org/qt5/qtbase/src/corelib/tools/qpoint.h.html#352

Thanks for getting to the bottom of this, `qFuzzyCompare` strikes again!
