### ISSUE TITLE
RemoteGraphicsView -- AttributeError: 'BarGraphItem' object has no attribute 'setGeometry'

### ISSUE THREAD

**Issue by YuMan-Tam** [pyqtgraph/pyqtgraph#1153]
I followed the example in ```RemoteSpeedTest.py``` to do histogram plots. I have to use ```BarGraphItem``` because I would like to plot two histograms with each bar side-by-side (```stepMode``` in ```PlotCurveIem``` can only do one bar). However, I encountered the error ```AttributeError: 'BarGraphItem' object has no attribute 'setGeometry'``` when I execute the following:

```
import pyqtgraph as pg
import pyqtgraph.widgets.RemoteGraphicsView

app = pg.mkQApp()

view = pg.widgets.RemoteGraphicsView.RemoteGraphicsView()
rplt = view.pg.BarGraphItem(x=range(5), height=[1,5,2,4,3], width=0.5)
view.setCentralItem(rplt)
```

There is no such a problem if I replace ```BarGraphItem``` with the ```PlotItem``` in the example. After checking source code, I can confirm the ```setGeometry``` attribute is defined in ```PlotItem``` but not ```BarGraphItem```.

I am not sure if this is a bug or an issue that I can get around with. I wonder if you could please point me to the correct place?

**Comment by ixjlyons** [comment]
`RemoteGraphicsView.setCentralItem` appears to expect a `QWidget` (`setGeometry` is a `QWidget` method), but `BarGraphItem` is a `QGraphicsObject`. What you probably want is to add a `PlotItem` to the `RemoteGraphicsView` then add a `BarGraphItem` to that:

```python
import pyqtgraph as pg
from pyqtgraph.widgets.RemoteGraphicsView import RemoteGraphicsView

app = pg.mkQApp()

view = RemoteGraphicsView()

plotitem = view.pg.PlotItem()
view.setCentralItem(plotitem)

bargraph = view.pg.BarGraphItem(x=range(5), height=[1, 5, 2, 4, 3], width=0.5)
plotitem.addItem(bargraph)

view.show()
app.exec_()
```

**Comment by YuMan-Tam** [comment]
That works! @ixjlyons  Thank you so much for the quick reply.
