### ISSUE TITLE
pg.mkQApp generates warning

### ISSUE THREAD

**Issue by 2xB** [pyqtgraph/pyqtgraph#1165]
### Short description
`pg.mkQApp()` generates warning `QSettings::value: Empty key passed`

### Code to reproduce
```python
import pyqtgraph as pg
pg.mkQApp()
```

### Expected behavior
No output

### Real behavior

Output to console:
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
```

### Tested environment(s)

 * PyQtGraph version: Latest commit from `develop` ( 6f4048596b080f71eaec544555159cb7c40c075f )
 * Qt Python binding: PyQt5 5.14.1 Qt 5.14.1
 * Python version: 3.8.2
 * NumPy version: 1.18.2
 * Operating system: Linux 5.5.7-1-MANJARO x86_64 19.0.2 Kyria
 * Installation method: Executed from source package

### Additional context
This is because `mkQApp` calls `QApplication([])`, which according to its documentation should never be called without arguments: See warning in https://doc.qt.io/qt-5/qapplication.html#QApplication

**Comment by j9ac9k** [comment]
whops i didn't mean to close this....
