### ISSUE TITLE
InfiniteLabel setVisible error

### ISSUE THREAD

**Issue by danielhrisca** [pyqtgraph/pyqtgraph#1170]
### Short description
Setting the visibility of a InfiniteLabel to True raises an AttributeError because _updateText_ method is not defined [here](https://github.com/pyqtgraph/pyqtgraph/blob/a2053b13d0234e210561a73fa044625fd972e910/pyqtgraph/graphicsItems/InfiniteLine.py#L554)

### Code to reproduce

```python
import pyqtgraph as pg

#...
line = pg.InfiniteLine(label='demo')
line.lable.setVisible(False) #ok 
line.label.setVisible(True) # AttributeError
import numpy as np
```

### Expected behavior
no error

### Real behavior

```
  File "d:\02__PythonWorkspace\asammdf\asammdf\gui\widgets\plot.py", line 1177, in keyPressEvent
    item.label.setVisible(True)
  File "d:\02__pythonworkspace\_venv\lib\site-packages\pyqtgraph\graphicsItems\InfiniteLine.py", line 552, in setVisible
    self.updateText()

<class 'AttributeError'>: 'InfLineLabel' object has no attribute 'updateText'
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0rc0
 * Qt Python binding: PyQt5 5.13.1 Qt 5.13.1
 * Python version: Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
 * NumPy version: 1.18.2
 * Operating system: Windows 10 x64
 * Installation method: pip

**Comment by ixjlyons** [comment]
This was fixed with #1487
