### ISSUE TITLE
feature request: radar chart

### ISSUE THREAD

**Issue by Alpenbelieve** [pyqtgraph/pyqtgraph#1182]
Hi, do you have plans to add a new kind of diagram called "radar chart"？

Or is there any suggestions on achieving the effect of radar chart using existing components?

Recently I'm working on making an interactive radar chart with pyqt5 and pyqtgraph in a GUI program, and a possible way I figure out is using polar coordinates, which is mentioned in [#452](https://github.com/pyqtgraph/pyqtgraph/issues/452) and [a stackoverflow answer](https://stackoverflow.com/questions/57174173/polar-coordinate-system-in-pyqtgraph)

Thanks a lot : )

**Comment by Cocco17** [comment]
I'm having the same ideas as @Alpenbelieve - would be great to know if it will happen any time soon :)

**Comment by nitrocalcite** [comment]
Another immediate approach to consider might be embedding other graphing tools.

`matplotlib` supports radar charts, and can be embedded in `pyqt5` applications using the `Qt5Agg` backend.  In fact, `pyqtgraph` already [provides](http://www.pyqtgraph.org/documentation/widgets/matplotlibwidget.html) such a widget, so implementing it should be relatively straightforward.

Of course, if you need live updates, you'll sacrifice `pyqtgraph`'s performance.  Making the aesthetics match and having interactivity will also take a little fiddling with `matplotlib`, so there are definitely downsides. 

 An alternative is `plotly` - it can also do radar charts, and it handles interactivity better.  It runs in the browser, but I've had good success embedding it in `pyqt5` with `QtWebEngineWidgets`'s `QtWebEngineView`.  The HTML can be served via the built-in `socketserver.TCPServer` or with something like `flask`.  It's not as complicated as it might first seem to implement, but it's harder than using `pyqtgraph`'s built-in support for sure.

Good luck!

**Comment by Alpenbelieve** [comment]
@nitrocalcite Thanks very much for your reply ! It's really helpful and I'd have a try.

`QtWebEngineView` is powerful, and it can cooperate with many html-based python visualization tools ( including Plotly, Echarts, Altair, Bokeh ...) to let them work in GUI.

And these days I found another possible method: use Qtchart. It's the official drawing library of QT, and it's component `QPolarChart` can draw "Polar Chart", which can be modified to "Radar Chart"(Maybe require some efforts). Here is an [example](https://doc.qt.io/qt-5/qtcharts-polarchart-example.html).
If want to use it in pyqt5, first install `pyqtchart`, then add this line: `from PyQt5.QtChart import QPolarChart`.

Finally, thanks again : )

**Comment by j9ac9k** [comment]
Hi @Alpenbelieve 

We have no plans on implementing such a feature, but we would sure work review and test such a feature if someone wanted to submit a PR for one.  We're primarily in bug-hunt/fix mode at this point trying to get 0.11 out the door so there isn't much demand from the maintainers to implement new features for the time being.

As @nitrocalcite suggested, easiest thing to do right now is use matplotlib and embed it using the widget.

**Comment by Alpenbelieve** [comment]
@j9ac9k I'm very understanding. Thanks for your response! ^_^
