### ISSUE TITLE
Graph permanently shifts to the right when having long tick strings

### ISSUE THREAD

**Issue by kangalioo** [pyqtgraph/pyqtgraph#1183]
### Short description
A plot with long tick names is squashed horizontally to make room for the tick names. That is good. However, even after changing the plot and the tick names, the plot stays squashed. Is there some way to prevent that from happening?

### Code to reproduce

```python
import pyqtgraph as pg

plot_widget = pg.plot(title="test")
plot_widget.getPlotItem().getAxis("left").setTicks([[(0, "a loooooooooooooooooooooooooooooong tick string")]])
input("Press enter to change the tick string to a short string")
plot_widget.getPlotItem().getAxis("left").setTicks([[(0, "short")]])
input("Press enter to quit")
```

### Expected behavior
Optimally I expect the plot to automatically adjust to tick strings whenever they are changed.

### Real behavior
The plot gets smaller when adding long tick strings, but it won't expand back again when having short tick strings.

### Tested environment(s)
 * PyQtGraph version: 0.11.0.dev0+ga76d9da
 * Qt Python binding: PyQt5 5.14.2 Qt 5.14.2
 * Python version: 3.8.2
 * NumPy version: 1.17.4
 * Operating system: Linux x64, KDE
 * Installation method: pip

### Additional context
For now I will circumvent this problem be completely replacing the entire PlotWidget on every graph update.

**Comment by j9ac9k** [comment]
Hi @kangalioo thanks for the issue and thanks for providing the code to reproduce.  This made it easy for me to verify that this issue is fixed in the PR I'm about to merge.
