### ISSUE TITLE
PolyLineROI context menu displays "Remove ROI" even when ROI is not removable

### ISSUE THREAD

**Issue by Aikhjarto** [pyqtgraph/pyqtgraph#1186]
### Short description
PolyLineROI context menu displays "Remove ROI" even when ROI is not removable.

### Code to reproduce and Real behavior
```python
import pyqtgraph.examples
pyqtgraph.examples.run()
```
Right click on a handle of the PolyLineROI and see the "ROI->Remove ROI" action, although in the source of the example the PolyLineROI is not set to be removable.
![image](https://user-images.githubusercontent.com/3519989/80692605-16e39400-8ad2-11ea-8677-221946d79c05.png)

### Expected behavior
No "Remove ROI" context menu entry should appear in handles of PolyLineROI when it is not set to be removable.

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0+g556ba55
 * Qt Python binding: PyQt5 5.9.2 Qt 5.9.6
 * Python version:  3.6
 * NumPy version: 1.18.1
 * Operating system:  Windows 10
 * Installation method: pip

**Comment by ixjlyons** [comment]
Good catch, thanks for reporting. #1197 will fix this.
