### ISSUE TITLE
Potential issues with GraphicsItem.pixelVectors caching

### ISSUE THREAD

**Issue by erikmansson** [pyqtgraph/pyqtgraph#1189]
I found some potential issues in the caching in GraphicsItem.pixelVectors.

In both the local cache lookup:

https://github.com/pyqtgraph/pyqtgraph/blob/720fa5f3c2e77dd1b5d18af26f65de41188b282e/pyqtgraph/graphicsItems/GraphicsItem.py#L189-L190

and global cache lookup:

https://github.com/pyqtgraph/pyqtgraph/blob/720fa5f3c2e77dd1b5d18af26f65de41188b282e/pyqtgraph/graphicsItems/GraphicsItem.py#L194-L198

the cached value is used if `direction is None` (implicitly `QtCore.QPointF(1, 0)`). However, the cached value may have been calculated for any direction, and the direction does seem not affect the key obtained from `dt`. This may result in returning an incorrect value in when `pixelVectors` has been called with an explicit direction prior to calling it with `direction=None`.

Furthermore, when `pixelVectors` is called with `direction=Point([1, 0])`, as done here:

https://github.com/pyqtgraph/pyqtgraph/blob/720fa5f3c2e77dd1b5d18af26f65de41188b282e/pyqtgraph/graphicsItems/ROI.py#L2266

and here

https://github.com/pyqtgraph/pyqtgraph/blob/720fa5f3c2e77dd1b5d18af26f65de41188b282e/pyqtgraph/graphicsItems/InfiniteLine.py#L306

through here:

https://github.com/pyqtgraph/pyqtgraph/blob/720fa5f3c2e77dd1b5d18af26f65de41188b282e/pyqtgraph/graphicsItems/GraphicsItem.py#L262-L268

No cache lookup is done since direction is not None, but should be since it's set to that value implicitly if direction is None. This slows down updating e.g. InfiniteLines _a lot_, which is an issue for a project I'm currently working on.

I'd be happy to help out fixing this, but I'd like to know what the intended behavior is first. Is including the direction in the cache key and then not checking if `direction is None` a potential good fix/improvement?

**Comment by erikmansson** [comment]
Can anyone have a look at this? I have a potential fix ready at https://github.com/erikmansson/pyqtgraph/commit/4cae76bd29fc63b670aeba3bfb2a68993d8dfc91. I'll create a PR if it looks ok.

**Comment by j9ac9k** [comment]
Hi @erikmansson sorry for the late response and thank you for the detailed issue creation. 

Your post and your commit on your fork looks good to me.  Changes in `GraphicsItem` can have big impacts to the library, so I would feel better about the process if our CI system did a run through the test suite.  If you could submit a PR with this change, our CI system will run through a test suite.

If you have code that demonstrates the performance improvement with using the caching correctly, I'd also love to see it!

**Comment by erikmansson** [comment]
No problem - I've used my own fork in the meantime.

I'd love to show you, but the project is yet to be published openly. The issue appeared when zooming a plot with many (~100) LinearRegionItems visible. Fixing this cut the total draw time by half, making it a lot smoother.

**Comment by j9ac9k** [comment]
That's great to hear, I've experienced some other issues when plotting dozens/hundreds of linear region items, I've found some performance improvements in adding them in one go (didn't make the change upstream yet).

No problem is the project is still not available, I understand.

**Comment by 2xB** [comment]
Closing since your PR #1212 was merged. Thank you for reporting!
