### ISSUE TITLE
Incorrect scaling on high-resolution displays

### ISSUE THREAD

**Issue by campagnola** [pyqtgraph/pyqtgraph#119]
This is particularly common on some OSX machines.

Example:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pyqtgraph/nBeb9R3kkRo/Bh75r18MJC0J

**Comment by j9ac9k** [comment]
I'm not sure we can produce this on any configuration at this point, should we perhaps close this out?  I'm using macOS with a "retina" display and haven't had any scaling issues on any of the configurations  that I'm aware of.
