### ISSUE TITLE
How to plot multiple, discontinuous edges using PlotWidget?

### ISSUE THREAD

**Issue by vitsensei** [pyqtgraph/pyqtgraph#1193]
Hi,
I'm using PlotWidget to draw hundreds of discontinue edges in my Qt application. So far my approach is to create a myplotwidget.plot() and then setData() for each of my edge. It seems like this is an inefficient approach since my computer takes about 10 seconds to plot all those edges.
How should I approach this better? Thank you.

**Comment by 2xB** [comment]
You could use one single `PlotDataItem` (make a single call to `.plot()`) and use the `connect` argument of the functions `plot` and `setData` to specify which of the data should be drawn with a line. Also see the documentation of the `connect` argument here: http://www.pyqtgraph.org/documentation/functions.html#pyqtgraph.arrayToQPath
Here is a minimal example using said `connect` argument for you to play around with:

```python3
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore
import numpy as np

app = pg.mkQApp()

win = pg.GraphicsLayoutWidget(show=True)
win.setWindowTitle('pyqtgraph example: Scrolling Plots')

p1 = win.addPlot()
data1 = np.random.normal(size=300)
connected = np.round(np.random.rand(300))
curve1 = p1.plot(data1, connect=connected)
def update1():
    global data1, connected
    data1[:-1] = data1[1:]  # shift data in the array one sample left
                            # (see also: np.roll)
    connected = np.roll(connected, -1)
    data1[-1] = np.random.normal()
    curve1.setData(data1, connect=connected)
    
timer = pg.QtCore.QTimer()
timer.timeout.connect(update1)
timer.start(50)

app.exec_()
```

Does this help?

**Comment by 2xB** [comment]
Also, since you only draw edges, maybe the `connect` argument `pairs` would be a way to go. There is more information in the documentation linked above, if that sounds right for you.

**Comment by 2xB** [comment]
One last thing: Just for fun I've tested this with 30.000 data points instead of 300, and it still plots all the data points (with correct partly disconnected edges) instantaneously. So there should not be a worry about performance.

**Comment by vitsensei** [comment]
Your enthusiast really touch me at 2am in the morning. I quickly wrote down what I wanted to say on a piece of paper and a note to myself reminding me to test your snippet of code first thing after breakfast. 

It works really really well, thank you! I did a bit of looking around right after this post and found someone with the same problem: https://github.com/pyqtgraph/pyqtgraph/issues/1039#issue-496430461

I wonder if this feature is added after or before this post.

**Comment by 2xB** [comment]
Thank you for the kind words and the hint to issue #1039! I've added a comment according to your hint. The feature is quite old, but not that visible.

It looks like this issue is solved - if there is anything to add or you have anything else, feel free to add a comment here or to create a new issue!
