### ISSUE TITLE
opengl installation/usage

### ISSUE THREAD

**Issue by timjolson** [pyqtgraph/pyqtgraph#1194]
### Short description
In trying to install and use pyqtgraph with opengl, I get `ImportError: cannot import name 'QtOpenGL'` .

### Code to reproduce
Using a fresh installation of ubuntu 18.04.4 64bit with gnome 3.28.2
Using various installation methods and combinations (apt and pip3), and in various orders.
See a spreadsheet of the tested combinations and results [here](https://github.com/timjolson/publicshares/tree/master/pyqtgraph%20opengl).

After install, run `python3 -m pyqtgraph.examples` then run `3D Graphics / Line Plot`.

### Expected behavior
Window opens, 3D example shows and is interact-able. Using PyQt5, with it selected automatically as the default for the system.

### Real behavior
Certain install combinations work:
1. PyQt4 sometimes does, but I am building in PyQt5
2. PyQt5 sometimes works, but never when it is the default graphics system

Most do not work:
The error when it does not work, regardless of PyQt5 or 4, is `ImportError: cannot import name 'QtOpenGL'`

```
Using PyQt5 (default graphics system)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyqtgraph/examples/GLLinePlotItem.py", line 10, in <module>
    import pyqtgraph.opengl as gl
  File "/usr/local/lib/python3.6/dist-packages/pyqtgraph/opengl/__init__.py", line 1, in <module>
    from .GLViewWidget import GLViewWidget
  File "/usr/local/lib/python3.6/dist-packages/pyqtgraph/opengl/GLViewWidget.py", line 2, in <module>
    from OpenGL.GL import *
ModuleNotFoundError: No module named 'OpenGL'
```

### Tested environment(s)

 * PyQtGraph version: 0.10.0
 * Qt Python binding: PyQt5==5.9 (PyQt4 built into ubuntu)
 * Python version: 3.6.9
 * NumPy version: 1.18.4
 * Operating system: Ubuntu 18.04.4
 * Installation method: various

### Additional context
I previously had another compatibility issue with pyqtgraph that may be [somewhat related](https://stackoverflow.com/questions/56574060/pyqt5-installation-results-in-designer-qtopengl-possibly-pyqtgraph-errors/58636138#58636138). Forgive the messiness of that post, as I updated it, it became harder to follow.

If there is a reasonably simple way to set PyQt5 as the default graphics system, then this issue might simply be resolved using an install combination where the example works, plus setting the default.

**Comment by j9ac9k** [comment]
for openGL functionality, you need to install the pyopengl library (`pip install pyopengl`).  


I would also recommend installing pyqtgraph 0.11rc0, countless bug-fixes and performance improvements have gone been made since 0.10.0, we're still not at the point of doing a stable release yet though.  You can install 0.11rc0 by running `pip install pyqtgraph==0.11rc0`

**Comment by timjolson** [comment]
I reinstalled from fresh with `pip3 install pyqt5==5.9 pyopengl pyqtgraph==0.11rc0`. GL examples work now, thanks!

My other issue that I linked to is not resolved, but is no longer applicable.
