### ISSUE TITLE
Some widget sizes (e.g. combo box) are not good on high dpi displays

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#1200]
### Code to reproduce

Parameter Tree pyqtgraph exaple:
![image](https://user-images.githubusercontent.com/23620506/82159964-ffd9cb80-985f-11ea-9e34-7cd839a52338.png)

### Expected behavior
The whole number should be displayed

### Real behavior
The top and bottom of the list parameter is truncated during editing

### Tested environment(s)

 * PyQtGraph version: '0.11.0.dev0+g720fa5f'
 * Qt Python binding: 'PyQt5 5.9.2 Qt 5.9.6'
 * Python version: 3.7
 * Operating system: Windows 10 Home build 1909
 * Installation method: pip

**Comment by j9ac9k** [comment]
HiDPI scaling issues with Qt on Windows have been a constant thorn in my side and I have yet to find a good fix that can be applied across the board.

There was some work in #1154 to attempt to address HiDPI sizing issues for the text in DateAxisItem, but I'm not sure how much that method could be applied across the board.

Tagging @2xB as they reviewed PR #1154 and tested some of the fixes.

**Comment by 2xB** [comment]
What we did there was using `QPainter.fontMetric().boundingRect(text)` to get the DPI-aware size of a given string, and used `QPainter.device().logicalDpiX()` to get the DPI of the currently visible device. I do not know how well those methods translate here.

**Comment by ntjess** [comment]
Just a note for whoever starts implementing this fix: During testing it may be good to look at the PlotWidget's context menu as well:
![image](https://user-images.githubusercontent.com/23620506/86397641-3635a380-bc72-11ea-8ad0-f866f0436c89.png)

**Comment by j9ac9k** [comment]
Working on #1509 here is a screen grab of the parameter tree on a hidpi monitor

![image](https://user-images.githubusercontent.com/646398/105610307-f811e580-5d63-11eb-9311-973a1dda36d3.png)

Also PlotWidgets look good too (I'm using PyQt5 5.15 for testing, this should work reliably on 5.14+; 5.12 may work a bit but font size may not be great... on Qt6 it should "just work". 

I'm off to test some of the other hidpi issues, if they are all resolved I'll merge and close out this issue.  Sorry this has taken so long for me to address.
