### ISSUE TITLE
Will there be a new release soon?

### ISSUE THREAD

**Issue by vitsensei** [pyqtgraph/pyqtgraph#1204]
Hi,
I just found out that the version of pyqtgraph I installed (0.9.0 I believe) is a few years old and I have been missing out some new features and bug fixes. I only knew about this because I tried to clear the content of the legend and encounter the error that my LegendItem does not have attribute clear(), which it does in the documentation. Weird.

Anyways, I installed the development branch and everything is resolved.

**Comment by ksunden** [comment]
We released a release candidate of 0.11.0rc0 a little while back, and that is available on both [pypi](https://pypi.org/project/pyqtgraph/0.11.0rc0/) and [conda-forge](https://anaconda.org/conda-forge/pyqtgraph/files)

We are tracking down the last few known regressions before finalizing the 0.11.0 release.

**Comment by vitsensei** [comment]
Huh, I downloaded from pip recently but for some reason it gave me 0.9.0 instead.
