### ISSUE TITLE
Having a QSlider on top of GLViewWidget

### ISSUE THREAD

**Issue by vitsensei** [pyqtgraph/pyqtgraph#1205]
Hi,
After adding a QSlider on top of GLViewWidget, it seems like the 3D plotter does not automatically update after I move the slider, which result in a weird behavior like [this](https://imgur.com/L1T4qsO). Any idea on how to solve this? Thanks.
Edit: I tried the same thing with PlowWidget but it's working perfectly.

**Comment by 2xB** [comment]
Hey, could you please provide a minimal code example that one can execute to replicate this? Also, could you please fill out the default Issue template that you see when you click on "New issue" and then on "Getting started"? Both massively helps tracking down your issue.
Also, you can upload images directly to GitHub, which I would highly encourage, as there might be the need to revisit an issue a few years after it is posted and e.g. `imgur` might already have that image deleted then. Thank you!

**Comment by vitsensei** [comment]
Hi,
Sorry for the low quality post. I use Ubuntu 18, with pyqt5 + pyqtgraph development branch. Here's the code that is mostly generated by qtcreator:
```

from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph.opengl import GLViewWidget
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = GLViewWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalSlider = QtWidgets.QSlider(self.widget)
        self.verticalSlider.setGeometry(QtCore.QRect(740, 30, 20, 481))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self)

app = QtWidgets.QApplication(sys.argv)

window = MainWindow()
window.show()
app.exec()

```

**Comment by 2xB** [comment]
Okay, thank you. If someone wants to work on this, here's a version of the code that might be easier to use for debugging:

```python3
import sys
from PyQt5 import QtCore, QtWidgets

import pyqtgraph.opengl as gl
import pyqtgraph as pg

app = pg.mkQApp()

window = QtWidgets.QMainWindow()
window.resize(800, 600)

centralwidget = QtWidgets.QWidget(window)
gridLayout = QtWidgets.QGridLayout(centralwidget)

widget = gl.GLViewWidget()
gx = gl.GLGridItem()
widget.addItem(gx)

verticalSlider = QtWidgets.QSlider(widget)
verticalSlider.setGeometry(QtCore.QRect(740, 30, 20, 481))
verticalSlider.setOrientation(QtCore.Qt.Vertical)

gridLayout.addWidget(widget, 0, 0, 1, 1)

window.setCentralWidget(centralwidget)
window.show()
app.exec_()
```

The issue: The area behind the slider is not redrawn when the slider is moved. It is redrawn if one uses a QWidget instead of a GLViewWidget though.

![image](https://user-images.githubusercontent.com/31772910/82765772-d568af00-9e19-11ea-8670-aaa0096532d3.png)


### Tested environment(s)

 * PyQtGraph version: Branches `master` and `develop`, commit c715c5ac2855bc6208ef2f3b810af305969a5748
 * Qt Python binding: PyQt5 5.14.2 Qt 5.14.2
 * Python version: 3.8.2
 * NumPy version: 1.18.4
 * Operating system: Linux 5.6.10-3-MANJARO x86_64 20.0 Lysia
 * Installation method:

**Comment by 2xB** [comment]
Btw. this also appears for an ordinary `QGLWidget` instead of `pyqtgraph`s `GLViewWidget`. I can't judge if this is an issue of `pyqtgraph` or just inherited behavior from `Qt` though. Probably the reason for `Qt` behaving this way would be good to know now.

**Comment by pijyoi** [comment]
This issue seems to have fixed by the move from QGLWidget to QOpenGLWidget.
