### ISSUE TITLE
Debian 8 plots doesn't appear

### ISSUE THREAD

**Issue by mgtm98** [pyqtgraph/pyqtgraph#1207]
### Short description

When making plots in Debian 8 plot window appear normally but it doesn't plot.

### Code to reproduce

```python
import pyqtgraph as pg
pg.plot(x = [1,2], y=[2,3])
```
### Tested environment(s)

 * PyQtGraph version:  latest version from github 
 * Qt Python binding:  pyside2
 * Python version: 3.7.3
 * NumPy version: 
 * Operating system: Debian 8
 * Installation method:  from source

**Comment by ixjlyons** [comment]
Are you typing this code into a Python shell (i.e. running interactively)? There's some discussion of this situation [here](https://pyqtgraph.readthedocs.io/en/latest/how_to_use.html#command-line-use). With PySide2, you need to explicitly run the Qt event loop for the GUI to process events and update. You could do that by running `pg.mkQApp().exec_()` at the end. That should make the plot appear in the window and you should be able to interact with it. It will block further inputs to the Python shell until the window is closed, though.

PyQt5 uses a low-level mechanism to allow the Qt and Python interpreter event loops to cooperate, as [described here](https://www.riverbankcomputing.com/static/Docs/PyQt5/python_shell.html). That means you don't need the `exec_()` call and you can iteratively add items to the plot etc. while still interacting with the GUI.

If you are running the code as a script, you most likely want the `exec_()` at the end regardless. This is why the examples have this at the end:

```python
## Start Qt event loop unless running in interactive mode.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()
```

**Comment by mgtm98** [comment]
I already do this 
```python
from PySide2.QtWidgets import QApplication
import PySide2.QtCore as QtCore
import numpy as np
import pyqtgraph as pg


app = QApplication([])

x = np.random.normal(size=1000)
y = np.random.normal(size=1000)
pg.plot(x, y, pen=None, symbol='o')

if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QApplication.instance().exec_()`
```
But it displays a blank window
![Screenshot from 2020-05-24 11-47-09](https://user-images.githubusercontent.com/43015074/82750969-4ffee380-9db4-11ea-8379-c319401eef17.png)

**Comment by ixjlyons** [comment]
Could you provide some details of your configuration for running scripts (looks like pycharm)? Could you also try running the script from a terminal with just `python testPyqtgraph.py`? Finally, are you able to interact with the plot shown in the screenshot (i.e. can you zoom, pan, open a context menu, etc.)?

**Comment by mgtm98** [comment]
- I use conda environment 
![Screenshot from 2020-05-27 06-58-21](https://user-images.githubusercontent.com/43015074/82979529-8f614600-9fe7-11ea-9a37-bc0310cd67b4.png)
- Yes i can interact with plot
- i already run i using pyhon3 testPyqtgrraph.py
- another code example i tried 
``` python
import pyqtgraph as pg
import pyqtgraph.exporters
import numpy as np

# define the data
theTitle = "pyqtgraph plot"
y = [2,4,6,8,10,12,14,16,18,20]
y2 = [0,1,2,4,12,14,16,17,14,22]
x = range(0,10)

# create plot
plt = pg.plot()
plt.showGrid(x=True,y=True)
plt.addLegend()

# set properties
plt.setLabel('left', 'Value', units='V')
plt.setLabel('bottom', 'Time', units='s')
plt.setXRange(0,10)
plt.setYRange(0,20)
plt.setWindowTitle('pyqtgraph plot')

# plot
c1 = plt.plot(x, y, pen='b', symbol='x', symbolPen='b', symbolBrush=0.2, name='red')
c2 = plt.plot(x, y2, pen='r', symbol='o', symbolPen='r', symbolBrush=0.2, name='blue')

## Start Qt event loop.
if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1 or not hasattr(pg.QtCore, 'PYQT_VERSION'):
        pg.QtGui.QApplication.exec_()
```
and this was the output 
![Screenshot from 2020-05-27 06-58-34](https://user-images.githubusercontent.com/43015074/82979650-dfd8a380-9fe7-11ea-8f65-1e84d559ffe5.png)

**Comment by ixjlyons** [comment]
I'm not sure what might cause this, but I'd be inclined to try upgrading Qt.

**Comment by j9ac9k** [comment]
Just saw PySide2 5.6 ...yeah you're going to have a bad time there.  We had so many issues w/ that version that I completely scraped it from our CI pipelines and even added a blurb on the README about we recommend _not_ using it.

If you really want to stick w/ Python 5.6, use PyQt5 instead of PySide2, but we recommend upgrading to Qt 5.12 or newer is feasible.

**Comment by j9ac9k** [comment]
I'm going to close out this issue and chalk it up to the old version of PySide2, if you still have the same problem with PySide2 5.12 or newer, post back here and we'll investigate.
