### ISSUE TITLE
Non-important warning with large images

### ISSUE THREAD

**Issue by diegoasua** [pyqtgraph/pyqtgraph#1210]
### Short description
When handling large images one gets a warning:

...\pyqtgraph\imageview\ImageView.py:588:

FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

  data = data[sl]

### **Proposed fix**

line 588 in ImageView.py:

_replace_

data = data[sl]

_for_

data = data[tuple(sl)]

### Tested environment(s)

 * PyQtGraph version: '0.10.0'
 * Qt Python binding: 'PyQt5 5.9.2 Qt 5.9.6'
 * Python version: 3.7.4
 * NumPy version: '1.16.5'
 * Operating system: Windows 10
 * Installation method: pip

**Comment by j9ac9k** [comment]
@diegoasua can you see if this is still an issue with 0.11.rc0?  you can install the rc build by running `pip install pyqtgraph==0.11.rc0`

**Comment by diegoasua** [comment]
@j9ac9k this solved the issue, thanks!
