### ISSUE TITLE
Custom parameter item context menu is destroyed on context menu event

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#1224]
### Short description

The following works in 0.10 to add custom menu options to a parameter:

```python
from typing import List

import pyqtgraph as pg
from pyqtgraph.Qt import QtWidgets
from pyqtgraph.parametertree import parameterTypes


class CustGrp(parameterTypes.GroupParameter):
  def __init__(self, menuActions: List[str]=None, **opts):
    if menuActions is None:
      menuActions: List[str] = []
    self.menuActions = menuActions
    self.item = None
    super().__init__(**opts)

  def makeTreeItem(self, depth):
    item = super().makeTreeItem(depth)
    self.item = item
    item.contextMenuEvent = lambda ev: item.contextMenu.popup(ev.globalPos())
    for actName in self.menuActions:
      act = item.contextMenu.addAction(actName)
    return item

app = pg.mkQApp()
t = pg.parametertree.ParameterTree()
w = QtWidgets.QMainWindow()
p = CustGrp(name='test', menuActions=['test', 'this'], removable=True)
parent = parameterTypes.Parameter.create(name='group', type='group', children=[p])
t.setParameters(parent)
w.setCentralWidget(t)
w.show()
app.exec()
```

However, the latest development branch errs out since the context menu isn't created until the first context menu event. A simple check for
```python
if not hasattr(item, 'contextMenu'):
  item.contextMenu = QtWidgets.QMenu()
```
can account for this, but then the subclasser is now responsible for also implementing removable/renamable/etc. which is not desirable.

### Expected behavior

I expect the behavior of 0.10 to stay. To listen for changes to 'removable' etc, I recommend `hide()`ing the unused menu options when the `opt` is `False` and showing when `True`. This way, the context menu isn't obliterated each context event.

Commit in question: 7672b5b72596687295488fd1b1164ece113c71db

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0+g932b975
 * Qt Python binding: 5.13
 * Python version: 3.7
 * NumPy version: 1.18.1
 * Operating system: Win10
 * Installation method: pip

**Comment by 2xB** [comment]
In that case, could you check out merged Pull Request #1206? It provides a solid way to add context menu options to `ParameterItem`s via the public API.

**Comment by 2xB** [comment]
Just noticed that I accidentally broke part of the functionality from PR #1206 in PR #1175, added a simple PR #1225 to fix that.

**Comment by ntjess** [comment]
Thanks for pointing that out. I am developing an app for users with pip release versions, so I still have to use my custom solution for now. I just want to make sure my code is forward compatible

**Comment by j9ac9k** [comment]
@ntjess this issue was one of the last I think we've identified to address pre 0.11 release

**Comment by 2xB** [comment]
@ntjess If this solves your issue, might you close it?

**Comment by ntjess** [comment]
Whoops, I thought I closed it earlier. My apologies.
