### ISSUE TITLE
Legend overlaps with plot contents

### ISSUE THREAD

**Issue by kangalioo** [pyqtgraph/pyqtgraph#1226]
### Short description

When adding a legend to a plot, the legend and the plot contents overlap. An example out of an application I'm building: 
![image](https://user-images.githubusercontent.com/21220820/83953076-b0266880-a83d-11ea-92c4-d0d14b892821.png)

### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np

plot = pg.plot().getPlotItem()
plot.addLegend()

x = np.arange(50)
y = np.cos(x / 100) * 3
item = pg.BarGraphItem(x=x, height=y, width=0.8, pen="w")

plot.addItem(item)
plot.legend.addItem(item, 'bar')

input("Press enter to quit")
```

### Expected behavior
I could imagine multiple possible fixes:

1. Make the legend opaque
2. Automatically zoom out a little to make space for the legend

### Real behavior
The legend simply appears on the top left, without any consideration whether it overlaps with the plot.

### Tested environment(s)

 * PyQtGraph version: 0.11.0rc0
 * Qt Python binding: PyQt5 5.14.2 Qt 5.14.2
 * Python version: 3.8.3
 * NumPy version: 1.17.4
 * Operating system: Arch Linux
 * Installation method: pip

**Comment by ixjlyons** [comment]
You can specify a brush for the `LegendItem` to have an opaque background:

```python
import pyqtgraph as pg
import numpy as np

win = pg.plot()
plot = win.getPlotItem()
legend = plot.addLegend()
legend.setBrush('k')

x = np.arange(50)
y = np.cos(x / 100) * 3
item = pg.BarGraphItem(x=x, height=y, width=0.8, pen="w")

plot.addItem(item)
plot.legend.addItem(item, 'bar')

pg.mkQApp().exec_()
```

There are a couple actionable items I think:

It's not obvious from the [docs](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/legenditem.html) that you can do this, so I'd say we should make sure each settable feature of the legend is documented.

It might also be nice for `addLegend` to take `**kwargs` and pass them along to create the `LegendItem` so that you could write `plotitem.addLegend(brush='k')` for convenience.

**Comment by 2xB** [comment]
The invisible default background for legend is btw. new since PR #958, using 0.10 legends have a solid background.

**Comment by kangalioo** [comment]
uhhh?
![Screenshot_20200607_001245](https://user-images.githubusercontent.com/21220820/83955478-a0b21a00-a853-11ea-9155-de52968d2a62.png)
Is this another bug or am I using it wrong

**Comment by ixjlyons** [comment]
Ah, that was fixed by #1139 and didn't make it in 0.11.0rc0

**Comment by kangalioo** [comment]
Back to the git version of pyqtgraph I guess. That's better anyway with all the new features. Thanks for the quick response btw

**Comment by j9ac9k** [comment]
FWIW this is the first issue that's been reported that wasn't addressed by 0.11rc0 I think.

**Comment by AndrewTrapani** [comment]
Setting the background of the Legend as black, for example, will block the contents of the data that has been plotted.

I want to be able to move the legend outside of the plotting area completely.

This would:

- Shrink the plot area enough for the legend to be drawn
- Draw the legend outside the plot. Configurable above, below, left, and right
- When drawing the legend, allow for it to be aligned configurable for centered, left, or right and top or bottom
- When drawing the text in the legend, allow for the text to be aligned configurable for centered, left, or right
- When drawing the icon for the legend (e.g. green curve has a green straight line, allow it to be aligned on the left or right of the text


Right now, in all my examples, the legend is drawn on top of our important data.

If I adjust the offset, e.g. move from default position (top left) to the bottom right (-30,-30), it will fix one set of data, but then block content on another set of data

The only work around is to adjust the zoom, but the user may simply adjust the zoom again and wonder where the legend went...

**Comment by 2xB** [comment]
Hello @AndrewTrapani, it might be reasonable to open a separate issue suggesting this. Comments under closed issues are often missed.
