### ISSUE TITLE
Duplicate clear methods in LegendItem

### ISSUE THREAD

**Issue by ixjlyons** [pyqtgraph/pyqtgraph#1227]
https://github.com/pyqtgraph/pyqtgraph/blob/1c67d3ea2f9c91390947fb7f1a3b07692c9ed3a8/pyqtgraph/graphicsItems/LegendItem.py#L179-L195

Any preference?

**Comment by j9ac9k** [comment]
I'm assuming there is some spacing issues with the code snippet here, as the lines in the first clear function aren't indented properly....

I'm partial to the code in the first, being that it's more readable IMO.

**Comment by j9ac9k** [comment]
Fixed with #1228

**Comment by j9ac9k** [comment]
Fixed with #1228
