### ISSUE TITLE
setSymbol<opt>() on PlotDataItem with numpy array raises error

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#1232]
### Short description

ScatterPlotItem checks whether the new symbol is an array and proceeds accordingly. However, PlotDataItem checks whether `self.opts['symbol'] == symbol` which crashes when one or both of the arguments are arrays.

### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np
app = pg.mkQApp()
data = np.tile(np.arange(5)[:,None], (1,2))
scat = pg.ScatterPlotItem(*data.T)
dat = pg.PlotDataItem(*data.T)
symbols = np.array(['star']*5)
scat.setSymbol(symbols) # works
dat.setSymbol(symbols) # failure
```

### Expected behavior

`setSymbol` with plot item should behave like setSymbol on scatterplot item (right?)
### Real behavior

ValueError is raised
```
An error occurred?
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\cdef\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-9f5791ddebcd>", line 1, in <module>
    dat.setSymbol(symbols)
  File "C:\ProgramData\Anaconda3\envs\cdef\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 268, in setSymbol
    if self.opts['symbol'] == symbol:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0+gf43b29
 * Qt Python binding: 
 * Python version: 3.7
 * NumPy version: 
 * Operating system: 
 * Installation method:

**Comment by ntjess** [comment]
I think simply checking `np.array_equals()` instead of `==` would resolve this issue

**Comment by ntjess** [comment]
I see this is also the case for `setSymbolBrush`, 'Size`, etc.

**Comment by j9ac9k** [comment]
Looks like `self.opts['symbol'] is expecting a `str` and not a `np.ndarray`, so `np.array_equal()` wouldn't work in that regard.  .... looking at the ScatterPlotItem, there is some logic to handle the case of symbols being a numpy array.

I haven't actually worked with these objects, so I don't feel comfortable with making claims to how they should work (or assessing your suggestions of those methods should work the way they do for ScatterPlotItem).

In terms of the other functions, `setSymbolBrush` looks fine to me, it takes `args` and `kwargs` to construct a Brush, but `functions.mkBrush` will always return a single brush.

`setSymbolSize` does appear to have the same issue.  I'll ask others that are more familiar with PlotDataItem to weigh in on a potential change in expected argument types.

**Comment by ksunden** [comment]
Any particular reason you are using numpy arrays here? numpy arrays of strings are mildly unusual, and a simple list works fine:

```
dat.setSymbol(list(symbols))
```

**Comment by ksunden** [comment]
@j9ac9k The line that is failing is there to avoid superfluous calls to `updateItems` when the symbol is set to what it already was.

All that said, `np.array_equal` does in fact validly compare strings and lists as well, but 2-3 orders of magnitude slower than `==`

**Comment by j9ac9k** [comment]
I just did some timeit measurements, yeah just replacing `==` with `np.array_equal` is not something I'm thrilled about

```
In [2]: %timeit np.array_equal("a", "b")
6.14 µs ± 90 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [3]: %timeit "a" == "b"
34.1 ns ± 0.522 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [4]: %timeit isinstance("a", str)
76.9 ns ± 0.764 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

I'm not opposed to throwing some `ifinstance` logic in there, it adds a little complexity but preserves the performance.

**Comment by ntjess** [comment]
For large arrays the performance converges and it helps when the sizes are mathematically computed, but I didn't realize the time disparity was that significant. I'm fine with changing my code and since the documentation doesn't specify compatibility with ndarrays I don't think it would be API-breaking

**Comment by ntjess** [comment]
@ksunden numpy arrays provide much faster indexing when a few pens in a long list must be changed:
```
tmp = np.random.permutation(10000)[:500]
def tst_a():
   ...:   a[tmp] = 'o'
   ...:   
def tst_aa():
   ...:   for idx in tmp:
   ...:     aa[idx] = 'o'
   ...:     
aa = a.tolist()
%timeit tst_a()
3.37 µs ± 21.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
%timeit tst_aa()
51.7 µs ± 341 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by ntjess** [comment]
@j9ac9k Thought about this a bit more after waking up today. It is possible to go the EAFP route if desired to avoid performance penalties for list or scalars:
```python
%timeit aa==bb
#7.62 µs ± 65.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

%%timeit
 try:
   bool(aa==bb)
 except ValueError:
   np.all(a==b)
 
#7.6 µs ± 65.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
