### ISSUE TITLE
Segfault with pg.plot(axisItems={"bottom": pg.DateAxisItem()})

### ISSUE THREAD

**Issue by kangalioo** [pyqtgraph/pyqtgraph#1233]
### Short description
Segfault with `pg.plot(axisItems={"bottom": pg.DateAxisItem()})`

### Code to reproduce

```python
import pyqtgraph as pg
pg.plot(axisItems={"bottom": pg.DateAxisItem()})
```

### Expected behavior
No segfault

### Real behavior
Segfault

```
113485 Segmentation fault      (core dumped)
```

### Tested environment(s)

 * PyQtGraph version: 6bd029915207e96ec4bd37cf6f52be31c3f10ee0
 * Qt Python binding: PyQt5 5.14.2 Qt 5.14.2
 * Python version: 3.8.3
 * NumPy version: 1.17.4
 * Operating system: Arch Linux
 * Installation method: pip

**Comment by j9ac9k** [comment]
@ixjlyons  you run arch right? Can you replicate?

**Comment by j9ac9k** [comment]
Wait, you haven't started the Qt event loop or have an application instance running.

```
import pyqtgraph as pg
app = pg.mkQApp()

pg.plot(axisItems={"bottom": pg.DateAxisItem()})

## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        pg.QtGui.QApplication.instance().exec_()
```

Try that.

**Comment by ksunden** [comment]
@j9ac9k that script displays the window, but still segfaults after it is done

**Comment by ixjlyons** [comment]
Yep, getting an application instance first should fix it. This is a somewhat tricky issue -- `pg.plot()` creates an application instance for you, but the `DateAxisItem` object is instantiated before the function runs, so you get an unhelpful segfault.

The segfault @ksunden is referring to happens because there's no reference to the `GraphicsView` created by `plot` when the app exits.

**Comment by j9ac9k** [comment]
Can confirm, having the reference did the trick for avoiding the segfault (and due to @2xB I had that nice little warning about not having a reference too!).

**Comment by kangalioo** [comment]
Oh I see. That makes total sense. I wonder if it would make sense for all pyqtgraph objects to have the capability to create an application instance if needed?

**Comment by j9ac9k** [comment]
I'd be open to a PR for that, but I would be worried about performance issues with that lookup.  Also not entirely sure if that should occur (probably one of the objects that everything inherits?).

I know PySide2 5.15 recently changed how the `qApp` variable works, so I'd be really worried about making something fast and cross-compatible with our present number of supported Qt bindings.

**Comment by j9ac9k** [comment]
Closing due to need  for starting a QApplication instances and needing to store the plot with a python reference so the garbage collector doesn't grab it.
