### ISSUE TITLE
Plots with custom x-axis and default y-axis have the y-axis missing

### ISSUE THREAD

**Issue by kangalioo** [pyqtgraph/pyqtgraph#1234]
### Short description
This is such a hilariously random but game-breaking bug; here goes: When a plot has a custom x-axis, but **not** a custom y-axis, the y-axis doesn't appear.
This issue has been introduces somewhere in-between 5cd19ba7a0eccf5158b16257470279d1acf4e6a1 and 6bd029915207e96ec4bd37cf6f52be31c3f10ee0 (inclusive).

### Code to reproduce

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtGui

app = QtGui.QApplication([])

w = pg.PlotWidget(axisItems={"bottom": pg.DateAxisItem()})

w.show()
app.exec_()
```

### Expected behavior
The y axis should be there

### Real behavior
The y axis is not there

### Tested environment(s)

 * PyQtGraph version: 6bd029915207e96ec4bd37cf6f52be31c3f10ee0
 * Qt Python binding: PyQt5 5.14.2 Qt 5.14.2
 * Python version: 3.8.3
 * NumPy version: 1.17.4
 * Operating system: Arch Linux
 * Installation method: pip 

### Additional context
![Screenshot_20200607_214925](https://user-images.githubusercontent.com/21220820/83978572-c3ead100-a908-11ea-96c5-a1392c6519cc.png)

**Comment by j9ac9k** [comment]
I don't know if this qualifies as a bug, there are plenty of instances where a vertical axis may not be desirable, especially if you're explicitly specifying axes, but do not specify a vertical axis.

**Comment by ksunden** [comment]
related: https://github.com/pyqtgraph/pyqtgraph/pull/391

**Comment by j9ac9k** [comment]
Ahh thanks for the reference @ksunden we did indeed change some of this behavior... 

I'd be open to a suggestion as to why pyqtgraph should behave differently from how it does now, but the current behavior makes sense to me.  If you're going to specify axes, why would you be surprised if an axes you didn't specify isn't there.

**Comment by kangalioo** [comment]
I've always seen the axisItems argument as optional arguments. So, when you do `axisItems={"bottom": whatever}`, you're overwriting the default. I mean, the way you described it also make sense. Both ways make sense.

But seeing as pyqtgraph has always done it the former way, changing it would be a breaking change without particularly good reasoning imo

**Comment by 2xB** [comment]
I would suggest to revert the behaviour to what it was 6 days ago, since this would be a break between 0.10.0 and 0.11.0, which we try to avoid. This changes e.g. the plot customization example or the `dateaxisitem.py` example, and it definitely affects anyones application when someone is using custom axes with 0.10.0.

**Comment by ixjlyons** [comment]
Also note we now have two methods for setting the axis items:

https://github.com/pyqtgraph/pyqtgraph/blob/f43b2973125a4510fbd1dda300cce2cee249e422/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L263

https://github.com/pyqtgraph/pyqtgraph/blob/f43b2973125a4510fbd1dda300cce2cee249e422/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L325

It seems to be two independent implementations from #391 and #1154.

**Comment by j9ac9k** [comment]
oof ...when merging #391 I didn't think to account for the use of #1154, which came from well after the fact.

Is there a suggested implementation/behavior we should aim for?

**Comment by ksunden** [comment]
Would simply reverting #391 be an option? (more clearly, does the `setAxisItems` method introduced in #1154 subsume the usecase of #391 entirely, without breaking backwards compatibility?)

**Comment by j9ac9k** [comment]
I'm good with reverting #391 I would like to make sure that `setAxisItems` method introduced in #1154 meets the issue that #391 was trying to address.

**Comment by j9ac9k** [comment]
On further reflection, if things were good the way before, being on the eve of a release, let's just revert #391 and I'll revisit later.

**Comment by j9ac9k** [comment]
I reverted #391 @kangalioo can you verify you're getting the intended behavior?

**Comment by kangalioo** [comment]
Yes! Everything seems to work perfectly in the latest commit
