### ISSUE TITLE
CI should generate templates automatically

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#1281]
While working on fixing up PR 467, I found myself in a position of having to update templates manually for `pyqtgraph/graphicsItems/PlotItem/plotConfigTemplate_pyqt5.py`, `pyqtgraph/graphicsItems/PlotItem/plotConfigTemplate_pyside.py` and `pyqtgraph/graphicsItems/PlotItem/plotConfigTemplate_pyside2.py`.

I agree that pyqtgraph should ship these templates, but I think the burden on developers to maintain these manually across all the bindings is a bit much; and thus I propose that these templates are generated manually as part of the CI process, and passed along as artifacts to the build/wheel stage.

Thoughts?

**Comment by ksunden** [comment]
How fast are these to build? would it make more sense to be a pre-commit hook? That would likely be easier to implement (or at least use)

**Comment by j9ac9k** [comment]
The process is certainly fast enough for pre-commit, the problem is that they are unique to each binding.  You need to use pyside2 to generate a pyside2 compatible template, pyqt5 for a pyqt5 compatible template and so on.  Installing the pyqt4 and pyside1 bindings isn't trivial (no clue how to do it on non conda setups).

I'm envisioning an extra CI step before the wheel step, that automatically creates the needed conda environments for each qt binding we support, and just cycles through all them creating the templates.

**Comment by j9ac9k** [comment]
Going to close this out as I think we're moving away from using templates altogether.
