### ISSUE TITLE
pyside2 and pyqtgraph cleanup

### ISSUE THREAD

**Issue by eyou102** [pyqtgraph/pyqtgraph#1288]
### Short description
Apologies, i'm a little new to pyqtgraph in case I've missed something obvious in the setup docs.  Using PySide2 and pyqtgraph I get an exception on closing the application.  Window shows fine.  

Appears to be related to the cleanup function in pyqtgraph init.  cleanup fails when o is of type 'django.conf.LazySettings'.  Produces a django.core.exceptions.ImproperlyConfigured that I've caught for examining.

Catching this exception and allowing cleanup to continue eliminates the crash, but I haven't figured out what is actually going on yet.  Not much experience with django.

Minimum reproducible example is from the scatter plot demo.

### Code to reproduce

```python
from PySide2 import QtWidgets
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui
import numpy as np
import sys

app = QtWidgets.QApplication()
win = pg.GraphicsLayoutWidget(show=True)

sys.exit(app.exec_())
```

### Expected behavior
Application closes successfully

### Real behavior
Application produces the following traceback

```
Traceback (most recent call last):
  File "C:\PydroXL_19\envs\Pydro38_Test\lib\site-packages\pyqtgraph\__init__.py", line 316, in cleanup
    if isinstance(o, QtGui.QGraphicsItem) and isQObjectAlive(o) and o.scene() is None:
  File "C:\PydroXL_19\envs\Pydro38_Test\lib\site-packages\django\utils\functional.py", line 224, in inner
    self._setup()
  File "C:\PydroXL_19\envs\Pydro38_Test\lib\site-packages\django\conf\__init__.py", line 57, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested settings, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Qt Python binding: PySide2 5.13.2 Qt 5.12.5
 * Python version: 3.8.2
 * NumPy version: 1.18.4
 * Operating system: Windows 10
 * Installation method: conda

**Comment by j9ac9k** [comment]
I've never messed with Django, and don't really know anything about web frameworks; I must admit I'm curious about your application that uses a desktop GUI framework alongside a web framework!

I'm not sure what would cause this error, the if statement is a series of 3 and conditions, and if `o` is of type `django.conf.LazySettings` it should fail the first condition, `isinstance(o, QtGui.QGraphicsItem)`, but does merely querying the type of `django.conf.LazySettings` cause it to misbehave in such a manner?

**Comment by ixjlyons** [comment]
Can't reproduce so far, at least on Linux. Do you have any other Django stuff imported or running when you run the example code above? I can't figure out how there could be a `LazySettings` object picked up by `gc.get_objects()` if nothing from Django is imported. Is this error thrown in a fresh Python shell?

**Comment by eyou102** [comment]
Thanks for the replies.  I now see it is only in my Pycharm console.  It by default seems to include Django, I'll have to look into what config options I have there.

I suppose that doesn't have anything to do with pyqtgraph, so I can close this issue if you think that is best.

**Comment by j9ac9k** [comment]
If you can reproduce this issue outside of the pycharm console let us know and we'll reopen but I'm the mean time I'm not sure we can help with this, sorry!

**Comment by galilley** [comment]
In fact I've just observed some interference of pyqtgraph-0.12.2 with diskcache module.  To reproduce it is enough make an import in the code from the first message like:
`from diskcache import Cache`.

However, it should be noted that the last version (0.13.3) works perfectly!

p.s. OS Linux, pip, pure python3 run.
