### ISSUE TITLE
DeprecationWarning in ThreadsafeTimer on creating parameter tree

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#1292]
### Short description

I noticed this running pytests for my application.

Wrap the examples code for parameter tree in a `test_` function so pytest can run it:

```python
# Everything before here is pasted directly from "pyqtgraph.examples -> parameter tree"

# The only difference between the following and the default example is wrapping it in a test function
def test_param():
  ## Create two ParameterTree widgets, both accessing the same data
  t = ParameterTree()
  t.setParameters(p, showTop=False)
  t.setWindowTitle('pyqtgraph example: Parameter Tree')
  t2 = ParameterTree()
  t2.setParameters(p, showTop=False)

  win = QtGui.QWidget()
  layout = QtGui.QGridLayout()
  win.setLayout(layout)
  layout.addWidget(QtGui.QLabel("These are two views of the same data. They should always display the same values."), 0,  0, 1, 2)
  layout.addWidget(t, 1, 0, 1, 1)
  layout.addWidget(t2, 1, 1, 1, 1)
  win.show()
  win.resize(800,800)

  ## test save/restore
  s = p.saveState()
  p.restoreState(s)
```

### Expected behavior

The test should succeed with no warnings

### Real behavior

```
============================== warnings summary ===============================
testparam.py: 24 tests with warnings
  C:\Users\ntjes\miniconda3\envs\py38\lib\site-packages\pyqtgraph\ThreadsafeTimer.py:26: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    self.timer.start(timeout)
```

adding a `warnings.simplefilter` to the example reveals the traceback:
```
Traceback (most recent call last):
  File "C:\Users\ntjes\miniconda3\envs\py38\lib\site-packages\pyqtgraph\SignalProxy.py", line 53, in signalReceived
    self.timer.start((self.delay*1000)+1)
  File "C:\Users\ntjes\miniconda3\envs\py38\lib\site-packages\pyqtgraph\ThreadsafeTimer.py", line 26, in start
    self.timer.start(timeout)
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Qt Python binding: PyQt5 5.15.0 Qt 5.15.0
 * Python version: Python 3.8.3
 * NumPy version: 1.19.0
 * Operating system: Windows 10
 * Installation method: pip

**Comment by j9ac9k** [comment]
Fixed with https://github.com/pyqtgraph/pyqtgraph/commit/b058d032d12305574a2851943bfded1c2c4beff1

**Comment by ntjess** [comment]
Same issue occurs here: https://github.com/pyqtgraph/pyqtgraph/blob/d8e4911fcd5fd8dbb86f059c0c53824e2b48ddc2/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L382

Similar to the reported issue, I don't see the warning unless during a pytest.

**Comment by j9ac9k** [comment]
Hi @ntjess can you verify which commit you're at, at this point we shouldn't really be getting any warnings from pytest.

**Comment by ntjess** [comment]
I get this warning on `0.11.0+g8fce6c6` (upgrading directly from `develop`, has many more warnings) and `0.11.1`

**Comment by j9ac9k** [comment]
`develop` branch is pretty far behind now, we've switched to `master` (and will likely switch to `main` once the PR count is down more).

If you're on the current commit of the master branch, and getting warnings, please open up a new issue (fair warning, on windows hidpi displays, I do get warnings/failures).

**Comment by ntjess** [comment]
Done, #1484
