### ISSUE TITLE
Import failure when launching cx_frozen application with pyqtgraph

### ISSUE THREAD

**Issue by berr** [pyqtgraph/pyqtgraph#1303]
### Short description
Freezing an application on linux with cx_freeze and python 3.8 leads to an error when importing pyqtgraph:
`ImportError: cannot import name 'ThreadsafeTimer' from partially initialized module 'pyqtgraph' (most likely due to a circular import)`

### Code to reproduce
Have the 3 files in your folder. Setup the virtual environment using requirements.txt and run the following commands:

```
python3 setup.py build  # build the executable
./build/exe.linux-x86_64-3.8/repro  #run it
```

File `repro.py`
```python
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import pyqtgraph as pg

app = QtGui.QApplication([])
win = pg.GraphicsLayoutWidget(show=True, title="Basic plotting examples")
p1 = win.addPlot(title="Basic array plotting", y=np.random.normal(size=100))

if __name__ == '__main__':
    QtGui.QApplication.instance().exec_()
```
File `setup.py`
```python
import sys
from cx_Freeze import setup, Executable
from pathlib import Path

include_files = []

if sys.platform == "linux":
    # On linux the numpy libraries are in site-packages/numpy.libs, but cx_freeze copies them to
    # lib/numpy/*.so instead of lib/numpy.libs/*.so
    import numpy
    numpy_folder = Path(numpy.__file__).parent
    for numpy_shared_library in numpy_folder.with_name("numpy.libs").iterdir():
        include_files.append((str(numpy_shared_library), f"lib/numpy.libs/{numpy_shared_library.name}"))

build_options = {
    "packages": [],
    "includes": [],
    "excludes": [],
    "zip_exclude_packages": "*",
    "zip_include_packages": "",
    "include_files": include_files,
}


base = 'Win32GUI' if sys.platform == 'win32' else None

executables = [
    Executable('repro.py', base=base)
]

setup(name='bug repro',
      version='1.0',
      description='bug repro',
      options={"build_exe": build_options},
      executables=executables)

```

File requirements.txt
```
cx-Freeze==6.1
numpy==1.19.0
pyqtgraph==0.11.0
PySide2==5.14.2.2
shiboken2==5.14.2.2
```

### Expected behavior
The application should launch normally.

### Real behavior
An exception is raised:

```
Traceback (most recent call last):
  File "/home/berr/Desktop/pyqtgraph_bug/venv/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
    module.run()
  File "/home/berr/Desktop/pyqtgraph_bug/venv/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
    exec(code, {'__name__': '__main__'})
  File "repro.py", line 1, in <module>
    from pyqtgraph.Qt import QtGui, QtCore
  File "/home/berr/Desktop/pyqtgraph_bug/venv/lib/python3.8/site-packages/pyqtgraph/__init__.py", line 213, in <module>
    from .graphicsItems.HistogramLUTItem import * 
  File "/home/berr/Desktop/pyqtgraph_bug/venv/lib/python3.8/site-packages/pyqtgraph/graphicsItems/HistogramLUTItem.py", line 11, in <module>
    from .GradientEditorItem import *
  File "/home/berr/Desktop/pyqtgraph_bug/venv/lib/python3.8/site-packages/pyqtgraph/graphicsItems/GradientEditorItem.py", line 9, in <module>
    from ..widgets.SpinBox import SpinBox
  File "/home/berr/Desktop/pyqtgraph_bug/venv/lib/python3.8/site-packages/pyqtgraph/widgets/SpinBox.py", line 10, in <module>
    from ..SignalProxy import SignalProxy
  File "/home/berr/Desktop/pyqtgraph_bug/venv/lib/python3.8/site-packages/pyqtgraph/SignalProxy.py", line 4, in <module>
    from . import ThreadsafeTimer
ImportError: cannot import name 'ThreadsafeTimer' from partially initialized module 'pyqtgraph' (most likely due to a circular import) (/home/berr/Desktop/pyqtgraph_bug/build/exe.linux-x86_64-3.8/lib/pyqtgraph/__init__.pyc)
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Qt Python binding: PySide2 5.14.2.2 Qt 5.14.2
 * Python version: 3.8.2
 * NumPy version: 1.19.0
 * Operating system: Gentoo Linux
 * Installation method: pip

**Comment by j9ac9k** [comment]
And here I thought nobody was using the `build` functionality of cx_freeze and was considering removing it.

Thanks for PR #1304 I will merge shortly.  I was hoping you could describe a little more your use case in general.

**Comment by berr** [comment]
Thanks for the fast merge :)

We develop scientific applications for the Oil & Gas industry and deploy them to be used on their own servers/clusters. 
Since we don't have control of their servers we have to freeze the application to make sure we're using the correct version of libraries and interpreter.
pyqtgraph was the best choice in terms of plotting speed (our plots must be interactive and matplotlib times were prohibitively slow for that) and ease to integrate into our qt application.

**Comment by j9ac9k** [comment]
I used to work in oil and gas once upon a time...feel for the industry right now.

If you don't mind me asking, is there a reason you don't use `pyinstaller` or `fbs` (which is a wrapper for pyinstaller and some other tools) to generate installable packages (AppSetup.exe files on windows, App.dmg files on macOS, and App.deb for linux)?

**Comment by berr** [comment]
I didn't use`pyinstaller` because we wanted to use python 3.8 and it seems that support isn't there yet. 
I didn't know about `fbs`, it seems pretty cool. But the licensing isn't that friendly for commercial applications (too expensive for non gpl, and according to them the support for pyside isn't as mature as for pyqt).

**Comment by j9ac9k** [comment]
Good reasons. Honestly I had assumed the build functionality had stopped working some time ago and just nobody had noticed, and was considering removing it.  I'll think about how to get they functionality tested in our CI pipelines.

The unfortunate fact is we (maintainers) have remarkably little knowledge about what functionality I'm our library is used

If you have suggestions on how to integrate the build component in a testible way into the test suite, please let us know.
