### ISSUE TITLE
PolyLineROI ignores hoverPen argument

### ISSUE THREAD

**Issue by ibrewster** [pyqtgraph/pyqtgraph#1308]
### Short description
When creating a PolyLineROI and specifying the hoverPen argument, the ROI created still uses the default yellow solid line for the hover pen.

### Code to reproduce

```python
import pyqtgraph as pg

roi=pg.PolyLineROI([(1,1),(1,5),(5,5),(5,1)], hoverPen='b') #Or whatever
```

### Expected behavior
When hovering over the ROI, the pen used to draw the ROI should change to the specified pen

### Real behavior
A solid yellow pen is used instead.
### Tested environment(s)

 * PyQtGraph version: 0.11.0+g11edbc0

### Problem/Solution

In ROI.py, in the _makePen function of _PolyLineSegment, the check for self.mouseHovering or self._parentHovering, line 2247, has the default yellow pen hard-coded as the return value. Instead, it should return self.hoverPen

**Comment by ibrewster** [comment]
Additionally, it would appear that self.hoverPen needs to be passed to the call to _PolyLineSegment (as the hoverPen argument) on line 2007, in the addSegment function. Perhaps there are other missing parameters here as well? This is just the one I noticed.

**Comment by ixjlyons** [comment]
Good catch. I'll try to get this fixed soon.

#1285 for reference
