### ISSUE TITLE
"tip" text more easily accessed by user?

### ISSUE THREAD

**Issue by jaxankey** [pyqtgraph/pyqtgraph#1313]
Hi all,

Very minor issue: currently in a ParameterTree (and other widgets, presumably), the "tip" option works, but it requires that the user select the item before the tip text pops up. It would be nice if it showed up more easily, e.g., when hovering with the mouse even when the value (or item itself) is not selected.

 * PyQtGraph version: v0.11.0
 * Qt Python binding: 'PyQt5 5.9.2 Qt 5.9.6'
 * Python version: 3.7
 * NumPy version: 1.18.5
 * Operating system: Linux Mint 20
 * Installation method: conda

**Comment by ntjess** [comment]
This is how I get that behavior in my parameter trees, especially since I also want the tooltip when hovering over the left column too:
```python
# Tree is a parameter tree
iterator = QtWidgets.QTreeWidgetItemIterator(tree)
    item: QtWidgets.QTreeWidgetItem = iterator.value()
    while item is not None:
      # if self.tree.itemWidget(item, 0) is None:
      #   lbl = QtWidgets.QLabel(item.text(0))
      #   self.tree.setItemWidget(item, 0, lbl)
      if ('tip' in item.param.opts
          and len(item.toolTip(0)) == 0
          and self.tree.itemWidget(item, 0) is None):
        item.setToolTip(0, item.param.opts['tip'])
      iterator += 1
      item = iterator.value()
```

Is that (sort of) what you're looking for?

**Comment by jaxankey** [comment]
Looks like a step in the right direction, (this will provide a tip from any location so long as the item is selected?). I'm wondering about a step further, where simply moving the mouse over something pops up a tip, without that item being selected.

I will probably incorporate this code if I can figure it out. Do you have a minimal working code that I could use to test its functionality?

**Comment by ntjess** [comment]
It actually should work on hover -- it's the code I'm using for this app:
![a5ad7eaa-6f6e-43f5-bc0b-91f2c43eba16](https://user-images.githubusercontent.com/23620506/88548831-97406500-cfed-11ea-8220-e2ff631bb5b3.gif)

**Comment by jaxankey** [comment]
That's awesome. Thanks!

**Comment by jaxankey** [comment]
(This should be the default behavior IMO :+1: )
