### ISSUE TITLE
#816 broke #922/#999

### ISSUE THREAD

**Issue by campagnola** [pyqtgraph/pyqtgraph#1322]
- In #922, a line was introduced completely surrounding the fill area of a PlotCurveItem
- In #999, this feature was made optional since it was an unexpected change for some (perhaps most) users of plot curve fill
- In #816, the code for drawing the fill outline in PlotCurveItem.paint was removed (https://github.com/pyqtgraph/pyqtgraph/pull/816/files#diff-b064b448cfe1000597d68d33cc5781b7L512), but the option still remains in the API.

**Comment by j9ac9k** [comment]
Fixed with #1456
