### ISSUE TITLE
what is : w and h parameters in method “ ItemAt (region=(x,y,w,h)) ”of class GLViewWidget ? 

### ISSUE THREAD

**Issue by banacch** [pyqtgraph/pyqtgraph#1330]
---> stands for parameters w and h in method ItemAt (region=(x,y,w,h)) of class GLViewWidget

I would to select region(maybe a region that contains a specific point with very small size) with extremely precision. So I don't know to set w and h to get this precision ! I think to know about x and y .

Thanks for help.

**Comment by j9ac9k** [comment]
Hi @banacch , sorry nobody followed up with you earlier.  I don't generally work w/ the 3D components of this library but generally `w` and `h` corresponds to width and height.  `x` and `y` correspond to the location of the upper-left corner of the region.

I'm going to close out this issue; but if you have further questions let us know, it shouldn't take us 6 months to follow up.
