### ISSUE TITLE
updating a GLVolumeItem within a PyQt5/PySide2 app

### ISSUE THREAD

**Issue by alekk** [pyqtgraph/pyqtgraph#1338]
### Short description
I am displaying a 3D cube in a `GLVolumeItem`, the whole thing displayed in a small PySide2 gui.
When a button is pressed, the content of the cube is updated. Unfortunately, this create issues: 
the colors are messed up, and only a subpart of the cube is updated.
<img width="250" alt="green" src="https://user-images.githubusercontent.com/1282389/88880968-b4309e80-d260-11ea-9414-ae4a296b3479.png">
while it should be all in red:
<img width="250" alt="red" src="https://user-images.githubusercontent.com/1282389/88880976-bdba0680-d260-11ea-996a-1d032fac00e5.png">

1. on MacOS Sierra 10.12.6: the issue is here (sorry, cannot test on later version) 
2. the bug is not there on Windows10 apparently: it is working
3. the "bug" is not there if the cube is updated directly (i.e. bypassing the button -- see code)
4. a dirty hack is to update first with a small empty cube before doing the actual update (see code)
5. the bug is there with `PySide2` and with `PyQt5`
6. also there when trying with PyOpenGL==3.1.0

### Code to reproduce
```python
import numpy as np
#import PyQt5
#from PyQt5 import QtWidgets, QtCore, QtGui
from PySide2 import QtWidgets, QtCore, QtGui
import PySide2

import pyqtgraph as pg
import pyqtgraph.opengl as gl

import sys, os

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)

        #create a button
        button_Test = QtWidgets.QPushButton("Change Cube")
        button_Test.clicked.connect(self.onTestClick)

        #create a 3d cube
        dx,dy,dz = 200,200,200
        self.data = np.zeros((dx,dy,dz,4), dtype=np.ubyte)
        self.data[:,:,:,1] = 200
        self.data[:,:,:,3] = 200

        #display cube
        self.w = gl.GLViewWidget()
        self.w.opts['distance'] = 500
        self.v = gl.GLVolumeItem(self.data, smooth=True)
        self.v.translate(-dx//2,-dy//2,-dz//2)
        self.w.addItem(self.v)

        #put everything in a horizontal box
        hbox = QtWidgets.QHBoxLayout()
        hbox.addWidget(button_Test)
        hbox.addWidget(self.w)

        #display
        widget = QtWidgets.QWidget()
        widget.setLayout(hbox)
        self.setCentralWidget(widget)

        # if the color of the cube is updated here, this works:
        #self.update_cube()

    def update_cube(self):
        # color the cube in red
        self.data[:,:,:,:] = 0
        self.data[:,:,:,0] = 200
        self.data[:,:,:,3] = 200

        # if the two following two lines are added, this kinda work
        #self.v.setData(np.zeros((1,1,1,4), dtype=np.ubyte))
        #self.v.paint()

        self.v.setData(self.data)

    def onTestClick(self):
        self.update_cube()

if __name__ == '__main__': 
    app = QtWidgets.QApplication(sys.argv)
    app.processEvents()
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
```

### Error

Only displayed error, but may not be related:
`Unable to load numpy_formathandler accelerator from OpenGL_accelerate`

### Tested environment(s)

 * PyQtGraph version: 0.11
 * Qt Python binding: 'PySide2 5.13.2 Qt 5.13.2'
 * Python version: Python 3.7.8 | packaged by conda-forge
 * NumPy version: '1.19.1'
* PyOpenGL==3.1.5
* PyOpenGL-accelerate==3.1.5
 * Operating system: MacOS Sierra 10.12.6
 * Installation method: tried both with pip and conda --> error in both

**Comment by j9ac9k** [comment]
Hi @alekk sorry nobody followed up with you on this.  

I just tested your minimum working example  on the current release 0.13.1 and things worked as they're supposed to with PySide2
