### ISSUE TITLE
LabelItem.getLabel method missing in pyqtgraph-0.11.0

### ISSUE THREAD

**Issue by iustin94** [pyqtgraph/pyqtgraph#1342]
Hello, I've noticed that on the 0.11.0 release, the **getLabel** method is missing along with some other parts of the class. It seems though that they have been added back at a later point on the master branch. Is it possible to fix this in the repository so that my project wheel can get the latest version without having to check out a custom git commit from the master?

To give a bit more context, in my local clone of the project, the tag pyqtgraph-0.11.0 points to commit id "f76fb3a" however, the master branch commit points to c8fc221. Somewhere along the way, the **getLabel** was removed and then added back. Per the documentation it should be there.

**Comment by ixjlyons** [comment]
I'm assuming you mean `LegendItem.getLabel`. I recall somewhat of a mess created by merging a couple PRs, one of which was somewhat old. In any case, another release is probably not a bad idea - I believe a few regressions introduced with 0.11.0 have been found and fixed.

**Comment by j9ac9k** [comment]
There are 3 very similar PRs that Luke wanted to performance test.  We
should probably nag him about those

**Comment by j9ac9k** [comment]
As this issue was fixed in the master branch, I'm going to close out this issue.  We're getting close to releasing 0.11.1, this issue should sort itself out shortly.
