### ISSUE TITLE
Possible bug with version 0.11.0

### ISSUE THREAD

**Issue by da0c** [pyqtgraph/pyqtgraph#1353]
### Short description
Possible bug with creating ImageItem in version 0.11.0

### Code to reproduce

```python
import sys
import pyqtgraph as pg
from PyQt5.QtWidgets import QApplication, QWidget
 
class TestWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
 
        # setting property causes an error with 0.11.0 but works well with 0.10.0
        self._imitem = pg.ImageItem(autoDownsample=True)
        # without setting works well with 0.11.0
        # self._imitem = pg.ImageItem()
 
        self._viewbox = pg.ViewBox()
        # the following line rises the error
        self._viewbox.addItem(self._imitem)
 
class MainWidget(QWidget):
    def __init__(self):
        super().__init__()
        self.testWidget = TestWidget(self)
 
def main():
    app = QApplication(sys.argv)
    mw = MainWidget()
    mw.show()
    return app.exec()
 
if __name__ == '__main__':
    main()
```

### Expected behavior
the code works in all previous versions of pyqtgraph.

### Real behavior
In version 0.11.0 the error rises.
Please see comments around the line
`self._imitem = pg.ImageItem(autoDownsample=True)`

```
Traceback (most recent call last):
  File "C:\_RT\OpenNFT\venv\lib\site-packages\pyqtgraph\graphicsItems\GraphicsObject.py", line 23, in itemChange
    self.parentChanged()
  File "C:\_RT\OpenNFT\venv\lib\site-packages\pyqtgraph\graphicsItems\GraphicsItem.py", line 458, in parentChanged
    self._updateView()
  File "C:\_RT\OpenNFT\venv\lib\site-packages\pyqtgraph\graphicsItems\GraphicsItem.py", line 515, in _updateView
    self.viewTransformChanged()
  File "C:\_RT\OpenNFT\venv\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 558, in viewTransformChanged
    w = Point(x-o).length()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Traceback (most recent call last):
  File "C:\_RT\OpenNFT\venv\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 558, in viewTransformChanged
    w = Point(x-o).length()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Traceback (most recent call last):
  File "C:\_RT\OpenNFT\venv\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 558, in viewTransformChanged
    w = Point(x-o).length()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
Traceback (most recent call last):
  File "C:\_RT\OpenNFT\venv\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 558, in viewTransformChanged
    w = Point(x-o).length()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Qt Python binding: PyQt5 5.13.2 Qt 5.13.2
 * Python version: 3.6.3
 * NumPy version: 1.17.4
 * Operating system: Windows 7/10
 * Installation method: pip

### Additional context

Initially, we get this bug in our project OpenNFT after upgrading pyqtgraph from 0.10.0 to 0.11.0,
the error rises in this line:
https://github.com/OpenNFT/OpenNFT/blob/master/opennft/opennft.py#L154

P.S. Actually, all works well for 0.11.0.dev0 too.

**Comment by ixjlyons** [comment]
Introduced with #755. I think the solution is pretty straightforward, just checking if `o`/`x`/`y` is None:

https://github.com/pyqtgraph/pyqtgraph/blob/9fdaffaf7dbdd1aaac7ab482afb5ceab21e81a31/pyqtgraph/graphicsItems/ImageItem.py#L553-L559

...as is done in `render()`:

https://github.com/pyqtgraph/pyqtgraph/blob/9fdaffaf7dbdd1aaac7ab482afb5ceab21e81a31/pyqtgraph/graphicsItems/ImageItem.py#L378-L380

For what it's worth, this shouldn't really have any negative consequences aside from the error messages.

I'm not sure off hand why `viewTransformChanged` is getting called when `ImageItem.scene()` is still None. It could be worth digging into that a bit more.

Thanks for reporting.

**Comment by da0c** [comment]
It looks like a solution.
Thank you for answer.
