### ISSUE TITLE
Function analogue to matplotlib.pyplot.text? 

### ISSUE THREAD

**Issue by vitsensei** [pyqtgraph/pyqtgraph#1363]
Hi,
I wonder if there is such a function that is analogue to [matplotlib.pyplot.text](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.text.html)? 

It's basically a function to plot some text on a certain coordinate. I have look at some example such as [text.py](https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/text.py) but it does not have the similar function syntax. In particular, I believe that the text item is related to the parent through "anchor" attribute, which I don't think is very intuitive.

**Comment by j9ac9k** [comment]
Hi,

This is what I typically do to accomplish that.

```python
textItem = pg.TextItem("text", anchor=(0, 0))
textItem.setParentItem(yourViewBox)
textItem.setPos(QPointF(10, 10))  # places in upper left corner of the viewbox
```

**Comment by vitsensei** [comment]
@j9ac9k the problem with setting parent item to the ViewBox is textItem will not move as I pan around. 

I have a scatter plot which I would like to put some annotation right next to each of the scatter points.

**Comment by j9ac9k** [comment]
> @j9ac9k the problem with setting parent item to the ViewBox is textItem will not move as I pan around. 
> 
> 
> 
> I have a scatter plot which I would like to put some annotation right next to each of the scatter points.

Oh I misunderstood... There is an example that shows how to place a text item within the coordinate system inside the viewbox...

Instead of calling setParentItem do viewBox.addItem(textItem) and set the position.

**Comment by vitsensei** [comment]
Perfect. Thank you, @j9ac9k !

**Comment by vitsensei** [comment]
Hi @j9ac9k . A small question, I found out that as soon as I plot multiple text item (adding them individually to my view box), the performance went down significantly, which is expected. 

I wonder is there any trick to increase the performance? I know that when plotting multiple disconnected lines, we can try to add all the lines together and only plot one single line, with connect attribute to mirroring the disconnected appearance.

**Comment by j9ac9k** [comment]
I'm actually dealing w/ a performance issue myself when I start passing > 1,000 text items... but to handle the case of > 100 items, the issue is in the `viewBox.addItem(textItem)` method ...so I sort of skirted that method and add my items in the following fashion

```python
graphicsItems = []
for text in list_of_text:
   textItem = pg.TextItem(text)
   textItem.setParentItem(viewBox.childGroup)
   textItem.setPos(whatever_you_want)
   graphicsItems.append(textItem)
viewBox.addedItems.extend(graphicsItems)
```

The call to create `pg.TextItem` takes about the same period of time as `textItem.setParentItem(viewBox.childGroup)` ... If you find a way to add a bazillion text items w/o issue, let me know!

**Comment by vitsensei** [comment]
@j9ac9k Very interesting solution. I just tried it and it makes a huge difference. Not only the overhead is reduced but also when you pan around the plot.

> If you find a way to add a bazillion text items w/o issue, let me know!
Definitely!

**Comment by j9ac9k** [comment]
yeah, the main issue with `viewBox.addItem` is it tries to see if the viewBox needs adjusting.  I think there is some code to handle bugs in older versions of Qt as well.

If you're interested in profiling code, the library has a _fantastic_ profiler in `debug.py`

```
import pyqtgraph as pg

profiler = pg.debug.Profiler(disabled=False, delayed=False)
# do stuff
profiler("did stuff")
# do more stuff
profiler("did more stuff")
....
```

you get the idea, it's been _super_ helpful in narrowing down any performance related issues.
