### ISSUE TITLE
ImageView unexpected behavior with `useOpenGL` and `autoDownsample`

### ISSUE THREAD

**Issue by edumur** [pyqtgraph/pyqtgraph#1371]
### Short description
When ImageItem.autoDownsample is set to False and useOpenGL set to True, the image shown does not correspond to the data.

### Code to reproduce

I wrote an independent script which reproduce the "error".

```python

import numpy as np
from pyqtgraph.Qt import QtCore, QtGui
import pyqtgraph as pg

pg.setConfigOptions(imageAxisOrder='row-major')
pg.setConfigOption('useOpenGL', True) # Set to False to get the expected behavior

data = np.random.random((20001,9))


app = QtGui.QApplication([])

win = QtGui.QMainWindow()
win.resize(800,800)

pw = pg.PlotWidget()
plotItem = pw.getPlotItem()

win.setCentralWidget(pw)

imageItem = pg.ImageItem()
imageItem.autoDownsample = False

imageView = pg.ImageView(imageItem=imageItem)
imageView.setImage(data)
imageView.autoRange()
imageView.view.invertY(False)
imageView.view.setAspectLocked(False)

plotItem.showGrid(x=True, y=True)
plotItem.vb.addItem(imageItem)

win.show()


if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()

```

### Expected behavior

![image](https://user-images.githubusercontent.com/13218882/93447332-94b60980-f8d2-11ea-933c-4561fd3b7767.png)

On this picture, obtained with `pg.setConfigOption('useOpenGL', False)` we see 9 column corresponding to the 9 column of the data array.

### Real behavior

![image](https://user-images.githubusercontent.com/13218882/93447483-be6f3080-f8d2-11ea-8068-660e8a6244a2.png)

On this picture, obtained with `pg.setConfigOption('useOpenGL', True)` we see 7 column instead of 9.

### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Qt Python binding: PyQt5 5.9.2 Qt 5.9.6
 * Python version: Python 3.7.7
 * NumPy version: 1.18.1
 * Operating system: windows 10
 * Installation method: conda

### Additional context

I "solved" this issue by setting `useOpenGL` to False in the software we wrote with pyqtgraph however this makes many of our plot much slower.

**Comment by ixjlyons** [comment]
This is a weird one. I can reproduce with PyQt5 and PySide2. If you save the `QImage` (`ImageItem.save` or `ImageView.export`), the file does end up 9 pixels wide. So if the `QImage` is correct and it's passed directly to `QPainter.drawImage`, I'm thinking this is an upstream issue in Qt. That said, we *are* using the deprecated `QGLWidget`, so perhaps migrating to `QOpenGLWidget` would resolve this.

**Comment by edumur** [comment]
Hi, I tried to replace all occurrences of `QGLWidget` in "GraphicsView" and "GLViewWidget" by `QOpenGLWidget` and that didn't modified the results.

**Comment by pijyoi** [comment]
@edumur , I modified your example to:

1. remove ImageView. ImageView is a standalone widget.
2. draw RGB bars to make the problem more apparent
3. draw your large image in separate ImageItems of size "chunk_size"

On my system, a maximum chunk_size of 8192 will draw a good image. Anything larger will get a bad image. The bad image differs depending on whether you are using QGLWidget or QOpenGLWidget. 

I think you are hitting some inherent limit of using OpenGL. (On my system, GL_MAX_TEXTURE_SIZE is reported as 16384.) So the workaround is to draw your large image in separate smaller chunks as is done in the modified example.

```python
import numpy as np
from pyqtgraph.Qt import QtCore, QtGui
import pyqtgraph as pg

pg.setConfigOptions(imageAxisOrder='row-major')
pg.setConfigOption('useOpenGL', True)
# pg.setConfigOption('enableExperimental', True)

num_rows = 20001
chunk_size = 8192

data = np.zeros((num_rows,9,3), dtype=np.uint8)
for x in range(data.shape[1]):
    data[:,x,x%3] = 255

app = pg.mkQApp()

pw = pg.PlotWidget()
plotItem = pw.getPlotItem()
plotItem.showGrid(x=True, y=True)
pw.show()

num_chunks = (num_rows + chunk_size - 1) // chunk_size
for idx in range(num_chunks):
    row_beg = idx * chunk_size
    row_end = min(row_beg + chunk_size, num_rows)
    imgitem = pg.ImageItem(data[row_beg:row_end,...], autoDownsample=False)
    imgitem.setRect(QtCore.QRectF(0, row_beg, data.shape[1], row_end - row_beg))
    plotItem.addItem(imgitem)

app.exec_()
```

**Comment by j9ac9k** [comment]
Hi @edumur Given we have merged #1525 and the workaround @pijyoi provided, I think we can close this.  You still running into the issue?

**Comment by edumur** [comment]
Well I tried to update pyqtgraph in a python 3.8 environment to the latest git version using `pip install git+https://github.com/pyqtgraph/pyqtgraph@master` and I got this error:

```bash
Traceback (most recent call last):
  File ".\b.py", line 2, in <module>
    from pyqtgraph.Qt import QtCore, QtGui
  File "C:\Users\ed261978\Anaconda3\envs\python38\lib\site-packages\pyqtgraph\__init__.py", line 13, in <module>
    from .Qt import QtGui, mkQApp
  File "C:\Users\ed261978\Anaconda3\envs\python38\lib\site-packages\pyqtgraph\Qt.py", line 137, in <module>
    from PyQt5 import QtGui, QtCore, QtWidgets, sip, uic
ImportError: cannot import name 'sip' from 'PyQt5' (C:\Users\ed261978\Anaconda3\envs\python38\lib\site-packages\PyQt5\__init__.py)
```

I will try harder soon...

**Comment by pijyoi** [comment]
If you are still using ```Qt Python binding: PyQt5 5.9.2 Qt 5.9.6```, you need to update to at least 5.12, preferably 5.15.

**Comment by edumur** [comment]
> If you are still using `Qt Python binding: PyQt5 5.9.2 Qt 5.9.6`, you need to update to at least 5.12, preferably 5.15.

I did: `pip install pyqt5`.
which gave me:
```bash
Collecting pyqt5
  Downloading PyQt5-5.15.4-cp36.cp37.cp38.cp39-none-win_amd64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 6.8 MB/s
Collecting PyQt5-Qt5>=5.15
  Downloading PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
     |████████████████████████████████| 50.1 MB 6.4 MB/s
Collecting PyQt5-sip<13,>=12.8
  Downloading PyQt5_sip-12.8.1-cp38-cp38-win_amd64.whl (63 kB)
     |████████████████████████████████| 63 kB 686 kB/s
Installing collected packages: PyQt5-Qt5, PyQt5-sip, pyqt5
Successfully installed PyQt5-Qt5-5.15.2 PyQt5-sip-12.8.1 pyqt5-5.15.4
```
So I guess my pyqt version is fine no.

However when I run the script above **I still go the unexpected behavior**...

**Comment by pijyoi** [comment]
Then the following should fail for you too, outside of pyqtgraph.
```
python -c "import PyQt5.sip"
```
Perhaps there may be some lingering older install of sip in your environment?

In any case, side-by-side installs of PyQt{5,6} are possible these days.
```
python -c "import PyQt5.sip; import PyQt6.sip"
```

**Comment by edumur** [comment]
I created a fresh conda environment with python 3.8 and did:
```bash
pip install git+https://github.com/pyqtgraph/pyqtgraph@master
pip install pyqt5
pip install pyopengl
```

and I still got the unexpected behavior.

@pijyoi What do you get if you run the script above?

**Comment by pijyoi** [comment]
I don't use Anaconda, I use vanilla Python from www.python.org
```
C:\work\venv>py -m venv testenv
C:\work\venv>testenv\Scripts\activate
(testenv) C:\work\venv>pip install git+https://github.com/pyqtgraph/pyqtgraph@master
(testenv) C:\work\venv>pip install pyqt5
(testenv) C:\work\venv>python -c "from PyQt5 import sip; print(sip.SIP_VERSION_STR)"
5.4.0
(testenv) C:\work\venv>pip list
Package    Version
---------- -----------
numpy      1.20.1
pip        20.2.3
PyQt5      5.15.4
PyQt5-Qt5  5.15.2
PyQt5-sip  12.8.1
pyqtgraph  0.11.1.dev0
setuptools 49.2.1
```

**Comment by edumur** [comment]
And what do you get if you run the script above, the expected or unexpected behavior?

**Comment by pijyoi** [comment]
So to run the script, I would need to install, in addition, pyopengl.
The script runs with no errors.

![capture](https://user-images.githubusercontent.com/2657027/111979002-837add80-8b3f-11eb-9d33-7259b6e8c1f6.PNG)

**Comment by edumur** [comment]
That's interesting!
I will dig more on my environment ;) .

**Comment by edumur** [comment]
Hi,

Yep, my bad 😅 it is working like a charm \o/ .

Thanks @pijyoi for your fix.

**Comment by j9ac9k** [comment]
Thanks @pijyoi and @edumur for following up.  Glad it's working out!
