### ISSUE TITLE
Axis ticks always with scientific notation.

### ISSUE THREAD

**Issue by 3fon3fonov** [pyqtgraph/pyqtgraph#1372]
In Astronomy, we often plot BJD (Barycentric Julian Day) on the x-axis. However, there is no easy way to plot the exact BJD's, and instead, I got this:

![Ticks_wrong](https://user-images.githubusercontent.com/44244057/93690161-694f3c80-fad5-11ea-826f-d6d251790afb.png)

Whereas, it must be:

![Ticks_right](https://user-images.githubusercontent.com/44244057/93690166-7835ef00-fad5-11ea-96b8-190ac2ca8cda.png)

The best way I found is to hack AxisItem's tickStrings(). I.e. in the new photograph version (0.11):

```
    def tickStrings(self, values, scale, spacing):
         if self.logMode:
            return self.logTickStrings(values, scale, spacing)

        places = max(0, np.ceil(-np.log10(spacing*scale)))
        strings = []
        for v in values:
            vs = v * scale
            if abs(vs) < .001 or abs(vs) >= 10000:
                vstr = "%g" % vs
            else:
                vstr = ("%%0.%df" % places) % vs
            strings.append(vstr)
        return strings
```

to 

```
    def tickStrings(self, values, scale, spacing):
         if self.logMode:
            return self.logTickStrings(values, scale, spacing)

        places = max(0, np.ceil(-np.log10(spacing*scale)))
        strings = []
        for v in values:
            vs = v * scale
            vstr = ("%%0.%df" % places) % vs
            strings.append(vstr)
        return strings
```

But this is uncomfortable because I cannot effectively make pyqtgraph as a dependency in my project. I must always include a custom pyqtgraph package version in my github repo. 

Is there any good way how to override the behavior of the AxisItem class outside of pyqtgraph in this particular case and in general? An option to chose between an exact, and scientific notation will be of course the best option!

Thanks!

**Comment by ixjlyons** [comment]
This is pretty much the recommended approach. You can see in the [tickStrings doc](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/axisitem.html#pyqtgraph.AxisItem.tickStrings) that you can write a subclass of `AxisItem` to customize the formatting. You can then pass your custom `AxisItem` implementation to `PlotItem` via its constructor or [setAxisItems](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/plotitem.html#pyqtgraph.PlotItem.setAxisItems). Example:

```python
import numpy as np
import pyqtgraph as pg

class CustomAxisItem(pg.AxisItem):

    def tickStrings(self, values, scale, spacing):
        if self.logMode:
            return self.logTickStrings(values, scale, spacing)

        places = max(0, np.ceil(-np.log10(spacing*scale)))
        strings = []
        for v in values:
            vs = v * scale
            vstr = ("%%0.%df" % places) % vs
            strings.append(vstr)
        return strings

app = pg.mkQApp()

plotwidget = pg.plot([2.4e6, 2.5e6, 2.6e6], [1, 2, 3])
plotwidget.plotItem.setAxisItems({'bottom': CustomAxisItem('bottom')})

app.exec_()
```

I could imagine a convenience method to override the tick string format string though. Suggestions welcome for doing that in a way that would make sense in different scenarios. We're probably not looking for something as general as matplotlib's Formatter system given that subclassing pyqtgraph classes is somewhat expected for cases where a lot of control is needed.

**Comment by 3fon3fonov** [comment]
Thanks a lot! This was what I was looking for. I was (unsuccessfully) trying to "monkey patch" the AxisItem class. What I did now is to make a small import of what you proposed, named pg_hack.py:

```
import numpy as np
import pyqtgraph as pg

class CustomAxisItem(pg.AxisItem):

    def tickStrings(self, values, scale, spacing):
        if self.logMode:
            return self.logTickStrings(values, scale, spacing)

        places = max(0, np.ceil(-np.log10(spacing*scale)))
        strings = []
        for v in values:
            vs = v * scale
            vstr = ("%%0.%df" % places) % vs
            strings.append(vstr)
        return strings

```

then:

```
import pg_hack 

...
...
...
# later in my code when I initialize all my plots in a loop:

for i in range(len(plots)):
    plots[i].setAxisItems({'bottom': pg_hack.CustomAxisItem('bottom')})
...
...
```

And it worked!

Thanks again, I am closing this issues as solved!
