### ISSUE TITLE
getGitVersion broken on py3

### ISSUE THREAD

**Issue by welshjf** [pyqtgraph/pyqtgraph#138]
getGitVersion (tools/setupHelpers.py) is broken in python 3 because map() returns an iterator instead of a list.

It's an easy fix to change to a list comprehension, but I'm wondering if it would be better to replace all that custom logic with a "git describe --tags", which does basically the same thing but more reliably.

**Comment by campagnola** [comment]
Thanks! Fix is committed and it now uses `git describe` as you suggested.
