### ISSUE TITLE
Bloated pyinstaller executable after importing pyqtgraph

### ISSUE THREAD

**Issue by Severian-desu-ga** [pyqtgraph/pyqtgraph#1381]
Hi,

First I must say that pyqtgraph is amazing with it's simplicity and excellent integration with PyQt5.
However I noticed that while trying to convert a python script to an executable with pyinstaller the executable became extremely bloated in file size from being 65MB without the import to 1.9GB after the import. 
Here is a list of the specific packages used.
PyQt5 5.15.1
pyqtgraph 0.11.0
pyinstaller  4.0

Pyinstaller built the executable on Ubuntu 18.04 with python 3.6.9
The specific pyinstaller build line was: pyinstaller -F -w --hidden-import=pkg_resources.py2_warn test.py 

I know this may be more of a pyinstaller issue, however are you aware of any possible solutions to fix this?

**Comment by Severian-desu-ga** [comment]
Hi,

So the solution has been found. The issue was twofold. The first was a need to downgrade the matplotlib version to 3.1.3 (this version worked but there may be others). The second's solution can be found on https://github.com/pyinstaller/pyinstaller/issues/2785. Since the issue dialogue is pretty long here is the quick guide to the fix. First determine what backend for matplotlib you are using whether Qt4Agg or Qt5Agg and then a modification to the hook file must be done. This hook file can be found in your pyinstaller dir/hooks with the name hook-matplotlib.backends.py. In this file there is a variable named backend_names, comment out the current input and replace with either backend_names = ['Qt4Agg'] or backend_names = ['Qt5Agg'] depending on which backend is used. This fix reduced the file size from 1.9GB to 98MB and the executable ran with no issues. Hope this will help any one else in the future that has a similar issue.

**Comment by j9ac9k** [comment]
Meant to comment here earlier; pyinstaller issues are _really_ tough to debug, so thank you for sharing the solution!
