### ISSUE TITLE
Graph stops updating when ploting continuous data

### ISSUE THREAD

**Issue by Zythyr** [pyqtgraph/pyqtgraph#1398]
I am using PyQt5 and Pyqtgraph to plot continuous live data set. Initialaly the plot works as expected. However after few minutes the graph stops updating or refreshing. I wouldn't say the graph is frozen because I can still right click on the graph and see various plot options. The only time I see the graph refresh by a frame is when I remove focus and refocus on the window or resize the window. 

The exact details on the issue are posted here: https://stackoverflow.com/questions/64307813/pyqtgraph-stops-updating-and-freezes-when-grapahing-live-sensor-data. Below are code to reproduce and gif showing the issue. 

My system:
python v3.8.6
PyQt5 v5.15.1
pyqtgraph v0.11.0
Windows 10 x64

**Graph BEFORE freezing**

[![enter image description here][1]][1]

**Graph AFTER freezing**

[![enter image description here][2]][2]

```python
import time 
import numpy as np
from threading import Thread
import pyqtgraph as pg
import bottleneck as bn
import PyQt5

class MySensor():
    def get_position(self, mean=0.0, standard_dev=0.1):
        # Random sensor data 
        return np.random.normal(mean,standard_dev,1)[0]

class SignalCommunicate(PyQt5.QtCore.QObject):
    # https://stackoverflow.com/a/45620056
    got_new_sensor_data = PyQt5.QtCore.pyqtSignal(float, float)
    position_updated = PyQt5.QtCore.pyqtSignal(float)

class LiveSensorViewer():

    def __init__(self, sensor_update_interval=50, graph_update_interval=5 ):
        # super().__init__()
        
        # How frequently to get sensor data and update graph 
        self.sensor_update_interval = sensor_update_interval
        self.graph_update_interval = graph_update_interval
        self.graph_update_interval_tracker = 0

        # Init sensor object which gives live data 
        self.my_sensor = MySensor()
        
        # Init with default values
        self.current_position = self.my_sensor.get_position(mean=0.0, standard_dev=0.1)
        self.current_position_timestamp = time.time()

        # Init array which stores sensor data 
        self.log_time = [self.current_position_timestamp] 
        self.log_position_raw = [self.current_position] 

        # Define the array size on max amount of data to store in the list 
        self.log_size = 1 * 60 * 1000/self.sensor_update_interval  

        # Setup the graphs which will display sensor data 
        self.plot_widget = pg.GraphicsLayoutWidget(show=True)
        self.my_graph = self.plot_widget.addPlot(axisItems = {'bottom': pg.DateAxisItem()})
        self.my_graph.showGrid(x=True, y=True, alpha=0.25)
        self.my_graph.addLegend()

        # Curves to be drawn on the graph 
        self.curve_position_raw = self.my_graph.plot(self.log_time, self.log_position_raw, name='Position raw (mm)', pen=pg.mkPen(color='#525252'))
        self.curve_position_moving_avg = self.my_graph.plot(self.log_time, self.log_position_raw, name='Position avg. 5 periods (mm)', pen=pg.mkPen(color='#FFF'))

        # A dialog box which displays the sensor value only. No graph. 
        self.my_dialog = PyQt5.QtWidgets.QWidget()
        self.verticalLayout = PyQt5.QtWidgets.QVBoxLayout(self.my_dialog)
    
        self.my_label = PyQt5.QtWidgets.QLabel()
        self.verticalLayout.addWidget(self.my_label)
        self.my_label.setText('Current sensor position:')

        self.my_sensor_value = PyQt5.QtWidgets.QDoubleSpinBox()
        self.verticalLayout.addWidget(self.my_sensor_value)
        self.my_sensor_value.setDecimals(6)

        self.my_dialog.show()

        # Signals that can be emitted 
        self.signalComm = SignalCommunicate()
         # Connect the signal 'position_updated' to the QDoubleSpinBox 
        self.signalComm.position_updated.connect(self.my_sensor_value.setValue)
        
        # Setup thread which will continuously query the sensor for data 
        self.position_update_thread = Thread(target=self.read_position, args=(self.my_sensor, self.sensor_update_interval))
        self.position_update_thread.daemon = True
        self.position_update_thread.start() # Start the thread to query sensor data 

    def read_position(self, sensor_obj, update_interval ):
        # This function continuously runs in a seprate thread to continuously query the sensor for data 

        c = SignalCommunicate() # https://stackoverflow.com/a/45620056 
        c.got_new_sensor_data.connect(self.handle_sensor_data)

        while True:
            # Get data and timestamp from sensor 
            new_pos = sensor_obj.get_position(mean=0.0, standard_dev=0.1)
            new_pos_time = time.time()

            # Emit signal with sensor data and  timestamp 
            c.got_new_sensor_data.emit(new_pos, new_pos_time)

            # Wait before quering the sensor again 
            time.sleep(update_interval/1000)


    def handle_sensor_data(self, new_pos, new_pos_time ):

        # Get the sensor position/timestamp emitted from the separate thread 
        self.current_position_timestamp = new_pos_time
        self.current_position = new_pos

        # Emit a singal with new position info 
        self.signalComm.position_updated.emit(self.current_position)

        # Add data to log array 
        self.log_time.append(self.current_position_timestamp)
        if len(self.log_time) > self.log_size:
            # Append new data to the log and remove old data to maintain desired log size 
            self.log_time.pop(0)

        self.log_position_raw.append(self.current_position)
        if len(self.log_position_raw) > self.log_size:
            # Append new data to the log and remove old data to maintain desired log size 
            self.log_position_raw.pop(0)

        if len(self.log_time) <= 10:
            # Skip calculating moving avg if only 10 data points collected from sensor to prevent errors 
            return 
        else:
            self.calculate_moving_avg()
        
        # Determine if graph needs to be updated 
        self.update_graph_interval_check()

    def calculate_moving_avg(self):
        # Get moving average of the position 
        self.log_position_moving_avg = bn.move_mean(self.log_position_raw, window=5, min_count=1)

    def update_graph_interval_check(self):
        # Update less frequently to reduce load on the application  

        self.graph_update_interval_tracker += 1 
        if self.graph_update_interval_tracker % self.graph_update_interval == 0:
            self.graph_update_interval_tracker = 0 # Reset back to 0
            self.update_graph() # Get graph to update 

    def update_graph(self):
        self.curve_position_raw.setData(self.log_time, self.log_position_raw)
        self.curve_position_moving_avg.setData(self.log_time, self.log_position_moving_avg)



if __name__ == '__main__':
    import sys
    from PyQt5 import QtWidgets, uic, QtCore, QtGui 

    app = QtWidgets.QApplication(sys.argv)

    z = LiveSensorViewer()

    app.exec_()
    sys.exit(app.exec_())   
```

  [1]: https://i.stack.imgur.com/qUF2P.gif
  [2]: https://i.stack.imgur.com/c6Ezl.gif

**Comment by Androwei** [comment]
I have the same problem.
I tested both PyQt5 v5.15.0 and PySide2 V5.15.0.
I try it on windows 10 64 and Ubuntu 20.04(Raspberry pi 4).
They all have the same situation.

**Comment by j9ac9k** [comment]
Hi @Zythyr thanks for this fantastic issue and the code to replicate.  I'm not sure when someone will be getting to this, we're trying to clear out the PR queue in preparation for adopting NEP-29 and removing Qt4 support.  If you become suspicious of some code within the library, please let us know and that will definitely help.

**Comment by Zythyr** [comment]
@j9ac9k @Androwei I think i figured out the issue. It may not be related to the pyqtgraph itself. I will post details and solutions soon.

**Comment by Zythyr** [comment]
@j9ac9k This issue can be closed. The graph freezing issue was NOT related to pyqtgraph. It was because I was unknowingly trying to update the graph outside of the main thread. 

@Androwei If you're still facing the same issue like I did, you may find the detail explanation and solution helpful. See https://stackoverflow.com/a/64520032/4988010

**Comment by usysinct** [comment]
@j9ac9k The problem I and probably most other face is the misunderstanding that (1) the app=QApplication must be instantiated in the __main__ thread (2) one's QMainWindow must also run in __main__ thread (3) a threading.Thread object cannot be used to send data to the QMainWindow because the thread signatures are different and the Qt event processor thinks that the QMainWindow.plotWidget for instance is been idle past it's default timeout. Note, from https://doc.qt.io/qt-6/qthreadpool.html#details, "threads that are unused for a certain amount of time will expire. The default expiry timeout is 30000 milliseconds (30 seconds). This can be changed using [setExpiryTimeout](https://doc.qt.io/qt-6/qthreadpool.html#expiryTimeout-prop)(). Setting a negative expiry timeout disables the expiry mechanism." I have not tried, but the implications are that one might be able to use a threading.Thread object along with modifying the setExpiryTimeout https://doc.qt.io/qt-6/qthreadpool.html#expiryTimeout-prop)(). (3) Qt's prescribed method is using a QRunnable threaded object to collect and send data to QMainWindow via Qt Signals  https://doc.qt.io/qt-6/signalsandslots.html. Using this mechanism, data sent from a blocking QRunnable thread for instance, sends data to QMainWindow with a __main__ thread ID signature thereby alerting the Qt event queue of the transaction and thus keeping your PlotWidget plotting to QMainWindow without timing out, and necessitating one to wiggle and resize the main window continuously to see one's data. The END.

**Comment by j9ac9k** [comment]
Yeah, there are certainly restrictions on what can be run on which thread, but the GUI thread is where the bulk of the work should be happening.

PyQtGraph does have a remote graphics view, but it doesn't get a lot of attention, I've never used it myself

https://pyqtgraph.readthedocs.io/en/latest/api_reference/widgets/remotegraphicsview.html#remotegraphicsview

If looking to use `threading.Thread` with pyqtgraph, take a look at the [pglive library](https://github.com/domarm-comat/pglive)
