### ISSUE TITLE
mouseReleaseEvent of Graphicsscene on double clicking a ListWidget

### ISSUE THREAD

**Issue by CPrescher** [pyqtgraph/pyqtgraph#141]
Hi all,

i have found a weird bug. When i am using a Graphicslayout widget in normal widget and open up a QDialog with a QListWidget, where double clicking in the QListWidget accepts the Dialog, the Graphicsscene of the GraphicsLayoutWidget raises the following error after double clicking an item in the list:

File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 200, in mouseReleaseEvent
    if self.sendClickEvent(cev[0]):
IndexError: list index out of range

This error is even raised when the dialog is not on top of the GraphicsLayoutWidget, but when dragging it to somewhere else.

Here is the example code, to reproduce the error:

``` Python
from PyQt4 import QtCore, QtGui
import pyqtgraph as pg

class MyGui(QtGui.QWidget):
    def __init__(self, *args, **kwargs):
        super(MyGui, self).__init__(*args, **kwargs)

        layout = QtGui.QHBoxLayout()
        self._pg_layout_widget = pg.GraphicsLayoutWidget()
        layout.addWidget(self._pg_layout_widget)
        self.setLayout(layout)

        self.dialog = MyDialog()

    def show(self):
        QtGui.QWidget.show(self)
        self.setWindowState(self.windowState() & ~QtCore.Qt.WindowMinimized | QtCore.Qt.WindowActive)
        self.activateWindow()
        self.raise_()

    def show_dialog(self):
        self.dialog.list_widget.addItems(['test', 'test2'])
        self.dialog.show()

class MyDialog(QtGui.QDialog):
    def __init__(self, *args, **kwargs):
        super(MyDialog, self).__init__(*args, **kwargs)
        layout = QtGui.QVBoxLayout()
        self.list_widget = QtGui.QListWidget()
        layout.addWidget(self.list_widget)
        self.setLayout(layout)

        self.list_widget.doubleClicked.connect(self.accept)

    def show(self):
        QtGui.QWidget.show(self)
        self.setWindowState(self.windowState() & ~QtCore.Qt.WindowMinimized | QtCore.Qt.WindowActive)
        self.layout().setSizeConstraint(QtGui.QLayout.SetFixedSize)

        self.activateWindow()
        self.raise_()

if __name__ == '__main__':
    app = QtGui.QApplication([])
    widget = MyGui()
    widget.show()
    widget.show_dialog()
    app.exec_()
```

I tried to understand what is going on, but was not really able to do so.

**Comment by ixjlyons** [comment]
I'm not able to reproduce this issue with Python 2 and PyQt4 (4.11.4). It's possible you were seeing a bug in Qt/PyQt or perhaps something in pyqtgraph has been improved in the meantime. I know it's been a long time, but if you happen to still be having this issue, let us know.

**Comment by j9ac9k** [comment]
I'll close out this issue, but if we can reproduce, will gladly re-open.
