### ISSUE TITLE
How to add LaTeX symbols on plot labels?

### ISSUE THREAD

**Issue by 3fon3fonov** [pyqtgraph/pyqtgraph#1425]
What is the correct way of adding LaTeX symbols on plots?

E.g.,

```
plot.setLabel('bottom', 'e cos (theta)', units='',  **{'font-size':'9pt'}) 
plot.setLabel('left', 'e sin (theta)', units='',  **{'font-size':'9pt'}) 
```

where theta in latex is $\theta$

in matplotlib something like 

```
plot.setLabel('bottom', r'e cos ($\theta$)', units='',  **{'font-size':'9pt'}) 
plot.setLabel('left', r'e sin ($\theta$)', units='',  **{'font-size':'9pt'}) 
```

would work...

but what is the correct way of doing this in pyqtgraph?

Thanks!

**Comment by 3fon3fonov** [comment]
Forget! I realized I can use HTML

plot.setLabel('bottom', '<html><head/><body><p>e%s cos(&omega;%s) </p></body></html>'%(e_ind+1,tet_n+1), units='',  **{'font-size':'9pt'}) 
plot.setLabel('left', '<html><head/><body><p>e%s sin(&omega;%s) </p></body></html>'%(e_ind+1,tet_n+1), units='',  **{'font-size':'9pt'}) 


Yet, it would be nice if you include the possibility of using LaTeX characters in pyqtgraph (if possible).

**Comment by JPalmerio** [comment]
Bump !
Indeed support for LaTeX would be amazing in pyqtgraph.

**Comment by borondics** [comment]
I wonder if this got on any future roadmap...?
