### ISSUE TITLE
ExampleApp Syntax Highlighter broken in PyQt5

### ISSUE THREAD

**Issue by 2xB** [pyqtgraph/pyqtgraph#1431]
### Short description
Since merge of #1302, the syntax highlighter in the ExampleApp is broken  (CC @j9ac9k ).

### Code to reproduce
```bash
cd pyqtgraph\examples
python3 .
```

### Expected behavior
Syntax highlighter should work

### Real behavior
Following error:

```
Traceback (most recent call last):
  File "/home/b2/Documents/synced/pyqtgraph/examples/ExampleApp.py", line 298, in highlightBlock
    format = self.styles[format]
AttributeError: 'PythonHighlighter' object has no attribute 'styles'
```

### Tested environment(s)

 * PyQtGraph version: 7e57e07068fc8a62e9ae3b68e5556b11b6ef1841 and newer
 * Qt Python binding: yQt5 5.15.1 Qt 5.15.1
 * Python version: Python 3.8.5
 * NumPy version: 1.19.2
 * Operating system: Linux 5.8.16-2-MANJARO
 * Installation method: Run in folder (see above)

**Comment by j9ac9k** [comment]
Hey @2xB,

Thanks for the issue.  We can launch the example app a variety of ways, but I didn't think that way was tested (although I don't see why it shouldn't work)...

if you go to the root project folder, can you launch the example app with 


```bash
python examples
```

or from python

```python
import pyqtgraph.examples
pyqtgraph.examples.run()
```

(also FYI running `python -m pyqtgraph.examples` does not work when pyqtgraph is installed via editable mode.

**Comment by 2xB** [comment]
Hey ^^ The same error occurs when run via `python3 examples`.

**Comment by j9ac9k** [comment]
Can you run it from the interpreter?

**Comment by j9ac9k** [comment]
this is so odd...on macOS I can't replicate at all... it's going to be a little while before I have decent access to a linux machine.

**Comment by 2xB** [comment]
Glanced over it - this looks weird, so I'm curious now. I try to investigate.

**Comment by 2xB** [comment]
Found it: The ExampleApp no longer uses pyqtgraph from the directory when run without installation. I'll have a PR to fix this up shortly. One can simply test this by uninstalling all installed instances of pyqtgraph and try running the example app, which works for commits before the merge and stopped working afterwards with the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 2, in <module>
    import pyqtgraph as pg
ModuleNotFoundError: No module named 'pyqtgraph'
```

**Comment by 2xB** [comment]
So I had an old version of pyqtgraph (0.11.0 from pip) installed, and ran the example app in the directory without installation. Therefore the example app used some classes from the old version.
