### ISSUE TITLE
Retrieve time index in GUI?

### ISSUE THREAD

**Issue by ercius** [pyqtgraph/pyqtgraph#1436]
### Short description
This is not a bug. Im asking whether there is a way for a user to determine the current time index from the GUI only. For long movies its hard to tell what the current frame number is due to the large number of ticks. Im not sure if there is a right click menu, or some other way to determine this with the basic widget.
![image](https://user-images.githubusercontent.com/15657108/98973341-7af70400-24c8-11eb-9bb9-660d7376463c.png)

### Code to reproduce
Create an ImageView() and use a 3D dataset for setImage().

### Expected behavior
Allow the user to retrieve the current time index.

### Real behavior
Can be hard to determine the exact time index for large numbers of frames.

**Comment by ixjlyons** [comment]
One fairly simple approach I can think of would be to add an `InfLineLabel` to the `timeLine`:

```python
import numpy as np
import pyqtgraph as pg

app = pg.mkQApp()
imv = pg.ImageView()
imv.setImage(np.random.rand(100, 20, 20))

# non-obvious that this alone works
tlabel = pg.InfLineLabel(imv.timeLine, text="{value:.0f}")

imv.show()
app.exec_()
```

![image](https://user-images.githubusercontent.com/943602/99011645-6f73ff00-2501-11eb-82e4-f75bec76dba6.png)

A right-click context menu or hover tooltip or something could be done by dynamically adding a callback to the `timeLine`, like this:

```python
def updateToolTip(infline):
    infline.setToolTip("{:.0f}".format(infline.x()))

imv.timeLine.sigPositionChanged.connect(updateToolTip)
```

**Comment by ercius** [comment]
excellent ideas. Thanks!

**Comment by 2xB** [comment]
@ercius Since this seems to be solved, I'll close this issue. Otherwise, feel free to add a new comment or a new issue!
