### ISSUE TITLE
HistogramLUTItem doesn't update when in LogMode

### ISSUE THREAD

**Issue by fedebarabas** [pyqtgraph/pyqtgraph#144]
Hi all,

I stumpled upon this weird issue. I wanted to have an histogramLUT with its y-axis in log mode. Following the example:

<pre><code>from pyqtgraph.Qt import QtCore, QtGui
import numpy as np
import pyqtgraph as pg
import pyqtgraph.ptime as ptime

app = QtGui.QApplication([])

## Create window with GraphicsView widget
win = pg.GraphicsLayoutWidget()
win.show()  ## show widget alone in its own window
win.setWindowTitle('pyqtgraph example: ImageItem')
view = win.addViewBox()

## lock the aspect ratio so pixels are always square
view.setAspectLocked(True)

## Create image item
img = pg.ImageItem(border='w')
view.addItem(img)
hist = pg.HistogramLUTItem()
hist.gradient.loadPreset('yellowy')
hist.setImageItem(img)
hist.plot.setLogMode(False, True)
hist.vb.setLimits(yMin=0, yMax=20000)
win.addItem(hist)

## Set initial view bounds
view.setRange(QtCore.QRectF(0, 0, 600, 600))

## Create random image
data = np.abs(np.random.normal(size=(15, 600, 600), loc=1024, scale=64).astype(np.uint16))
i = 0

updateTime = ptime.time()
fps = 0

def updateData():
    global img, data, i, updateTime, fps

    ## Display the data
    img.setImage(data[i])
    i = (i+1) % data.shape[0]

    QtCore.QTimer.singleShot(1, updateData)
    now = ptime.time()
    fps2 = 1.0 / (now-updateTime)
    updateTime = now
    fps = fps * 0.9 + fps2 * 0.1

    #print "%0.1f fps" % fps

updateData()

## Start Qt event loop unless running in interactive mode.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()</code></pre>

If I just delete the line 
<code><pre>hist.plot.setLogMode(False, True)</code></pre>
the histogram updates just fine. I realize it must have something to do with applying np.log to zero counts, but PlotItem seems to take care of that problem.

Am I doing something wrong?
Thank you for such a wonderful library

**Comment by 2xB** [comment]
Since `hist.plot` is no longer an instance of `PlotDataItem` but of `PlotCurveItem`, I currently do not see a possibility to set a log mode for a `HistogramLUTItem` except from directly passing log values. The latter solution does not produce this error.

Since this issue therefore seemingly does not apply for new versions of `pyqtgraph`, I close it now. If there is anything left to be discussed, feel free to add a comment or a new issue.
