### ISSUE TITLE
LinearRegionItem is not movable after upgrade version 0.10.0 -->0.11.0 

### ISSUE THREAD

**Issue by ytidhar** [pyqtgraph/pyqtgraph#1444]
### Code to reproduce

``` 
lr = pg.LinearRegionItem(values=(0, plot.xData.size * audio.scale_factor), bounds=(0, plot.xData.size * audio.scale_factor), movable=True)
```

### Expected behavior
movable=True should enable LinearRegionItem to move by mouse dragging 
### Real behavior
After upgrade to 0.11.0 the line region is not movable (same code work in version 0.10.0)

### Tested environment(s)

 * PyQtGraph version:  0.11.0
 * Qt Python binding:  PyQt5
 * Python version: 2.7
 * NumPy version:  1.14.2
 * Operating system: ubuntu 16.04
 * Installation method: pip

**Comment by j9ac9k** [comment]
py2/pyqt5, that's a rare combination!  ...will take me a bit to replicate that environment, can you be more specific with which version of PyQt5 you're using?

Thanks!

**Comment by j9ac9k** [comment]
@ytidhar can you provide more an example  to reproduce?  I routinely use LinearRegionItem's in my own applications, and the ones in the example application are working just fine as well.  

Do the LinearRegionItem's behave properly when you run the example app?

**Comment by ytidhar** [comment]
Ill try to make investigate more when i have time.

**Comment by j9ac9k** [comment]
Due to having not heard back, I'm going to close this issue out, @ytidhar if you are able to reproduce, please post here, or create a new issue with some code to assist us.  Thanks

**Comment by ytidhar** [comment]
Ok
Sorry that i didnt have the time to figure out what is happening
