### ISSUE TITLE
Regression: InfiniteLines became finite and movable

### ISSUE THREAD

**Issue by 2xB** [pyqtgraph/pyqtgraph#1450]
### Short description

`InfiniteLine`s are movable and finite along their "infinite" direction since PR #1391 (Tagging @jjuod )
. Moving them also moves their labels. PR #1413 only fixes their initial positions.

### Code to reproduce
`examples\InfiniteLine.py`

### Expected behavior

Lines should be infinite and dragging them should not move the label into their "infinite" direction.

![image](https://user-images.githubusercontent.com/31772910/99725346-45987a80-2ab5-11eb-915c-d14eb59ada5e.png)

### Real behavior

Lines are finite and moving them also moves their labels.

![image](https://user-images.githubusercontent.com/31772910/99725280-2863ac00-2ab5-11eb-9dfd-122641196bbc.png)

### Tested environment(s)

 * PyQtGraph version: Since commit 39f9c6a
 * Qt Python binding: PyQt5 5.15.1 Qt 5.15.1
 * Python version: 3.8.5
 * NumPy version: 1.19.2
 * Operating system: Linux 5.8.16-2-MANJARO x86_64 20.1.2 Mikah
 * Installation method: Executed in folder

**Comment by j9ac9k** [comment]
Thanks for making an issue for this @2xB; definitely need this resolved pre-0.11.1 release.

**Comment by jjuod** [comment]
Ah, yep, that's a consequence of the caching introduced in my PR. Submitted a fix in PR #1452
