### ISSUE TITLE
PyQtGraph Consulting Needed

### ISSUE THREAD

**Issue by StuartFarmer** [pyqtgraph/pyqtgraph#1454]
This may be a faux pas, but I'm looking to hire a PyQtGraph developer for a quantitative analysis application. As Github has no social networking component, this is really my only way of reaching out.

I'm a software engineer, so the architecture and technical scope will be provided. Please email me at stuart@lamden.io.

**Comment by j9ac9k** [comment]
Hey @StuartFarmer Thanks for posting.  I'm going to close out this issue in an effort to keep the number of outstanding issues to a minimum.  There is a mail list posted on the README where this sort of thing may get more attention.
