### ISSUE TITLE
Port to PySide6

### ISSUE THREAD

**Issue by absassi** [pyqtgraph/pyqtgraph#1465]
[Qt 6.0 was just released](https://www.qt.io/blog/qt-6.0-released), including Qt for Python, now packaged as PySide6.
It would be nice to have support for it too.

**Comment by j9ac9k** [comment]
Saw that, was wondering how long before an issue would be posted here 😆 

I'm looking to get some pull requests resolved, there will be some effort involved here in making pyside6 work...  if someone wants to start a PR for this, that would be great, I would gladly assist as best I can.

**Comment by ksunden** [comment]
I haven't tried anything, but nothing obvious popped out at me as significantly changed for what we use in the release docs, so we _may_ get away with little more than import changes (won't know for sure until we try).

We have also had conversations in the past about using the qt compatibility layer spyder-ide/qtpy

no real indication there about qt6 support yet

**Comment by ksunden** [comment]
https://github.com/matplotlib/matplotlib/pull/19255/files

Here is a start to mpl's qt6 support

https://github.com/spyder-ide/qtpy/pull/225

and here is one for qtpy, should we go that route.

I'm currently away from home for the holidays still, but may give qt6 a look once I'm back in a week or so (if nobody beats me to it, which they are welcome to do)

**Comment by j9ac9k** [comment]
Hi @ksunden I've been watching that PR as well... it's definitely tempting to think of this as a good opportunity to utilize `qtpy` as a dependency instead of trying to do this ourselves...

**Comment by j9ac9k** [comment]
Fixed with #1495

**Comment by stonebig** [comment]
maybe a new release would help to benefit this ?

**Comment by j9ac9k** [comment]
> maybe a new release would help to benefit this ?

We have some regressions with ScatterPlotItem that we need to address before we do another stable release.
