### ISSUE TITLE
Pausing a real-time plot

### ISSUE THREAD

**Issue by DrPaprikaa** [pyqtgraph/pyqtgraph#1481]
Hi,
Is there a way to pause a real-time plot, without pausing the script in the backgound ?

For example, adding a `Pause` button to the window to that I can take the time to analyse the graph, take a screenshot or whatever. When clicking that button again, the real-time plotting resumes (and therefore skipping the data that was processed but not displayed during the pause).

Thanks,
DrPaprikaa

**Comment by j9ac9k** [comment]
I'm sure it can be done; the way I would do it is have the `.setData` method in your plot object be called via a signal (that carries the data for the plot), and have the button toggle the signal being connected or disconnected.

Here is where we define our auto-scale button, I would consider adding something similar for pausing/un-pausing

https://github.com/pyqtgraph/pyqtgraph/blob/ea08dda62dade523f2193ec353b9bacac6d8d35d/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L126-L128

**Comment by DrPaprikaa** [comment]
I'll look into that, thanks !

**Comment by j9ac9k** [comment]
I'm going to close out this issue; but I'll leave a comment saying that if you're interested in this functionality being integrated into pyqtgraph; we would consider a PR.  If you have a minimal working example, we would encourage the submission of a pull request.

**Comment by DrPaprikaa** [comment]
Sorry for the delay, and unfortunately I'm not very familiar with PRs :/
I have a minimal working example, it goes like this :

```
import numpy as np
import sys
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui

class MyApp(QtGui.QMainWindow):

    def __init__(self, parent=None):
        super(MyApp, self).__init__(parent=parent)

        self.mainbox = QtGui.QWidget()
        self.setCentralWidget(self.mainbox)

        lay = QtGui.QVBoxLayout(self.mainbox)
        self.canvas = pg.GraphicsLayoutWidget()
        lay.addWidget(self.canvas)

        self.timer = QtCore.QTimer(self)
        self.timer.setInterval(1)
        self.timer.start()

        self.plot  = self.canvas.addPlot(title="Updating plot")
        self.curve = self.plot.plot(pen='y')
        self.data  = np.random.normal(size=(10,1000))
        self.ptr   = 0

        self.timer.timeout.connect(self.update)

        # Pause button in a toolbar. Pauses when checked
        self.toolbar = self.addToolBar("Pause")
        self.playScansAction = QtGui.QAction("Pause", self)
        self.playScansAction.triggered.connect(self.playScansPressed)
        self.playScansAction.setCheckable(True)
        self.toolbar.addAction(self.playScansAction)


    def playScansPressed(self):
        if self.playScansAction.isChecked():
            self.timer.stop()
        else:
            self.timer.start()


    def update(self):
        self.curve.setData(self.data[self.ptr % 10])
        if self.ptr == 0:
            self.plot.enableAutoRange('xy', False)  # stop auto-scaling after the first data set is plotted
        self.ptr += 1


def main():
    app = QtGui.QApplication(sys.argv)
    this_app = MyApp()
    this_app.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
```

Can you play with it and see if it works as intended ? Can it be implemented into the project ?
I would be honored to become a contributor to PyQtgraph !

DrPaprikaa

**Comment by j9ac9k** [comment]
Hi @DrPaprikaa 

Thanks for posting the code here.  I'm not sure this is something we would integrate into the current library, as there is likely little we could add that would simplify what you have provided.  The one place this might be use that comes to mind is in our ScrollingPlots example, adding another plot there that demonstrates this functionality. 

Thanks again for following up!

EDIT: I'm going to edit your post to enable python syntax highlighting.
