### ISSUE TITLE
vega lite grammar 

### ISSUE THREAD

**Issue by dridk** [pyqtgraph/pyqtgraph#1482]
It may not be possible... 
But having a Qt library to support vega grammar would be awesome. 
https://vega.github.io/vega-lite/

**Comment by j9ac9k** [comment]
@dridk can you give me an example of what that would look like from the user-endpoint?

**Comment by dridk** [comment]
building a chart with python [altair](https://altair-viz.github.io/) is really easy. This API is used to build a json structure using the grammar of [vega-lite](https://vega.github.io/vega-lite/)
Actually this grammar can only be interpreted by vega-lite.js into a html / canvas .
I would like to render vega grammar into a QPainter device from  Qt .

# Exemple 
## Plot a bar chart from json 

vega_grammar = { "data": { "values": [ {"a": "C", "b": 2}, {"a": "C", "b": 7}, {"a": "C", "b": 4}, {"a": "D", "b": 1}, {"a": "D", "b": 2}, {"a": "D", "b": 6}, {"a": "E", "b": 8}, {"a": "E", "b": 4}, {"a": "E", "b": 7} ] }, "mark": "bar", "encoding": { "x": {"field": "a", "type": "nominal"}, "y": {"aggregate": "average", "field": "b", "type": "quantitative"} } }

w = QVegaWidget()
w.load(vega_grammar) 
w.show()

# from python altair 

df = pd.DataFrame(...)
chart = alt.Chart(df).mark_bar().encode(...)
w = QVegaWidget()
w.load(chart.toJson())
w.show() 

I can start a new project. But I m not sure I will success to code this alone.

**Comment by j9ac9k** [comment]
I don't think we have enough maintainer effort to move something like this forward, and I'm not sure it should be part of pyqtgraph, but a separate library.... but I'm definitely eager to see what that would be like in practice.

If you do try starting a separate library to enable this functionality, I would like to know about it, and you can certainly reach out for assistance/input.
