### ISSUE TITLE
Dynamic Use of setData(), plotDataItem disappears in 0.11.1 but not in 0.11.0

### ISSUE THREAD

**Issue by andy1503hsu** [pyqtgraph/pyqtgraph#1521]
### Short description
After updating to pyqtgraph-0.11.1, setData() is behaving differently compared to pyqtgraph-0.11.0 and causes the plotDataItem to disappear.

### Code to reproduce
I initialized a plotDataItem like so:
```python
plotDataItem = self.graphWidget.plot(
    x = self.convert_to_np(time),
    y = self.convert_to_np(y),
    symbolBrush = pg.mkBrush('r'),
    symbol = None, 
    pen=pg.mkPen('r', width = 1),
    name = groupText + ": " + channelText
)
```
![image](https://user-images.githubusercontent.com/15189091/106189627-2a5d8180-616e-11eb-91f0-84e435dcca54.png)

And I use these lines to modify the color of the brush and pen. The "self.selectedButtons[(group,channel)][0]" is a reference to the now-initialized plotDataItem:
```python
color = QColorDialog.getColor()
self.selectedButtons[(group,channel)][0].setData(
    symbolBrush = pg.mkBrush(color),
    pen = pg.mkPen(color, width = 1)
)
```
### Behavior in pyqtgraph-0.11.0
pyqtgraph-0.11.0: The color of the plot changes accordingly.
![image](https://user-images.githubusercontent.com/15189091/106189886-7c9ea280-616e-11eb-9747-f1a13586f165.png)

pyqtgraph-0.11.1: The plotDataItem completely disappears.
![image](https://user-images.githubusercontent.com/15189091/106189720-45c88c80-616e-11eb-951c-3e5f90f5a06e.png)

Could someone explain why this change is occurring? Thank you!

**Comment by andy1503hsu** [comment]
I don't mind at all! Thank you for your help.

**Comment by j9ac9k** [comment]
There were a ton of changes from 0.11.0 to 0.11.1, including some in `.setData()`, which is a remarkably complex method due to the wide variety of acceptable inputs.

I think one of the features we implemented in 0.11.1 was calling `.setData()` with no x or y arguments was introduced; see PR #1446 

The idea here was that calling `.setData` without `x` or `y` args should effectively clear the plot.

If you're wanting to change the color, I would advice calling `plotDataItem.setBrush(color)`... I'm shooting from the hip here, but I would try that.

**Comment by andy1503hsu** [comment]
I just tried what you said -- the plotDataItem doesn't disappear anymore, but the color does not change. I tried both ```plotDataItem.setBrush(color)``` and ```plotDataItem.setBrush(pg.mkBrush(color))```

**Comment by andy1503hsu** [comment]
Got it! I had to use ```setPen(color)``` instead of ```setBrush(color)```

Thank you for your help!

**Comment by j9ac9k** [comment]
Sorry the API change there caused some confusion, we try not to do that, but hard to get methods like `.setData` to work for all use cases... glad it's sorted out!

**Comment by andy1503hsu** [comment]
I completely understand!
