### ISSUE TITLE
The setValue method of Parameter does not work for list type parameter

### ISSUE THREAD

**Issue by Fokatu** [pyqtgraph/pyqtgraph#1524]
Am I doing it wrong?

below is an example

```
from pyqtgraph.Qt import QtCore, QtGui

app = QtGui.QApplication([])
from pyqtgraph.parametertree import Parameter, ParameterTree

params = [
        {'name': 'Integer', 'type': 'int', 'value': 10},
        {'name': 'List', 'type': 'list', 'values': [1, 2, 3], 'value': 2},
        {'name': 'Named List', 'type': 'list', 'values': {"one": 1, "two": "twosies", "three": [3, 3, 3]}, 'value': 2},
]

p = Parameter.create(name='params', type='group', children=params)

p.child("Integer").setValue(5)
p.child("List").setValue(["a", "b", "c"])
p.child("Named List").setValue({"a": "a", "b": "b"})

t = ParameterTree()
t.setParameters(p, showTop=False)

win = QtGui.QWidget()
layout = QtGui.QGridLayout()
win.setLayout(layout)
layout.addWidget(QtGui.QLabel("These are two views of the same data. They should always display the same values."), 0,
                 0, 1, 2)
layout.addWidget(t, 1, 0, 1, 1)
win.show()
win.resize(800, 800)


if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()

```

**Comment by ixjlyons** [comment]
`setValue` on a `ListParameter` selects one of the options in the original list/dict. You can use `setLimits` to change the allowed values, i.e. in the above example:

```python
p.child("List").setLimits(["a", "b", "c"])
p.child("List").setValue("b")
```

**Comment by Fokatu** [comment]
@ixjlyons , thanks!
Another question. How can I add suffix for int parameter? When I try to add suffix, it does not show in the spin

**Comment by ixjlyons** [comment]
It looks like suffix/units aren't fully supported. As a workaround for now, you can specify the format string:

```python
params = [
    {'name', 'Integer', 'type': 'int', 'value': 10, 'suffix': 'V', 'format': '{value:d}{suffixGap:s}{suffix:s}'},
    ...
```

I believe updating this line to something like the above would help:

https://github.com/pyqtgraph/pyqtgraph/blob/e9eb8d50b6ea3381a508987684d81e198e6d096d/pyqtgraph/parametertree/parameterTypes.py#L107

I'm also noticing `siPrefix` doesn't quite work correctly either. There you'd want to use `scaledValue` instead of `value`, and I guess that would only really work well with float parameters anyway.

**Comment by ixjlyons** [comment]
@Fokatu if you have suggestions for improving things beyond the PRs above, let us know. Going to close this as having been addressed for now.
