### ISSUE TITLE
test example ViewBox.py Hanging on Windows/PySide6 CI

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#1531]
On GitHub Actions, we're seeing a test on Windows/Py39/PySide6 config timeout.  

The issue appears to be with `examples/ViewBox.py`.  I have been unable to replicate the issue locally; but opening the issue here to keep track of the issue.

**Comment by pijyoi** [comment]
Looking at the past 6 actions where Windows/Py39/PySide6 timed-out, it seems that 5 timed-out at MultiPlotSpeedTest.py and only 1 timed-out at ViewBox.py (https://github.com/pyqtgraph/pyqtgraph/runs/1800152221?check_suite_focus=true)

Furthermore, the first time it occurred (MultiPlotSpeedTest.py) was with a pure documentation commit.
https://github.com/pyqtgraph/pyqtgraph/runs/1798343349?check_suite_focus=true

**Comment by j9ac9k** [comment]
I'm not suggesting a diff in our codebase is causing the issue, especially as I don't think we saw those issues on azure pipelines; but some attempt should probably be made to see if we can make those examples be a bit more robust on github actions (no clue what that would look like though).

**Comment by pijyoi** [comment]
Why doesn't pytest's timeout of 30secs kick in?

**Comment by j9ac9k** [comment]
> Why doesn't pytest's timeout of 30secs kick in?

I'm not sure, I suspected it has to do with `pytest-xdist`, but as I can't replicate myself, hard to say.

**Comment by j9ac9k** [comment]
And we haven't seen this now in some time, so I'm going to say this was just CI gremlins, and close this out.
