### ISSUE TITLE
On changing undeprecated behavior

### ISSUE THREAD

**Issue by irgolic** [pyqtgraph/pyqtgraph#1535]
Hi, I'm Rafael, one of the https://github.com/biolab/orange3 core dev team. We've depended on pyqtgraph since the Qt4 age for a number of our visualizations, including scatter plots and heatmaps.

We run an automated future check against the master branches of a couple of repositories, pyqtgraph included. Sometimes when a bug is fixed upstream, behavior changes; there existed code that uses the bug as a feature. These changes in behavior are desired, even though they may incur some upkeep downstream.

Some breaking changes occurred in the recent releases of pyqtgraph (https://github.com/biolab/orange3/pull/5046). We clamped it at first (https://github.com/biolab/orange3/pull/5082), but pyqtgraph plays a big role in Orange, so we maintain compatibility (https://github.com/biolab/orange3/pull/5207).

More recently, https://github.com/pyqtgraph/pyqtgraph/pull/1533 got merged – monkeypatched methods back from the Qt4 migration were removed. Thanks for bringing attention to these, so we're able to fully migrate our widgets to Qt5 (https://github.com/biolab/orange3/pull/5231). However, I'd agree with the conversation in the PR regarding a deprecation cycle preceding removal. From our point of view, part of the Qt API just disappeared.

I'm writing this issue to start a discussion about maintaining API and behavioral consistency. But I do realize that pyqtgraph is an `0.x` versioned project – generally in versioning, the major version number guarantees consistency.

Would you consider going `1.0.0`? Or idk, running a test for a downstream dependency? What do you guys think?

Love and thanks,
Rafael

**Comment by j9ac9k** [comment]
Hi Rafael,

Thanks for reaching out.  My apologies for the head ache as I am the one that merged the PR.  I certainly didn't mean to cause downstream trouble.   While we are trying to move quick through a long backlog of issues and PRs that goes back for years, that's no justification for killing off portions of the public API that other libraries rely on; in the future we'll certainly be more mindful of going through a deprecation process.  Also, FWIW this is the first library I've maintained with a user size that's greater than 1 digit; so I certainly welcome input from people that use pyqtgraph.

Back to the specific issue here though, what would you like a deprecation phase to look like? 

Regarding the version numbers, I do not have a strong opinion here; so I'll leave this decision to other maintainers/contributors.  I'm not sure that would have helped in this case; as think the issue you brought up is just a result of us trying to migrate away from long-ago deprecated upstream functionality and cleaning up our own library; but as for reasons you point out, we need to be more careful about that.

**Comment by irgolic** [comment]
Dw, everyone eventually breaks a master branch :)

Ideally... When you decide you want to change existing behavior, you add a deprecation warning and let it sit there for a couple of minor releases. In the next major release (e.g. `1.x.x` -> `2.0.0`), you follow through with the change.

**Comment by j9ac9k** [comment]
We are trying to migrate to a faster release cycle with smaller changes (our change-log entries are too long!)... part of that has just involved working through the backlog I described earlier, as well as the complexities with supporting wider array of Qt versions.  Doing this should make it easier to deprecate stuff at a more appropriate pace.  Just to make sure I understand you correctly, when you say a deprecation warning, you literally mean a [deprecation warning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) right?

I have no problem using semantic versioning more so.

While I have you here, I know the kill-off of support of Qt < 5.12 was big, has this made an impact on your end?

**Comment by irgolic** [comment]
Off the top of my head, Anaconda Navigator uses `PyQt5==5.9`. Orange3 requires `PyQt5>=5.12,!=5.15.1`, but we do our best to maintain compatibility with 5.9.

@markotoplak, have you possibly checked if these changes break Orange on PyQt5.9?

**Comment by irgolic** [comment]
DeprecationWarning example:
```python
def toogleExpandedAction(self):
warnings.warn(
    "'toogleExpandedAction is deprecated, use 'toggleExpandedAction' "
    "instead.", DeprecationWarning, stacklevel=2
)
return self.toggleExpandedAction()
```
