### ISSUE TITLE
Arrow keys in ImageView Without Time Axis

### ISSUE THREAD

**Issue by pknodle** [pyqtgraph/pyqtgraph#1545]
### Short description
When you type an arrow key in to a ImageView without a time axis, the application crashes with a unhandled exception.

### Code to reproduce
```
from PySide2.QtWidgets import QMainWindow, QAction, qApp, QApplication
from PySide2.QtCore import Qt

import numpy as np
import pyqtgraph as pg

class BugWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.resize(800, 800)
        self.imv = pg.ImageView()
        self.setCentralWidget(self.imv)



app = QApplication([])
win = BugWindow()
win.show()

app.exec_()

```

### Expected behavior
Nothing, 

### Real behavior
An unhandled exception occurs.

```
Traceback (most recent call last):
  File "D:\Repositories\Art\pyqtgraph\pyqtgraph\imageview\ImageView.py", line 452, in keyPressEvent
    self.evalKeyState()
  File "D:\Repositories\Art\pyqtgraph\pyqtgraph\imageview\ImageView.py", line 476, in evalKeyState
    self.jumpFrames(1)
  File "D:\Repositories\Art\pyqtgraph\pyqtgraph\imageview\ImageView.py", line 516, in jumpFrames
    if self.axes['t'] is not None:
KeyError: 't'

```

### Tested environment(s)

 * PyQtGraph version: 0.11.1.dev0/commit: cd914495ece
 * Qt Python binding: 'PySide2 5.13.2 Qt 5.12.9'
 * Python version: 3.9.1
 * NumPy version: '1.19.5'
 * Operating system:  Windows 10
 * Installation method: conda and git

### Additional context
I have a patch at https://github.com/pknodle/pyqtgraph/tree/image-display-bugfix
I'm not sure if this fix affects any other part of the system.

**Comment by pijyoi** [comment]
From a read of ImageView.py, it appears that all axes, including the time
axis, are created upon calling setImage(), which your minimal example does
not do.

So the issue is more that the keys processing code does not check for the
presence of an image.

**Comment by pknodle** [comment]
With this example, it crashes with up/down, but not left/right.

```

from PySide2.QtWidgets import QMainWindow, QAction, qApp, QApplication
from PySide2.QtCore import Qt

import numpy as np
import pyqtgraph as pg

class BugWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.resize(800, 800)
        self.imv = pg.ImageView()
        junk_array = np.random.random((400,400))
        self.imv.setImage(junk_array)
        self.setCentralWidget(self.imv)



app = QApplication([])
win = BugWindow()
win.show()

app.exec_()

```
