### ISSUE TITLE
Clickable PlotDataItem curve

### ISSUE THREAD

**Issue by lidstrom83** [pyqtgraph/pyqtgraph#155]
Currently a PlotDataItem's PlotCurveItem is not clickable unless explicitly setting it to be after initialization: `item.curve.setClickable(True)`.  Is this the intended behavior, or would you prefer PlotDataItem to take a 'clickable' keyword argument?  If so, should a 'clickable' attribute be added to ScatterPlotItem for uniformity?  Let me know, and I will submit a PR.

**Comment by pijyoi** [comment]
"clickable" keyword to PlotDataItem was added in https://github.com/pyqtgraph/pyqtgraph/pull/1714

**Comment by j9ac9k** [comment]
Look, a current maintainer's open issue from 6+ years ago 😆 

Thanks @pijyoi for flagging this.
