### ISSUE TITLE
RawImageWidget ignores imageAxisOrder config option

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#1580]
### Short description
RawImageWidget ignores imageAxisOrder whereas RawImageGLWidget respects it.
In the included example below, the user needs to manually transpose the image.

### Code to reproduce
```python
import scipy.misc
import pyqtgraph as pg
from pyqtgraph.widgets.RawImageWidget import RawImageWidget, RawImageGLWidget

pg.setConfigOptions(imageAxisOrder='row-major')

data = scipy.misc.face()

app = pg.mkQApp()
win = pg.Qt.QtWidgets.QMainWindow()
if 1:
    wgt = RawImageWidget(scaled=True)
    # data = data.transpose(1,0,2)    # needs a manual transpose
else:
    wgt = RawImageGLWidget()
wgt.setImage(data)
win.setCentralWidget(wgt)
win.resize(800, 600)
win.show()
app.exec_()
```

### Expected behavior

Image displayed right-side up

### Real behavior

Image displayed transposed

### Tested environment(s)

 * PyQtGraph version: 0.11.1.dev0
 * Qt Python binding: PyQt5 5.15.2 Qt 5.15.2
 * Python version: 3.7.9
 * NumPy version: 1.19.4
 * Operating system: Windows 10 x64
 * Installation method: pip install -e .

### Additional context
None

**Comment by j9ac9k** [comment]
Here I was expecting to have to debug for a while, only to see that config option isn't even referenced anywhere in `RawImageWidget` ... I'll look into fixing that up.

**Comment by j9ac9k** [comment]
@pijyoi since I don't work w/ these objects much, should the two Image widgets behave the same?

For example `RawImageWidget`

![image](https://user-images.githubusercontent.com/646398/108162069-3370ad00-70a1-11eb-9d83-339d478ed83e.png)

and `RawImageGLWidget`:
![image](https://user-images.githubusercontent.com/646398/108162112-4aaf9a80-70a1-11eb-86a6-3de897ab8983.png)


I don't imagine that's intentional, or is that a separate issue?

**Comment by pijyoi** [comment]
That's strange indeed. On Windows and Linux, I get the following for RawImageGLWidget.
![Capture](https://user-images.githubusercontent.com/2657027/108165853-39609f80-712e-11eb-9dae-1df31d7f0935.PNG)

**Comment by j9ac9k** [comment]
That was weird how `RawImageGLWidget` needed the transpose if it was `col-major`, but `RawImageWidget` needs the transpose if it's `row-major`.  I'm going to write this off to how openGL is being utilized.

**Comment by pijyoi** [comment]
I think it may have to do with RawImageWidget calling ```fn.makeQImage(argb, alpha)``` relying on the default arguments copy=True and transpose=True.

**Comment by j9ac9k** [comment]
ahh yes, I'm sure that would be it.

Thanks for reporting! 👍
