### ISSUE TITLE
GLVolumeItem Example Generates RuntimeWarnings

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#1584]
### Short description
Running the `GLVolumeItem.py` example app generates Runtime warnings for division by zero

### Code to reproduce

```bash
python examples/GLVolumeItem.py
```

### Expected behavior

Run example without  errors or warnings.

### Real behavior

```
/Users/ogi/Developer/pyqtgraph/examples/GLVolumeItem.py:45: RuntimeWarning: divide by zero encountered in log
  positive = np.log(np.clip(data, 0, data.max())**2)
/Users/ogi/Developer/pyqtgraph/examples/GLVolumeItem.py:46: RuntimeWarning: divide by zero encountered in log
  negative = np.log(np.clip(-data, 0, -data.min())**2)
```

### Tested environment(s)

 * PyQtGraph version: master
 * Qt Python binding: PyQt6 6.0.1
 * Python version: 3.9.1
 * NumPy version: 1.20.1
 * Operating system: macOS 11
 * Installation method: pip

### Additional context

This would be a good first issue; and I'm labeling it as such.

**Comment by pijyoi** [comment]
fixed by #1778
