### ISSUE TITLE
log scale with high axis values generates a overflow RuntimeWarning

### ISSUE THREAD

**Issue by EfremBraun** [pyqtgraph/pyqtgraph#1604]
### Short description
A spurious RuntimeWarning is produced when transforming a plot with high values to log scale.

### Code to reproduce
Take https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/Plotting.py and change `p1 = win.addPlot(title="Basic array plotting", y=np.random.normal(size=100))` to `p1 = win.addPlot(title="Basic array plotting", y=np.random.normal(size=10000))`

### Expected behavior
When clicking Plot Options -> Transforms -> Log X, no errors or warnings should be produced since all x-data is greater than 0.

### Real behavior
A RuntimeWarning occurs. However, the plot appears fine.

```
/Users/edbraun/opt/anaconda3/envs/pyside2-nomkl/lib/python3.9/site-packages/pyqtgraph/graphicsItems/AxisItem.py:831: RuntimeWarning: overflow encountered in power
estrings = ["%0.1g"%x for x in 10 ** np.array(values).astype(float) * np.array(scale)]
```

### Tested environment(s)

 * PyQtGraph version: 0.11.1
 * Qt Python binding: PySide2 5.15.2 Qt 5.15.2
 * Python version: 3.9.1
 * NumPy version: 1.19.4
 * Operating system: macOS Catalina
 * Installation method: pip

**Comment by EfremBraun** [comment]
This is occurring because AxisItem.py calls self.tickStrings() on line 1038 with the original non-transformed values before it calls it again with the transformed values. The first calling is what produces the warning. I'm not sure why it's being called that first time if it just ends up needing to call it again anyway to get final values.

**Comment by sneakers-the-rat** [comment]
+1 

happens here: https://github.com/pyqtgraph/pyqtgraph/blob/98d7bcf5600948be88c97c13bbb2b423439d6ca9/pyqtgraph/graphicsItems/AxisItem.py#L845

where each of the values are used to exponentiate 10, so eg. if you have the far right of your axis be 20,000 then 10**20000 causes an overflow error which returns `'inf'`

**Comment by pijyoi** [comment]
This spurious warning no longer appears in 0.12.2. Bisecting points to the change occurring in 61f067bf7c908c8a8f9f0de5cdc1a95c444bf722.

Testing script
```python
import numpy as np
import pyqtgraph as pg
app = pg.mkQApp()
pw = pg.PlotWidget()
pw.show()
pi = pw.getPlotItem()
pi.setLogMode(x=False, y=True)
y = np.arange(1, 500, dtype=np.float64)
pi.plot(y)
app.exec()
```

**Comment by calceiin** [comment]
The problem still arises for AxisItems. Adapting your code to:
```python
import numpy as np
import pyqtgraph as pg
app = pg.mkQApp()
pw = pg.PlotWidget()
pw.show()
pi = pw.getPlotItem()
y = np.arange(1 , 500, dtype=np.float64)
ai = pi.getAxis("bottom") # new
ai.setLogMode(True) # new
pi.plot(y)
app.exec()
```
This still gives the same error `RuntimeWarning: overflow encountered in power
  estrings = ["%0.1g"%x for x in 10 ** np.array(values).astype(float) * np.array(scale)]` which seems to be due to `10 ** np.array(500)` that gives the overflow.

**Comment by pijyoi** [comment]
With your script, the overflow warning appears for pyqtgraph 0.12.3 but not for master.

I am not quite understanding your issue, does `PlotItem.setLogMode(x=True, y=False)` not serve your use-case? PlotItem will call `AxisItem.setLogMode` as necessary.

>In my case it is quite likely that i want to plot an x-axis with values larger than 500.

Did you want to plot x ~= 500 or x ~= 10**500?
The latter exceeds double precision dynamic range.

**Comment by calceiin** [comment]
Hey, thanks for your reply!

> I am not quite understanding your issue, does PlotItem.setLogMode(x=True, y=False) not serve your use-case? 

No no, if that works, i'm happy. However, i thought i'd mention the bug, too.

> With your script, the overflow warning appears for pyqtgraph 0.12.3 but not for master.

Good to know, thanks. But in the coding environment i (have to) use, it seems like only full releases are usable. So if there is a bug in 0.12.3, which is already fixed in master, i didn't known, sorry.

> Did you want to plot x ~= 500 or x ~= 10**500? The latter exceeds double precision dynamic range

Yes, i know. The plots above are for the same data and same script, just with the difference mentioned above. I would expect the right one with the linear plot to look exactly like the on on the left, with the slope of an exponential and ticks of powers of 10.

**Comment by pijyoi** [comment]
So if you really wanted to do things manually instead of letting `PlotItem` do it for you, this is how it might be done.
You have to call `setLogMode` on both the `AxisItem` and the `PlotDataItem`.
No more overflow warnings on pyqtgraph 0.12.3 either.
```python
import numpy as np
import pyqtgraph as pg
app = pg.mkQApp()
pw = pg.PlotWidget()
pw.show()
pi = pw.getPlotItem()
y = np.arange(1, 500, dtype=np.float64)
ai = pi.getAxis("bottom")
ai.setLogMode(True)
pdi = pi.plot(y)
pdi.setLogMode(True, False)
app.exec()
```

**Comment by calceiin** [comment]
Great, that works. Thank you for your time!

**Comment by j9ac9k** [comment]
Going to close this out as I'm seeing no errors/warnings on 0.13.1.
