### ISSUE TITLE
examples main stanza incorrect for PyQt6

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#1609]
### Short description

The following standard stanza is not working as intended for PyQt6.
```python
if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1 or not hasattr(QtCore, 'PYQT_VERSION'):
        pg.QtGui.QApplication.exec_()
```
PyQt5 installs an input hook by default., https://doc.bccnsoft.com/docs/PyQt5/python_shell.html. 
It appears that PyQt6 does not do the same by default.

### Code to reproduce

```
set PYQTGRAPH_QT_LIB=PyQt6
py -i examples\SimplePlot.py
```

### Expected behavior

A plot window should appear. (Plot window appears for PyQt5, PySide2, PySide6)

### Real behavior

Plot window does not appear.
Python REPL appears.

### Tested environment(s)

 * PyQtGraph version: 0.11.1.dev0 
 * Qt Python binding: PyQt6 6.0.1 Qt 6.0.1
 * Python version: 3.7.9
 * NumPy version: 1.19.5 
 * Operating system: Windows 10 x64
 * Installation method: pip install -e . 

### Additional context
```sys.flags.interactive == 1``` is only true if python is executed with the "-i" argument. So in fact, the standard stanza is targeting only the case where the user wants to execute the example in interactive mode _and_ is running PyQt5.

If such a use case is not common, the standard stanza could be simplified to:
```python
if __name__ == '__main__':
    pg.Qt.QtWidgets.QApplication.exec_()
```

Another way to look at it is that out of the current 4 supported bindings, PyQt5 is the only one that installs an input hook by default.

Incidentally, examples\CLIexample.py did not import QtCore, so executing ```py -i examples\CLIexample.py``` under PyQt5 throws an exception.

**Comment by j9ac9k** [comment]
I'm good with simplifying the standard stanza; ... I suspect this was more commin in pyqt4/pyside1 bindings, but probably time to remove it now.

Thanks for digging into this @pijyoi
