### ISSUE TITLE
PySide6 Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by F3zz1k** [pyqtgraph/pyqtgraph#1614]
### Short description

Creating a graph using PySide6 on windows 10 fails with the error then exits:

> QWidget: Must construct a QApplication before a QWidget

While the same example with PyQT5 works.  What testing I could do seems to suggest that pyqtgraph may be attempting to use Pyqt5 when I want it to use PySide6.  I do import PySide6 before pyqtgraph.
### Code to reproduce

Working:
```
from PyQt5 import QtWidgets
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
import sys  # We need sys so that we can pass argv to QApplication
import os

class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)

        self.graphWidget = pg.PlotWidget()
        self.setCentralWidget(self.graphWidget)

        hour = [1,2,3,4,5,6,7,8,9,10]
        temperature = [30,32,34,32,33,31,29,32,35,45]

        # plot data: x, y values
        self.graphWidget.plot(hour, temperature)


def main():
    app = QtWidgets.QApplication(sys.argv)
    main = MainWindow()
    main.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```
Not Working:
```
from PySide6 import QtWidgets
from pyqtgraph import PlotWidget, plot
import pyqtgraph as pg
import sys  # We need sys so that we can pass argv to QApplication
import os

class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)

        self.graphWidget = pg.PlotWidget()
        self.setCentralWidget(self.graphWidget)

        hour = [1,2,3,4,5,6,7,8,9,10]
        temperature = [30,32,34,32,33,31,29,32,35,45]

        # plot data: x, y values
        self.graphWidget.plot(hour, temperature)


def main():
    app = QtWidgets.QApplication(sys.argv)
    main = MainWindow()
    main.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```

### Tested environment(s)

 * PyQtGraph version: '0.11.1'
 * Qt Python binding: 'PyQt5 5.15.2 Qt 5.15.2'
 * Python version: 3.9.1
 * Operating system: Windows 10
 * Installation method: pip install pyqtgraph

### Additional context
 Following tutorial from https://www.learnpyqt.com/tutorials/plotting-pyqtgraph/ but intend on adding to an application already using PySide6

**Comment by pijyoi** [comment]
Currently, you need to use git master branch to get Qt6 support.

**Comment by j9ac9k** [comment]
@F3zz1k as @pijyoi you need to use the current master branch as of right now if you want Qt6 support, Qt6 is not supported on any currently released version of the library.

We're pretty close to releasing 0.12.0 which will have PyQt6 6.0.1+ and PySide6 support, not going to give an ETA, be soon.  We consider the master branch to be stable, and there won't be any major changes from now until 0.12.0 is released.

**Comment by F3zz1k** [comment]
For anyone on windows having this issue in the meantime, install git and then update pyqtgraph with:
`pip install git+https://github.com/pyqtgraph/pyqtgraph@master`

@j9ac9k @pijyoi  Thanks for your help.

**Comment by j9ac9k** [comment]
@pijyoi deserves all the credit; as they implemented the Qt6 support before any of the other libraries that have Qt abstraction layers did so, including QtPy, pytest-qt, and AnyQt.
