### ISSUE TITLE
mkColor() does not handle QBrush objects

### ISSUE THREAD

**Issue by mspoorendonk** [pyqtgraph/pyqtgraph#1616]
### Short description

When creating a plot with a legend and a curve that has a brush and a filllevel specified, the following error is thrown: 

TypeError: Not sure how to make a color from "(<PyQt5.QtGui.QBrush object

Somewhere in the legend drawing code (I didn't investigate) mkColor() is called with a brush as argument. The mkColor() does not handle brushes though.

### Code to reproduce

```python
p2 = charts.addPlot()
p2.addLegend()
grad = QtGui.QLinearGradient(0, 0, 0, 100)
grad.setColorAt(0, pg.mkColor('#00ff0001'))
grad.setColorAt(0.9, pg.mkColor('#00ff0050')) # green
greenBrush = QtGui.QBrush(grad)

curve5 = p2.plot(pen=pg.mkPen(color='#00ff00', width=2), fillLevel=0, brush=greenBrush, name='test')


```

### Expected behavior

I don't know. Personally I don't want the brush that I use to fill the area under the curve to show up in the legend. But you could show it if you wanted.

### Real behavior

```
An error occurred?
Post the full traceback inside these 'code fences'!
Traceback (most recent call last):
  File "C:\Users\marc_\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\graphicsItems\LegendItem.py", line 329, in paint
    p.setPen(fn.mkPen(opts['fillBrush']))
  File "C:\Users\marc_\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\functions.py", line 328, in mkPen
    color = mkColor(color)
  File "C:\Users\marc_\AppData\Local\Programs\Python\Python39\lib\site-packages\pyqtgraph\functions.py", line 253, in mkColor
    raise TypeError(err)
TypeError: Not sure how to make a color from "(<PyQt5.QtGui.QBrush object at 0x0000019B349A13C0>,)"
```

### Tested environment(s)

 * PyQtGraph version:  0.11.1
 * Qt Python binding: PyQt5 5.15.2 Qt 5.15.2
 * Python version: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
 * NumPy version: 
 * Operating system: Windows 10
 * Installation method: 
pip
### Additional context
I added this to silence the error: I hardly call it a fix.

```
# the original mkColor() doesn't support brushes and throws an error when a brush is passed to the legend.
# this just returns a transparent color to get rid of the problem.
def mkColorNew(*args):
    #print('make color')
    if len(args) == 1 and isinstance(args[0], QtGui.QBrush): # handle brushes
        return QtGui.QColor('#00000000') # transparent
    return pg.functions.mkColorOrig(*args) # call the original function

pg.functions.mkColorOrig = pg.functions.mkColor
pg.functions.mkColor = mkColorNew
```

**Comment by j9ac9k** [comment]
Thanks for reporting, and the code to reproduce.

`functions.mkColor` should definitely not be getting called with the QBrush argument (obvious statement is obvious).

**Comment by j9ac9k** [comment]
#1665 should fix this issue, thanks for reporting @mspoorendonk

**Comment by mspoorendonk** [comment]
Excellent. Thx for the quick fix.
