### ISSUE TITLE
stepMode arguments not working properly 

### ISSUE THREAD

**Issue by Cademan10** [pyqtgraph/pyqtgraph#1621]
Using stepMode=True in a PlotDataItem creates a histogram that associates a given y-value with the left boundary, and using the other string commands ("center", "left", or "right") raises an error regarding array sizes. 

(Tested on Windows 10 using Python 3.7.9 and pyqtgraph  0.11.0)

**Comment by Cademan10** [comment]
The issue was resolved by simply updating to the latest version of PyQtGraph

**Comment by j9ac9k** [comment]
Thanks for following up @Cademan10 

Hopefully this will become less of an issue as we move to a quicker/smaller release cycle.
