### ISSUE TITLE
Remove warning: QApplication was created before pyqtgraph was imported

### ISSUE THREAD

**Issue by titusjan** [pyqtgraph/pyqtgraph#1623]
Due to the plugin nature of my project I have to import PyQtGraph after I have created my `QApplication` object. On MacOS this results in a warning by PyQtGraph. For example ...

```
from PyQt5 import QtWidgets
app = QtWidgets.QApplication([])
import pyqtgraph
```

prints the following to stdout:

```
Warning: QApplication was created before pyqtgraph was imported; there may be problems.
```

It does not state what these problems may be but I never encountered any issues. I vaguely recall reading that it had something to do with setting the graphics system to `raster`, but I can't find anything about it anymore. If this is the case I think the warning can be removed since `setGraphicsSystem` had been removed from Qt5, and Qt4 is no longer supported by PyQtGraph.

So, can the warning be removed? And if not, can you please make it a proper warning by using Pythons logging or warning mechanism?

 * PyQtGraph version: 0.11.1
 * Operating system: OSX 10.14.1

**Comment by j9ac9k** [comment]
Doing a search from my phone, it looks like this only occurs on macOS?  When that print statement was created the versions of Qt we support now likely didn't exist, so it's quite possible whatever issue was occurring is no longer a problem.  when I hop on a PC I'll try and look through the git history and see if I can find an example of something that is broken.

What I would support right now, is changing that print statement to a warning emission, which users can suppress with greater ease.

**Comment by titusjan** [comment]
Thanks.

It seems that there was some more information in the comments before the `setGraphicsSystem` calls were removed. This is were I read that it was related to the Qt4 graphics system. Before commit [61616ffa](https://github.com/pyqtgraph/pyqtgraph/commit/61616ffad943221ab42c52bff3ce55a31c3f229a) the code was:

```
if QtGui.QApplication.instance() is not None:
    print('Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).')
if QtGui.QApplication.setGraphicsSystem:
    QtGui.QApplication.setGraphicsSystem('raster')  ## work around a variety of bugs in the native graphics system 
```
 Perhaps @campagnola remembers what the problems were.
