### ISSUE TITLE
Different yData values obtained 0.11.0 vs 0.11.1

### ISSUE THREAD

**Issue by nicoddemus** [pyqtgraph/pyqtgraph#1634]
Hi folks!

First of all thanks a lot for the great graph library!

I've noticed a difference in behavior of versions `0.11.0` and `0.11.1` when comparing `item.curve.yData` with the original values passed during `plotItem.plot`.

This example reproduces the issue:

```python
from PyQt5.QtWidgets import QApplication
from pyqtgraph import PlotWidget, __version__
import numpy as np

app = QApplication([])
plot_window = PlotWidget()

x = np.array([2250, 2500, 2750, 3000, 3250, 3500, 3750])
y = np.array([41539180., 32281334., 23945627., 16794226., 11033336., 6815729., 4245312.])

plot_window.plotItem.plot(x, y)

item = plot_window.plotItem.items[0]
print(f"pyqtgraph version: {__version__}")
print("x matches:", np.all(np.isclose(item.curve.xData, x)))
print("y matches:", np.all(np.isclose(item.curve.yData, y)))
print(item.curve.yData)

plot_window.show()
app.exec()
```

In `0.11.0` I get this output:

```
pyqtgraph version: 0.11.0
x matches: True
y matches: True
[41539180. 32281334. 23945627. 16794226. 11033336.  6815729.  4245312.]
```

And this graph:

![image](https://user-images.githubusercontent.com/1085180/111697783-befe6a80-8814-11eb-976f-9f60a8cd4e3c.png)

While in `0.11.1` I get this:

```
pyqtgraph version: 0.11.1
x matches: True
y matches: False
[2000001.5 2000001.5 2000001.5 2000001.5 2000001.5 2000001.5 2000001.5]
```

The graph image however is the same:

![image](https://user-images.githubusercontent.com/1085180/111697862-dccbcf80-8814-11eb-9289-ef5ddefab10d.png)

---

This is not a big deal, I'm just curious if this is a bug or some expected behavior.

I browsed the CHANGELOG, but couldn't find anything obvious (at least to me as an user).

Thanks a lot!

**Comment by j9ac9k** [comment]
👋🏻  @nicoddemus I had no idea you were a pyqtgraph user (would love to hear about your use of the library sometime); big fan of your open source work, we're hoping to incorporate pytest-qt in our library before much longer, but back to your issue.  

Our changelog is a bit (understatement of the century) tough to read.  As we migrate to faster release cycles we hope this to be less of an issue.

Thanks to your example, was able to isolate the difference via git-bisect to #1140 which was merged as a work-around for [QTBUG-36720](https://bugreports.qt.io/browse/QTBUG-36720) and reported in our issue tracker as #31 

I made a slight modification to your script to get the correct data out:

```python
from pyqtgraph.graphicsWindows import PlotWindow
from PyQt5.QtWidgets import QApplication
from pyqtgraph import PlotWidget, __version__
import numpy as np

app = QApplication([])
plot_window = PlotWidget()

x = np.array([2250, 2500, 2750, 3000, 3250, 3500, 3750])
y = np.array([41539180., 32281334., 23945627., 16794226., 11033336., 6815729., 4245312.])

plot_window.plotItem.plot(x, y)
item = plot_window.plotItem.items[0]

print(f"pyqtgraph version: {__version__}")
print("x matches:", np.all(np.isclose(item.xData, x)))
print("y matches:", np.all(np.isclose(item.yData, y)))
print(item.yData)

plot_window.show()
app.exec()
```

I'm not saying there isn't a bug, I'll let @NilsNemitz chime in a bit more about some intent here.

I am curious about your use-case.  We're starting to have some discussions internally about whether we want to preserve the underlying numpy array in our objects as a copy.  Things get weird with lots of data points and downsampling, combined with the interactive nature of the library.

**Comment by nicoddemus** [comment]
> 👋🏻 @nicoddemus I had no idea you were a pyqtgraph user (would love to hear about your use of the library sometime); big fan of your open source work, we're hoping to incorporate pytest-qt in our library before much longer, but back to your issue.

Thanks, appreciate that! Sounds good about `pytest-qt`. 😁 

> Our changelog is a bit (understatement of the century) tough to read. As we migrate to faster release cycles we hope this to be less of an issue.

You folks really did an amazing work with that release already, understandable the changelog is a bit dev-oriented right now. 👍 

> I made a slight modification to your script to get the correct data out:

Ahh cool, that's certainly workable.

> I am curious about your use-case.

I'm playing around with `pyqtgraph` a bit, studying it as a replacement for PyQwt; I stumbled on this because I am writing some simple tests, and one of my utility test functions was testing that the curve I passed to `plot` is actually being plotted (as I switch between different curves). Not a big deal in my case because I could workaround that, but decided to post here to see if there was a better way (and there is!).

Thanks for the quick reply, appreciate it!

**Comment by NilsNemitz** [comment]
Dear @nicoddemus,
Thank you for the report and the ready-to-run example!

Just to explain a little bit:
The `plotItem.plot()` command gives you a PlotDataItem, which contains some high level functionality for downsampling etc.
The data that gets passed to the PlotCurveItem that you have as item.curve is the processed data.

Your example is triggering the "dynamic range limiter" added in #1140. At the time that you are checking the data, nothing has been drawn, and PlotDataItem assumes a default viewing range of 0...1. The dataset contains points far outside that range, which tends to trigger a Qt bug where paths don't render at all when they are zoomed in on a tiny fraction (<1E-7 or so) of the full size.

For that reason, it is intentional that the data is clipped (to ~2E6 the view range) before it is passed to the PlotCurveItem for display. PlotCurveItem keeps the clipped copy around. As @j9ac9k points out, there might be more elegant ways to handle that.

Once drawn, the vertical axis auto-ranges and the clipping calculation is redone. For the expanded axis, the clipping limit will be >1E13 and no longer affect the data, but that happens after the checks in your example.

If you want to check that the correct data gets passed all the way to the PlotCurveItem, I would recommend to set 
`plot_window.plotItem.setYRange(0, 2e6) `
before adding the actual data. Choose any range of similar magnitude to what you expect to ultimately see on screen, 

Here is a modified example to play with
```
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtCore import QTimer
from pyqtgraph import PlotWidget, __version__
import numpy as np

class TestApp(QMainWindow):
    def __init__(self,app):
        super().__init__()
        plot_window = PlotWidget()
        self.setCentralWidget( plot_window )
        self.timer = QTimer(singleShot=False)
        self.timer.timeout.connect(self.repeat)
        self.timer.start(1)
        self.countdown = 10

        x = np.array([2250, 2500, 2750, 3000, 3250, 3500, 3750])
        y = np.array([41539180., 32281334., 23945627., 16794226., 11033336., 6815729., 4245312.])
        # pre-setting the vertical range removes the need for range limiting:
        # plot_window.plotItem.setYRange(0, 2e6) 
        plot_window.plotItem.plot(x, y)
        self.item = plot_window.plotItem.items[0]

        print(f"pyqtgraph version: {__version__}")
        print('\nchecks against clipped PlotCurveItem:')
        print("x matches:", np.all(np.isclose(self.item.curve.xData, x)))
        print("y matches:", np.all(np.isclose(self.item.curve.yData, y)))
        print('\nchecks against original data held by PlotDataItem:')
        print("x matches:", np.all(np.isclose(self.item.xData, x)))
        print("y matches:", np.all(np.isclose(self.item.yData, y)))
        print('\noriginal data is kept in PlotDataItem :', self.item.yData)
        print('PlotDataItem provides processed data  :', self.item.getData()[1])
        print('PlotCurveItem stores this clipped data:', self.item.curve.yData)
        print('\nWatching data settle after drawing:')
        self.show()

    def repeat(self):
        print('data now:', self.item.curve.yData)
        self.countdown -=1
        if self.countdown == 0: self.timer.stop()

app = QApplication(sys.argv)
window = TestApp(app)
sys.exit(app.exec_())
```

This runs a timer to watch PlotCurveItem's data update as the plot gets drawn. Once done it does match the original dataset.

```
pyqtgraph version: 0.11.1.dev0

checks against clipped PlotCurveItem:
x matches: True
y matches: False

checks against original data held by PlotDataItem:
x matches: True
y matches: True

original data is kept in PlotDataItem : [41539180. 32281334. 23945627. 16794226. 11033336.  6815729.  4245312.]
PlotDataItem provides processed data  : [1999999.5 1999999.5 1999999.5 1999999.5 1999999.5 1999999.5 1999999.5]
PlotCurveItem stores this clipped data: [1999999.5 1999999.5 1999999.5 1999999.5 1999999.5 1999999.5 1999999.5]

Watching data settle after drawing:
data now: [1999999.5 1999999.5 1999999.5 1999999.5 1999999.5 1999999.5 1999999.5]
data now: [1999999.5 1999999.5 1999999.5 1999999.5 1999999.5 1999999.5 1999999.5]
data now: [2999999. 2999999. 2999999. 2999999. 2999999. 2999999. 2999999.]
data now: [3999998.5 3999998.5 3999998.5 3999998.5 3999998.5 3999998.5 3999998.5]
data now: [4999998. 4999998. 4999998. 4999998. 4999998. 4999998. 4245312.]
data now: [41539180. 32281334. 23945627. 16794226. 11033336.  6815729.  4245312.]
```

**Comment by NilsNemitz** [comment]
There *are* two bugs here:
1) We spend too much effort drawing into the original undefined viewbox.
2) When the entire dataset falls out of the clipping range on the high end (all >1E7), then the clipped data is flat (all 1999999.5 here) and the automatic view range (top-to-bottom) fails to expand. It just kind of hops toward the proper range. While the final view is good, it can take a lot of wasted steps to get there. Scale up the numbers by a few orders of magnitude, and this will take many iterations. 

So, thanks again for the report @nicoddemus , I will think about (1) and try to come up with a fix for (2) on the weekend :)

**Comment by j9ac9k** [comment]
@nicoddemus 

If you're wanting to test if an image is _actually_ plotted; we actually have a function, `assertImageApproved`, that takes the contents of the displayed window, and compares it to a pre-stored image:

https://github.com/pyqtgraph/pyqtgraph/blob/3f9e56f62e3cdb2e6115400350a90b953e0c14ce/pyqtgraph/tests/image_testing.py#L104

We use that function to test curve items (and some other things as well):

https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/tests/test_PlotCurveItem.py

Here are the images we test again (for the plot curves) https://github.com/pyqtgraph/test-data/tree/master/plotcurveitem (one of my projects has been to move the test images into this repository and simplify our test suite some).

The downside here is you have to have "known good" images ahead of time, but for this kind of smoke-test, we've found they work fairly well.

**Comment by nicoddemus** [comment]
@NilsNemitz thanks a lot for the detailed and clarifying answer!

@j9ac9k that `assertImageApproved` is definitely interesting and I will keep it in mind. It seems similar to [`pytest-regressions`](https://github.com/ESSS/pytest-regressions), which we use extensively. 👍 

Thanks again folks for the detailed and quick answers! Keep up the excellent work on the library. 👍
