### ISSUE TITLE
Parentless ViewBox object in ImageView not executing ViewBox.unregister() on close of main windown in IPython

### ISSUE THREAD

**Issue by NoerthersTheorem** [pyqtgraph/pyqtgraph#1640]
### Short description
This is a very simple, small bug that sometimes causes problems in an IPython shell when class static variables hang around between code executions.  When an ImageView instance is created, it creates a parentless ViewBox, and then another parentless ViewBox in the ROI plot.  These ViewBox instances are "registered" in static class dictionaries ViewBox.NamedViews and ViewBox.AllViews.  Because the ViewBox instances have no parents, I *think* their proper ViewBox close() functions are not always getting called when a main Window closes in IPython.  This means the ViewBox instances are not unregistered from ViewBox.NamedViews and ViewBox.AllViews. I don't know if hardcoding a parent object for these ViewBoxes is an option (maybe it breaks something else?), but assigning them in my code fixed the problem and I would just like to bring it to the developers' attention. 

EDIT: Forgot to say why this is a bug not feature:  Sometimes ViewBoxes that have their wrapped C++ objects deleted stay registered between code executions.

**Comment by j9ac9k** [comment]
This issue has sort of nagged at me for quite some time.  I don't have a solid enough of an understanding of QObject lifecycles to say with certainty if it _should_ be one way or another.  

I know @pijyoi has done a lot of work/experimentation in this area recently, they may have something to add. Also @campagnola if around, I'd love to hear your thoughts.

**Comment by pijyoi** [comment]
I am afraid I can't help here. I don't run pyqtgraph in an interactive manner because usually the code required to set things up is already quite long.

**Comment by j9ac9k** [comment]
Yeah, pyqtgraph (or really anything Qt related) in interactive mode definitely feels a bit of an anti-pattern.  My thoughts were mostly in the context of various `QGraphicsWidget` s not having parent objects in general.  This never felt right to me, but again, my understanding of Qt lifecycle management is not that great.

Which object should be the parent of a `ViewBox`; the `GraphicsScene` it's a member of?

**Comment by NoerthersTheorem** [comment]
I'm doing code development in Spyder and was letting it run in the IPython console.  I can instead run in external terminal and fix this problem, which is one of garbage collection. However, I figured out how to solve the problem...manually clear any main window references to the ImageViews on close...or, don't have them in the first place.  Something weird is going on such that even deleting the main window object won't get rid of the member references.   Keeping ImageView references creates circular references that prevent ViewBox garbage collection, even after the wrapped C++ object is destroyed. 

So I guess parentage isn't really the issue as much as circular strong references.   I guess go ahead and close this  issue once it is decided whether or not to break those circular references in ImageView.  Circular references with sip wrappers seem to make it more likely to see those runtime errors that raise when the underlying C++ objects are destroyed but the Python object isn't collected.

**Comment by NoerthersTheorem** [comment]
Nevermind, I'm closing this because I think it's just something weird about Spyder's variable explorer--or something else--holding strong references. Maybe, maybe not. I don't think it's worth thinking about anymore.

**Comment by j9ac9k** [comment]
@NoerthersTheorem Thanks for reporting and thanks for following up. I think you are onto something with the series of circular strong references, that's tricky to get right and it's quite possible we have a mistake in our library.   We don't get a lot of interactive users here, so hearing about potential issues in this kind of use-case is valuable to us.

If you don't mind me asking, how did you determine what was holding the reference?  In case you're debugging this, pyqtgraph does have some tools to help trace references: 

https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/debug.py#L914

**Comment by NoerthersTheorem** [comment]
I used gc, the garbage collection interface module, however, the pyqtgraph utility shows the same thing: ImageView.roi is circularly referenced with ImageView.view.  Mystery solved.

**Comment by NoerthersTheorem** [comment]
I reopened this because I did finally figure out the circular reference (see previous comment's edits):  ImageView.view -> ImageView.imageItem -> ImageView.image -> ImageView -> ImageView.view.  I tested this in an IPython shell.  Create ImageView instance *im*.  Leave im.image = None and you can delete the ImageView instance *im* with everything getting collected.  Set im.image = an immutable like a numpy array, the viewboxes do not get collected.  That's the circle.

**Comment by j9ac9k** [comment]
@NoerthersTheorem Thanks so much for staying on this.  Just for completeness sake, can you give the code you used to generate this issue ... or at least the commands you used in interactive mode?

**Comment by NoerthersTheorem** [comment]
@j9ac9k You know...I'm just going to have to admit I was wrong again.  A reference to member variables is not the same as a reference to the containing object.  I got my result when I was performing list(ViewBox.AllViews) in IPython, which apparently creates some permanent unreachable references to the keys.  This has something to do with the environment. Maybe something related to the _ variable (previous cmd). 

I closed again because I think this is just an issue where if you run the code in terminal and let the system clean up everything, you're fine.  I'm sure this incomplete cleanup is happening with a lot of PyQt5 objects, but there's no static list to throw errors so I don't see them.

**Comment by j9ac9k** [comment]
As I said earlier, we don't get a lot of users using pyqtgraph in interactive mode, it's quite reasonable to assume that there is a bug within the library that is more noticeable when running in interactive mode.

Also, this kind of errors can lead to segfaults, which are _really_ annoying to troubleshoot, so if you have identified a potential source of a segfault, I'm going to want to investigate.

**Comment by NoerthersTheorem** [comment]
@j9ac9k Heh, I thought we moved to Python to avoid segfaults. :-P.  

In all seriousness, I think the solution is not to run in IPython, but if you do, do setAttribute(Qt.WA_DeleteOnClose,True)  on PyQt objects where appropriate, and delete everything at least 2 nested levels down from the main namespace.  This seems to clean everything up.  I think it's a PyQt issue not a pyqtgraph issue.  But watch me be wrong and feel such angst at being so close to the answer but missing it.
