### ISSUE TITLE
Release a new version to support pyqt6 and pyside6

### ISSUE THREAD

**Issue by diepala** [pyqtgraph/pyqtgraph#1642]
I think it should be released a new version of pyqtgraph (0.11.2 for example) so that the support for pyqt6 and pyside6 are included. At the moment support is only available in the development version.

**Comment by j9ac9k** [comment]
We are close to a release, as there are a number of PRs that are close to being ready to merge, #1617 is the primary one which has significant performance benefits to one of the parts of the library that is most impacted.
