### ISSUE TITLE
How does pyqtgraph turn off autoscale?

### ISSUE THREAD

**Issue by lyl1836** [pyqtgraph/pyqtgraph#1654]
I want to do financial analysis with pyqtgraph. I need to calculate the trend change rate.

Auto scaling causes the trend angle to change,

How to turn off auto zoom?

![image](https://user-images.githubusercontent.com/48607893/112397384-f00efb80-8d3c-11eb-9125-b77c9f7dad8c.png)

**Comment by j9ac9k** [comment]
If you know you're fixed range values, you want to limit the view at, you can do `viewBox.setYRange(y_min, y_max)`  (or `plotItem.setYRange(y_min, y_max)`)

**Comment by lyl1836** [comment]
@j9ac9k ：
Thank you very much.

Ask another question: I hope pyqtgraph can only move horizontally and turn off the up and down movement function. How to set it?

**Comment by lyl1836** [comment]
@j9ac9k ：
Thank you very much.

Ask another question: I hope pyqtgraph can only move horizontally and turn off the up and down movement function. How to set it?

**Comment by lyl1836** [comment]
Can you add scrollbars to pyqtgraph?

![image](https://user-images.githubusercontent.com/48607893/112451882-f333d700-8d90-11eb-8810-7db8f6e4b218.png)

**Comment by j9ac9k** [comment]
You can see we disable those by default here:

https://github.com/pyqtgraph/pyqtgraph/blob/d7668f91b39269c1b9bd48d3cbcaa903fd3469f1/pyqtgraph/widgets/GraphicsView.py

I haven't tested this, but you could like do something like `plotItem.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)`

**Comment by lyl1836** [comment]
@j9ac9k ：
Thank you very much for your guidance!
I just learned pyqtgraph, and hope to embed the pyqtgraph diagram in the application of pyqt5.
My application is to do financial analysis and support mouse events.
My current component application structure is as follows：
horizontalLayout --> GraphicsLayoutWidget --> addPlot --> addItem --> QPicture --> QPainter --> drawLine , drawRect. 
In such a structure, the reference to your guidance of the three code failed!
I don't use graphicsview. I use graphicsview to realize the structure of pyqtgraph embedded in pyqt5. I can't do it yet. Please give me some guidance!

**Comment by lyl1836** [comment]
@j9ac9k ：
Thank you very much for your guidance!
I just learned pyqtgraph, and hope to embed the pyqtgraph diagram in the application of pyqt5.
My application is to do financial analysis and support mouse events.
My current component application structure is as follows：
horizontalLayout --> GraphicsLayoutWidget --> addPlot --> addItem --> QPicture --> QPainter --> drawLine , drawRect. 
In such a structure, the reference to your guidance of the three code failed!
I don't use graphicsview. I use graphicsview to realize the structure of pyqtgraph embedded in pyqt5. I can't do it yet. Please give me some guidance!

**Comment by j9ac9k** [comment]
Almost everything in pyqtgraph uses `GraphicsView` (including `GraphicsLayoutWidget`) somewhere in the inheritance tree.  You can see this digram here for more information (which reminds me I really should poke around at it and see if it can be made easier to follow/read) 

https://github.com/pyqtgraph/pyqtgraph/pull/1631

What you probably want to do is for `your instance of `GraphicsLayoutWidget`  to call `.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)`

This is the first request I'm aware of for scroll-bars; most people just plot the visible range, and pan the plot with mouse/keyboard.  What I often do in my work is use a "selectable region" and a "global" view at one level, and then adjust the region to look at the area of interest.

![image](https://user-images.githubusercontent.com/646398/112526261-fd3ce200-8d5e-11eb-98ca-485b6ee3dc09.png)

**Comment by lyl1836** [comment]
@j9ac9k ：
#The picture of 1631 problem is very good!

I'll study it first according to your instruction.

Thank you very much.
