### ISSUE TITLE
How can multiple subplots of pyqtgraph share the same X-axis?

### ISSUE THREAD

**Issue by lyl1836** [pyqtgraph/pyqtgraph#1658]
With pyqtgraph, how can multiple subplots share the same Y-axis?

![image](https://user-images.githubusercontent.com/48607893/112564182-c2e24c00-8e15-11eb-8a5e-6b8bb3e69652.png)

**Comment by j9ac9k** [comment]
Take a look at the linkedViews example: https://github.com/pyqtgraph/pyqtgraph/blob/4951bd743ef7e2a5198615573167301c9603b72f/examples/linkedViews.py

from the example app, in `GraphicsItems` take a look at "Linked Views", run the example, it shows how to connect the axes of multiple plots together.

**Comment by lyl1836** [comment]
Thank you very much. According to your method has been set up!

There is another question: how to hide the x-axis or y-axis of a plot?

**Comment by lyl1836** [comment]
This article is very good! Thank you very much.

How to make the graph generated by multiple addplots not equal scale display? For example: in the financial chart, the K-line chart is twice of the trading volume chart.

**Comment by j9ac9k** [comment]
Assuming the plots are laid out in a GraphicsLayout item, the way I set fixed heights is my interacting with the underlying QGraphicsGridLayout.

For example, assuming your layout is as a variable `graphicsLayout` it would go something like:

```python
graphicsLayout.layout.setRowFixedHeight(0, 200)
graphicsLayout.layout.setRowFixedHeight(1, 200)
graphicsLayout.layout.setRowFixedHeight(2, 200)
```

The `GraphicsLayout` object has a `QGraphicsGridLayout` object set as it's `layout` property, and it's perfectly fair game to manipulate that.  Here is the documentation to handle the resizing of elements there, which will give you more control: http://doc.qt.io/qt-5/qgraphicsgridlayout.html

**Comment by lyl1836** [comment]
@j9ac9k 
Thank you very much. Pyqtgraph is great!
Want to challenge again: can pyqtgraph show cross hairs and show x, Y values?

**Comment by lyl1836** [comment]
@j9ac9k :
Since I embed pyqtgraph in pyqt5 and use the graphicslayouwidget, how can I customize the height when using multiple addplots?

**Comment by j9ac9k** [comment]
For the crosshairs, your can see this example: examples/crosshair.py

For heights, I'm not sure what you mean but I would look at that underlying `QGraphicsGridItem`  and manipulating that object.

**Comment by lyl1836** [comment]
@j9ac9k ：
Thank you very much.

**Comment by shujaatak** [comment]
> With pyqtgraph, how can multiple subplots share the same Y-axis?
> 
> ![image](https://user-images.githubusercontent.com/48607893/112564182-c2e24c00-8e15-11eb-8a5e-6b8bb3e69652.png)

Have you made this financial plot in pyqtgraph? 

I am looking for a graph like this. Can you please share ideas?

**Comment by j9ac9k** [comment]
You can certainly do that, although it might get tricky if the lines start getting lengthy.  The way to do it would be to use a GraphicsLayout, have the plots, and x-axis axis items be in one column, and have the y-axis axisitem's be in another column.  This will force the y-axis axis items to have the same width.  There is a diagram of the layouts here if you scroll down a bit: https://pyqtgraph.readthedocs.io/en/latest/plotting.html

I'm going to close out this issue as it's not reporting an issue with the library, and we're trying to get a handle of our issue tracker.
