### ISSUE TITLE
pip installation of pyqtgraph 0.12.0 does not bundle colors/maps directory

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#1659]
### Short description

In a pip install of pyqtgraph 0.12.0, the colors/maps subdirectory is not included in the install.

### Code to reproduce

```
py -m pyqtgraph.examples.colorMaps
```

### Expected behavior

Color Maps example should execute.

### Real behavior

```
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\XYZ\\AppData\\Local\\Programs\Python\\Python38\\lib\\site-packages\\pyqtgraph\\colors\\maps'
```

### Tested environment(s)

 * PyQtGraph version: 0.12.0
 * Qt Python binding: PySide6 6.0.1 Qt 6.0.1
 * Python version: 3.8.8
 * NumPy version: 1.20.1
 * Operating system: Windows
 * Installation method: pip

### Additional context
The user can more easily trigger this by trying to run the Color Maps example from the ExampleApp GUI.

**Comment by j9ac9k** [comment]
Wouldn't have had this issue if we were still on azure pipelines where we could test against the installed package, not a clone of the repo.

I'll look into this.  0.12.1 shoulder probably come out soon.

**Comment by NilsNemitz** [comment]
That is very unfortunate. Thank you @pijyoi , I hope we can fix that before we get too many downloads of the new version.

**Comment by j9ac9k** [comment]
I haven't done enough `setup.py` work to be able to point out what's wrong from the error alone, but I've done enough `setup.py` work I can debug this, so I've self assigned.
