### ISSUE TITLE
3D Graphics examples fail on Wayland (disabled XWayland)

### ISSUE THREAD

**Issue by adabru** [pyqtgraph/pyqtgraph#1661]
### Short description

Some of the 3D Graphic examples fail when running the examples under native Wayland (no XWayland).

### Long description

When running `QT_QPA_PLATFORM=wayland-egl python -m pyqtgraph.examples` under the linux weston compositor, the examples *Volumetric* and *Image* run fine.

The examples *Isosurface*, *Surface Plot*, *Scatter Plot*, *Shaders* and *Mesh* show a grid but no data and fail with:

```
[08:49:35]

    |==============================>>
    |  Traceback (most recent call last):
 <<shortened>>
    |    File "/home/adabru/.local/lib/python3.9/site-packages/pyqtgraph/opengl/items/GLMeshItem.py", line 179, in paint
    |      glVertexPointerf(verts)
    |    File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
    |    File "src/wrapper.pyx", line 321, in OpenGL_accelerate.wrapper.Wrapper.__call__
    |    File "/home/adabru/.local/lib/python3.9/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    |      contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
    |    File "/home/adabru/.local/lib/python3.9/site-packages/OpenGL/contextdata.py", line 58, in setValue
    |      context = getContext( context )
    |    File "/home/adabru/.local/lib/python3.9/site-packages/OpenGL/contextdata.py", line 40, in getContext
    |      raise error.Error(
    |  OpenGL.error.Error: Attempt to retrieve context when no valid context
    |==============================<<
```

The example *Line Plot* fails with:

```
[08:49:40]

    |==============================>>
    |  Traceback (most recent call last):
 <<shortened>>
    |    File "/home/adabru/.local/lib/python3.9/site-packages/pyqtgraph/opengl/items/GLLinePlotItem.py", line 68, in paint
    |      glVertexPointerf(self.pos)
    |    File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
    |    File "src/wrapper.pyx", line 321, in OpenGL_accelerate.wrapper.Wrapper.__call__
    |    File "/home/adabru/.local/lib/python3.9/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    |      contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
    |    File "/home/adabru/.local/lib/python3.9/site-packages/OpenGL/contextdata.py", line 58, in setValue
    |      context = getContext( context )
    |    File "/home/adabru/.local/lib/python3.9/site-packages/OpenGL/contextdata.py", line 40, in getContext
    |      raise error.Error(
    |  OpenGL.error.Error: Attempt to retrieve context when no valid context
    |==============================<<
```

### Steps to reproduce

Boot into a linux desktop. Start a weston session (taken from a [fedora HowTo](https://fedoraproject.org/wiki/How_to_debug_Wayland_problems)):

- install your distribution's `weston` package (pacman, dnf, apt-get, ...)
- switch into another VTE by pressing ctrl+alt+fx
- run `weston-launch` (you can quit the session by pressing ctrl+alt+backspace)
- click on the weston-terminal and run `QT_QPA_PLATFORM=wayland-egl python -m pyqtgraph.examples`
- try out the 3D Graphics examples and observe the mentioned errors

If you just run `python -m pyqtgraph.examples` (or equivalently `QT_QPA_PLATFORM=xcb python -m pyqtgraph.examples`), the examples are run under XWayland and everything works fine.

### Tested environment(s)

 * PyQtGraph version: 0.12.0
 * Qt Python binding: PyQt5 5.15.4 Qt 5.15.2
 * Python version: 3.9.2
 * NumPy version: 1.20.1
 * Operating system: linux arch
 * Installation method: pip
 * weston: 9.0.0
 * PyOpenGL 3.1.5, PyOpenGL-accelerate 3.1.5

### Additional context

It could be an upstream problem in pyqt5, qt5, pyopengl, wayland or the compositor. Since only a part of the examples don't work, I first reported the issue here. 

My next step would've been creating a MWE causing the error using only pyqt5 and pyopengl without pyqtgraph, but I ran out of time for now. If you have some thoughts on that I'd be glad to hear them.

**Comment by pijyoi** [comment]
Would there happen to be a "wayland" plugin rather than a "wayland-egl"?

Pyqtgraph 3d examples use OpenGL 2.0 and don't run on OpenGL ES.

**Comment by pijyoi** [comment]
I logged into "Ubuntu on Wayland" on Ubuntu 20.04 and I got the same results as you both on Qt5 and Qt6. Also, there were some warnings being printed out by Qt such as:
"Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway."

So I guess running Qt on wayland is not quite there yet?

**Comment by pijyoi** [comment]
I got the examples running by setting the following environment variables:
```
QT_QPA_PLATFORM=wayland
PYOPENGL_PLATFORM=egl
```

**Comment by j9ac9k** [comment]
> I got the examples running by setting the following environment variables:

So I'm not a linux desktop daily driver user, but what's the expectation of library support here?  Should pyqtgraph try and recognize if it's running on wayland, and emit a warning if those variables are not set?  Should we just put a blurb somewhere in the docs?

**Comment by adabru** [comment]
> PYOPENGL_PLATFORM=egl

Oops, I thought I tried that already, but apparently didn't. Thank you very much @piyoi, that also works for me!

> Should pyqtgraph try and recognize if it's running on wayland, and emit a warning if those variables are not set? Should we just put a blurb somewhere in the docs?

Referring to https://github.com/FlorianRhiem/pyGLFW/issues/49#issuecomment-617927056 this seems to be an upstream issue of pyopengl. There already is a [bug report](https://sourceforge.net/p/pyopengl/bugs/275/) and an unmerged fix done a year ago waiting for a response. I'll try it out and report back when I got a response there.

**Comment by j9ac9k** [comment]
I think for the time being something should be put in the docs, referencing the bug report in the pyopengl issue tracker.

**Comment by adabru** [comment]
This could be fixed by now: [github.com/mcfletch/pyopengl/issues/41](https://github.com/mcfletch/pyopengl/issues/41) . The relevant code is merged into master. I can't test at the moment though.

**Comment by adabru** [comment]
Okay, I tested it today. `QT_QPA_PLATFORM=wayland-egl python -m pyqtgraph.examples` runs fine now without setting PYOPENGL_PLATFORM.
