### ISSUE TITLE
Expanding group parameters in ParameterTree not working

### ISSUE THREAD

**Issue by ikost** [pyqtgraph/pyqtgraph#1663]
### Short description
Issue with controlled expanding and collapsing group type parameters in ParameterTree. 

### Expected behaviour
Parameter.setOpts(expanded=True) expands collapsed group parameter in the ParameterTree

### Real behaviour
Using Parameter.setOpts(expanded=True) not working. The "opt" value is changing but the expanding of the parameter does not happen. Looks like the opts == "expanded" is not defined in the parameter.setOpts() method

### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Qt Python binding: PySide2                   5.15.2
 * Python version: 5.9.2
 * NumPy version: 1.19.4
 * Operating system: Mac OS and Windows
 * Installation method: pip

**Comment by lidstrom83** [comment]
Thanks for the report. This has been fixed in #1469, which is included in 0.12.0 which was just released yesterday.

**Comment by ikost** [comment]
I have tested the v 12.0 and the problem does not seem to be solved. Both
`Parameter.setOpts(expanded=True)`
and 
`Parameter.opts['expanded']=True`
are not expanding the group type parameters.

**Comment by lidstrom83** [comment]
Here is the minimal working example I used to verify it was working:
```
import pyqtgraph as pg
from pyqtgraph.parametertree import Parameter, ParameterTree


app = pg.mkQApp()
pt = ParameterTree(showHeader=False)
p = Parameter.create(name='params', type='group', children=[
    dict(name='group', type='group', children=[
        dict(name='int', type='int')
    ])
])
pt.setParameters(p)
p.child('group').setOpts(expanded=False)
pt.show()
app.exec_()
```

If you're triggering a bug in some other way, please post a MWE to demonstrate and I will investigate further.

**Comment by lidstrom83** [comment]
FY this works fine for me as well:
```
import pyqtgraph as pg
from pyqtgraph.parametertree import Parameter, ParameterTree


app = pg.mkQApp()
pt = ParameterTree(showHeader=False)
p = Parameter.create(name='params', type='group', children=[
    dict(name='group', type='group', expanded=False, children=[
        dict(name='int', type='int')
    ])
])
pt.setParameters(p)
p.child('group').setOpts(expanded=True)
pt.show()
app.exec_()
```

**Comment by ikost** [comment]
Yes. Correct. It is working! My problem had different origin.
