### ISSUE TITLE
Displayed image is interpolated on Linux (anaconda), not on windows

### ISSUE THREAD

**Issue by kubaraczkowski** [pyqtgraph/pyqtgraph#167]
Hi,

Identically to issue reported here : (https://groups.google.com/forum/#!msg/pyqtgraph/SDUGIkMgEJk/wDPKCw8FSt8J) there is no control on interpolation of images. Specifically, it seems to be platform/installation dependent.

Any idea how to enable/disable interpolation on displayed images?

**Comment by campagnola** [comment]
Summary from the mailing list:

* This appears to be a Qt bug, and so far is only seen on Linux.
* A workaround is to call `QtGui.QApplication.setGraphicsSystem('native')` _before_ creating the `QApplication` instance.

**Comment by j9ac9k** [comment]
Given we haven't heard more of this, I'm willing to bet this has been fixed, so I'm going to close this out.
