### ISSUE TITLE
How to save a complete picture?

### ISSUE THREAD

**Issue by lyl1836** [pyqtgraph/pyqtgraph#1670]
I embed pyqtgraph in pyqt5. 

In pyqtgraph, the predetermined graphic proportion allocation can not be realized. 

Currently, pyqt5 is used to allocate the proportion. The component structure is: qgridlayout > qhboxlayout > graphicslayoutwidget > addplot.

This structure can only save one plot at a time. Is there any way to save the whole picture?

Or is there a way to achieve such proportional allocation in pyqtgraph?

![image](https://user-images.githubusercontent.com/48607893/112776082-40ee5f00-9071-11eb-874f-943ae69811a8.png)

![image](https://user-images.githubusercontent.com/48607893/112776134-63807800-9071-11eb-9084-6ca30877e0da.png)

**Comment by lyl1836** [comment]
Please refer to:
#1674

**Comment by j9ac9k** [comment]
You can export the whole picture by selecting "Entire Scene" from the tree view of the export window.

**Comment by lyl1836** [comment]
@j9ac9k : 
How to save pictures automatically with program code?

**Comment by j9ac9k** [comment]
I'm not sure about that off the top of my head; but we have a blurb about it in our docs: https://pyqtgraph.readthedocs.io/en/latest/exporting.html?highlight=exporting%20api#exporting-from-the-api

**Comment by lyl1836** [comment]
@j9ac9k ：

There is only one plotitem in the sample program. What should I do if there are multiple plotitems?

![image](https://user-images.githubusercontent.com/48607893/112907676-d8f75180-9120-11eb-8b12-3db3b2fc53cd.png)

**Comment by j9ac9k** [comment]
I'm guessing, but probably want to do `plt.plotItem.scene()`

**Comment by lyl1836** [comment]
@j9ac9k ：
I tried and failed!

**Comment by j9ac9k** [comment]
> @j9ac9k ：
> 
> I tried and failed!

Try passing the layout object?

**Comment by lyl1836** [comment]
@j9ac9k ：

![image](https://user-images.githubusercontent.com/48607893/112926763-829d0980-9146-11eb-9e8f-bea2c51a561d.png)

**Comment by ixjlyons** [comment]
A `GraphicsLayout` can be passed directly to `ImageExporter`. From a `GraphicsLayoutWidget`, you can get the underlying `GraphicsLayout` via the `ci` attribute.

**Comment by lyl1836** [comment]
@ixjlyons :

The teacher's method is very good! Thank you very much.

The fly in the ointment is: the proportion of the exported image is not consistent with the original image!

![image](https://user-images.githubusercontent.com/48607893/112942829-4b892100-9163-11eb-97c1-6a5f9f02c2f6.png)

**Comment by ixjlyons** [comment]
Probably based on [this](https://github.com/pyqtgraph/pyqtgraph/issues/1673#issuecomment-809915175).

Example:

```python
import pyqtgraph as pg
from pyqtgraph.exporters import ImageExporter

app = pg.mkQApp()

glw = pg.GraphicsLayoutWidget()
glw.show()

glw.addPlot(x=[1, 2, 3], y=[1, 2, 3])
glw.nextRow()
glw.addPlot(x=[1, 2, 3], y=[1, 8, 27])

glw.ci.layout.setRowStretchFactor(0, 2)

# app.processEvents()

exp = ImageExporter(glw.ci)
exp.export("export.png")

app.exec_()
```

If you insert an `app.processEvents()` between setting the row stretch factor and calling `export`, it should work. I think this is a somewhat general issue with programmatic export - I'm not sure if there's a better solution.

**Comment by lyl1836** [comment]
@ixjlyons ：
Your example is very good! The actual measurement is also effective! Thank you very much.

**Comment by j9ac9k** [comment]
I think we can close this out as it's been answered.
