### ISSUE TITLE
In pyqtgraph, how to use mouse hand animation line?

### ISSUE THREAD

**Issue by lyl1836** [pyqtgraph/pyqtgraph#1671]
In financial analysis, we often need to draw some analysis charts on the original graphics, such as trend line, blocking position, etc.

In pyqtgraph, how to use mouse hand animation line?

**Comment by ixjlyons** [comment]
Check out [ROI](https://pyqtgraph.readthedocs.io/en/latest/region_of_interest.html) to see if what you're after can be done with one of the built in classes. You can add a line segment that can be manually positioned for example. There are a couple examples that cover most of them I think:

https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/ROIExamples.py
https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/ROItypes.py

**Comment by lyl1836** [comment]
The problem has been solved, thank you very much!
