### ISSUE TITLE
What is the command for exporting pictures from multiple plots under Graphicslayoutwidget?

### ISSUE THREAD

**Issue by lyl1836** [pyqtgraph/pyqtgraph#1674]
I add multiple plots under the Graphiclayoutwidget. I can export pictures manually. How to export through code?

![image](https://user-images.githubusercontent.com/48607893/112855213-3075cd00-90e1-11eb-8e97-d4fdc401a753.png)

**Comment by ixjlyons** [comment]
Answered in #1670
