### ISSUE TITLE
Rendering entire image

### ISSUE THREAD

**Issue by bsobhani** [pyqtgraph/pyqtgraph#1681]
If I run the following code,

```
from PIL import Image
import pyqtgraph as pg
import pyqtgraph.exporters
from PyQt5.QtWidgets import QApplication
import numpy as np
from scipy.ndimage import rotate


app = QApplication.instance()

image = Image.open("cameraman.png")

array = np.asarray(image)
im = pg.ImageView(view=pg.PlotItem())
im.show()
im.setImage(array)
im.getImageItem().rotate(30)
```

I get this image:

![rotated_image](https://user-images.githubusercontent.com/16730331/113241028-db21f300-927b-11eb-9175-0ed615a446e9.PNG)

Since I rotated the image by 30 degrees, the corners in the above image were cut off. What I am trying to get is a numpy array of the entire image, with the corners in tact, but still rotated. I essentially want a numpy array of the image that I would get if I pressed the "view all" button. I also only want the image and not the xy axes or histogram, etc. Is there a way to access this?

**Comment by pijyoi** [comment]
You could rotate the image using ```ndimage.rotate()```
```python
import numpy as np
from scipy import ndimage, misc
import matplotlib.pyplot as plt
img = misc.ascent().astype(np.uint8)
out = ndimage.rotate(img, 30, reshape=True)
plt.imshow(out, cmap='gray')
plt.axis('off')
plt.show()
```

**Comment by j9ac9k** [comment]
@bsobhani if you just want the numpy matrix with the image rotated; then [`ndimage.rotate()`](https://docs.scipy.org/doc/scipy-1.6.2/reference/generated/scipy.ndimage.rotate.html#scipy.ndimage.rotate) is probably what you want as @pijyoi pointed out.

Rotating the image item won't give you the full numpy matrix; it just changes the orientation of the angle of the view within the plotting area.
