### ISSUE TITLE
PyQt6 in Spyder

### ISSUE THREAD

**Issue by BlackbirdB51** [pyqtgraph/pyqtgraph#1682]
Trying to use PyQt6 and a pyqtgraph widget in Spyder IDE results in an error. Running the same file in a normal shell works fine. Spyder itself is a Qt5 application, I think, therefore ```'PyQt5' in sys.modules``` returns always True and pyqtgraph uses PyQt5 (see Qt.py, lines 32-47), while the rest of the application tries to use PyQt6.

Changing the research order (libOrder in Qt.py line 33) such that PyQt6 is in front of PyQt5 might alleviate this problem. For automatic import, the old order could be used.

### Short description
In Spyder scripts with PyQt6 and pyqtgraph widget cannot start.

### Code to reproduce
```python
from PyQt6 import QtWidgets
import pyqtgraph

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        centralWidget = QtWidgets.QWidget()
        self.setCentralWidget(centralWidget)
        image = pyqtgraph.ImageView(parent=centralWidget)
        self.show()

app = QtWidgets.QApplication([])
start = MainWindow()
app.exec()
```

### Expected behavior
An ImageView is shown.

### Real behavior
Error message (in Spyder only):
```
Traceback (most recent call last):

  File "C:\MeasurementSoftwarePython\Test\WidgetTest.py", line 27, in <module>
    start = MainWindow()

  File "C:\MeasurementSoftwarePython\Test\WidgetTest.py", line 20, in __init__
    image = pyqtgraph.ImageView(parent=centralWidget)

  File "C:\Program Files\Python39\lib\site-packages\pyqtgraph\imageview\ImageView.py", line 116, in __init__
    QtGui.QWidget.__init__(self, parent, *args)

TypeError: QWidget(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'QWidget'
```

### Tested environment(s)

 * PyQtGraph version: '0.12.0'
 * Qt Python binding: 'PyQt5 5.15.2 Qt 5.15.2'
 * Python version: '3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]'
 * NumPy version: '1.19.4'
 * Operating system:  Windows 10
 * Installation method: pip

### Additional context

In Spyder environment only.

**Comment by pijyoi** [comment]
You could try adding to the start of your script
```python
import os
os.environ["PYQTGRAPH_QT_LIB"] = "PyQt6"
```

**Comment by BlackbirdB51** [comment]
Thanks a lot. I totally overlooked that possibility.
It should be sufficient to run those two commands in the Spyder shell, because I use Spyder just for development. Normally I run the scripts alone, in which case it is fine.

**Comment by j9ac9k** [comment]
Ahh yeah, Spyder being a Qt application itself, it's going to have Qt installed, which can certainly conflict with different versions of Qt you're trying to have pyqtgraph use.  I don't think there is a way for PyQtGraph to be able to recognize which version the user wants to use, other than through environment variables, which is what @pijyoi suggested.

I'm going to close out the issue, I'm open to other suggestions regarding ways pyqtgraph could try and figure this out, so if you can think of something, feel free to follow up 👍🏻
