### ISSUE TITLE
FillBetweenItem has no way to change FillRule

### ISSUE THREAD

**Issue by billbo100** [pyqtgraph/pyqtgraph#1698]
### Short description
There is currently no way (at least that I have found) to change the fillrule for the painterpath in the FillBetweenItem. being able to set it to winding would be very useful for certain cases.

### Code to reproduce

```python
import pyqtgraph as pg
from PySide2.QtWidgets import QApplication

win = pg.plot()
win.setWindowTitle('pyqtgraph example: FillBetweenItem')
win.setXRange(0, 1.5)
win.setYRange(0, 1.5)

x1=[0,1,1,0,0]
y1=[0,0,1,1,0]
x2=[0.5,1.5,1.5,0.5,0.5]
y2=[0.5,0.5,1.5,1.5,0.5]
curve1 = win.plot(x=x1, y=y1, pen='k')
curve2 = win.plot(x=x2, y=y2, pen='k')
brushes = [0.5, (100, 100, 255), 0.5]
fill = pg.FillBetweenItem(curve1, curve2,brush=(100,100,255))
win.addItem(fill)

## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    QApplication.instance().exec_()
```

### Expected behavior
Fill in the overlap

### Real behavior
Hole in the middle.

### Tested environment(s)

 * PyQtGraph version: 0.12.1
 * Qt Python binding: PyQt5 5.15.4 Qt 5.15.2
 * Python version: 3.7.7
 * NumPy version: 1.20.2
 * Operating system: Windows 10
 * Installation method: PIP

**Comment by BousquetSophie** [comment]
Hello, can we fix this bug? As part of our degree course we have to contribute to an open-source project.

**Comment by BousquetSophie** [comment]
We were able to reproduce this bug on ubuntu 22.04 using python 3.10.12 and the development version of pyqtgraph.

We obtained the following error 
line 21, in <module>
    QApplication.instance().exec_()
AttributeError: 'NoneType' object has no attribute 'exec_' 
 
We had to use the PySide6 library instead of PySide2 to avoid the error.

**Comment by BousquetSophie** [comment]
For the moment, we've extracted the intersection points and used them to create a new polygon to fill the empty space.
The only problem is that when you create a polygon from above, there's a margin around it, which sometimes creates bugs.

**Comment by j9ac9k** [comment]
@billbo100 Hi, sorry for the late response, I have implemented a way to use WindingFill (locally on my machine) but it does not fill in that middle rectangle.  That said, I created a PR that has the ability to set the fill rule, see #3006

**Comment by j9ac9k** [comment]
I'm re-opening this issue as #3006 undoes the change in #2971.
