### ISSUE TITLE
PythonQt support

### ISSUE THREAD

**Issue by fbordignon** [pyqtgraph/pyqtgraph#1699]
Hi everyone, I see that pyqtgraph supports pyside and pyqt, which is great. I know that pyqtgraph uses the Qt.py to centralize qt imports, that is awesome as well. I am trying to add the support to PythonQt because I want to use pyqtgraph inside [3D Slicer](http://www.slicer.org), which uses pythonqt.

My questions are: Have anyone tried it? Do you have any idea of issues and/or problems that may arise? Is it possible?

Thank you

**Comment by j9ac9k** [comment]
There may be some confusion, pyqtgraph does use the [Qt.py library](https://pypi.org/project/Qt.py/) we have our abstraction layer in  a file named [Qt.py](https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/Qt.py) which should not interfere with Qt imports outside the library (or at least interfere in minimal of ways that are hopefully not noticeable).  The abstraction in the Qt.py file is intended for within the library, although some of our users do use it for their own projects, but use at your own risk.

I routinely use [QtPy](https://pypi.org/project/QtPy/) library for an abstraction layer for my larger Qt projects, which has no problems.  

Hopefully this addressed your question.

**Comment by ksunden** [comment]
https://mevislab.github.io/pythonqt/

As far as I can tell, pythonqt is _not_ at the same level as pyside/pyqt, it is for embedding python into majorly C++ programs (its not a python library itself, even).

As such, I don't know that there is anything we _can_ do here.

**Comment by j9ac9k** [comment]
oh, ... yeah, no clue if that would work, or what it would take to make it work.... @fbordignon I don't know of anyone that has used pythonqt with pyqtgraph, so I'm not sure we can be of assistance here.  If you do run into an issue, and you think making a change can be made to pyqtgraph to make it work, let us know.

I'm going to close out the issue here, as there is nothing we can do at this time.  @fbordignon please do follow up and let us know if you were able to integrate successfully.

**Comment by fbordignon** [comment]
I got a better understanding of pythonqt now. From what I gather they propose a bidirectional interaction between python and C++. Hence, in theory I can access the Qt of the C++ application via pythonqt to perform the tasks needed by pyqtgraph. A member of our team did a similar feat for matplotlib, but he is not available anymore. I will try it and report back.
I saw that I can do things like `from PythonQt import QtCore` from the python shell of the application, so it is looking promising.
Thank you for the prompt reply.

**Comment by j9ac9k** [comment]
ahh, issue here being, can you import Qt modules, but not from the typical python bindings; but from a different import altogether.... hmm...i'm not sure w/o some testing, and I'm not sure that's an environment we can easily replicate.

Maybe something like

```python
import sys
import PythonQt

sys.module["PySide2"] = sys.modules["PythonQt"]

import pyqtgraph as pg
```

**Comment by fbordignon** [comment]
Yeah it is not so direct. I am not entirely sure of what is happening, but I think that some properties of qt classes are shadowing methods when calling from python.
Example:
QGraphicsWidget has the layout property and the layout() method to access it. From the python side, only the property is visible. I cannot call the method.
A lot of functions are like that, for instance geometry, size and others from numerous classes. And I cannot overwrite the member because it is accessing the C++ object directly, so it is not possible to just overwrite QGraphicsWidget.geometry. I may be giving up soon. It is too much work and I cannot se a way to keep it compatible with pyside and pyqt.

**Comment by fbordignon** [comment]
Well I guess I could create functions like:

```
def get_size(self):
  return self.size()
```

use them on pyqtgraph objects and replace it at Qt.py file to return self.size, like scale and rotate are replaced for PYQT5 and PYSIDE2. But then some functions are missing from pythonqt such as QDataStream operators and QMetaObject slot connectSlotsByName. I am raising this issue on pythonqt to see why they are missing and if it is possible to add them and other similar functions/operators.

I've got to this point on the arrow example, I still got some hope left =)

![image](https://user-images.githubusercontent.com/4790289/114038493-4c533e80-9858-11eb-9e3d-5b95f29bdafc.png)

**Comment by j9ac9k** [comment]
For context, this is the issue https://github.com/MeVisLab/pythonqt/issues/42

If the maintainers there are engaging, and you get some good guidance on using pyqtgraph within pythonqt, I would like to add that information to the documentation.
