### ISSUE TITLE
modification of builtins in python2_3.py breaks module mpmath

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#170]
In python2_3.py, builtins namespace is modified in order to achieve Python 2/3 compatibility. In particular we have
```python
builtins.xrange = range
```
However, module mpmath imported by sympy makes use of non-existence of name "xrange" to determine if it's running on Python3. See
https://github.com/fredrik-johansson/mpmath/blob/master/mpmath/libmp/backend.py

**Comment by kalvdans** [comment]
I would say mpmath is doing it wrong, it should check sys.version instead of checking for xrange. It should only check for xrange when it intends to use xrange.

**Comment by campagnola** [comment]
I would say we're both doing it wrong. I will work on removing all modifications to builtins.

**Comment by campagnola** [comment]
This should be fixed in https://github.com/pyqtgraph/pyqtgraph/commit/96292d39f3abd51f404820013d939473d031a436.

**Comment by kalvdans** [comment]
Nice!
