### ISSUE TITLE
Is it possible to plot a correlation matrix with pyqtgraph?

### ISSUE THREAD

**Issue by Bio-Otto** [pyqtgraph/pyqtgraph#1705]
I am trying to plot a correlation matrix.  For this purpose, I want to use the infrastructure of pyqtgraph. But I could not see any examples. Can you provide guidance on this issue? Thanks.

**Comment by j9ac9k** [comment]
@Bio-Otto 

We don't have any convenience methods to plot those from the get-go.  

If you can generate your own correlation matrix as a numpy object, you can certainly plot one using an [ImageItem](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/imageitem.html)

If you can provide some sample data here, I can try and do a simple example.

**Comment by Bio-Otto** [comment]
I put a sample script below and also the output figure. 
``` python
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

data = {'A': [45,37,42,35,39],
        'B': [38,31,26,28,33],
        'C': [10,15,17,21,12]
        }

df = pd.DataFrame(data,columns=['A','B','C'])

corrMatrix = df.corr()
sn.heatmap(corrMatrix, annot=True)
plt.show()
```
![resim](https://user-images.githubusercontent.com/57147948/114318584-54d89d00-9b16-11eb-85b4-5f6432860174.png)

**Comment by j9ac9k** [comment]
So, first off, I'll _freely_ admit that our API/functionality here isn't as clean as seaborn, and I think this would be a great thing to add; and I'll gladly work w/ anyone that wants to submit a PR extending similar functionality here)

Here is the code I quickly wrote up:

```python
import pyqtgraph as pg
import numpy as np
# import pandas as pd

pg.setConfigOptions(imageAxisOrder="row-major")

app = pg.mkQApp()
data = {
    'A': [45,37,42,35,39],
    'B': [38,31,26,28,33],
    'C': [10,15,17,21,12]
}

columns = ["A", "B", "C"]

# df = pd.DataFrame(data, columns=columns)
# corrMatrix = df.corr().to_numpy()
corrMatrix = np.array([
    [ 1.        ,  0.5184571 , -0.70188642],
    [ 0.5184571 ,  1.        , -0.86094096],
    [-0.70188642, -0.86094096,  1.        ]
])

colorMap = pg.colormap.getFromMatplotlib("magma")
lut = colorMap.getLookupTable()

correlogram = pg.ViewBox()
imageItem = pg.ImageItem(image=np.flipud(corrMatrix), level=(-1, 1), lut=lut)
correlogram.addItem(imageItem)
plotItem = pg.PlotItem(viewBox=correlogram)
win = pg.PlotWidget(plotItem=plotItem)
win.show()

app.exec_()
```

Which generates this image:

![image](https://user-images.githubusercontent.com/646398/114428709-5e432300-9b71-11eb-9189-5808e6209211.png)

If you want to see the colorbar on the side, there is some a newly added (but we forgot to add it to the documentation, a wrong we will be righting soon) ColorBarItem.  You can see some examples there in `examples/ColorBarItem.py`  (as it is not documented yet, I can assist with this if you'd like)

I'm not sure the best way to modify the axes to show A-B-C like seaborn, or to write the numbers on top of the colors in such a contrasting fashion.

I hope this helps.  

Loosely related:

The other thing that is awkward here, and I have run this in my own projects, is how do you create a PlotWidget with just an ImageItem, but assuming you don't want all the functionality/features of ImageView.  

What I first do is create a ViewBox

```python
correlogram = pg.ViewBox()
```

Then I create my ImageItem

```python
imageItem = pg.ImageItem(image=np.flipud(corrMatrix), level=(-1, 1), lut=lut)
```

Then I add the ImageItem to my already created viewbox:

```python
correlogram.addItem(imageItem)
```

Then I create my PlotItem, telling it to use my already created ViewBox

```python
plotItem = pg.PlotItem(viewBox=correlogram)
```

and lastly, I create a `PlotWidget`, with the already created PlotItem.

```
win = pg.PlotWidget(plotItem=plotItem)
```

This is a pattern I've found myself using a bit too often, and it's not obvious;

**Comment by Bio-Otto** [comment]
Thank you so much for your time. This is very clear indeed and I can adapt it for myself. I am grateful for your help. @j9ac9k

**Comment by j9ac9k** [comment]
Glad this is helpful.  Feel free to post back if you're running into other issues.  If someone else knows how to modify the AxisItem to show the labels instead of the numbers, hopefully they'll post here.

**Comment by NilsNemitz** [comment]
The example raises an interesting question:
Our axes generally indicate the *edge* of a pixel. 
For applications like this matrix plot, it would be more useful to instead enumerate the pixels / matrix elements like in the seaborn plot above. This would also make the ColorBarItem indicator more accurate...

It seems that Matplotlib does indeed put the tick marks in the middle of a pixel:
https://matplotlib.org/stable/gallery/images_contours_and_fields/image_demo.html#sphx-glr-gallery-images-contours-and-fields-image-demo-py  --> section "Interpolating images"

@pijyoi , since you seem to be working with the images a lot, is there a preferred implementation?
Does it make sense to add the option to display an image of (w/h) to display over coordinates [ -0.5 to (w-0.5) ]  and  [ -0.5 to (h-0.5) ] instead of [0 to w] and [0 to h]?

**Comment by NilsNemitz** [comment]
Here is how I would set that up.
``` python
import numpy as np
import pyqtgraph as pg
# import pandas as pd

pg.setConfigOptions(imageAxisOrder="row-major")

app = pg.mkQApp()
data = {
    'A': [45,37,42,35,39],
    'B': [38,31,26,28,33],
    'C': [10,15,17,21,12]
}
columns = ["A", "B", "C"]

# df = pd.DataFrame(data, columns=columns)
# corrMatrix = df.corr().to_numpy()
corrMatrix = np.array([
    [ 1.        ,  0.5184571 , -0.70188642],
    [ 0.5184571 ,  1.        , -0.86094096],
    [-0.70188642, -0.86094096,  1.        ]
])

correlogram = pg.ViewBox()
correlogram.invertY(True)
imageItem = pg.ImageItem(image=corrMatrix)
correlogram.addItem(imageItem)
plotItem = pg.PlotItem(viewBox=correlogram)

ticks = [ (idx+0.5, label) for idx, label in enumerate( columns ) ]
for side in ['left', 'top']:
    ax = plotItem.getAxis(side)
    ax.show()
    ax.setZValue(0.1)
    ax.setTicks( (ticks, []) )
    if side == 'left': ax.setWidth(20)
    if side == 'top' : ax.setHeight(20)
for side in ['right', 'bottom']:
    ax = plotItem.getAxis(side)
    ax.show()
    ax.setZValue(0.1)
    ax.setTicks( (ticks, []) )
    ax.setStyle(showValues=False)
    if side == 'bottom': ax.setHeight(10)

plotItem.setXRange(0, corrMatrix.shape[0], padding=0 )
plotItem.setYRange(0, corrMatrix.shape[1], padding=0 )

colorMap = pg.colormap.get("cet-d1")
bar = pg.ColorBarItem( values=(-1,1), cmap=colorMap)
bar.setImageItem(imageItem, insert_in=plotItem)

win = pg.PlotWidget(plotItem=plotItem)
win.show()

app.exec_()
```
Output:
![matrix plot](https://user-images.githubusercontent.com/19742018/115111105-9e633500-9fb9-11eb-9538-731d5f1e1eb4.png)

**Comment by pijyoi** [comment]
I don't think there's a one-size fits all solution to setting the image coordinates. 
For instance, one application may plot many ImageItem(s), each at different locations, like in https://github.com/pyqtgraph/pyqtgraph/issues/1371#issuecomment-770133079
I also often need to offset the coordinates to [-0.5, w - 0.5 ] or some variant where the zero coordinate is somewhere other than at the left edge.
So I would say just leave the API as it is, and let the user call setRect() to set their required coordinates.
