### ISSUE TITLE
Color based on value

### ISSUE THREAD

**Issue by DrPaprikaa** [pyqtgraph/pyqtgraph#1712]
Hi,
I would like to draw in real time a line plot (think reading the data from a sensor), with the points colored based on their values.
Two cases I can think of :
- The point is red or green, if < or > 0
- More broadly, a color scale : all my points are in [-1, 1], create a color map of n colors (n bins) and display the colored points.

How could I do that ?
Thanks

**Comment by j9ac9k** [comment]
Before your call to `PlotDataItem.setData(newData)` you need to figure out the color you want to use.

```python
newColor = yourFunctionMappingDataToColor(newData)
PlotDataItem.setData(newData, pen=newColor)
```

**Comment by j9ac9k** [comment]
Just realized you're trying to color the points, not the lines... that's a bit different.  

@lidstrom83 may know of an easier way of doing this, but the way I would do it is first, create a lookup table

```pyqtgraph
nPts = 512
colormap = pg.colormap.get(colormap_name)
valueRange = np.linspace(-1, 1, num=nPts)
colors = colormap.getLookupTable(-1.0, 1.0, nPts=nPts)
brushes = colors[np.searchsorted(valueRange, y)]
 
plotItem.setData(x, y, symbolBrush=brushes)
```

```

**Comment by DrPaprikaa** [comment]
Thanks ! I can't seem to get it working tho, what shall `colormap_name` be ?
I also get the error `module 'pyqtgraph.colormap' has no attribute 'get'`

**Comment by j9ac9k** [comment]
oh, if you're not looking for a continuous colormap, but want to highlight a range that's a bit different.

> Thanks ! I can't seem to get it working tho, what shall `colormap_name` be ?

This would be whatever colormap you wanted, you can see the available ones by running the Color Map example.
![image](https://user-images.githubusercontent.com/646398/114886880-cc2f5a80-9dbc-11eb-9ead-e671dea96d86.png)


I also get the error module 'pyqtgraph.colormap' has no attribute 'get'.

That's odd, here is the method, what version of pyqtgraph are you using?  The colormap various `get` methods are fairly new, but are in the last released version.

https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/colormap.py#L48

> To be clear, I would like to color one point at a time, the last point that I received, depending on it's value.

Oh, if you're not looking for as continuous colormap but something more discrete, I think you can do that by the following (I haven't actually tested)

```python
nPts = 5
valueRange = np.linspace(-1, 1, endpoint=False, num=4)
colors = np.ndarray([[255, 0, 0],  [128, 0, 128], [255, 255, 0], [0, 255, 0]])
brushes = colors[np.searchsorted(valueRange, y)]
plotDataItem.setData(x, y, symbolBrush=brushes)
```

**Comment by DrPaprikaa** [comment]
Thanks I got it working using your last example, exactly what I wanted ! Just needed to change `np.ndarray()` by `np.array()`.

I'm closing this issue, cheers !
