### ISSUE TITLE
ImageItem seems to reset to previous view

### ISSUE THREAD

**Issue by nico218a** [pyqtgraph/pyqtgraph#1713]
Dear all,

I am writing an application that uses an ImageItem to show paticles on a surface. People can click on the image and the program determines the nearest particle and highlights it in the image and in a table.

When I use pyqtgraph 0.12.1 then something strange happens (0.11.1 works fine). If I click a particle, it is highlighted and shown in the table. So far so good. When I use my mouse and hover over some widget that has a tooltip, the tooltip appears, but also the view of the ImageItem seems to jump back to previous state. The previous view will be shown (including zoom) and even the previous particle will be selected in the table. I think the last action can only happen if the signal of the previous mouse click is send again. I have the feeling some wrong buffer is used for the redraw of the ImageItem.

I am using Python 3.9, but I also tried 3.8.

Does anyone have a clue?

Before I used 0.10.0. This worked very fast. Version 0.11.1 seems to be slow regarding reaction to mouse clicks on the image. That is the reason I wanted to try 0.12.1. Pyqtgraph 0.10.0 does not work with PySide2.

Any suggestions are welcome.

Best regards,
Nico

**Comment by j9ac9k** [comment]
Hi Nico, can you provide some sample code, or detail the steps using one of the examples to replicate this issue?  This would make it a lot easier for us to debug and look through our version control history to track down the change that caused the differences.

**Comment by nico218a** [comment]
Dear j9ac9k,
Thanks for your reply.
I just made a simple script that has only the ImageItem and a button for drawing something, but there the strange effect is not present. So it is probably caused by some combination or other use in the real program.
I will try to find out what is different and come back later.

**Comment by j9ac9k** [comment]
Thanks for reporting back @nico218a 

One thing that may be of help in your debugging, even within your application is to clone the pyqtgraph repository; install pyqtgraph using a pip editable install, and then use `git bisect` to identify which commit things go from ok to not ok.

**Comment by nico218a** [comment]
Hi @j9ac9k,
Thanks for the suggestion. It sounds like a good plan. I will let you know what comes out of this test. It can take some time before I have the opportunity to test.

**Comment by nico218a** [comment]
I did use gitlab bisect, knowing that 0.11.1 worked fine. I ended up with the first bad commit to be 8aec44d088112ff63010886f994ba8c2550b5d4c, with changes in Console.py.
Does this make sense?
Only one line was changed and one was added.

8aec44d088112ff63010886f994ba8c2550b5d4c is the first bad commit
commit 8aec44d088112ff63010886f994ba8c2550b5d4c
Author: Luke Campagnola <luke.campagnola@gmail.com>
Date:   Tue Sep 6 17:54:54 2016 -0700

    Use console's namespace as both local and global context for exec/eval.
    This allows functions defined in the console to access global variables.
    Also expose the console itself via special __console__ variable.

 pyqtgraph/console/Console.py | 3 ++-

**Comment by nico218a** [comment]
Hi @j9ac9k,

Using the git bisect method I found this information:

`9145d7f24dfbeb7966f247eaeda8d44d5022af89 is the first bad commit
commit 9145d7f24dfbeb7966f247eaeda8d44d5022af89
Author: KIU Shueng Chuan <nixchuan@gmail.com>
Date:   Thu Jan 14 14:44:26 2021 +0800

    switch to usage of QOpenGLWidget

    this drops support for Qt4

 pyqtgraph/opengl/GLViewWidget.py    | 17 ++++-------------
 pyqtgraph/widgets/RawImageWidget.py |  6 +++---
 2 files changed, 7 insertions(+), 16 deletions(-)`

**Comment by j9ac9k** [comment]
In your application were you using QGLWidget?

**Comment by nico218a** [comment]
Not directly. I also draw a 3D surface plot, like this:


```
import pyqtgraph.opengl as gl


        self.image3d = gl.GLViewWidget()
        self.image3d.setWindowTitle("3D Particle view")
        self.image3d.setCameraPosition(distance=100, elevation=50, azimuth=0)
        self.image3d.setMinimumWidth(100)

        g = gl.GLGridItem()
        g.scale(6, 6, 1)
        g.setDepthValue(10)  
        self.image3d.addItem(g)

        :
		:
		
        self.particle_3d_element = gl.GLSurfacePlotItem(
            x=x, y=y, z=z, shader="shaded", colors=colors
        )
        # self.particle3delement.translate(-10,-10,0)
        self.particle_z_data = z
        self.image3d.addItem(self.particle_3d_element)

```

**Comment by j9ac9k** [comment]
Hi Nico,

So here is the commit in question:

https://github.com/pyqtgraph/pyqtgraph/commit/9145d7f24dfbeb7966f247eaeda8d44d5022af89

What the change shows is the removal of the already deprecated opengl object  (`QtOpenGL.QGLWidget`) and replaced them with what should be their equivalent, currently supported widget (`QtWidgets.QOpenGLWidget`). 

It's not surprising that there would be some different behavior under the hood that's different; but reverting that is a non-starter due to its deprecated status.

I think the better question would be, can you generate a minimum working example that demonstrates this jumping you're seeing, and we can see if we can try and tackle that more directly.

**Comment by pijyoi** [comment]
@nico218a , you seem to be using together non-OpenGL elements (ImageItem) and OpenGL elements (GLViewWidget). I don't know if pyqtgraph was intended to be used that way. But there certainly seems to be many caveats listed in https://doc.qt.io/qt-5/qopenglwidget.html#limitations

**Comment by nico218a** [comment]
Hi @pijyoi, thanks for the information and the link. Now I understand why the whole window is acting differently (sometimes disappears for a while etc.), because it becomes of a different type if there is a qopenglwidget on it.
I will investigate it a bit more. Can take a while.

**Comment by j9ac9k** [comment]
I'm going to close out this issue, but I suppose we should consider adding that limitations link somewhere in our documentation.
