### ISSUE TITLE
QOpenGLWidget: Failed to create context

### ISSUE THREAD

**Issue by ptoews** [pyqtgraph/pyqtgraph#1719]
I'm using `GLViewWidget` to plot 3D data embedded in a Qt application. Today I noticed that the widget stopped working, the widget stays black and isn't redrawn on window resize, but no errors are shown. So I upgraded from 0.11.1 to 0.12.1 where I encountered the following errors:

```
QOpenGLWidget: Failed to create context
QOpenGLWidget: Failed to create context
QOpenGLWidget: Failed to create context
QOpenGLWidget: Failed to create context
QOpenGLWidget: Failed to create context
qt.qpa.backingstore: composeAndFlush: QOpenGLContext creation failed
qt.qpa.backingstore: composeAndFlush: makeCurrent() failed
qt.qpa.backingstore: composeAndFlush: makeCurrent() failed
qt.qpa.backingstore: composeAndFlush: makeCurrent() failed
...
```

I'm not sure whether the cause of the issues before and after is the same, so any help is appreciated.

### Tested environment(s)

 * PyQtGraph version: Same issue with 0.12.0 and 0.12.1
 * Qt Python binding: PyQt5 5.15.4 Qt 5.15.2 
 * Python version: 3.8
 * NumPy version: 1.20.2 
 * Operating system: Ubuntu 20.04
 * Installation method: pip 
 * I'm using the proprietary nvidia drivers version 460

More versions:

```
PyOpenGL                          3.1.5
PyQt5                             5.15.4
PyQt5-Qt5                         5.15.2
PyQt5-sip                         12.8.1
PyQt5-stubs                       5.15.2.0
pyqtgraph                         0.12.1
python-qt-binding                 0.4.3
qt-dotgraph                       0.4.2
qt-gui                            0.4.2
qt-gui-cpp                        0.4.2
qt-gui-py-common                  0.4.2
qtconsole                         5.0.3
QtPy                              1.9.0
```

**Comment by j9ac9k** [comment]
@ptoews can you provide a minimum reproducible example?  During this change we moved away from QGLWidgets to QOpenGLWidgets due to the former being deprecated by Qt.

**Comment by ptoews** [comment]
After restarting I can't reproduce the issue with neither of the versions. Will reopen if it happens again.
