### ISSUE TITLE
LayoutWidget.addLabel and addLayout are broken

### ISSUE THREAD

**Issue by sbourdeauducq** [pyqtgraph/pyqtgraph#172]
https://github.com/pyqtgraph/pyqtgraph/commit/f99ed791bc4ae39c21a0c6d12f6595641114c258#commitcomment-11330678
https://github.com/pyqtgraph/pyqtgraph/commit/f99ed791bc4ae39c21a0c6d12f6595641114c258#commitcomment-11330693

**Comment by j9ac9k** [comment]
Fixed with merging #473
