### ISSUE TITLE
HistogramLUTWidget kargs bug?

### ISSUE THREAD

**Issue by liubin1977** [pyqtgraph/pyqtgraph#175]
# lut_widget = HistogramLUTWidget(background='w')

 File "/usr/local/lib/python3.4/dist-packages/pyqtgraph-0.9.8-py3.4.egg/pyqtgraph/widgets/HistogramLUTWidget.py", line 18, in **init**
    self.item = HistogramLUTItem(_args, *_kargs)
# TypeError: **init**() got an unexpected keyword argument 'background'

I can fix it by:

class HistogramLUTWidget(pg.GraphicsView):

```
def __init__(self, parent=None,  *args, **kargs):
    # background = kargs.get('background', 'default')
    background = kargs.pop('background', 'default')
```

...

**Comment by j9ac9k** [comment]
Regarding the code change directly, the placement between the `background='default'` and `*args` should probably be switches (so `*args` and `**kwargs` are at end together).

That said is this the right fix, as opposed to the suggestion of the issue, where we just pop the background item from the kwargs dict?

I haven't used these widgets before, but would it be inappropriate to pass the background color to `HistogramLUTItem`?

Also, we should add a test case for this as well, I'm not seeing any kind of existing test for these widgets, maybe just to initialize one without an error (and with a background passed to it).
