### ISSUE TITLE
"LESS THAN" ("<") - symbol not displayed in plot title

### ISSUE THREAD

**Issue by paulmueller** [pyqtgraph/pyqtgraph#1750]
### Short description
The "<" symbol (and all characters following it) is not rendered in the plot title.

### Code to reproduce

```python
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import pyqtgraph as pg

app = pg.mkQApp("Plot Auto Range Example")

win = pg.GraphicsLayoutWidget(show=True)

d = np.random.normal(size=100)
p1 = win.addPlot(title="Hello world, I <3 pyqtgraph!", y=d)


if __name__ == '__main__':
    pg.mkQApp().exec_()

```

### Expected behavior
The plot should have the title: `Hello world, I <3 pyqtgraph!`

### Real behavior
The title is broken at the "<" sign:
![image](https://user-images.githubusercontent.com/2853022/116621533-95704d00-a943-11eb-8b64-3aac03244a20.png)
There is no error message.
### Tested environment(s)

 * PyQtGraph version: 0.12.1
 * Qt Python binding: 'PyQt5 5.15.4 Qt 5.15.2'
 * Python version: 3.8.5
 * NumPy version: 1.20.2
 * Operating system: Ubuntu 20.04.2 LTS
 * Installation method: pip

**Comment by pijyoi** [comment]
You could change your title string to ```"Hello world, I &lt;3 pyqtgraph!"```

**Comment by paulmueller** [comment]
Aha, I see. So pyqtgraph tries to parse html. In that case my workaround would be to replace `<` with `&lt;` if `<` is in the title string but `>` is not. Is there any chance this could be fixed in pyqtgraph?

**Comment by pijyoi** [comment]
If you need your text to be interpreted literally, you could wrap it with ```html.escape()```
```python
In [6]: html.escape("Hello world, I <3 pyqtgraph!")
Out[6]: 'Hello world, I &lt;3 pyqtgraph!'
```

**Comment by paulmueller** [comment]
Thank you, this is a very reasonable solution!
