### ISSUE TITLE
GraphicsLayoutWidget Scrollbar

### ISSUE THREAD

**Issue by fbordignon** [pyqtgraph/pyqtgraph#1751]
Hi everyone, I don't know if it is a bug, a feature request or I am using it wrong.
I want to add a scrollbar to the bottom of many plots on a GraphicsLayoutWidget.
Here it is a sample code adapted from arrow:
```
import numpy as np
from pyqtgraph.Qt import QtGui, QtCore
import pyqtgraph as pg


app = pg.mkQApp("Arrow Example")

w = QtGui.QMainWindow()
cw = pg.GraphicsLayoutWidget()
w.show()
w.resize(400,600)
w.setCentralWidget(cw)
cw.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)

for i in range(50):
    p = cw.addPlot()
    p.setRange(QtCore.QRectF(-20, -10, 60, 20))


if __name__ == '__main__':
    pg.mkQApp().exec_()
```

output:
![image](https://user-images.githubusercontent.com/4790289/116634029-68b33a00-a931-11eb-825b-d6e4695d6895.png)

My app adds and removes plots that are narrow and tall dynamically. I figure a scrollbar at the bottom should be good to handle many plots being added, but I can't make it work. Adding the GraphicsLayoutWidget to a scroll area does not make a difference.
Another issue is that if I add many plots and remove them afterwards, it seems that the layout width grows and never comes back to its original size.
Thanks

**Comment by NilsNemitz** [comment]
Dear @fbordignon ,

I don't think that the `GraphicsLayoutWidget` has a concept of scrolling the region, but you *should* be able to make it work by sticking that same `GraphicsLayoutWidget` in a QScrollArea.

Here is what seems to work for me:
```python
from pyqtgraph.Qt import QtGui, QtCore
import pyqtgraph as pg

app = pg.mkQApp("Arrow Example")

w = QtGui.QMainWindow()
w.show()
w.resize(400,600)

cw = QtGui.QScrollArea()

glw = pg.GraphicsLayoutWidget()
cw.setWidget(glw)
w.setCentralWidget(cw)

for i in range(50):
    p = glw.addPlot()
    p.setRange(QtCore.QRectF(-20, -10, 60, 20))

if __name__ == '__main__':
    pg.mkQApp().exec_()
```
![graph_with_scrollbars](https://user-images.githubusercontent.com/19742018/118396132-fe1c3100-b688-11eb-8595-ae4b80d0fd15.png)

I guess the layout could use some hints for how large the various parts should be... After all the area that QScrollArea looks into is basically infinite. But it does scroll, and the mouse interactions with the plots seems to work, too.

If you've run into a specific problem with the QScrollArea, please let us know!

**Comment by fbordignon** [comment]
@NilsNemitz, thank you very much for your reply.
The example seems to work, but the scroll bars are not scrolling the plots but the entire graphics layout widget. Please take a look to the extreme right of the plot, there are plots not showing:

![image](https://user-images.githubusercontent.com/4790289/119512946-29b6af80-bd4a-11eb-821d-ac2ac193851c.png)

Do I need to grow the glw to acomodate the plots?

**Comment by NilsNemitz** [comment]
Dear @fbordignon ,
Yes, I think the widget could use some help in figuring out how large you want everything to be.

Ideally, each PlotItem would request a certain minimum width, the GraphicsLayoutWidget would add all of these together, and then request that size for the scrollable area of the QScrollArea. That's how I believe this is supposed to work in Qt... The inner widget thinks it draws on a near-infinite surface, and the QScrollArea picks what part the user gets to see.

Obviously, that doesn't work quite as intended, and the GraphicsLayout somehow fails to request enough space for 50 minimum width plots. But even if it did, you would still end up with minimum width plots (see image), which is probably not what you want. So I would recommend manually controlling the size of the elements. We will keep our eyes open for issues with the size hints that are supposed to control this.

In the mean time, here is what seems to work on my system. Manually setting the spacing and margins on the layout makes it a little easier to predict how many pixels are needed. And adding titles makes it a little easier to count fifty identical looking plots:
``` python
cw = QtGui.QScrollArea()

glw = pg.GraphicsLayoutWidget()
glw.ci.setContentsMargins(5,0,5,0)
glw.ci.setSpacing(0)
cw.setWidget(glw)
w.setCentralWidget(cw)

width = 10 # left and right margin
for i in range(50):
    p = glw.addPlot()
    p.setTitle(f'#{i}')
    p.setFixedWidth(140)
    width += 140
    p.getAxis('left').setWidth(35)
    
    p.setRange(QtCore.QRectF(-20, -10, 60, 20))
glw.setFixedWidth(width)
```

**Comment by fbordignon** [comment]
@NilsNemitz, awesome. Thanks for the tips. It ended up being more related to my poor knowledge of Qt than anything else.
At least if someone bumps into this, here we have a good way of doing it. Thank you again!

**Comment by j9ac9k** [comment]
Qt window sizing is something I _very_ frequently mess up on (not that I consider myself a pro).  Unfortunately it's a par for the course sort of thing.

**Comment by fbordignon** [comment]
Meddling a bit more with this and this hack seems to work in this case of a fixed plot width. I've registered to update the glw width based on the contents of the central widget. Maybe it helps someone.

```python
from pyqtgraph.Qt import QtGui, QtCore, QtWidgets
import pyqtgraph as pg

app = pg.mkQApp("Arrow Example")

w = QtGui.QMainWindow()
w.show()
w.resize(400,600)
wid = QtWidgets.QWidget()
cw = QtGui.QScrollArea()

layout = QtWidgets.QVBoxLayout()
wid.setLayout(layout)
glw = pg.GraphicsLayoutWidget()

cw.setWidget(glw)
layout.addWidget(cw)
w.setCentralWidget(wid)

def addplot():
    p = glw.addPlot()
    p.setFixedWidth(140)
    p.setRange(QtCore.QRectF(-20, -10, 60, 20))
    
def removeplot():
    if len(list(glw.ci.items)) > 0:
        glw.removeItem(list(glw.ci.items)[0])

def updatewellplotwidth():
    glw.setFixedWidth(glw.ci.contentsRect().width())

glw.ci.geometryChanged.connect(updatewellplotwidth)

btn = QtWidgets.QPushButton("Add plot")
btn.clicked.connect(addplot)
layout.addWidget(btn)

btn_remove = QtWidgets.QPushButton("Remove plot")
btn_remove.clicked.connect(removeplot)
layout.addWidget(btn_remove)


if __name__ == '__main__':
    pg.mkQApp().exec_()
```
