### ISSUE TITLE
Implement cross-hair in custom pyqtgraph plot widget like in the pyqtgraph stock example

### ISSUE THREAD

**Issue by Faiz87372** [pyqtgraph/pyqtgraph#1755]
i want to done this task please help me Thannks.

https://stackoverflow.com/questions/67343848/implement-cross-hair-in-custom-pyqtgraph-plot-widget-like-in-the-pyqtgraph-stock

**Comment by j9ac9k** [comment]
Hi @Faiz87372 

So you have one major issue, you're using Qt4, which pyqtgraph no longer supports.  

May I suggest you try and remove content from your application as it stands right now, and do the minimal code attempting to get the crosshairs functional?  I did not see any reference to InfiniteLine objects in your code, and those are the lines the cross-hairs are drawn with.

**Comment by j9ac9k** [comment]
Hi @Faiz87372 

I'm going to close out the issue since the question is fairly broad and I don't want to use the issue tracker for code-review.  If you can narrow down your question some, feel free to open another issue 👍🏻
