### ISSUE TITLE
Documentation typo in InfiniteLine (sigclicked vs. sigClicked)

### ISSUE THREAD

**Issue by jbattat** [pyqtgraph/pyqtgraph#1758]
In the "signals" section of the current documentation for InfiniteLine the name of the signal is written with a lower-case "c" instead of a capital "C":
[https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/infiniteline.html](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/infiniteline.html)

**Comment by alimustafashah** [comment]
Can you assign this task to me?

**Comment by j9ac9k** [comment]
> Can you assign this task to me?

Done 😀
