### ISSUE TITLE
ImageView(levelMode='rgba') throws exception

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#1769]
### Short description

Instantiating ImageView widget as ImageView(levelMode='rgba') causes an exception in HistogramLUTItem.
Providing an ImageItem upon instantation doesn't help.

Changing the levelMode to rgba after instantiation does work as shown in the "workaround" codepath.

### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np

data = np.random.randint(256, size=(256,256,3))

app = pg.mkQApp()

imgitem = pg.ImageItem(data)
if 1:
    # fails
    imv = pg.ImageView(imageItem=imgitem, levelMode='rgba')
else:
    # workaround
    imv = pg.ImageView(imageItem=imgitem)
    imv.getHistogramWidget().item.setLevelMode('rgba')
imv.show()

app.exec_()
```

### Expected behavior

Program starts with no exception thrown

### Real behavior

```
Traceback (most recent call last):
  File "d:\github\pyqtgraph\pyqtgraph\imageview\ImageView.py", line 130, in __init__
    self.ui.histogram.setLevelMode(levelMode)
  File "d:\github\pyqtgraph\pyqtgraph\graphicsItems\HistogramLUTItem.py", line 309, in setLevelMode
    self._showRegions()
  File "d:\github\pyqtgraph\pyqtgraph\graphicsItems\HistogramLUTItem.py", line 337, in _showRegions
    xdif = 1.0 / nch
UnboundLocalError: local variable 'nch' referenced before assignment
```

### Tested environment(s)

 * PyQtGraph version: master 
 * Qt Python binding: PySide6 6.0.4 Qt 6.0.4
 * Python version: 3.8.9
 * NumPy version: 1.20.2 
 * Operating system: Windows 10
 * Installation method: pip install -e .

**Comment by magnium** [comment]
Not only one has to place the call to self.ui.histogram.setLevelMode after self.ui.histogram.setImageItem, but also the variable nch should always be initialized in HistogramLUTItem._showRegions. The variable imax is set, but not used in the original code. Instead, nch can be initialized there.

After applying the fix this code works in both cases:

```
import pyqtgraph as pg
import numpy as np

data = np.random.randint(256, size=(256,256,3))

app = pg.mkQApp()

imgitem = pg.ImageItem(data)
if 1:
    # works
    imv = pg.ImageView(imageItem=imgitem, levelMode='rgba')
else:
    # works
    imv = pg.ImageView()
    imv.getHistogramWidget().item.setLevelMode('rgba')
    imv.setImage(data)
imv.show()

app.exec_()
```

However the result is not exactly the same: clicking on the ROI button in the first case shows an empty plot and in the second case the three curves for RGB channels.
