### ISSUE TITLE
GLVolumeItem example rendered image changed

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#1775]
### Short description

c4a1cf11a166201f3da1b99705d7cb8acea0d602 from PR #1724 changed significantly the rendered output of the hydrogen electron probability density function in GLVolumeItem.py

### Code to reproduce

examples/GLVolumeItem.py

### Expected behavior

![old_good](https://user-images.githubusercontent.com/2657027/118205751-a9639500-b493-11eb-8666-bcfb0b625ebf.png)

### Real behavior

![new_bad](https://user-images.githubusercontent.com/2657027/118205766-b2546680-b493-11eb-88e2-8f61083eb5ce.png)

### Tested environment(s)

 * PyQtGraph version:  master
 * Qt Python binding: PySide6 6.1.0 
 * Python version: 3.8.10
 * NumPy version: 1.20.3 
 * Operating system: Windows 10
 * Installation method: pip install -e .

**Comment by NilsNemitz** [comment]
Apparently, the earlier example code deliberately accepts 
"RuntimeWarning: divide by zero encountered in log"
to generate the desired plotting data. The epsilon offset in #1724 avoids this, but seems to generate unwanted data where there were probably NaN values before.

Editing the lines in the example (somewhere around L42) to read
  `positive = np.log(fn.clip_array(data, 0, data.max())**2)`
  `negative = np.log(fn.clip_array(-data, 0, -data.min())**2)`
seems to bring back the previous image.

@pijyoi, if you want to turn that into a PR, go ahead. I probably won't get around to it for a few days, sorry.

**Comment by pijyoi** [comment]
>but seems to generate unwanted data where there were probably NaN values before.

There are no NaN values, only -Infs.
There is at least a reliance on the side-effect that casting non-finite values to uint8 results in 0.

**Comment by pijyoi** [comment]
This would suppress the warning locally:
```python
with np.errstate(divide = 'ignore'):
    positive = np.log(fn.clip_array(data, 0, data.max())**2)
    negative = np.log(fn.clip_array(-data, 0, -data.min())**2)
```

**Comment by j9ac9k** [comment]
> This would suppress the warning locally:
> 
> ```python
> with np.errstate(divide = 'ignore'):
>     positive = np.log(fn.clip_array(data, 0, data.max())**2)
>     negative = np.log(fn.clip_array(-data, 0, -data.min())**2)
> ```

that would certainly be the way to do it.  I can submit the fix for this, given that I broke it...

[anytime someone posts a git commit hash on a new issue](https://en.meming.world/images/en/1/17/Monkey_Puppet.jpg)

![](https://en.meming.world/images/en/1/17/Monkey_Puppet.jpg)
