### ISSUE TITLE
fix for PYSIDE-1563 could break makeQImage()

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#1784]
http://bugreports.qt.io/browse/PYSIDE-1563
https://codereview.qt-project.org/c/pyside/pyside-setup/+/348876
https://github.com/qtproject/pyside-pyside-setup/commit/cc011c8980cc4ce02e3d9cceb74ee028c204214e

Certain parts of pyqtgraph use QImage to wrap existing memory buffers and expect that future changes to those buffers will affect the QImage.
1) https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/ImageItem.py#L222
2) https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/widgets/RemoteGraphicsView.py#L248

The fix referred to above seems to make a private copy of the input buffer. Thus future changes to the input buffer would not be seen by the QImage.

Furthermore, for usages where no further change to the memory buffer is required, the fix also means that ```QImage(buffer)``` is no longer zero-copy.
e.g. https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/widgets/RemoteGraphicsView.py#L83

**Comment by j9ac9k** [comment]
@pijyoi I can bring this issue to the attention of the pyside2 devs, but I don't think I can speak to the specifics (and appropriate fixes) as well as you could.  Would you be ok commenting on their bug tracker, or pinging one of the devs in their [gitter chat](https://gitter.im/PySide/pyside2)?  

@outofculture is this something you might be up for doing either?

I've found the pyside2 devs to be very responsive and receptive of input when you can point to specific issues.

**Comment by pijyoi** [comment]
A useful post on how QImage is intended to be used: https://www.qt.io/blog/2017/01/20/inside-qimage-touch-qt-quick-opengl. 

The 2 cases that I listed above (ImageItem.py and RemoteGraphicsView.py) fall under the blog's "Case 3: Wrapping and modifying external image data".

[1] https://github.com/qtproject/pyside-pyside-setup/commit/cc011c8980cc4ce02e3d9cceb74ee028c204214e

We could convert ImageItem.py to "Case 2: Wrapping external, read-only image data" and RemoteGraphicsView.py to "Case 1: Image data owned by the QImage" and this would avoid breakage when [1] arrives. (This makes RemoteGraphicsView.py make 1 extra copy even in the absence of [1])

When [1] arrives, probably in PySide6 6.1.1, PySide6 binding would then run slower than the other bindings. (The fix is also applied to PySide2 5.15 but only for commercial users)

A case against [1] is that it has removed the zero-copy nature of "Case 2: Wrapping external, read-only image data".

**Comment by j9ac9k** [comment]
> (The fix is also applied to PySide2 5.15 but only for commercial users)

Yeah, we can't support that unfortunately; we have no way of testing.... It might be worth asking the Qt company for a python package with some kind of special license to be only used for testing, but until there is some user-demand, I'm going to hold off there.

**Comment by pijyoi** [comment]
PySide6 6.1.1 has been released and it passes the test script in: https://github.com/pyqtgraph/pyqtgraph/pull/1795#issuecomment-853084414
