### ISSUE TITLE
AttributeError: module 'pyqtgraph.colormap' has no attribute 'getFromMatplotlib'

### ISSUE THREAD

**Issue by AlexanderGroeger** [pyqtgraph/pyqtgraph#1803]
### Short description
The docs claim the [getFromMatplotlib](https://pyqtgraph.readthedocs.io/en/latest/colormap.html#pyqtgraph.colormap.getFromMatplotlib) API call exists, however using it raises this error. The same error occurs when using the 'get' call with the source = 'matplotlib' argument.

### Code to reproduce
```python
import pyqtgraph as pg
colors = pg.colormap.getFromMatplotlib("rainbow")
```

### Tested environment(s)

 * PyQtGraph version: 0.11.1
 * Qt Python binding: PyQt5 5.15.4 Qt 5.15.2
 * Python version: 3.6.13
 * NumPy version: 1.19.5
 * Operating system: Windows 10
 * Installation method: conda environment installed with pip

**Comment by j9ac9k** [comment]
Hi @AlexanderGroeger 

That API call was not present in 0.11.1 version of the library, in read-the-docs, you can check the docs for older versions, and you can see the available hooks at the time here: https://pyqtgraph.readthedocs.io/en/pyqtgraph-0.11.1/colormap.html

As you are on a recent version of Qt, we'd recommend you migrate over to the current release.
