### ISSUE TITLE
Windows .exe installer not present on pyqtgraph webpage

### ISSUE THREAD

**Issue by jonmatthis** [pyqtgraph/pyqtgraph#1808]
The Windows installation instructions state: 

"Windows: Download and run the .exe installer file linked at the top of the pyqtgraph web page: http://pyqtgraph.org"

..but there is no link to a .exe installer on that webpage

**Comment by j9ac9k** [comment]
Oh, yeah we should probably update the website, we stopped distributing those quite some time ago.  For windows, the recommended method to install pyqtgraph is just like any other python package `python -m pip install pyqtgraph`

**Comment by NilsNemitz** [comment]
There is also a conda package package if you are using that.

But since conda provides a rather old version of PyQt5 by default, you have to enable the conda-forge channel if you want the latest version.

It's simple though, and described on
https://pyqtgraph.readthedocs.io/en/latest/installation.html

**Comment by jonmatthis** [comment]
Thanks, I managed to install via conda easily, I just wanted to let you know your instructions were out of date!

This is a really amazing software, I've been having a lot of fun playing with the examples! 

I look forward to integrating this into my project soon!

**Comment by j9ac9k** [comment]
@jonmatthis out of date documentation is a perfectly legit reason to open an issue.

For the record; I (we?) recommend installing the pip package via pypi; the reasoning being that conda only distributes Qt 5.9 (which pyqtgraph no longer supports) and Qt 5.12 via conda-forge channel.  In Qt 5.15+ we're seeing various performance benefits in some aspects of the library.  Given that conda does not distribute anything newer than Qt 5.12, we still support that though 👍🏻

**Comment by ixjlyons** [comment]
Website was updated https://github.com/pyqtgraph/pyqtgraph.github.io/pull/2

Thanks for reporting @jonmatthis
