### ISSUE TITLE
Suggestion: Raise TypeError instead of Exception in pg.eq

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#1815]
The error raised in https://github.com/pyqtgraph/pyqtgraph/blob/e29f86578f120fda2281cfddb7429d03470fe29b/pyqtgraph/functions.py#L544 could be more clearly specified as a `TypeError` than a general Exception to make it easier to catch in outer scopes.

This could be a breaking change, so it is understandable if it is rejected.

**Comment by ixjlyons** [comment]
I don't think this is technically a breaking change. If someone currently catches it with `except Exception:` or a bare `except:`, that'd still catch the `TypeError`. I'm in favor of being more specific.

**Comment by j9ac9k** [comment]
I _hate_ bare exceptions, so anything is better than that IMO.  I approve of this change too.

**Comment by ntjess** [comment]
Closed by #1885
