### ISSUE TITLE
PySide 6.1.1 Segfaults 

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#1820]
Just tried running the test suite with PySide6 6.1.1 and getting loads of segfaults:

Failed tests:

```
FAILED tests/graphicsItems/test_ImageItem.py::test_ImageItem
FAILED tests/graphicsItems/test_ImageItemFormat.py::test_uint16
FAILED tests/graphicsItems/test_ROI.py::test_getArrayRegion
FAILED tests/graphicsItems/test_ImageItemFormat.py::test_uint8
FAILED tests/graphicsItems/test_ImageItemFormat.py::test_float32
FAILED tests/graphicsItems/test_ImageItem.py::test_ImageItem_axisorder
FAILED tests/widgets/test_histogramlutwidget.py::testHistogramLUTWidget
FAILED tests/graphicsItems/test_ROI.py::test_getArrayRegion_axisorder
```

Failed examples:

```
FAILED examples/test_examples.py::testExamples[ colorMaps.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ ColorBarItem.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ DataSlicing.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ GraphicsLayout.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ HistogramLUT.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ imageAnalysis.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ Draw.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ ImageItem.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ ImageView.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ isocurve.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ MatrixDisplayExample.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ ROItypes.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ ROIExamples.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ ScaleBar.py - PySide6 ]
FAILED examples/test_examples.py::testExamples[ VideoSpeedTest.py - PySide6 ]
```

**Comment by j9ac9k** [comment]
Stepping through the  debugger:

```
> /Users/ogi/Developer/pyqtgraph/pyqtgraph/graphicsItems/ImageItem.py(538)render()
-> self.qimage = qimage
(Pdb) n
Fatal Python error: Segmentation fault
```

Was chatting with pyside devs, they pointed out to two patches that were likely the culprits:

 https://codereview.qt-project.org/c/pyside/pyside-setup/+/350622
 https://codereview.qt-project.org/c/pyside/pyside-setup/+/352422

Good next step would be to determine which patch caused the breakage (would likely need to rebuild pyside6 bindings with those patches excluded).

Posting link to build instructions for each OS here:
https://doc.qt.io/qtforpython/gettingstarted.html

Will try and look into this more later.

**Comment by pijyoi** [comment]
I did a CI run on {3.8, 3.9} x {PySide6 6.1.1, PyQt6 6.1.0}
https://github.com/pijyoi/pyqtgraph/tree/adhoc_testing
https://github.com/pijyoi/pyqtgraph/actions/runs/916710075

The only failure is for (macOS, PySide6, colorMaps.py)

**Comment by j9ac9k** [comment]
Huh, the CI is running on macOS 10.15, locally I'm running macOS 11, I have an old mac with macOS 10.13 I can fire up to see if this is the issue is consistent.

**Comment by pijyoi** [comment]
In fact, the CI has been using PySide6 6.1.1 since its release.
https://github.com/pyqtgraph/pyqtgraph/actions?query=workflow%3Amain
Besides the occasional test_ScatterPlotItem.py segfault, all the rest are {macOS, PySide6 6.1.1, colorMaps.py}

**Comment by j9ac9k** [comment]
I wonder if this has to do with the issues I'm having building pyside bindings from source... I was trying to re-build the bindings with each of those changes removed...but I got errors during compiling.

**Comment by j9ac9k** [comment]
I have some access to macOS 10.15 machines; I'm going to see if I'm going to try and reproduce there; ....thinking about it more, I have access to other macOS 11 machines as well that I can attempt to reproduce on... will report back there.

**Comment by j9ac9k** [comment]
Confirmed test suite passes on the macOS 10.15 machine I use at work for CI purposes.  The macOS 11 CI machine has an apple M1 chip, so I can't install PySide6 on there unfortunately... Pleading with some colleagues to run the test suite for me to try and reproduce.
