### ISSUE TITLE
Multiple GLViewWidget with GLScatterPlotItem crash

### ISSUE THREAD

**Issue by PaulDebus** [pyqtgraph/pyqtgraph#1822]
Hey,

I am getting OpenGL Errors, when I try to create a second `GLViewWidget` that contains `GLScatterPlotItem` instances. The first widget works fine, the second produces the following error:

```
OpenGL.error.GLError: GLError(
      	err = 1281,
      	description = b'invalid value',
      	baseOperation = glUseProgram,
      	cArguments = (3,)
     )
```
### Short description
I had an old program using pyqtgraph as the graphics backend and it worked very well. Now I touched it again, updating all the dependencies, especially the Qt backend from an old PyQt5 to the current PySide6 (though anything recent shows the same error).

### Code to reproduce
The example code is basically the same from this thread: https://groups.google.com/g/pyqtgraph/c/AOj_oRoN_fk/m/jYvKDoclmTQJ
```python
import numpy as np
from PySide6 import QtGui, QtOpenGL
import sys

import pyqtgraph.opengl as gl

app = QtGui.QApplication.instance()
if not app:
    app = QtGui.QApplication(sys.argv)

v1 = gl.GLViewWidget()
v1.show()
v2 = gl.GLViewWidget()
v2.show()

v1.addItem(gl.GLScatterPlotItem(pos=np.array([[1, 1, 1]])))
v2.addItem(gl.GLScatterPlotItem(pos=np.array([[1, 1, 1]])))

sys.exit(app.exec_())

```

### Expected behavior
The scattered items in the second view should show.

### Real behavior
I get many errors and nothing shows. The following error repeats many times

```
[10:41:40]  

    |==============================>>
    |  Traceback (most recent call last):
    |    File "/home/paul/.miniconda3/envs/pathtest2/bin/pathplanning", line 33, in <module>
    |      sys.exit(load_entry_point('pathplanning', 'console_scripts', 'pathplanning')())
    |    File "/home/paul/work/pathplanning/pathplanning/main.py", line 26, in run
    |      QtGui.QApplication.instance().exec_()
    |    File "/home/paul/work/pathplanning/pathplanning/widgets/mainwindow.py", line 348, in define_base_station
    |      result = dialog.exec_()
    |    File "/home/paul/work/pathplanning/pathplanning/widgets/ortho_mesh_widget.py", line 48, in paintGL
    |      self.drawItemTree(useItemNames=useItemNames)
    |    File "/home/paul/.miniconda3/envs/pathtest2/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 297, in drawItemTree
    |      self.drawItemTree(i, useItemNames=useItemNames)
    |    File "/home/paul/.miniconda3/envs/pathtest2/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 278, in drawItemTree
    |      debug.printExc()
    |    --- exception caught here ---
    |    File "/home/paul/.miniconda3/envs/pathtest2/lib/python3.9/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 275, in drawItemTree
    |      i.paint()
    |    File "/home/paul/.miniconda3/envs/pathtest2/lib/python3.9/site-packages/pyqtgraph/opengl/items/GLScatterPlotItem.py", line 124, in paint
    |      with self.shader:
    |    File "/home/paul/.miniconda3/envs/pathtest2/lib/python3.9/site-packages/pyqtgraph/opengl/shaders.py", line 317, in __enter__
    |      glUseProgram(self.program())
    |    File "/home/paul/.miniconda3/envs/pathtest2/lib/python3.9/site-packages/OpenGL/error.py", line 230, in glCheckError
    |      raise self._errorClass(
    |  OpenGL.error.GLError: GLError(
    |  	err = 1281,
    |  	description = b'invalid value',
    |  	baseOperation = glUseProgram,
    |  	cArguments = (3,)
    |  )
    |==============================<<
Error while drawing item <pyqtgraph.opengl.items.GLScatterPlotItem.GLScatterPlotItem(0x558622b695f0) at 0x7f24281b8200>.

```

### Tested environment(s)

 * PyQtGraph version: 0.12.1
 * Qt Python binding: PyQt5, PySide2, PySide6
 * Python version: 3.8, 3.9
 * NumPy version: 1.20.3
 * Operating system: PopOS 20.10, Windows 10
 * Installation method: pip

### Additional context
Seems similar to the issue adressed in https://github.com/pyqtgraph/pyqtgraph/pull/102

**Comment by pijyoi** [comment]
Setting ```AA_ShareOpenGLContexts``` seems to do the trick
```python
import numpy as np
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore

import pyqtgraph.opengl as gl

QtCore.QCoreApplication.setAttribute(QtCore.Qt.ApplicationAttribute.AA_ShareOpenGLContexts)

pg.mkQApp()

v1 = gl.GLViewWidget()
v1.show()
v2 = gl.GLViewWidget()
v2.show()

v1.addItem(gl.GLScatterPlotItem(pos=np.array([[1, 1, 1]])))
v2.addItem(gl.GLScatterPlotItem(pos=np.array([[1, 1, 1]])))

pg.exec()
```

**Comment by j9ac9k** [comment]
Considering multiple views is not exactly an uncommon use-case for this library, wonder if we should attempt to set this attribute as part of `mkQApp`.  Of course this would have no guarantee it would work for end-users, as if they integrate pyqtgraph within their own application, they may have their own `QApplication` instantiation process.

**Comment by pijyoi** [comment]
It is documented somewhere that for QOpenGLWidget, contexts are automatically shared for widgets sharing the same top-level window. In this case, two separate windows are created and thus setting this attribute becomes necessary.

It is also stated somewhere that one should set this attribute only for the cases where it is needed.

**Comment by j9ac9k** [comment]
Ahh, yeah two top level windows is definitely not a default use-case.  Thanks for sharing @pijyoi

**Comment by PaulDebus** [comment]
@pijyoi thank you! This change solves it for me. Does not seem to be a bug.

It was more me not fully reading/understanding the docs. I do not know if this should be in the docs somewhere, but maybe this issue alone can help people looking for it. If anybody has a better idea, I could work in a pull request with a doc change or something.

Else, I would close the issue, as my problem is solved. Thanks again!
