### ISSUE TITLE
PySide6 6.1.1 changes the root log level from WARNING to INFO

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#1823]
This would be an upstream issue, but creating it here to document it.

This explains why the CI was failing on the colorMaps.py example on PySide6 6.1.1.
https://github.com/pyqtgraph/pyqtgraph/pull/1797#issuecomment-855984846
Because the log level had been changed to INFO, a matplotlib info log (that contained the string "error") started showing up.

This is a PySide6 6.1.1 issue. It does not happen with PyQt6 6.1.1

Minimal example:
```python
import logging
root = logging.getLogger()

before = root.level
import pyqtgraph as pg
after = root.level

if before != after:
    print(f'log level from {before} to {after}')

logging.info('FYI')
```

**Comment by j9ac9k** [comment]
I think we can close this one out; as there isn't really anything for us to do here other than to be aware of it (and thanks for tracking this down @pijyoi )

**Comment by pijyoi** [comment]
This has been addressed by https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-1614.
