### ISSUE TITLE
How to add custom objects and labels to AxisItem/Y-Axis?

### ISSUE THREAD

**Issue by shujaatak** [pyqtgraph/pyqtgraph#1841]
In Y-Axis, I want to display a rectangle(box) with a current value of the graph in it. The box will move up and down as the graph current value changes. I wonder how to do this in pyqtgraph.

Can anyone please share ideas?

**Comment by j9ac9k** [comment]
PyQtGraph definitely does not have native support for this, but given inheritance is the Qt way, it's certainly doable.  You would have to inherit from `pg.AxisItem` and modify `AxisItem.label` and replace the instance the `QGraphicsTextItem` with the `QGraphicsObject` of your choosing.  Other methods of `AxisItem` expect to be able to interact with `QGraphicsTextItem` specific methods in `self.label` so you would have to address those accordingly; doing a quick scan of `AxisItem` this doesn't appear to be too bad though, so it should certainly be doable.

Hope that helps!

**Comment by shujaatak** [comment]
@j9ac9k Thank you so much for the hint. Now I wonder how I will move the box up and down according to the current value of the chart and also it should move with panning and zooming of the chart.

I would definitely try on my own to code this functionality but it would be a lot helpful if someone with experience could quickly show some example code.

**Comment by j9ac9k** [comment]
If I am envisioning something are you effectively looking for something like a scroll bar on the location of the axis items so you can envision how much of your data is actually visible.  Would you say that's an accurate assessment?  If so, it _might_ be easier for you to re-enable the scrollbars that PyQtGraph's GraphicsView hides by default, and just hide the axis items in general.
