### ISSUE TITLE
Grid pans at different rate from plot

### ISSUE THREAD

**Issue by drdott** [pyqtgraph/pyqtgraph#1842]
Hello,

I noticed that the grid does not move in synchronisation with the data in a plot. I started running the "PlotWidget.py" example.

Here is what the graph looks like initially. I have marked roughly where the "1" tickmark of the grid aligns to the data:
![image](https://user-images.githubusercontent.com/76479557/122584889-ca9b4080-d052-11eb-9eaa-7f28a186df07.png)

And if I use the left mouse button to pan to the right somewhat, this is what I end up with, with the grid having moved about 1.5 times as much as the graph:
![image](https://user-images.githubusercontent.com/76479557/122585000-e868a580-d052-11eb-9b73-b16f68b2a11e.png)

**Comment by j9ac9k** [comment]
Hi @drdott 

Some version and Qt binding information would be helpful here; also any chance you're using a hidpi monitor, and if so, what scaling do you have for it?

**Comment by drdott** [comment]
Hi @j9ac9k,
Of course, I forgot. Windows 10x64, python 3.8.10, Qt 5.12.9, Pyside2 5.13.2, pyqtgraph 0.12.1.

Yes, I am using a hidpi monitor, it is set to 125%. When I change that setting to 100% the grid and plot stay in sync. I read the note about HiDPI Displays at [https://pyqtgraph.readthedocs.io/en/latest/how_to_use.html#hidpi-displays](url) but didn't realise what "ideal behaviour" meant.

So I guess the answer is for me to upgrade to Qt 5.14+ or Qt 6?

**Comment by j9ac9k** [comment]
There is definitely a bug in how we're handling hidpi scaling (hard to say if that's something we can fix or not), but Qt < 5.14 definitely has the worst support for it on Windows in that regard.  Qt6 in my hidpi testing "just worked" during my testing, but admittedly I don't think I tested out this condition.

Regarding "ideal" behavior, in the docs, I define ideal behavior as no display abnormalities, or how it should look/interact.

Also last question, are you using the pyqtgraph instantiation of QApplication (aka are you using `pg.mkQApp()`) or do you instantiate your own instance before importing pyqtgraph?

If upgrading to PyQt6/PySide6 6.1 is not a deal breaker for your use-case I would highly recommended; we generally see higher performance on from our Qt bindings with newer versions (note we have just phased out Qt 6.0 support, but 6.1 should work everywhere, if you have high performance needs involving scatter plots, we recommend PySide6).

**Comment by drdott** [comment]
Thanks for the explanations.

I have tried my own QApplication instantiation with the recommended configuration calls, and also the PlotWidget.py example (which uses pg.mkQApp()), and they both appear to behave the same on my system.

Upgrading is not an issue for this, so I'll try that. Thanks.

**Comment by drdott** [comment]
I can confirm that using the latest versions for Qt (Qt v6.1.1, PySide6 v6.1.1, pyqtgraph 0.12.1) fixes this issue.
