### ISSUE TITLE
GradientLegend broken in y-inverted viewbox

### ISSUE THREAD

**Issue by campagnola** [pyqtgraph/pyqtgraph#1847]
### Short description
If GradientLegend is placed in a ViewBox with inverted Y axis, the text is flipped vertically. If the y-axis is not inverted, then the text is upright but the rest of the item is upside-down. This changed was introduced in [5fa3901c0](https://github.com/pyqtgraph/pyqtgraph/commit/5fa3901c00f4ffb9cc9951d7cac4af02fb56a497). Prior to that, a similar issue was present, but only for viewboxes that were _not_ inverted (apparently this had only ever been used in y-inverted views, which is common when working with images).

### Code to reproduce
```
import pyqtgraph as pg
p1 = pg.plot(title='inverted')
l1 = pg.GradientLegend([25, 300], [-20, -30])
l1.pen = pg.mkPen(color='w', width=1, cosmetic=True)
p1.addItem(l1)
p1.invertY()
p2 = pg.plot(title='normal')
l2 = pg.GradientLegend([25, 300], [-20, -30])
l2.pen = pg.mkPen(color='w', width=1, cosmetic=True)
p2.addItem(l2)
```

### Expected behavior
item placement and visual appearance should be the same regardless of whether `p.invertY()` is called. The legend item should appear in the upper-right, and the max value (red) should be at the top.

**Comment by NilsNemitz** [comment]
Dear @campagnola , sorry for breaking things here. I hope that the next revision in #1864 will solve the orientation dependence for all possible alignments.
If you have the chance to test-run the new code in the context of your application, that would be very helpful! It does seem to work in my test cases, but I don't have enough experience with how items get assigned a viewbox (or not) to be really sure that I haven't missed some important corner case.
