### ISSUE TITLE
ImageView throws 'Must construct a QApplication before a QWidget' error

### ISSUE THREAD

**Issue by vmsch** [pyqtgraph/pyqtgraph#1856]
### Short description
Running ImageView throws an error message:
QWidget: Must construct a QApplication before a QWidget

### Code to reproduce
```python
import pyqtgraph as pg
imv = pg.ImageView()
```

throws error message

```
QWidget: Must construct a QApplication before a QWidget
Abort trap: 6
```

### Tested environment(s)

 * PyQtGraph version: 0.12.1 
 * Qt Python binding: PySide6 6.1.1 Qt 6.1.1
 * Python version: 3.9.5
 * NumPy version: 1.20.3
 * Operating system: Mac OS Big Sur (11.4)
 * Installation method: conda environment; pyqt6, pyside6 and numpy vs pip, tried pyqtgraph both with pip and setup.py install

### Additional context
This is related to closed issue  #1614, but I already use pyqtgraph version 0.12, and also tried installing the current master branch and it still didn't work. I created different test environments using different installation methods, I first tried installing everything with conda, then everything with pip, and finally pyqtgraph separately with setup.py. The same error also ocurred on a windows machine.

The final test environment was created via
```
conda create -n test python=3.9
. activate test
pip install PyQt6
pip install PySide6
pip install numpy
git clone https://github.com/pyqtgraph/pyqtgraph pyqtgraph
cd pyqtgraph
python setup.py install
```

**Comment by j9ac9k** [comment]
Qt applications as a whole require a QApplication instance to be started before showing Widgets.  We have some methods that act as convinience methods

**Comment by vmsch** [comment]
Does that mean it shouldn't work to begin with? I have some code just for displaying images, that basically does the above just adding some data which ran in late April and now throws this error message.

**Comment by j9ac9k** [comment]
> Does that mean it shouldn't work to begin with? I have some code just for displaying images, that basically does the above just adding some data which ran in late April and now throws this error message.
> 
> 

I accidentally hit submit before finishing my answer (thank you mobile client).  Take a look at my edited answer for more context.

**Comment by vmsch** [comment]
Thanks, that worked!
(With app.exec_() at the end of the file)
