### ISSUE TITLE
ColorBarItem does not work with {"imageAxisOrder": "row-major"}

### ISSUE THREAD

**Issue by paulmueller** [pyqtgraph/pyqtgraph#1863]
### Short description

Setting the imageAxisOrder to row-major:
```python
import pyqtgraph as pg
pg.setConfigOption("imageAxisOrder", "row-major")
```
apparently breaks the colorbar.

### Code to reproduce

```python

import numpy as np
import pyqtgraph as pg
from pyqtgraph.graphicsItems.GradientEditorItem import Gradients

if __name__ == '__main__':
    pg.setConfigOption("imageAxisOrder", "row-major")

    app = pg.mkQApp()

    pw = pg.plot()

    cm = pg.ColorMap(*zip(*Gradients["viridis"]["ticks"]))
    
    # use ColorBarItem
    bar = pg.ColorBarItem(cmap=cm, values=(0,20),interactive=False)
    pw.plotItem.layout.setColumnFixedWidth(4, 5) # enforce some space to axis on the left
    pw.plotItem.layout.addItem(bar,2,5)

    app.exec()

```

### Expected behavior

(without row-major)
![image](https://user-images.githubusercontent.com/2853022/123230548-aa96d180-d4d7-11eb-9c76-3b1d7fd30194.png)

### Real behavior

![image](https://user-images.githubusercontent.com/2853022/123230618-baaeb100-d4d7-11eb-957e-b2c9c1691cea.png)

### Tested environment(s)

 * PyQtGraph version: 0.12.1
 * Qt Python binding: 'PyQt5 5.15.1 Qt 5.15.1'
 * Python version: 3.8.5 (default, May 27 2021, 13:30:53)
 * NumPy version: '1.18.5'
 * Operating system: Ubuntu 20.04
 * Installation method: pip

### Additional context
https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/issues/87
https://github.com/pyqtgraph/pyqtgraph/issues/1849

**Comment by pijyoi** [comment]
Was fixed in #1723

**Comment by paulmueller** [comment]
My bad. I only searched for "ColorBar" and not for "ColorBarItem" in the issue list.

**Comment by j9ac9k** [comment]
Yeah I've been bitten by the search too... Thanks for reporting nonetheless!
