### ISSUE TITLE
pg.ImageView  zValue failed?

### ISSUE THREAD

**Issue by jekoie** [pyqtgraph/pyqtgraph#1890]
I use pyqtgraph  image to write a simple demo , it failed with follow error?
```python
import numpy as np
import pyqtgraph as pg
from PyQt5.QtWidgets import *
from PIL import Image

app = QApplication([])

p = pg.PlotWidget(title="s")

iv = pg.ImageView()

data = np.array(Image.open("lena.jpg"))


iv.setImage(data)
p.addItem(iv)
p.show()
app.exec()
```

Error
```
PS E:\test> & D:/python38/python.exe e:/test/test.py
Traceback (most recent call last):
  File "e:/test/test.py", line 16, in <module>
    p.addItem(iv)
  File "D:\python38\lib\site-packages\pyqtgraph\graphicsItems\PlotItem\PlotItem.py", line 532, in addItem
    self.vb.addItem(item, *args, **vbargs)
  File "D:\python38\lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py", line 406, in addItem  
    if item.zValue() < self.zValue():
AttributeError: 'ImageView' object has no attribute 'zValue'
PS E:\test> 
```

**Comment by ixjlyons** [comment]
`ImageView` is a `QWidget`, so it is not really intended to be used as an "item" in the `PlotWidget`/`PlotItem` context, which is [graphics view](https://doc.qt.io/qt-5/graphicsview.html) based. It would actually [be feasible](https://doc.qt.io/qt-5/graphicsview.html#embedded-widget-support) to add the widget to the scene, but I doubt it'd work very well.

Take a look at [examples/ImageView.py](https://github.com/pyqtgraph/pyqtgraph/blob/6b4385ce0d0f9078aa22e2e27aa5307271e95ae1/examples/ImageView.py) for typical usage of `ImageView`.

There's also [examples/imageAnalysis.py](https://github.com/pyqtgraph/pyqtgraph/blob/6b4385ce0d0f9078aa22e2e27aa5307271e95ae1/examples/imageAnalysis.py) that demonstrates building up something similar to `ImageView`.

Perhaps [this page of the docs](https://pyqtgraph.readthedocs.io/en/latest/images.html) could use some more info along these lines. It's also a little unfortunate the name is Image*View* and not `ImageAnalysisWidget` or something to help make the distinction clear.

I could also imagine a check in `addItem` to give a more helpful error message.

**Comment by ntjess** [comment]
Usually, `ImageView` is meant to be its own widget, rather than be embedded in a plot. Perhaps you are looking to use an `ImageItem`?

Also, just a minor point -- usually, your pyqtgraph applications can be a bit more portable if instead of importing from `PyQt5`, you imported from `pyqtgraph.Qt`:

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtWidgets
from skimage.data import chelsea
# Make sure image keeps aspect ratio and is displayed upright
pg.setConfigOption('imageAxisOrder', 'row-major')

app = QtWidgets.QApplication([])

p = pg.PlotWidget(title="s")
data = chelsea()
# Or lena.png
iv = pg.ImageItem(data)

iv.setImage(data)
p.addItem(iv)

vb = iv.getViewBox()
vb.setAspectLocked(True)
vb.invertY()

p.show()
app.exec()
```

**Comment by ntjess** [comment]
@ixjlyons Argh, just beat me to it, haha

**Comment by jekoie** [comment]
@ntjess  @ixjlyons Thanks very much for solve my problem, I love you very much and also learn more. ^-^
