### ISSUE TITLE
Add sigWidthChanged signal to the AxisItem class

### ISSUE THREAD

**Issue by shujaatak** [pyqtgraph/pyqtgraph#1896]
I needed to draw custom shapes over Y-Axis(AxisItem) region,  so I made a custom GraphicsItem and layered it over Y-Axis item. Now to ensure that the width of my custom GraphicsItem is equal to Y-Axis item so that the shapes drawn can appear only over Y-Axis, I added this signal to AxisItem `sigWidthChanged = QtCore.Signal(float)` and emitted it in the end of the `_updateWidth() `function of AxisItem like this `self.sigWidthChanged.emit(self.width())`. I simply connected this signal with a slot of my custom GraphicsItem and changed it's width accordingly.

Just like me, some other people may require this feature so I wish if this signal may be included in pyqtgraph please!

**Comment by shujaatak** [comment]
Only two additional lines are needed for adding signal `sigWidthChanged` to the AxisItem class.

1. Add `sigWidthChanged = QtCore.Signal(float)`  to line number 24, here:
https://github.com/pyqtgraph/pyqtgraph/blob/b9e079b10cc95ec7344c2da95b5ac6827fb02cc5/pyqtgraph/graphicsItems/AxisItem.py#L24

2. Add `self.sigWidthChanged.emit(self.width())` to line number 417, here:
https://github.com/pyqtgraph/pyqtgraph/blob/b9e079b10cc95ec7344c2da95b5ac6827fb02cc5/pyqtgraph/graphicsItems/AxisItem.py#L417

**Comment by shujaatak** [comment]
@j9ac9k Can you please look into this possibility of adding `sigWidthChanged` signal to the `AxisItem` class?

**Comment by shujaatak** [comment]
@ixjlyons @j9ac9k Is there any possibility to add sigWidthChanged signal to AxisItem please?

I can get the width of the axis item by using @j9ac9k [this logic](https://github.com/pyqtgraph/pyqtgraph/issues/1848#issuecomment-865517729):

> You can get the dimensions of the axis item by using the .boundingRect() which will return a QRectF object, which you can get the width from there. Same with the label within the axis item, you can do AxisItem.label.boundingRect() as well.

but I have noticed that the widths of the axis item and my custom overlayed axis item can't be reliably synchronized without width change signal from the axis item. 

It would be more useful if instead of `sigWidthChanged` the `sigSizeChanged(width, height) `signal gets included in the AxisItem class! That way one looking for height can easily extract height information from sigSizeChanged signal.

**Comment by ixjlyons** [comment]
`AxisItem` inherits from `QGraphicsWidget`, so you should be able to connect [`geometryChanged`](https://doc.qt.io/qt-5/qgraphicswidget.html#geometryChanged) to a slot that calls `axis.width()`.

**Comment by shujaatak** [comment]
> `AxisItem` inherits from `QGraphicsWidget`, so you should be able to connect [`geometryChanged`](https://doc.qt.io/qt-5/qgraphicswidget.html#geometryChanged) to a slot that calls `axis.width()`.

Fantastic! This neat and clean solution works perfectly!
Thank you!
