### ISSUE TITLE
Make h5py an optional dependency in the test suite (just like matplotlib)

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#1898]
Currently if you attempt to run the test suite, and do not have h5py installed, one of the tests will fail due to it not being installed.  This library should be made an optional dependency, much the same way that matplotlib has been as pointed out by here: https://github.com/pyqtgraph/pyqtgraph/pull/1895#issuecomment-881146056

**Comment by pijyoi** [comment]
> one of the tests will fail due to it not being installed.

That's not what happens. Pytest will fail altogether while collecting the tests.

**Comment by j9ac9k** [comment]
Ahh right, in my case it failed toward the end of the test suite, but yes, it is indeed the test collection phase that breaks

![image](https://user-images.githubusercontent.com/646398/125887781-c026d7eb-65a9-4df2-b6e1-38a8009fbcfa.png)
