### ISSUE TITLE
Hide crosshair when mouse is not over the plot

### ISSUE THREAD

**Issue by shujaatak** [pyqtgraph/pyqtgraph#1899]
How to hide the crosshair when mouse is not over the plot?

**Comment by ixjlyons** [comment]
Assuming you're referring to the crosshair example (`examples/crosshair.py`). `InfiniteLine` inherits from `QGraphicsItem` so you can use `show()`/`hide()`/`isVisible()`. The example already detects when the mouse is inside the scene in the `mouseMoved` callback:

https://github.com/pyqtgraph/pyqtgraph/blob/d28e1c807518ac52fca71af28df0288c83a6ca93/examples/crosshair.py#L67-L69

So just a bit more logic is needed to hide/show the lines as appropriate.

**Comment by j9ac9k** [comment]
the `plot.sceneBoundingRect().contains(pos)` is definitely the way to do it as @ixjlyons indicated ((I call `InfiniteLine.show()` then) if that resolves to False, I call `InfiniteLine.hide()`
