### ISSUE TITLE
Do not close non-closable docks that are floating

### ISSUE THREAD

**Issue by sbourdeauducq** [pyqtgraph/pyqtgraph#192]
Non-closable docks that are floating can still be closed by closing their window. This is a pretty serious bug as it may render the application completely unusable when the improperly closed docks contain important widgets.

This patch fixes the problem by moving non-closable docks to the home area when they are floating and their window is closed.
https://github.com/m-labs/artiq/blob/master/misc/pyqtgraph-do-not-close-nonclosable-docks.patch

**Comment by 2xB** [comment]
This was fixed by the merged Pull Request #657. Thank you for the report!
