### ISSUE TITLE
[ENH] Set Antialiasing optional for PlotCurveItem with OpenGL?

### ISSUE THREAD

**Issue by marsipu** [pyqtgraph/pyqtgraph#1926]
## Short Description
For PlotCurveItems plotting with OpenGL enabled, antialiasing is currently always enabled by default. Would it be possible to make it optional?

## Long Description
In `GLGridItem`, the following lines (l.69-72) are depending on the parameter `antialias`:
```python
glEnable(GL_LINE_SMOOTH)
glEnable(GL_BLEND)
glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
glHint(GL_LINE_SMOOTH_HINT, GL_NICEST)
```
For `PlotCurveItem` currently the same lines (l.631-643) aren't optional thus antialiasing is always enabled.
I tried commenting them out and it had the desired effect of turning antialiasing off while the plot was still working.

**What do you think about making antialiasing optional here too?
Or is there a specific reason why it has to be always enabled?**

**Comment by pijyoi** [comment]
The code in question was last modified in 2013 2980f8335c1745564e89259a026e83167bb33e96. There probably wasn't any particular reason to it not being a settable option. Why don't you submit a PR to add this feature?

**Comment by marsipu** [comment]
@pijyoi Done:)

**Comment by j9ac9k** [comment]
Think we can close this as #1932 was merged.  Thanks @marsipu
