### ISSUE TITLE
Log mode broken in 0.12.2

### ISSUE THREAD

**Issue by hppi-johnsson** [pyqtgraph/pyqtgraph#1933]
### Short description
Log mode shows wrong sign in the exponent, completely wrong numbers, and inverted axis.
Everything works as expected in 0.12.1

### Code to reproduce
```
import pyqtgraph as pg

from pyqtgraph.Qt import QtCore, QtGui

app = pg.mkQApp()
pw = pg.PlotWidget(enableMenu=False)

pw.plotItem.setLogMode(x=False, y=True)
x = range(8)
y = [1e-6,2e-6,3e-6,4e-6,5e-6,6e-6,7e-6,8e-6]
pw.plot(x, y, symbol='o')

pw.show()
# Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()
```

### Expected behavior
logarithmic y axis

### Real behavior
Wrong sign in the exponent and inverted scale

### Tested environment(s)

 * PyQtGraph version: 0.12.2
 * Qt Python binding: pyqt5
 * Python version: 3.8

**Comment by pijyoi** [comment]
bisect points to 314121192ad8661f2db0be0221bfeacfbb50a736

**Comment by j9ac9k** [comment]
> bisect points to 314121192ad8661f2db0be0221bfeacfbb50a736

Yeah I was thinking this was likely the commit.  Thanks for the git bisect results!
