### ISSUE TITLE
[question] Why is MetaArray.view() set to be removed in v0.13?

### ISSUE THREAD

**Issue by Achilles1515** [pyqtgraph/pyqtgraph#1950]
`MetaArray.view` states the following deprecation warning:

`MetaArray.view is deprecated and will be removed in 0.13. Use MetaArray.asarray() instead.`

And instantiating a `MetaArray` class itself states the following deprecation warning:

`MetaArray is deprecated and will be removed in 0.14. Available though https://pypi.org/project/MetaArray/ as its own package.`

--------------

What is the purpose of deprecating a specific method (`view`) when the entire class is about to be deprecated from the pyqtgraph module?

Second, the new standalone package does not show anything about `view` being deprecated.

https://github.com/outofculture/metaarray/blob/7b44bb0b18c31281fefa357cf0bfca2a2b72a74a/src/MetaArray/__init__.py#L305

Is there really an intention to deprecate `view` in v0.13 producing a pyqtgraph `MetaArray` with a different list of methods than the `MetaArray` standalone package?

**Comment by j9ac9k** [comment]
Hi @Achilles1515,

You're running into two issues with different judgments/motivations behind them made at the same time, and in turn it is likely a bit confusing from your end.

We made official a _lot_ of deprecations for removal in 0.13.  We looked through the codebase for comments specifying deprecations and turned them into actual emitted warnings.  Here you can see the comment for the 0.11.1 release.

https://github.com/pyqtgraph/pyqtgraph/blob/pyqtgraph-0.11.1/pyqtgraph/metaarray/MetaArray.py#L322-L327

So deprecating the view method was a decision made _9 years ago_.  As to the why, that is a question for @campagnola but as there is an alternative method in place, we saw it as being safe to emit a warning that it will be removed.  

Regarding the decision to remove MetaArray outright; I pushed for that change, and given it's a bigger change, I put a much longer deprecation warning period (0.14.0).  The reasons for removal are fairly straight forward IMO

- `MetaArray` is not used anywhere else within the library (some methods have some checks for MetaArray)
- From what I could tell, nobody outside of ACQ4 was actually using MetaArray (which I recognize there are likely usages I am unaware of, but point being it's not a frequently used portion of the library).
- It's _entirely_ untested... like there is no one test code path that uses MetaArray
- `xarray` is likely a better alternative for similar functionality

In terms of of having different methods be deprecated now that it's a separate package, that's a question for the new package owner, @outofculture :D

**Comment by outofculture** [comment]
> the new standalone package does not show anything about view being deprecated

Ah! That's my mistake. I removed all the deprecation warnings without reading them. Presumably I can just remove that method if I do it quick before anyone downloads it. [Not many have...](https://pypistats.org/packages/metaarray)

As I was extracting MetaArray, I actually found a few tests. Those tests weren't being _run_, and the don't pass, so... I can only imagine that it's the tests' fault they don't pass, at this point; the code hasn't really changed in years.

I haven't fully committed to the statement "use `xarray` instead", yet. `xarray` is more active and broadly used, which would be cause enough to use it, barring any specific feature disparity.

Anyway, I'll move this discussion over to the new package. Thanks for noticing this deprecation discrepancy!

**Comment by Achilles1515** [comment]
It sounds like `view` just shouldn't be deprecated.
Even the latest MetaArray documentation still uses it in examples.
https://github.com/outofculture/metaarray/blob/main/README.md#performance-tips

It would be one thing if it was a huge pain to maintain, but it doesn't seem that way (on top of the fact that not much, in terms of "new development", is being done inside `MetaArray` to begin with nor specifically inside `ndarray.view` to need to keep up with).

It was obviously added for interface similarity with numpy - and despite having alternatives, numpy is not deprecating `ndarray.view`.

I was looking into refactoring the way `PlotDataItem` handles x/y data inputs, and was planning on using the `view` method in a duck-typed manner for concisely handling multiple data types. I've since found a better way and don't plan to use `view` anymore, so I don't care strongly about the outcome here.

**Comment by j9ac9k** [comment]
I'm going to close this issue out as it involves MetaArray, and while MetaArray is still part of pyqtgraph, it won't be for much longer.
