### ISSUE TITLE
ROI overrides pen parameters explicitly

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#1960]
I would expect ROIs that take a `pen` parameter to preserve aspects of that pen, but `Handle` instances explicitly reset their `width` and `cosmetic` properties during init. Is there a reason these aren't simply inferred from the starting pen? Otherwise, I would request that these lines be removed.

https://github.com/pyqtgraph/pyqtgraph/blob/0d8eba36a6a19ab6d8453f66a7dcf8d7e6f3c6a3/pyqtgraph/graphicsItems/ROI.py#L1361-L1362

**Comment by j9ac9k** [comment]
I don't think the Pen should have its attributes overwritten,...there is no comment and nothing in git history to suggest why it is this way, so we should likely remove those attributes.  `mkPen` defaults to setting the `QPen` instance it returns to be cosmetic; perhaps in the docstring, we say that the Pen should be cosmetic.

**Comment by j9ac9k** [comment]
> Is there any timetable on a fix for this issue? We had to resort to temporarily increase the width on hove over for the handle to be visible enough to be dragged, which was the easiest way without rewriting the entire handle from scratch.

None of the current maintainers are funded to work on this project, so maintainer hours come and go on a volunteer basis. Waiting on a maintainer to fix an issue that isn't an absolute show-stopper for the library here is likely not going to yield the desired results.

If you have an issue that needs to be fixed (sounds like this one is impacting you), best thing you can do is submit a PR with the fix.  I try and keep the number of outstanding PRs under 30 (hoping to get under 20 in the coming months).  If it's a small change, which looks like this issue would be, chances are it will be merged in short order.
