### ISSUE TITLE
Cross widget to plot not working?

### ISSUE THREAD

**Issue by jekoie** [pyqtgraph/pyqtgraph#1966]
I am trying to add `GraphicsLayoutWidget`  and `LinearRegionItem`, that two ratio is 4:1 or m:n, but I don't found any layout in `pygtgraph`.So I try to the code like below, but unfortunately it don't work and cast out trackback error info.

**code**
```python

import pyqtgraph as pg
import numpy as np
from PyQt5.QtWidgets import *


class Chart(pg.GraphicsLayoutWidget):
	def __init__(self):
		super().__init__()
		self.data = np.linspace(0, 2*np.pi, 100)
		self.data = np.sin(self.data)
		self.p = self.addPlot(y=self.data)

class LR(pg.GraphicsLayoutWidget):
	def __init__(self, target):
		super().__init__()
		self.p = self.addPlot()  # type:pg.PlotItem
		self.target = target  # type: pg.PlotItem

		rg = (target.data[0], target.data[-1])
		self.p.setXRange(rg[0], rg[1], padding=0)
		self.lr = pg.LinearRegionItem([rg[0], rg[1]])
		self.lr.sigRegionChanged.connect(self.onLRChanged)
		self.p.addItem(self.lr)

	def onLRChanged(self):
		print(self.target, self.lr.getRegion())
		self.target.setXRange(*self.lr.getRegion())


class Win(QWidget):
	def __init__(self):
		super().__init__()
		lay = QVBoxLayout()

		self.chart = Chart()
		self.lr = LR(self.chart)

		lay.addWidget(self.chart)
		lay.addWidget(self.lr)

		lay.setStretch(0, 4)
		lay.setStretch(1, 1)
		self.setLayout(lay)


app = QApplication([])
win = Win()
win.show()
app.exec()
```

**image**
![image](https://user-images.githubusercontent.com/6836400/129170599-fc8990fe-2354-4fe3-bcd4-a378d4be7707.png)

**error**
![image](https://user-images.githubusercontent.com/6836400/129170722-f9606ee3-adee-4015-bbb3-2ee7473acca7.png)
environment
Python 3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32

Name: pyqtgraph Version: 0.12.2
Name: numpy Version: 1.20.3
Name: PyQt5 Version: 5.15.4

The traceback info will show when user drag LinearRegionItem line in both side of the bottom graph(plot). –

**Comment by pijyoi** [comment]
In the following line, your comment says you expect a ```PlotItem```
```python
self.target = target  # type: pg.PlotItem
```

but you actually passed in a Chart which is a ```GraphicsLayoutWidget```
```python
self.chart = Chart()
self.lr = LR(self.chart)
```

**Comment by jekoie** [comment]
@pijyoi  Yes, You are right, It my fault.
