### ISSUE TITLE
The scale argument from the ImageView setImage does not work as expected with PyQt6

### ISSUE THREAD

**Issue by Anatoly1010** [pyqtgraph/pyqtgraph#1967]
### Short description
The scale argument from the ImageView setImage method does not work as expected when using PyQt6.

### Code to reproduce

```python
import numpy as np
# force to use pyqt6 
import PyQt6
from pyqtgraph.Qt import QtGui, QtWidgets
import pyqtgraph as pg

def main():
    app = QtWidgets.QApplication([])
    
    # dummy data
    kwargs = {}
    data = np.random.normal( size = (2, 600, 600), loc = 1024, scale = 64 )

    win = QtGui.QWidget()
    win.setLayout( QtGui.QHBoxLayout() )
    win.resize(800,800)

    plot_item = view = pg.PlotItem()
    img_view = pg.ImageView( view = view )
    item = plot_item.getViewBox()
    item.invertY(False)
    
    # pos argument works correctly
    kwargs['pos'] = (500, 500)
    # scale gives rise to an error
    kwargs['scale'] = (10, 1)
    img_view.setImage( data, **kwargs )
    
    win.layout().addWidget(img_view)
    win.show()
    win.raise_()
    app.exec()
    
if __name__ == "__main__":
    main()
```

### Expected behavior

The scale argument should change a scale of the image.

### Real behavior

When using PyQt6, the scale argument returns an error. In the case of PyQt5, everything works as expected.
```
Traceback (most recent call last):
  File "image_view_error.py", line 33, in <module>
    main()
  File "image_view_error.py", line 25, in main
    img_view.setImage( data, **kwargs )
  File ".../python3.8/site-packages/pyqtgraph/imageview/ImageView.py", line 363, in setImage
    self.imageItem.scale(*scale)
TypeError: scale(self): too many arguments
```

### Tested environment(s)

 * PyQtGraph version: 0.12.2
 * Qt Python binding: PyQt6 Qt 6.1.2 // PyQt5 Qt 5.14.1 
 * Python version: 3.8.10
 * NumPy version: 1.18.3
 * Operating system: Linux Ubuntu 20.04
 * Installation method: pip

**Comment by pijyoi** [comment]
Hi, thank you for reporting. ImageView is using a deprecated monkey-patched method QGraphicsItem.scale(). This monkey-patching was deliberately left out for Qt6 and usage of this method within the library was removed. You have found a leftover.

It would be appreciated if you could test out #1968 to see whether it fixes this issue.

**Comment by Anatoly1010** [comment]
Thanks for comment. I checked that #1968 fixes this issue. PyQt6 starts to work the same as PyQt5.
