### ISSUE TITLE
Y axis log scale is wrongly ploting data. Resulting plot makes no sense.

### ISSUE THREAD

**Issue by joaorsbarbosa** [pyqtgraph/pyqtgraph#1972]
### Short description

When plotting data in a Y semi-log plot, the resulting plot has no relation to the original data. The resulting plot makes no sense in relation to the original data

### Code to reproduce
```
from PyQt5 import QtWidgets
import pyqtgraph as pg
import sys

class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.graphWidget = pg.PlotWidget()
        self.setCentralWidget(self.graphWidget)
        self.graphWidget.showGrid(x=True, y=True)
        self.graphWidget.setLogMode(False, True)
        # My apologies for the stupidity about to happen. Was the easiest way I found to include my data.
        y = [0.004970316,0.007285618,0.010831383,0.012846427,0.015166943,0.018170679,0.021120025,0.023543733,0.026538899,0.03005896,0.032421201,0.03681,0.038335541,0.043457847,0.046070799,0.048203563,0.051874497,0.056167554,0.060257959,0.065740501,0.068693202,0.074038281,0.079207154,0.084342503,0.091756608,0.099545109,0.108533146,0.118271091,0.129843741,0.143869488,0.160039519,0.176430087,0.196230407,0.219090687,0.245351039,0.276739619,0.31083016,0.352437218,0.40319806,0.46285079,0.53323348,0.622956388,0.73135715,0.866264476,1.036095281,1.25036544,1.522975887,1.872760566,2.317224235,2.883407302,3.598737581,4.496827995,5.614696007,6.988399062,8.660674649,10.66152307,13.01943443,15.75143999,18.85517812,22.34622265,26.2175263,30.45464901,35.04633026,39.97525808,45.2303697,50.79772118,56.65940459,62.80745442,69.22106157,75.88324784]
        x = [0.041991046,0.051986659,0.061981112,0.071977008,0.081972618,0.09196758,0.101962597,0.111958106,0.121953084,0.131947559,0.141943126,0.151936781,0.161933137,0.171926108,0.181921446,0.191917222,0.201911562,0.211905315,0.221899244,0.231891875,0.241886878,0.251879639,0.261872565,0.271865509,0.281856318,0.291846758,0.301836097,0.311824699,0.32181157,0.331796156,0.34177869,0.351761016,0.361740155,0.371716377,0.381689392,0.391657599,0.401623227,0.411581764,0.421531666,0.43147321,0.441404601,0.451317748,0.461213304,0.471083825,0.4809214,0.490717083,0.500457699,0.510125512,0.519704037,0.529167707,0.538490676,0.547641235,0.556584464,0.565286405,0.573706624,0.581816877,0.58959029,0.597010794,0.604080618,0.610785129,0.617130857,0.623131484,0.628797631,0.634145631,0.639185921,0.643931713,0.648399782,0.652597703,0.656545106,0.660258007]
        self.graphWidget.plot(x, y)


def main():
    app = QtWidgets.QApplication(sys.argv)
    main = MainWindow()
    main.show()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()
```
### Expected behavior
The resulting plot should look as follows: (This plot was created using an external program)
![image](https://user-images.githubusercontent.com/46036952/129767313-74d73d7a-bac1-4664-bfd6-7944eac7076c.png)

### Real behavior
Using the exact same data, the pyqtgraph Y semi-log plot looks likes this:
![image](https://user-images.githubusercontent.com/46036952/129767460-668aa636-71d8-4bb2-8a77-b81c055320b9.png)

### Tested environment(s)

 * PyQtGraph version: 0.12.2 
 * Qt Python binding: 5.15.4
 * Python version: 3.9.6
 * NumPy version: 1.21.2
 * Operating system: Windows 10 Pro 21H1
 * Installation method: PyCharm Package Manager

**Comment by j9ac9k** [comment]
Hi @joaorsbarbosa 

thanks for opening the issue.  We have numerous issues w/ our log mode, I suspect your issue can be worked around by setting the log-mode _after_ plotting the lines; or in other words, move this line to the very end.

```python
self.graphWidget.setLogMode(False, True)
```

Recently we have been focused on more performance oriented changes/improvements, but the status of our log mode clearly needs some rework, and we're trying to evaluate what are good ways to try and tackle that.  At the crux of our problem is that Qt doesn't have non-linear transformations that we can easily call; so we need to figure out an efficient way of plotting data with these kinds of transformations.  If you have input/suggestions, we'd love to hear it :)

**Comment by joaorsbarbosa** [comment]
Hello @j9ac9k! 

Thank you for your swift reply!
I changed the setLogMode to the bottom of the code but it made no difference.
I also tried removing said line, and setting the Y axis to log manually, using the mouse on the created plot, but it made no difference as well.

I would love to make a suggestion but I'm new to Qt and to Python in general, so I don't think I am able to make a constructive suggestion yet. Sorry 😕

**Comment by joaorsbarbosa** [comment]
A "workaround" I might use in the meantime, is to use linear scale plots and do the logarithm of my Y data. 
I'll just have to mention that the Y axis is the order of magnitude instead.

**Comment by ksunden** [comment]
https://github.com/pyqtgraph/pyqtgraph/commit/aebc66dcaaad73a0c6948f81ab06697f3db632e4

This was reverted recently by #1940

And has been previously reported in #1933

**Comment by j9ac9k** [comment]
Wonder of we should do another patch release given this has come up a few times now.

**Comment by joaorsbarbosa** [comment]
That fixes it!
I changed my local PlotDataItem.py as mentioned in #1933 and the Log Y is now plotting correctly!

![image](https://user-images.githubusercontent.com/46036952/129774922-f6113c65-379c-4ce9-9362-24407a7b6fa1.png)

**Comment by ksunden** [comment]
Closing as fixed on master
