### ISSUE TITLE
Plot "average" menu option is broken

### ISSUE THREAD

**Issue by sbourdeauducq** [pyqtgraph/pyqtgraph#198]
See screenshot below.

![average_broken](https://cloud.githubusercontent.com/assets/720864/8874533/6c939dbe-3244-11e5-894f-af12eae1cd78.png)

**Comment by NilsNemitz** [comment]
I don't see the graphical bug in the screenshot, but I am wondering if the "Average" option should always be present in the menu. The submenu did not present any options for any of the examples, and selecting 'average' just duplicates one of the plots in a new color.

**Comment by j9ac9k** [comment]
> I don't see the graphical bug in the screenshot, but I am wondering if the "Average" option should always be present in the menu. The submenu did not present any options for any of the examples, and selecting 'average' just duplicates one of the plots in a new color.


Probably worthy of its own issue (I've always wished the context menu entries were a bit more editable in general).  I'm going to close this one out as we can't replicate, and a fix was likely implemented long ago (or an upstream issue was addressed).
