### ISSUE TITLE
How to use clickable feature with PlotDataItem?

### ISSUE THREAD

**Issue by Bio-Otto** [pyqtgraph/pyqtgraph#1980]
I am trying to click the PlotDataItem object but it's not working. Then I tried it with PlotCurveItem and it worked. But I need PlotDataItem because I need exporter features of pyqtgraph. Thanks in advance for your help.

**Comment by pijyoi** [comment]
According to the source code (as opposed to the documentation), you could either pass ```clickable=True``` to the ```PlotDataItem``` constructor, or call its method ```setCurveClickable(True)```.

**Comment by Bio-Otto** [comment]
Yes i see and checked it but not working

**Comment by pijyoi** [comment]
Could you provide a runnable sample of your code?

**Comment by pijyoi** [comment]
I took the following example and replaced ```PlotCurveItem``` with ```PlotDataItem```. Clicking works with either one.
https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/MouseSelection.py

**Comment by Bio-Otto** [comment]
Ahh i solved my problem. The problem is exactly what it says in the documentation that it can be installed via `conda-forge` with the `[conda install -c conda-forge pyqtgraph](https://pyqtgraph.readthedocs.io/en/latest/installation.html)` command. But it automatically installed the old version (`version 0.11`). Now I downloaded it directly from `github` and the problem was solved. Thank you so much for your help and precious time. But I still don't understand why `conda-forge` doesn't install the latest version directly.

**Comment by ixjlyons** [comment]
@Bio-Otto I would guess you have an older version of Qt/bindings in your environment --- pyqtgraph started explicitly requiring 5.12+ after 0.11.0 I think. If you run something like `conda install -c conda-forge pyqtgraph=0.12`, it might prompt you to upgrade qt and pyqt/pyside packages.
