### ISSUE TITLE
Log-Log Scale Y-Axis Shows Wrong Values

### ISSUE THREAD

**Issue by electronsandstuff** [pyqtgraph/pyqtgraph#1983]
### Short description
Hey folks!  Thanks for the great library.  I am having an issue with setting a plot to log-log mode using `setLogMode(True, True)`.  When I plot my data on a linear axis it shows up just fine.  However, when I add the the line to go to log-log mode the plot displays nonsense values on the y-axis.

Here is a screencap of the data plotted on a linear scale with the y-axis (a measurement in Amps) is on the scale of nA.
![Capture2](https://user-images.githubusercontent.com/61094787/132115522-86b1c501-3e8f-4532-9bd0-ad64f70f9f79.PNG)

When going to log-log mode, the data is now shown as TA instead and is shown as decreasing with increasing scan parameter.  It kind of looks like it is showing 1/y instead of y.
![Capture](https://user-images.githubusercontent.com/61094787/132115559-9666d684-625b-405e-9b1c-4188054993f2.PNG)

### Code to reproduce

```python
import sys
from PyQt5.QtWidgets import QMainWindow, QApplication
import pyqtgraph as pg
import numpy as np


class Example(QMainWindow):
    def __init__(self):
        super().__init__()

        self.sample_plot = pg.PlotWidget()
        self.scan_plot = pg.PlotWidget()
        self.setCentralWidget(self.scan_plot)

        self.setGeometry(300, 300, 300, 300)
        self.setWindowTitle('Buttons')
        self.show()
        self.statusBar().showMessage('Ready')

        x = np.linspace(0.1, 1.0)
        y = x**4 * 1e-9 + 1e-13
        self.scan_plot.clear()
        self.scan_plot.setLogMode(True, True)
        self.scan_plot.plot(x, y, symbol="x", pen=None)
        self.scan_plot.setLabel("left", "Current", units="A")
        self.scan_plot.setLabel("bottom", "Scan Parameter")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Example()
    sys.exit(app.exec_())
```

### Expected behavior
Data is displayed on a log-log scale.

### Real behavior
See attached screencap in description.

### Tested environment(s)

 * PyQtGraph version: 0.12.2
 * Qt Python binding: PyQt5 5.15.4 Qt 5.15.2
 * Python version: 3.9
 * NumPy version: 1.21.2
 * Operating system: Windows 10
 * Installation method: pip

**Comment by electronsandstuff** [comment]
Whelp... here's a riddle: I tried plotting 1/y as a quick workaround in my application.  However, it shows up as the same values.  Here I am plotting y and 1/y as exes and crosses (data is a slightly different because this is my production application, not an example for github, so don't mind that).  They show up at the same points:

![image](https://user-images.githubusercontent.com/61094787/132116114-8c6dac2d-ea5b-40d7-aa30-da30a3741978.png)

Example code:
```python
self.scan_plot.plot(x, y, symbol="x", pen=None)
self.scan_plot.plot(x, 1/y, symbol="+", pen=None)
```

**Comment by pijyoi** [comment]
Hello, thank you for your bug report. This issue was fixed in #1940.

**Comment by j9ac9k** [comment]
If #1940 is the fix, we should roll out a new patch release as I think this would be the 4th reported issue.  I'll get the ball rolling on that today.

**Comment by electronsandstuff** [comment]
Cool, thanks!  I'll take a look at updating my install.

**Comment by j9ac9k** [comment]
I an going to close this out as having been fixed.
