### ISSUE TITLE
Pyqtgraph internal error handling

### ISSUE THREAD

**Issue by Bio-Otto** [pyqtgraph/pyqtgraph#1989]
When I used PlotDataItem I get the following error. it's not an issue actually but I want to report it. Thank you so much.

> Traceback (most recent call last):
>   File "C:\Users\HIbrahim\anaconda3\envs\moldyn\lib\site-packages\pyqtgraph\graphicsItems\GraphicsObject.py", line 24, in itemChange
>     self.parentChanged()
>   File "C:\Users\HIbrahim\anaconda3\envs\moldyn\lib\site-packages\pyqtgraph\graphicsItems\GraphicsItem.py", line 471, in parentChanged
>     self._updateView()
>   File "C:\Users\HIbrahim\anaconda3\envs\moldyn\lib\site-packages\pyqtgraph\graphicsItems\GraphicsItem.py", line 527, in _updateView
>     self.viewRangeChanged()
>   File "C:\Users\HIbrahim\anaconda3\envs\moldyn\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 939, in viewRangeChanged
>     self.updateItems(styleUpdate=False)
>   File "C:\Users\HIbrahim\anaconda3\envs\moldyn\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 639, in updateItems
>     x,y = self.getData()
>   File "C:\Users\HIbrahim\anaconda3\envs\moldyn\lib\site-packages\pyqtgraph\graphicsItems\PlotDataItem.py", line 781, in getData
>     top_exc =-(self._drlLastClip[0]-view_range.bottom()) / view_height
> ZeroDivisionError: float division by zero

**Comment by j9ac9k** [comment]
Hi @Bio-Otto 

The issue template which you elected not to fill out is sort of crucial for us to look into this.  Without knowing more about the code to reproduce, what version of the library you're using and what dependencies you are using, attempting to reproduce can take significant time (and thus if we don't stumble across this issue ourselves, we are likely not going to go looking into it further).

I recognize filling that out takes time/effort on your end; but imagine the effort on maintainers end if we had never seen this behavior before just to try and reproduce.

Thanks

**Comment by Bio-Otto** [comment]
Thank you so much @NilsNemitz. The commit solved my problem.
