### ISSUE TITLE
Graphical Canvas documentation or example are missing 

### ISSUE THREAD

**Issue by daliagachc** [pyqtgraph/pyqtgraph#1993]
### Short description
documentation for Graphical Canvas is lacking 

### Code to reproduce
In a way i feel this is the problem. i cannot find the docs

**Comment by j9ac9k** [comment]
Hi @daliagachc 

The canvas stuff was worked on by @campagnola but I'm not sure if it was ever "finished".  It didn't end up getting much integration in the rest of the library, so it hasn't really had any attention.  I myself don't know much about it; and it's largely been kept within the library as it may have gotten some adoption we're unaware of.

If @campagnola come's around these parts, would love to hear more about what the Canvas stuff is supposed to do, and what it's missing from widespread adoption

**Comment by j9ac9k** [comment]
We have elected to remove the canvas stuff from the library, it is slated for removal now in ~September 2023.
