### ISSUE TITLE
levels argument is required for float input types

### ISSUE THREAD

**Issue by Grumium** [pyqtgraph/pyqtgraph#1994]
### Short description

fn.makeARGB() requires a levels argument why is not given. No backward compatibility.
In case of floats, if no levels argument is provided, the 'min,max' values should be determined automatically from the image.
In my case and image with integer values transitions to floats and raises the exception upon redrawing it.

> 
>     Exception: levels argument is required for float input types
>     Traceback (most recent call last):
>     File "C:\XXX\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 834, in paint
>     self.render()
>     File "C:\XXX\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 561, in render
>     fn.makeARGB(image, lut=lut, levels=levels, output=self._processingBuffer)
>     File "C:\XXX\lib\site-packages\pyqtgraph\functions.py", line 1401, in makeARGB
>     raise Exception('levels argument is required for float input types')

### Tested environment(s)

PyQtGraph version: 0.12.1 (works)
PyQtGraph version: 0.12.2 (fails)
Qt Python binding: PyQt5

**Comment by Grumium** [comment]
sorry, wrong repo

**Comment by pijyoi** [comment]
Hello, you say that you have an integer image but it transitions to float, so this might be related to #1984 which was fixed by #1985.
It would be helpful if you could provide a minimum example. Are you calling ```setLookupTable()``` with a float dtype lut?

**Comment by Grumium** [comment]
I can confirm that this is fixed by #1985 . Thanks!

**Comment by pijyoi** [comment]
If #1985 does fix your use-case, may I suggest that you change your code to ensure that your lookup tables are np.uint8? As it is now, your code would be taking the slow path.

Possible ways to get a colormap: https://github.com/pyqtgraph/pyqtgraph/pull/1985#issuecomment-914851149
