### ISSUE TITLE
Top Alignment not Respected in The Main Layer

### ISSUE THREAD

**Issue by MosGeo** [pyqtgraph/pyqtgraph#2016]
### Short description
When a pyqtgrpah object is inserted into a sub-layout (or a subwidget), it does not respect the alignment of the main layout. See the first image below.  If the pyqtgraph object is removed, the window shows the correct behavior (see second figure).

![image](https://user-images.githubusercontent.com/10503349/136893874-d497f336-4e31-460c-b422-4ca9f33b5465.png)
![image](https://user-images.githubusercontent.com/10503349/136894045-f0a8fcbd-4ac2-4b70-aaf1-93d121416270.png)

### Code to reproduce

After the window is displayed, vertically expand the window to see the issue.

```python
import sys
from PyQt5 import QtCore
from PyQt5.QtWidgets import QApplication, QBoxLayout, QLabel, QPushButton, QVBoxLayout, QWidget
import pyqtgraph as pg

app = QApplication(sys.argv)

main_widget = QWidget()
layout = QVBoxLayout()
layout.setAlignment(QtCore.Qt.AlignTop)
layout.addWidget(QLabel("I am the first label in the layout"))

sub_widget = QWidget()
graphics_widget = pg.GraphicsLayoutWidget()
extra     = QPushButton(text="I am a button inside the subwidget")
sublayout = QVBoxLayout()
sublayout.addWidget(graphics_widget) # comment this line to reproduce the second figure
sublayout.addWidget(extra)
sub_widget.setLayout(sublayout)
sub_widget.setMaximumHeight(200)

layout.addWidget(sub_widget)
layout.addWidget(QLabel("I am the last label in the layout"))

main_widget.setLayout(layout)
main_widget.show()
sys.exit(app.exec_())

```

### Expected behavior
All the controls are aligned to the top

### Real behavior
Controls are centered (stretched?)

### Tested environment(s)

 * PyQtGraph version:  0.12.3 
 * Qt Python binding:  PyQt5 5.15.4 Qt 5.15.2
 * Python version: Python 3.9.7 (64bit)
 * NumPy version: 1.21.2
 * Operating system: Windows 10 21H1
 * Installation method: pip

**Comment by MosGeo** [comment]
@NilsNemitz Thanks for testing it.

If you extend the window vertically manually (with the mouse), are the controls aligned to the top? (I should have mentioned this as a step to reproduce.

**Comment by MosGeo** [comment]
@NilsNemitz adding `layout.addStretch()` after the last label did the trick. Thanks so much!

Still, it is a strange behavior as `layout.addStretch()` is not needed unless the `GraphicsLayoutWidget` is added.

**Comment by NilsNemitz** [comment]
Well, the layout procedure of Qt is mysterious and unknowable. I would not be surprised if it has something to do with different default layout policies for labels and more expandable widgets. I think we would want to be very careful with changes to the layout properties at this point, otherwise we'll probably end up breaking a lot of carefully tweaked user code :)

Just out of curiosity, do you get the same behavior if you add a `QPlainTextEdit` widget instead of the 
`GraphicsLayoutWidget`? Should be a simple replacement, and that should have similar layout requirements: Needs a little more space than a label, and can make good use of any additional space.

**Comment by MosGeo** [comment]
You are absolutely right :) I am getting the same behavior with `QPlainTextEdit`. So, it is related to expandable widget behavior.

I am just starting at my Qt journey so this info is great!

As of now, you can close the issue as the workaround layout.addStretch is working.
