### ISSUE TITLE
SVGExporter: Background color

### ISSUE THREAD

**Issue by JensReimann** [pyqtgraph/pyqtgraph#2018]
SVGExporter generates an additional background tag of 100% width and height in generateSvg(). This tag uses rgba to define the color which seens not to be fully supported by the standard. I.e. inkscape won't recognize the color, causing it to appear black (BTW: the size is also not correct).

### Short description
Background color rectangle is incorrectly rendered.

### Code to reproduce
Call export from context menu and select SVG as output format. Press "Copy" button and insert SVG image to e.g. inkscape (tested with version 1.1). 

### Expected behavior
The background shall be filled by the selected color.

### Real behavior
The background rectangle will be black no matter what color was selected. The size is also wrong. 

### Tested environment(s)

 * PyQtGraph version: 0.12.3
 * Qt Python binding: PySide2 5.13.2 Qt 5.12.9
 * Python version: 3.8
 * NumPy version: 1.20.1
 * Operating system: Windows 10
 * Installation method: conda

### Additional context
Proposed solution: either use Qt SVGGenerator to generate the background rectangle or add an option to disable background export at all (no background rectangle to be generated).

**Comment by 3fon3fonov** [comment]
I confirm this. I got the same with programs like "inkscape" and "convert"....An user also confirm the bug using CorelDraw.

 However, I was able to make it work with "rsvg-convert"

I have a small bash script that converts from .svg to .pdf 

```
#!/bin/bash

for i in $@; do
  rsvg-convert -f pdf -o $(basename $i .svg).pdf $(basename $i .svg).svg
done
```

E.g.,



$ bash svg2pdf.sh test.svg


produces the attached file (pdf-->.png shown), which is 1:1 with the .svg

 
![test](https://user-images.githubusercontent.com/44244057/152871871-55f5f3d0-41d7-4077-b4e4-dd5a5e7eadb4.png)


However, notice that the top plot also exports the x-axis, whereas, the GraphicsScene should be:

![test_after_gimp](https://user-images.githubusercontent.com/44244057/152871887-631ebb75-b003-421e-9e1a-11656f40018b.png)

**Comment by j9ac9k** [comment]
Well, I got the background issue sorted out; but the height/width is proving to be really problematic!

**Comment by j9ac9k** [comment]
Ok, figured out the scaling issue...that one was a doozy, but the diff ended up being tiny.

@3fon3fonov I would encourage you to open a separate issue for any issues with the SVG you have.  Ideally with some code that I can replicate the issue you're having.

**Comment by 3fon3fonov** [comment]
Dear Ogi,

Many thanks! However, updating to the new pyqtgrapg leads to this:

Traceback (most recent call last):
  File "exostriker_gui.py", line 2, in <module>
    import exostriker
  File "/home/trifonov/exostriker/exostriker/__init__.py", line 1, in
<module>
    from exostriker import gui
  File "/home/trifonov/exostriker/exostriker/gui.py", line 51, in <module>
    import pyqtgraph as pg
  File "/home/trifonov/exostriker/exostriker/lib/pyqtgraph/__init__.py",
line 205, in <module>
    from .graphicsItems.AxisItem import *
  File
"/home/trifonov/exostriker/exostriker/lib/pyqtgraph/graphicsItems/AxisItem.py",
line 11, in <module>
    from .GraphicsWidget import GraphicsWidget
  File
"/home/trifonov/exostriker/exostriker/lib/pyqtgraph/graphicsItems/GraphicsWidget.py",
line 2, in <module>
    from .GraphicsItem import GraphicsItem
  File
"/home/trifonov/exostriker/exostriker/lib/pyqtgraph/graphicsItems/GraphicsItem.py",
line 40, in <module>
    class GraphicsItem(object):
  File
"/home/trifonov/exostriker/exostriker/lib/pyqtgraph/graphicsItems/GraphicsItem.py",
line 613, in GraphicsItem
    nodes: dict[str, Element]
TypeError: 'type' object is not subscriptable



I am on Python3.8 & PyQt5==5.15.4

I cannot even open the exostriker.

Again, many thanks for looking at the SVG exporter!

**Comment by j9ac9k** [comment]
PyQtGraph follows NEP-29 when it comes to deprecating support for Python and NumPy versions. We actually kept Python 3.8 super a few months after the date to remove it.

There are other PRs in the queue that will further break 3.8 support, so that ship has sailed.
