### ISSUE TITLE
Bug introduced in setState in version 0.11.x, 0.12.3 (but it's working on 0.12.0!)

### ISSUE THREAD

**Issue by JeanBilheux** [pyqtgraph/pyqtgraph#2029]
### Short description
Prior to version of pyqtgraph 0.11.x, I heavily used the **setState** property in order to be able to keep the pan and zoom settings the user defined. For example, some of my application have the imageView on top and a slider at the bottom. The user click on the slider to display a different image. But if he pan or zoom into the image, switching to another image keeps the pan and zoom settings. Other applications I wrote modified the image and refresh it, still keeping the pan and zoom settings as shown in this animation. 

![without_issue](https://user-images.githubusercontent.com/1138324/137905140-dbbeeb5a-13a1-430e-8be6-bddbe81fe263.gif)

But if I'm using pyqtgraph 0.11.x or later, the view auto-reset. and a single action on the mouse (little pan, little zooming) correctly reset the image view to the range previously defined. 

![withIssue](https://user-images.githubusercontent.com/1138324/137906205-84130e9e-8f99-4d24-89ea-c48df6f3eb15.gif)

I tested the issue with various pyqtgraph version and came up with the following conclusion:
0.10.x -> it's working
0.11.0 -> not working
0.12.0 -> it's working
0.12.3 -> not working

### Code to reproduce

Here is some of the code that I use to record the image settings before plotting a new image, and then resetting the 
view according to the parameters saved

```python

[...]

 _view = self.parent.ui.image_view.getView()
 _view_box = _view.getViewBox()
 _state = _view_box.getState()

  self.parent.ui.image_view.setImage(_image)
  _view_box.setState(_state)

[...]

```

### Expected behavior
The new plot should have the same view state as the previous plot

### Real behavior
The new plot state is reset. 

```
An error occurred?
Post the full traceback inside these 'code fences'!
```

### Tested environment(s)

 * PyQtGraph version: tested with 0.10.x, 0.11.0, 0.12.0, 0.12.3
 * Qt Python binding: PyQt5 5.15.4 Qt 5.15.2
 * Python version:  3.7
 * NumPy version: 1.21.0
 * Operating system:  Mac OS, Linux
 * Installation method: Using conda environment for most librairies. Used pip for pyqtgraph.

**Comment by j9ac9k** [comment]
Hi @JeanBilheux 

Thanks for reporting, the gifs are 👍🏻 

It would be helpful to have a reproducible example (often one of the built-in examples can be useful here, to make a slight modification).  Once we have that, we can run `git bisect` and identify the commit that the breakage got re-introduced.  Alternatively, if you have pyqtgraph installed from the cloned repository in editable mode, you can run `git bisect` yourself, and test for which commit was good/bad against your own application.

It's also possible someone else may recognize the failure mode here more clearly and know what's wrong right away.

**Comment by j9ac9k** [comment]
@JeanBilheux can you clone the repository to your local machine; and use that version (not the one from pypi) within your application?

Assuming your application is part of a custom venv

```bash
source .venv/bin/activate # activate the virtual environment your application runs in
pip uninstall pyqtgraph
cd ~/
git clone https://github.com/pyqtgraph/pyqtgraph.git
cd pyqtgraph
pip install -e .
```

that will install pyqtgraph from the current commit on the `master` branch into the virtual environment your application runs.  From there make sure you're exhibiting the same behavior....

Since it's working in 0.12.1 but not working on 0.12.2, that's probably the easiest span of commits to browse between


```bash
git bisect start pyqtgraph-0.12.2 pyqtgraph-0.12.1
```

On each iteration, rerun your application and see if the issue appears or not, if it's working as intended then run `git bisect good` if not, then run `git bisect bad`.  Eventually you will zero in on the first commit that was "bad".
