### ISSUE TITLE
Text in 3D Graphics

### ISSUE THREAD

**Issue by lvdgraaff** [pyqtgraph/pyqtgraph#2037]
API change #1525 makes `GLViewWidget` inherit `QOpenGLWidget` instead of `QGLWidget`.
The `QOpenGLWidget` does not have text rendering capabilities.

In my application I make use of displaying text in a 3D Graphic: I use it to label some axis of a 3D plot. 
I did this, based on solution from [Stackoverflow](https://stackoverflow.com/questions/64600904/plot-text-in-3d-plot-that-does-not-scale-or-move), which provides a `GLTextItem` class.
Under the hood, this class relies on the `QGLWidget.renderText` method for drawing text.

* Are there any methods for rending text in the 3D Graphics?
* Would it make sense to have a GLTextItem in your 3D API, alongside the [current items](https://pyqtgraph.readthedocs.io/en/latest/3dgraphics/index.html)?

**Comment by Breviel** [comment]
Here is a way i got it to work for me. By defining a GLTextItem and then adding it to the plot.
If I have stepped out of my bounds with posting this example please feel free to delete it :)

        import numpy as np
        import pyqtgraph as pg
        import pyqtgraph.opengl as gl
        from PyQt5.QtCore import QRect
        from PyQt5.QtWidgets import QWidget, QHBoxLayout
        
        
        class plot(QWidget):
            def __init__(self, parent=None):
                QWidget.__init__(self, parent)

                self.setGeometry(0, 0, 1024, 768)
                self.LayOut = QHBoxLayout()
                self.setLayout(self.LayOut)
        
                self.Plotter = gl.GLViewWidget(self)
                self.Plotter.setGeometry(QRect(0, 30, 1024, 768))
                self.Plotter.opts['center'] = pg.Vector(3, 0, 0)
                self.Plotter.opts['distance'] = 10
                self.Plotter.opts['elevation'] = 40
                self.Plotter.opts['azimuth'] = 50
                self.LayOut.addWidget(self.Plotter)
        
                xdata = [(0, 0, 0), (5, 0, 0)]
                ydata = [(0, 0, 0), (0, 5, 0)]
                zdata = [(0, 0, 0), (0, 0, 5)]
        
                xplt = gl.GLLinePlotItem(pos=np.array([xdata]), color=pg.glColor(255, 140, 140, 200))
                yplt = gl.GLLinePlotItem(pos=np.array([ydata]), color=pg.glColor(140, 255, 140, 200))
                zplt = gl.GLLinePlotItem(pos=np.array([zdata]), color=pg.glColor(140, 140, 255, 200))
                gridItem = gl.GLGridItem(size=pg.Vector(10, 10, 0), antialias=True)
                textItem = gl.GLTextItem(pos=np.array([0, 0, 0]), text="Back", color='y')
        
                self.Plotter.addItem(xplt)
                self.Plotter.addItem(yplt)
                self.Plotter.addItem(zplt)
                self.Plotter.addItem(gridItem)
                self.Plotter.addItem(textItem)
                self.Plotter.show()

        if __name__ == "__main__":
            import sys
            from PyQt5.QtWidgets import QApplication
            app = QApplication(sys.argv)
            ui = plot()
            ui.show()
            app.exec_()
