### ISSUE TITLE
Plot does not do show constant values for value above 4.5e15 (roughly)

### ISSUE THREAD

**Issue by msmttchr** [pyqtgraph/pyqtgraph#2056]
### Short description
If you run the example attached, you will see a constant value curve, if you change the value of `constant `variable from `4.5e15` to `4.6e15`, constant value curve is no longer shown. Presumably this is true for any value >= 4.6e16.

### Code to reproduce

```python
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import pyqtgraph as pg

app = pg.mkQApp()
mw = QtGui.QMainWindow()
cw = QtGui.QWidget()
mw.setCentralWidget(cw)
l = QtGui.QVBoxLayout()
cw.setLayout(l)

pw = pg.PlotWidget(name='Plot1') 
l.addWidget(pw)

mw.show()

## Create an empty plot curve to be filled later, set its pen
p1 = pw.plot()

constant = 4.5e15 # From 4.6 onward, it fails, that is line is not shown
pw.plot(y=[constant,]*2, x=list(range(2)))

if __name__ == '__main__':
    pg.exec()

```

### Expected behavior

Curve is shown for `constant = 4.6e15`
### Real behavior

See short description. No error occurs, but curve is not shown. Auto range issue ?

### Tested environment(s)

 * PyQtGraph version: 0.12.2
 * Qt Python binding: 
 * Python version: PyQt5 5.15.4 Qt 5.15.2
 * NumPy version: 1.20.1
 * Operating system: Windows 10
 * Installation method: pip

**Comment by pijyoi** [comment]
The issue arises from here:
https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/ViewBox/ViewBox.py#L547-L552

When ```mn``` equals ```mx``` and is relatively very large, it is possible for ```mn - dy*0.5 == mx + dy*0.5```
