### ISSUE TITLE
Enhancement: allow string or colormap to be passed to ImageItem directly

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#2067]
I find matplotlib's ability to accept a string `cmap` to be extremely convenient during plotting, i.e. `plt.imshow(data, cmap='red')`. It would be fantastic to enable the same functionality with pyqtgraph's `pg.colormap`, i.e. `item.setImage(data, lut='viridis')` or `lut=pg.colormap.get('viridis')`.

The current workaround is `lut=pg.colormap.get('viridis').getLookupTable(nPts=X)`. The trick with a str lut is how to determine X (i.e. during autolevels, should nPts always be set to image range?), what should happen if the image has negative values, and probably a host of options I'm not even considering. But it would be quite convenient :slightly_smiling_face:

**Comment by NilsNemitz** [comment]
PR #2090 tries to address the inconvenience now, and should reduce the amount of code required to get a color map applied and illustrated by a color bar.

Unfortunately, I think your application may be unusual in that it wants to apply specific colors to specific image values.
Typically this is decoupled, and even interactively adjusted. So we always want the largest number of lookup table entries that doesn't come at a significant performance cost. This is either 256 of 512 throughout the code now.

If you really need to match the number of LUT elements to the data, it might be best to keep doing that in user space.
But please let me know if you see a way to make *that* more convenient.
