### ISSUE TITLE
LinearRegionItem loses mouse focus after being dragged if grid is enabled

### ISSUE THREAD

**Issue by agausmann** [pyqtgraph/pyqtgraph#2076]
When dragging a LinearRegionItem in a plot widget with gridlines enabled, the region item loses mouse focus immediately after being dragged.

If you attempt to click and drag the region item immediately after dropping it (without moving the mouse cursor), the viewport is panned instead.

If you move the cursor in between dropping and re-dragging, then the region item regains focus and dragging works as expected.

If gridlines are not enabled, then dragging works as expected.

### Code to reproduce

```python
import sys
import pyqtgraph
from PyQt5.QtWidgets import QApplication

app = QApplication(sys.argv)

plot = pyqtgraph.PlotWidget()
plot.getPlotItem().showGrid(True, True)

region_item = pyqtgraph.LinearRegionItem((0.5, 0.6))
plot.addItem(region_item, ignoreBounds=True)

plot.show()
app.exec_()
```

### Expected behavior

Clicking and dragging a LinearRegionItem immediately after dropping it should continue to move it.

### Actual behavior

When gridlines are enabled, dragging a LinearRegionItem immediately after dropping it does not move the item, it instead pans the viewport.

### Tested environment(s)

 * PyQtGraph version: **0.12.3**
 * Qt Python binding: **PyQt5 5.15.2**
 * Python version: **3.8.10**
 * NumPy version: **1.21.2**
 * Operating system: **Windows 10**
 * Installation method: **pip**

**Comment by j9ac9k** [comment]
We just merged a PR that fixed an issue very similar to this.  I just ran the minimum example and it seems to be working as expected.  Can you try using pyqtgraph from the master branch and confirm it's working for you?

**Comment by agausmann** [comment]
Yes, it seems to be fixed. Thanks

**Comment by j9ac9k** [comment]
Awesome, thanks for checking and reporting back.
