### ISSUE TITLE
Is PyQtGraph right for our project?

### ISSUE THREAD

**Issue by andrea-bistacchi** [pyqtgraph/pyqtgraph#2078]
Hello, we are developing a geological modelling application, based on many different libraries. The GUI is in Qt with multiple windows and in some of them we plot 2D maps combining vector graphics and raster images. 

At the moment we use the Matplotlib backend for this, but performance is becoming an issue as the size and number of objects we plot is increasing. We read that PyQtGraph should be faster and we are wondering if it could be the right solution for us.

The 2D plot units are map units, so we tend to have very large numbers as in UTM coordinates, and images must be georeferenced (shifted and scaled in their geographical position, not just in pixel coordinates).

Points in scatterplots should have custom symbols (e.g. STIX fonts) and should be rotated one by one according to an additional field.

We also need to capture coordinates with mouse, e.g. to draw new lines (and we understand you have tools for selection zoom and pan).

Finally, we need to turn objects on and off quickly, to add and remove them, and setting transparency for vectors and images would be a plus.

Thanks in advance for suggestions!

**Comment by sem-geologist** [comment]
why normal GIS applications does not work for you? You know QGIS has this possibility to get minimal app for custom applications using their canvas (with full geo data support). Also you can install Qgis in special conda environment, so you could get some conda-available libraries at versions you want. Pyqtgraph AFAIK and looked into it could not find any support to geographic data. While all your data would be guaranteed to come in same georeferencing system - that would be no problem, but visualising data with different geographic reference systems would require complete implementation of projection framework. (Albeit Qt itself has some affine transformation methods, but geographic systems and transformations inbetween are no more linear... I don't imagine implementing those in python/qt). Implementing `proj` into pyqtgraph in my opinion makes little sense while there are ready solutions like QGIS available.
