### ISSUE TITLE
Jupyter ROIExamples plot truncated when run on binder

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#2107]
### Short description

This issue is to document an unresolved anomaly. 
The ROIExamples.ipynb plot looks truncated when run on binder with QT_QPA_PLATFORM=offscreen.

### Code to reproduce

Go to the following link
https://mybinder.org/v2/gh/pyqtgraph/pyqtgraph/HEAD?labpath=pyqtgraph%2Fexamples%2Fnotebooks%2FROIExamples.ipynb
and then run the notebook. The plot will seem be truncated on the right.

### Expected behavior

Plot Should not be truncated.

### Real behavior

Plots are truncated.

![roi_truncated](https://user-images.githubusercontent.com/2657027/142130282-952ec020-cb96-4776-abf5-02da2da92eb7.png)

### Tested environment(s)

 * PyQtGraph version: master 
 * Qt Python binding: PyQt5 5.15 
 * Python version: 3.7 (binder)
 * NumPy version: latest from pip 
 * Operating system: Ubuntu 18.04 
 * Installation method: binder requirements.txt 

### Additional context

This could be reproduced on WSL2 Ubuntu 20.04 also using QT_QPA_PLATFORM=offscreen. The truncation appears on PyQt5, PySide2 but not on PyQt6, PySide6.

In https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/jupyter/GraphicsView.py, there is a line:
```self.gfxView.render(painter, self.gfxView.viewRect(), self.gfxView.rect())```.

```self.gfxView.rect()``` specifies the source rect. If I increase the size of that source rect, then more of the plot gets rendered. However the mouse coordinates will be wrong. It seems like internally the correct size of the plot has not been propagated. (Note that the unmodified value of self.gfxView.rect() is the correct size)

**Comment by pijyoi** [comment]
So I think the issue has to do with ```GraphicsLayout``` not being able to shrink items with text in them.
In the following script, the center plot is given as much space as is needed to fit the long title text.
```python
import numpy as np
import pyqtgraph as pg

text = "The quick brown fox jumps over the lazy dog"

pg.mkQApp()
glw = pg.GraphicsLayoutWidget(show=True)
p1 = glw.addPlot(y=np.arange(10))
p2 = glw.addPlot(y=np.arange(10), title=text)
p3 = glw.addPlot(y=np.arange(10))
pg.exec()
```

As for the supposed difference between Qt5 and Qt6, it seems to have to do with the different font size used. The larger font used in Qt5 (why?) makes the title text occupy more space. Hence, the plot truncation seen for Qt5 but not in Qt6.

WSL2 / PyQt5 offscreen
![wsl2_pyqt5](https://user-images.githubusercontent.com/2657027/142204295-504bfc05-43ea-4779-a3a1-a03b162cacbb.png)

WSL2 / PyQt6 offscreen
![wsl2_pyqt6](https://user-images.githubusercontent.com/2657027/142204314-bcc3e064-9445-45c6-bb0d-da5d8c486810.png)

binder / PyQt5 offscreen / all text removed
With all the text removed, nothing gets truncated.
![binder_notext](https://user-images.githubusercontent.com/2657027/142205775-f35e9b94-7a34-4772-9905-b35257d7111b.png)

**Comment by j9ac9k** [comment]
Nice find @pijyoi 

I suspect the easiest (maybe even best?) thing to do is to wait until binder offers a 20.04 image and migrate to that (as well as to Qt6) when it's available?

**Comment by pijyoi** [comment]
The thing is that the truncated plot is only a symptom of some other differences between Qt5 and Qt6 that we have been ignoring. Now that I know what to look for, it's clear that different fonts are being used. Very obvious for the capital letter "I".

PyQt5 desktop
![pyqt5_font](https://user-images.githubusercontent.com/2657027/142317196-9c19a64c-7af8-4113-bcb3-e823528a58b8.png)

PyQt6 desktop
![pyqt6_font](https://user-images.githubusercontent.com/2657027/142317247-00b46ee1-34fb-4e12-9755-4314b3308bc2.png)
