### ISSUE TITLE
Support for time_ns()

### ISSUE THREAD

**Issue by servaenergy** [pyqtgraph/pyqtgraph#2119]
### Short description
I have data timestamped with 500 nanosecond precision using `time.time_ns()`. When plotting these with `pyqtgraph` the timestamps get converted from `int64` to `float64` which seems to introduce errors due to floating point unable to represent the timestamp accurately.

I had partial success by creating own subclass of `AxisItem` and overriding its `tickStrings` method, however this only works well when timestamps start from zero. If I use actual data from `time.time_ns()` the timestamp gets represented as ~1.6377e+18 float with inaccuracies at sub-millisecond level.

### Code to reproduce
```python
import time

import numpy as np
import pyqtgraph as pg
from PySide6.QtWidgets import QApplication
from pyqtgraph import AxisItem

app = QApplication()


def make_data(start):
    length = 30
    timestamps = [start + i * 500 for i in range(length)]  # samples equally spaced 500 ns apart
    data = [0] * length
    return np.array(list(zip(timestamps, data)))

class MyAxisItem(AxisItem):
    def tickStrings(self, values, scale, spacing):
        strings = []
        for v in values:
            vs = v * scale
            strings.append(f"{vs:,.0f} ns")
        return strings


win = pg.GraphicsLayoutWidget()

item = win.addPlot(row=0, col=0)
item.setTitle("(CORRECT) Starting with 0, equally spaced samples")
item.setAxisItems({'bottom': MyAxisItem(orientation='bottom')})
line = item.plot(make_data(start=0))
line.setSymbol('o')

item = win.addPlot(row=1, col=0)
item.setTitle("(INCORRECT) Starting with current time, representation errors, samples not equally spaced")
item.setAxisItems({'bottom': MyAxisItem(orientation='bottom')})
line = item.plot(make_data(start=time.time_ns()))
line.setSymbol('o')

win.show()

app.exec()

```

### Expected behavior
I would love to be able to use `DateAxisItem` class with `time.time_ns()` so that I can zoom out and get nicely formatted dates. At the same time I NEED to be able to zoom down to at least microsecond level and have scatter-plot items positioned equidistantly as specified by input data.

### Real behavior
The `DateAxisItem` class currently only supports `time.time()` which doesn't have enough resolution and accuracy for my data. The `AxisItem` can be subclassed as a work-around, but the values for current time in nanoseconds from epoch are too big and get converted to floating point data type and similar inaccuracy results.

### Tested environment(s)

 * PyQtGraph version: `0.12.3`
 * Qt Python binding: `PySide6 6.2.1 Qt 6.2.1`
 * Python version: `3.9`
 * NumPy version: `1.21.3`
 * Operating system: `Linux fes 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 * Installation method: `venv` in PyCharm 2021.2.3 (Community Edition)

**Comment by pijyoi** [comment]
How about something like the following?
```python
import time

import numpy as np
import pyqtgraph as pg
from pyqtgraph import AxisItem

pg.mkQApp()


def make_data(start):
    length = 30
    timestamps = [start + i * 500 for i in range(length)]  # samples equally spaced 500 ns apart
    data = [0] * length
    return np.array(list(zip(timestamps, data)))

class MyAxisItem(AxisItem):
    def __init__(self, offset=0, **kwds):
        self.myoffset = offset
        super().__init__(**kwds)

    def tickStrings(self, values, scale, spacing):
        strings = []
        for v in values:
            vs = int(v * scale) + self.myoffset
            strings.append(f"{vs} ns")
        return strings


win = pg.GraphicsLayoutWidget()

item = win.addPlot(row=0, col=0)
item.setTitle("(CORRECT) Starting with 0, equally spaced samples")
item.setAxisItems({'bottom': MyAxisItem(offset=0, orientation='bottom')})
item.setMouseEnabled(x=True, y=False)
line = item.plot(make_data(start=0))
line.setSymbol('o')

offset = time.time_ns()
item = win.addPlot(row=1, col=0)
item.setTitle("(INCORRECT) Starting with current time, representation errors, samples not equally spaced")
item.setAxisItems({'bottom': MyAxisItem(offset=offset, orientation='bottom')})
item.setMouseEnabled(x=True, y=False)
line = item.plot(make_data(start=0))
line.setSymbol('o')

win.show()

pg.exec()
```

**Comment by servaenergy** [comment]
Thank you, workaround like that sounds reasonable for my use case.
