### ISSUE TITLE
TypeError: native Qt signal is not callable exception with PySide6 6.2.2

### ISSUE THREAD

**Issue by servaenergy** [pyqtgraph/pyqtgraph#2136]
### Short description
When adding a plot to ```GraphicsLayoutWidget``` and manipulating plots ```TypeError```exceptions are being raised.

The issue has emerged with upgrade of PySide6 to version 6.2.2. With 6.2.1 the example below works without any problems.

### Code to reproduce

```python
import pyqtgraph as pg
from PySide6.QtWidgets import QApplication

app = QApplication()
win = pg.GraphicsLayoutWidget()
item = win.addPlot(row=0, col=0)
win.show()
app.exec()
```

### Expected behavior
Work without issues as it does with PySide6 6.2.1 

### Real behavior
Non-fatal exceptions and tracebacks are produced, slowing the application execution down. Additionally I experience some weird plot data corruption when zooming in/out.

```
Traceback (most recent call last):
  File "/home/stan/Downloads/venv/lib/python3.9/site-packages/pyqtgraph/graphicsItems/GraphicsObject.py", line 24, in itemChange
    self.parentChanged()
TypeError: native Qt signal is not callable

```

### Tested environment(s)

 * PyQtGraph version: ```0.12.3```
 * Qt Python binding: ```PySide6 6.2.2 Qt 6.2.2```
 * Python version: ```3.9```
 * NumPy version: ```1.21.4```
 * Operating system:  Ubuntu 21.10, Archlinux
 * Installation method: PyCharm ```venv```

**Comment by j9ac9k** [comment]
Hi @servaenergy, thanks for the bug-report; This was fixed in #2132 already 👍🏻
