### ISSUE TITLE
Creation of human walking animation using 4x4 homogeneous matrix. (Need help!!!)

### ISSUE THREAD

**Issue by Ganesh1009** [pyqtgraph/pyqtgraph#2159]
**Goal:** To create an animation simulating human walking in 3D.

**Available data:** 

1. I have lower body segments ( Pelvis, Left/Right Upper leg, Left/Right Lower leg, Left/Right foot ) and their corresponding position and orientation vectors.
2. The position and orientation and placed in a 4x4 homogeneous matrix for 6 minutes. 

With the available data, I want to create a lower body skeleton ( stick figure ) with seven segments mentioned above apply the homogeneous matrix to the segments which act like animation data for the segments.

Currently, I have created a basic window that has a 3D grid and an origin as below:

```
class Visualizer :

	def __init__ ( self ) :
		self.app = QtGui.QApplication ( [ ] )
		self.view = gl.GLViewWidget ( )
		self.view.setGeometry ( 110 , 110 , 1200 , 700 )
		self.view.show ( )

		grid = gl.GLGridItem ( )
		grid.scale ( 0.5 , 0.5 , 0.5 )
		self.view.addItem ( grid )

		self.origin = gl.GLAxisItem ( )
		self.view.addItem ( self.origin )

	def start ( self ) :
		self.app.instance ( ).exec_ ( )

	def update ( self ) :
		pass

	def animation ( self ) :
		timer = QtCore.QTimer ( )
		timer.timeout.connect ( self.update )
		timer.start ( 30 )
		self.start ( )
```

Requesting help as I am very new to this PyQtGraph/animation world.

**Comment by j9ac9k** [comment]
Hi @Ganesh1009 

This kind of help is something well outside of the sort of thing we can do with the issue tracker.  We do have one example with an animation here: https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/examples/Arrow.py  I can see over time us adding more examples, but us maintainers are not well equipped to provide this level of support, sorry!
