### ISSUE TITLE
console colors do not play well with dark color themes

### ISSUE THREAD

**Issue by sbourdeauducq** [pyqtgraph/pyqtgraph#216]
![consolebug](https://cloud.githubusercontent.com/assets/720864/9288279/1de87034-4371-11e5-8743-acf8b886e2be.png)

**Comment by 2xB** [comment]
This should be fixed by https://github.com/pyqtgraph/pyqtgraph/commit/a15057835a78aedcb33e544cf2a94268bd048cf5 . Please check this using the latest pyqtgraph version! Also: Thanks for the report!

**Comment by j9ac9k** [comment]
Since already fixed and we can't reproduce, I'm going to close this, if you can still replicate this go ahead and let us know.
