### ISSUE TITLE
PlotDataItem.setData() raises generic Exception instead of TypeError.

### ISSUE THREAD

**Issue by mjablons1** [pyqtgraph/pyqtgraph#2167]
When using setData() method in the context of a try: except statement (plenty possible application since that's the low level way of redrawing fast) one has to resort to a generic Exception catch which looks nooby and can lead to undetected bugs (just what happened to me). setData() should probably be raising more specific exception types, judging by the Exception messages in place these should probably both be TypeErrors.

### Short description
PlotDataItem.setData() raises generic Exception instead of TypeError.

### Code to reproduce 1
```
import pyqtgraph as pg
plotWidget = pg.plot()
plot_data_item = plotWidget.plot()
plot_data_item.setData(None)
```

### Expected behavior
```
TypeError: Invalid data type <class 'NoneType'>
```

### Real behavior
```
Exception: Invalid data type <class 'NoneType'>
```

### Code to reproduce 2
```
import pyqtgraph as pg
plotWidget = pg.plot()
plot_data_item = plotWidget.plot()
plot_data_item.setData(None,None)
```

### Expected behavior
```
TypeError: When passing two unnamed arguments, both must be a list or array of values. (got <class 'NoneType'>, <class 'NoneType'>)
```

### Real behavior
```
Exception: When passing two unnamed arguments, both must be a list or array of values. (got <class 'NoneType'>, <class 'NoneType'>)
```

### Tested environment(s)
  - python=3.7.6=cpython_h60c2a47_6
  - pyqtgraph=0.11.0=pyh9f0ad1d_0 (this is certainly not the latest but the raise Except statements are there in master still)

PS: There is another 'raise Exception' in PlotDataItem.py relating to wrong dimensioning on numpy arrays. Here some specific class ArrayDimensionError(Exception) could be created or perhaps numpy readily implements some applicable exception type.

**Comment by Nibba2018** [comment]
Hello @mjablons1 and @j9ac9k , I would like to work on this issue if no one else is already assigned to it.

**Comment by j9ac9k** [comment]
@Nibba2018 please have at it!
