### ISSUE TITLE
Scatter plots are very slow

### ISSUE THREAD

**Issue by astrofrog** [pyqtgraph/pyqtgraph#217]
I am impressed by how fast PyQtGraph is for line plots, and was surprised to see that for scatter plots, the performance is no better than (and in some cases worse than) matplotlib. For example, the following example runs around 1 fps when dragging/panning:

```python
import pyqtgraph as pg
import numpy as np

N = 1e5
x = np.arange(N)
y = np.random.normal(0, 1, N)

plotWidget = pg.plot(title="Three plot curves")
plotWidget.plot(x, y, pen=None, symbol='o')
```

Is there a way to speed this up? I was hoping to be able to use PyQtGraph as an alternative to Matplotlib for scatter plots with 1e6-1e7 points, but at the moment this doesn't seem possible.

I am running this with Python 3.4 on MacOS X, and have the latest developer version of PyQtGraph at the time of writing.

**Comment by astrofrog** [comment]
Does anyone have any suggestions on speeding up scatter plots?

**Comment by kernc** [comment]
While at it, how's Matplotlib for you in comparison?

**Comment by campagnola** [comment]
Agreed, scatter plot performance drops off at about 10k samples. The only solution I know for this at the moment is to use OpenGL--you can easily plot millions of points on the GPU. If you've got time, try playing with PyQt and see if there is any way to get faster updates.

VisPy might be better in your case, although you may find it is not yet mature enough.

**Comment by astrofrog** [comment]
@campagnola - thanks, I will try out VisPy, but was just curious to first check that this was expected (which you answered). Feel free to close this issue!

**Comment by LucaMarconato** [comment]
I am having the same problem. I am plotting 300K points and the pan and zoom performance of the ViewBox is very slow. @campagnola is OpenGL supported now? I would prefer not to switch to VisPy or other libraries if possible. Thank you.
