### ISSUE TITLE
No module named 'pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt5' while executing exe

### ISSUE THREAD

**Issue by mnwato** [pyqtgraph/pyqtgraph#2179]
`
 No module named 'pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt5'
`

Facing with this error while executing exe file which is created via pyinstaller module.

- python -version: 3.8
- pyqtgraph -version: 0.12.3
- pyinstaller -version: 4.2

**Comment by j9ac9k** [comment]
Hi @mnwato 

This is a known issue, the problem is that the freezing portion of pyinstaller doesn't recognize those modules as needing to be imported.  Here is a comment not long ago for the same issue: 

https://github.com/pyqtgraph/pyqtgraph/issues/1981#issuecomment-912031468

tl;dr you need to tell pyinstaller to grab a handful of files explicitely in the `.spec` file.

If you are familiar with pyinstaller hooks, we would greatly appreciate a PR to https://github.com/pyinstaller/pyinstaller-hooks-contrib specifying the supplemental files needed.

**Comment by agausmann** [comment]
Was having the same issue, but the most recent PyInstaller 4.8 release is working for me.

**Comment by mnwato** [comment]
Hi @j9ac9k

Thanks. I tried to make exe with `--paths=pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyside2` but it still stuck on the following error.

Here is `.spec` file:
```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['NobitexMarketWatch_noToken.py'],
             pathex=['C:/Users/mostafa/AppData/Local/Programs/Python/Python310/Lib/site-packages/pyqtgraph/graphicsItems/ViewBox/axisCtrlTemplate_pyside2.py'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [],
          name='NobitexMarketWatch_noToken',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )

```

Am I missing something?

**Comment by mnwato** [comment]
@agausmann I used to upgrade PyInstaller from 4.2 to 4.8 but nothing happened.
What is your installed python version?

**Comment by mnwato** [comment]
Although editting `.spec` file did not work for me. but I solved these No module errors with importing these files into my python code.
The problem is that, although `.exe` file run correctly, but part of program which contains plots does not display any plots.

**Comment by mnwato** [comment]
Finally I solved this issue by reinstall PyInstaller==4.8.
Thanks to everyone.

**Comment by tiantian1645** [comment]
--hidden-import pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt5 \
    --hidden-import pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyqt5 \
    --hidden-import pyqtgraph.imageview.ImageViewTemplate_pyqt5

**Comment by xuhuasheng** [comment]
I upgraded pyqtgraph==0.13.1 and solved this problem
env:
 - python==3.8.13
 - pyinstaller==5.2
 - pyqtgraph==0.13.1
 - PyQt5==5.15.4
