### ISSUE TITLE
Can infiniteline change the linetype to a dotted line?

### ISSUE THREAD

**Issue by lyl1836** [pyqtgraph/pyqtgraph#2195]
Hi：

Can infiniteline change the linetype to a dotted line?

thank you!

**Comment by ixjlyons** [comment]
This can be done by specifying the [`pen`](https://doc.qt.io/qt-5/qpen.html) used, either in constructing the `InfiniteLine` or calling [`setPen`](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/infiniteline.html#pyqtgraph.InfiniteLine.setPen).

Note also that [`mkPen`](https://pyqtgraph.readthedocs.io/en/latest/functions.html#pyqtgraph.mkPen) does offer a `dash` argument that internally uses [`QPen.setDashPattern`](https://doc.qt.io/qt-5/qpen.html#setDashPattern).

So one way to do this:

```python
import pyqtgraph as pg

p = pg.plot()
p.addItem(pg.InfiniteLine(pen=pg.mkPen((0, 0, 255), dash=[2, 4])))
app.exec()
```

**Comment by j9ac9k** [comment]
I'm going to close this issue as @ixjlyons answered it.
