### ISSUE TITLE
Visual glitches with thick line(>1) on version 0.12.4

### ISSUE THREAD

**Issue by temeddix** [pyqtgraph/pyqtgraph#2213]
### Short description
When setting line width thicker than 1, zooming in causes some line to fill up a large area
https://user-images.githubusercontent.com/66480156/156883464-b96a4b43-101e-46aa-afed-2ff300aae082.mp4

### Code to reproduce
That light green line was created this way
```python
import pyqtgraph as pyqtgraph
plot_item = pyqtgraph.PlotItem()
line = plot_item.plot(
    pen=pyqtgraph.mkPen("#E2F200", width=2.5),
    connect="finite",
),
```

### Expected behavior
Zooming in normally

### Real behavior
Light green line fills up a large space. No error occured.

### Tested environment(s)
 * PyQtGraph version: 0.12.4
 * Qt Python binding: Pyside6 6.2.3 Qt 6.2.3
 * Python version: 3.10.2
 * NumPy version: 1.22.2
 * Operating system:  Windows 11
 * Installation method: pip

### Additional context
None

**Comment by j9ac9k** [comment]
Hi @temeddix 

I'm having trouble reproducing.  Could you perhaps modify one of the existing examples to get the problematic behavior?

Here is the MWE I just developed, but zoom behavior was working as intended for me.

```python
import pyqtgraph as pg
import numpy as np

pg.mkQApp()

win = pg.GraphicsLayoutWidget(show=True, title="Basic plotting examples")
win.resize(1000,600)
win.setWindowTitle('pyqtgraph example: Plotting')

# Enable antialiasing for prettier plots
# pg.setConfigOptions(antialias=True)

p1 = win.addPlot(title="Basic array plotting", y=np.random.normal(size=100), pen=pg.mkPen("#E2F200", width=2.5), connect="finite")
pg.exec()
```

**Comment by temeddix** [comment]
I'm trying to reproduce on a more simple code but honestly it's not easy. There are many factors driving the graph of the app and I think it may take some time to find out the cause of this.

Here's the code I've been testing, just to tell the attempts I've been through.
```python
import pyqtgraph as pg
import numpy as np
import random

pg.mkQApp()

win = pg.GraphicsLayoutWidget(show=True, title="Basic plotting examples")
win.resize(1000, 600)
win.setWindowTitle("pyqtgraph example: Plotting")

# Enable antialiasing for prettier plots
# pg.setConfigOptions(antialias=True)

p1 = win.addPlot(
    title="Basic array plotting",
    x=np.arange(0, 100, 0.1),
    y=np.random.normal(size=1000),
    pen=pg.mkPen("#E2F200", width=2.5),
    connect="finite",
)
p1.setDownsampling(auto=True, mode="subsample")
p1.setClipToView(True)
p1.setAutoVisible(y=True)
p1.showGrid(x=True, y=True, alpha=0.1)
p1.enableAutoRange(y=True)
for _ in range(40):
    p1.plot(
        x=[-50, 150],
        y=[random.randint(-8, 8), random.randint(-8, 8)],
        pen=pg.mkPen("#0082FF", width=2.5),
        connect="finite",
    )
pg.exec()
```

**Comment by j9ac9k** [comment]
I get the difficulty of making small reproducible issues.  Starting from one of the examples we ship with I've found to generally be helpful.

If you are comfortable editing the pyqtgraph source code, you could try some other steps for debugging.

Modify this method to return `False`, you'll take a major performance penalty but see if you can replicate the issue

https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/PlotCurveItem.py#L627-L637

**Comment by temeddix** [comment]
Okay, thanks!

**Comment by j9ac9k** [comment]
Hi @temeddix I'm curious if you got to the bottom of this issue.

**Comment by temeddix** [comment]
Sorry, I didn't got the reason yet and using it with linewidth 1 because of personal lack of time

**Comment by j9ac9k** [comment]
Hi @temeddix 

I'm going to close out this issue as we can't reproduce it, but if you can provide an example that can show the issue I'll gladly reopen it.  Thanks!
