### ISSUE TITLE
Problem when setting the viewbox background color

### ISSUE THREAD

**Issue by lesauxvi** [pyqtgraph/pyqtgraph#223]
When I use the setBackgroundColor method from the ViewBox class, the axis and grid are hidden behing the background. To force them to come in front of the background, I use the setZValue method for the four axisItem and the problem is solved from a visual point of view. However, when doing that, I can't use my mouse to change the x or yrange (depending on the order I use to upper the level of the axis and grid) of the top and bottom  (or left and right) axis with a drag action. Here is an example highlighting the problem. The problem does not seem to be platform dependant (tried it on Win7 and Archlinux) using python 2/3 and PyQt4/PyQt5...

# -*- coding: utf-8 -*-
import pyqtgraph as pg
from PyQt4 import QtGui

class TestWidget(pg.PlotWidget):

    def __init__(self, parent=None, background="default", name=None,
                 labels=None, title=None, viewBox=None, axisItems=None,
                 enableMenu=True, image=None, **kargs):

        pg.PlotWidget.__init__(self, parent, background=background,
                               enableMenu=False,
                               **kargs)
        self.getViewBox().setBackgroundColor((255, 255, 255, 255))
        self.plotItem.showGrid(x=True, y=True)
        top = self.plotItem.getAxis("top")
        bottom = self.plotItem.getAxis("bottom")
        left = self.plotItem.getAxis("left")
        right = self.plotItem.getAxis("right")
        top.setZValue(0)
        bottom.setZValue(0)
        left.setZValue(0)
        right.setZValue(0)

        self.data = pg.PlotDataItem(pen=(0, 114, 189), antialias=True)
        self.data.setData([1, 2, 3], [1, 3, 2])
        self.addItem(self.data)

if __name__ == '__main__':
    import sys
    app = QtGui.QApplication(sys.argv)
    main = TestWidget()
    main.show()
    sys.exit(app.exec_())

**Comment by lesauxvi** [comment]
Issue closed. With a recent pyqtgraph development version, the problem has gone.

**Comment by jorgeja** [comment]
I have almost this exact problem in pyqtgraph: '0.11.0.dev0+g2e69b9c'

After doing 'functionally' the same as OP (extracting the axis and changing their z-values after setting vb background colour) I have a visually good result, but mouse-interaction is borked.. Depending on the sequence of setting the axis z-values I get either full x-axis control or y-axis control inside the viewbox. i can still control both axis' axis-scaling by interacting (moving the mouse over the axis) with the axis, but not inside the viewbox.
