### ISSUE TITLE
0.12.4 regression of GL transformation

### ISSUE THREAD

**Issue by cwiede** [pyqtgraph/pyqtgraph#2230]
### Short description
I'm drawing an image in a 3D view with a specific transformation and I realize there are differences between 0.12.3 and 0.12.4. The image is appearing flipped compared to 0.12.3.

### Additional context
EDIT: When the changes from https://github.com/pyqtgraph/pyqtgraph/commit/36b2e49cd3b0ba38a2169e8cb3b2d2d7c8b5e619 are reverted, the image is displayed in its original pose. So I guess there is an issue with this commit.

**Comment by pijyoi** [comment]
Hello, thank you for the report. The commit in question was part of #2131 and there was a script included https://github.com/pyqtgraph/pyqtgraph/pull/2131#issue-1071166647 used for verifying that the "fix" had not changed the pose.

Running the script in both 0.12.3 and 0.12.4 seems to show the same pose, so I would say that there's something missing about my reasoning there.

Is your image data row-major or column-major? (The test script uses a row-major image)
By "flipped", do you mean a transpose or a left-right flip?
Would it be possible for you to provide an MWE?

**Comment by cwiede** [comment]
The relevant code snippet is

```python
        T = np.array([
            [0          , (y0-y1)/w,0 ,y1],
            [(x0 - x1)/h, 0        ,0 ,x1],
            [0          , 0        ,0 ,z ],
            [0          , 0        ,0 ,1 ],
        ])
        logger.info("T=%s", T)
        t = Transform3D(*T.flatten())
        self.resetTransform()
        self.applyTransform(t, True)
        self.setData(rgba)
        self.setVisible(True)
```
where 

```
    T = [[ 0.          0.05        0.         -5.00000007]
           [ 0.05        0.          0.         -5.00000007]
           [ 0.          0.          0.         -0.01      ]
           [ 0.          0.          0.          1.        ]]
```
RGBA has the following properties:

```
rgba.shape=(200, 200, 4)
rgba.flags=  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

Results of 0.12.3 (the image is the black white projection of the point cloud to the floor, the point cloud is also displayed in color coding for reference; i have asserted that only the version of pyqtgraph has changed, everything else is exactly same)
![grafik](https://user-images.githubusercontent.com/62332054/158769195-c60bc5f3-22f9-4040-a09f-e2e1e0e0c362.png)

Results of 0.12.4
![grafik](https://user-images.githubusercontent.com/62332054/158769464-ff8c995f-8f8d-414d-b6f6-d6ff018fa797.png)

**Comment by pijyoi** [comment]
Thank you for the code snippet showing the use of `Transform3D`. It shows a gap in our testing, because none of the included OpenGL examples makes use of it.
Would you be able to help test that #2232 fixes this issue?

**Comment by cwiede** [comment]
yes that pull request fixes the issue

**Comment by j9ac9k** [comment]
Going to re-open so I can have the PR close this issue on merge 👍🏻 

Thank you @cwiede for reporting and testing the fix.  Thank you @pijyoi for making the fix so quickly.
