### ISSUE TITLE
Application exit on right click

### ISSUE THREAD

**Issue by Cosmicoppai** [pyqtgraph/pyqtgraph#2233]
Application exits when right clicked on node label

### Code to reproduce

```python
from PyQt5 import QtWidgets as Qtw
from pyqtgraph.flowchart import Flowchart


class MainWindow(Qtw.QWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        layout = Qtw.QGridLayout()

        # Create flowchart, define input/output terminals
        fc = Flowchart(terminals={
            'Input': {'io': 'in'},
            'Output': {'io': 'out'},
        })

        layout.addWidget(fc.widget())
        self.setLayout(layout)
        self.show()


if __name__ == '__main__':
    import sys
    app = Qtw.QApplication(sys.argv)
    w = MainWindow(windowTitle="create FlowChart")
    sys.exit(app.exec_())
```

### Expected behavior
Application should be continue running

### Real behavior
Application exits

 ### Tested environment(s)

 * PyQtGraph version: 0.12.3
 * Qt Python binding:  PyQt5
 * Python version:  3.10
 * Operating system: Windows 10
 * Installation method: pip

**Comment by Cosmicoppai** [comment]
Made the pull request : https://github.com/pyqtgraph/pyqtgraph/pull/2236

**Comment by j9ac9k** [comment]
Hi @Cosmicoppai 

Sorry nobody followed up with you on this issue; I really need to be better about managing the issue tracker.  

Thanks for the PR, the FlowChart module is not something I interact with very much, and generally doesn't get a lot of attention from the current maintainers.  I'd love to hear about your use-case for it.

I'll mege your PR shortly, thanks for the contribution!
