### ISSUE TITLE
Please update the version of PyQtGraph in Pypi to one that includes Qt5 support!

### ISSUE THREAD

**Issue by fake-name** [pyqtgraph/pyqtgraph#225]
The current version of PyQtGraph in PyPi is sufficently out-of-date that it doesn't support Qt5 at all.

Could you folks pack up a more recent release, so my build scripts don't have to build from git?

That's be awesome!  
Thanks,

**Comment by onlyjus** [comment]
`$ pip install pyqtgraph` installs 0.10.0

https://pypi.python.org/pypi/pyqtgraph/0.10.0

This can be closed.
