### ISSUE TITLE
Can pyqtgraph use 'stem' function just like in matplotlib？

### ISSUE THREAD

**Issue by XxxuLimei** [pyqtgraph/pyqtgraph#2267]
I'm using pyqtgraph to draw stem figure, but it seems like no same function in pyqtgraph

**Comment by XxxuLimei** [comment]
> 
Thanks for replying! I've solved this question by the same way, just 'plot' first and then 'scatter'

**Comment by mourKa86** [comment]
but scatter doesn't have symbol '|' so again there is no stem.
