### ISSUE TITLE
ViewBox ImageItem Mouse click offset 

### ISSUE THREAD

**Issue by Em607867** [pyqtgraph/pyqtgraph#2268]
I have a simple script displaying images/videos from a camera and I am using ImageItem() to display this. I can display mouse coordinates after mapping from scene and everything works fine. 

However, whenever I try to draw a line with mouse click event, there seems to be some offset in the first position (the end position is correct i.e. the line stops when I release my mouse). 

Please refer to the image below. The intended start point is the bottom edge of the dark pixel. 

![image](https://user-images.githubusercontent.com/95716966/164575344-07d191be-f34c-45a2-8a70-39d36f5b9ef9.png)

I have also attached the functions for my mouse events below ; 

    def mouseMovedEvent_line(self, pos):
        if not len(self.begin) == 0 and not len(self.destination) == 0  :
            if self.view.sceneBoundingRect().contains(pos):
                mousePoint = self.img.mapFromScene(pos)
                #print(self.click)
                x_i = (mousePoint.x())
                y_i = (mousePoint.y())
                if x_i >= 0 and x_i < self.picture.shape[0] and y_i >= 0 and y_i < self.picture.shape[1]:
                    self.destination = [x_i, y_i]
                    self.line.setLine(self.begin[0], self.begin[1], self.destination[0],self.destination[1])
                    
                    
    
        
    def mouseClickEvent_line(self,event):
        #Eventually add a condition here for if line is clicked 
        if event.buttons() & Qt.LeftButton:
                if self.view.sceneBoundingRect().contains(event.pos()):
                    mousePoint = self.img.mapFromScene(event.pos())
                    x_i = (mousePoint.x())
                    y_i = (mousePoint.y())
                    print(x_i, y_i)
                    if x_i >= 0 and x_i < self.picture.shape[0] and y_i >= 0 and y_i < self.picture.shape[1]:
                        if len(self.begin)==0:
                            print('first click')
                            self.begin.extend([x_i, y_i])
                            print(self.begin)
                            self.destination = self.begin
                            self.line = QGraphicsLineItem(self.begin[0], self.begin[1], self.destination[0],self.destination[1])
                            pen = QPen(Qt.red)
                            pen.setWidth(0)
                            self.line.setPen(pen)
                            self.line.setBoundingRegionGranularity(0)
                            self.view.addItem(self.line)
                            self.update() 
                        else:
                            print('click 2')
                            self.line = QGraphicsLineItem(self.begin[0], self.begin[1], self.destination[0],self.destination[1])
                            print(self.line.childrenBoundingRect())
                            x_distance = self.destination[0] - self.begin[0]
                            y_distance = self.destination[1] - self.begin[1]
                            print(f'x distance is {x_distance/0.442} um , y distance is {y_distance/0.442} um')
                            self.begin, self.destination = [],[]
                            self.update()

**Comment by j9ac9k** [comment]
@outofculture didn't you have some deep dive into this topic/functionality recently?

**Comment by Em607867** [comment]
@outofculture Any pointers would be appreciated. Thanks :))

**Comment by outofculture** [comment]
@Em607867 I looked for some similar possible behaviors, but I couldn't find anything that corroborates the behavior you're describing. Could you post the entire class you made?

**Comment by j9ac9k** [comment]
I'm going to close out this issue.  @Em607867 if you can provide a reproducible example of the issue please post here and I'll reopen 👍🏻
