### ISSUE TITLE
why change plotItem.plot source code clearPlots() to clear()

### ISSUE THREAD

**Issue by zhangxingjing** [pyqtgraph/pyqtgraph#2269]
when I upgrade pyqtgraph 0.11 to 0.12 , I found that my application hs a bug, the InfiniteLine is not visible, then I found that is because I set 'clear=True' in PlotItem.plot, so I check the source code, found 'clearPlots' is changed to 'clear'.

I think 'clearPlots' is better than 'clear', because when I set 'clear=True', I want to just clear the plots, not others, because the line is just like a tool, It`s unnessery to add a tool everytime I plot data. 

Of course, there must be a reason why you did this，so I want to ask the reason.

**Comment by j9ac9k** [comment]
Hi @zhangxingjing 

I'm looking at the source code with the tag 0.11.0 and I'm not seeing any reference to `clearPlots` other than the method in the `PlotItem` class, which is there currently.

If you know the line of code that changed, may I recommend running git blame and identifying the commit that the change was made?  If that triggers a memory, I'll gladly share more.

**Comment by j9ac9k** [comment]
Going to close due to inactivity.  @zhangxingjing if you can provide a code to replicate your issue, please post and I'll reopen.
