### ISSUE TITLE
Exception for polyline ROI region  with value more then 1000

### ISSUE THREAD

**Issue by sasha-sem** [pyqtgraph/pyqtgraph#2283]
Hi,
I found a thing that I don't understand.
For some reason if I usestriangle or polyline ROI, I can't get region of ROI with width of its containing rectangle more than 1000. In this case python throws Exception if i change this value to any other it works with no problems.
https://github.com/pyqtgraph/pyqtgraph/blob/6f6e86e0deff0e41745396c18bdba8883e0eee6a/pyqtgraph/graphicsItems/ROI.py#L1200

That's why, I have a question. Is there any reason for this limitation and is there way to change/remove it?
Thank you!

**Comment by j9ac9k** [comment]
Hi @sasha-sem 

That change was introduced quite some time ago as part of this commit: https://github.com/pyqtgraph/pyqtgraph/commit/bb507cf6d089a6aa7dcbbd8656a75969b754815f

As there is no comment there, I would be ok with removing that if-check provided the test suite still passes.

**Comment by j9ac9k** [comment]
@campagnola you happen to have any memory of that if-check?

**Comment by campagnola** [comment]
Most likely I added this to debug some issue and should never have committed it.

**Comment by j9ac9k** [comment]
> Most likely I added this to debug some issue and should never have committed it.

I've _never_ done that 😆
