### ISSUE TITLE
InfiniteLine met some strange issues

### ISSUE THREAD

**Issue by mike9755** [pyqtgraph/pyqtgraph#2284]
When I use InfiniteLine I got some strange issues, like a vertical InfiniteLine can be dragged vertically, and the lable will zoom in when I zoom in plot area with label inside, and crashed when try to set text to the label, but no prolbem in the plotting on start up, I met the problem after try to plot new graphs.
`def addInfiniteLine(self):
    try:

        self.inf1=pg.InfiniteLine(movable=False,pos=0,pen='w')
        self.inf2 = pg.InfiniteLine(movable=True,pos=30, angle=90, pen='r',label='{value:0.1f} ms',
                   labelOpts={'position':0.1, 'color': (200,200,100), 'fill': (200,200,200,50), 'movable': False})
        self.inf3=pg.InfiniteLine(movable=True,pos=60,pen='y',label='{value:0.1f} ms',
            labelOpts={'position':0.1, 'color': (200,200,100), 'fill': (200,200,200,50), 'movable': False})

        self.inf2Label1=pg.InfLineLabel(self.inf2, "my label", position=0.7, color=(200,200,100), fill=(200,200,200,50),anchor=(1, 1), movable=True)
        self.inf3Label1=pg.InfLineLabel(self.inf3, "Δ △ my label", position=0.7, color=(200,200,100), fill=(200,200,200,50),anchor=(1, 1), movable=True)

        self.plt.addItem(self.inf1)
        self.plt.addItem(self.inf2)
        self.plt.addItem(self.inf3)

        self.inf2.sigPositionChanged.connect(self.inf2PosChanged)
        self.inf3.sigPositionChanged.connect(self.inf3PosChanged)
    except Exception as e:
        print('addInfiniteLine:'+str(e))

def inf2PosChanged(self):
    try:
        value2=self.inf2.value()
        self.inf2Label1.setPosition(value2/100)
        self.inf2Label1.setText(str(value2))
    except Exception as e:
        print('inf2PosChanged:'+str(e))`

in below picture the bottom label should be 60 ms, but never changed when I drag the red InfiniteLine, and can drag the infiniteLine vertically. And the label was zoom in
![image](https://user-images.githubusercontent.com/5673534/166150879-aff0d7e9-c187-417a-bd75-a0b98f4538d1.png)

**Comment by j9ac9k** [comment]
Hi @mike9755 

Thanks for reporting the issue; can you update the formatting in the original post, and ideally supply an example I can run to reproduce the issue?  This is usually easiest to do by modifying one of of the examples, in this case I would try modifying the Infinite Line example and see if you can recreate the issue there: https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/examples/InfiniteLine.py

**Comment by mike9755** [comment]
Hi Friend
I have uploaded the completed test document, you can run it directly, after open the window then you can click the "Test" button in the right top to see all the problem I mentioned above, I have setted the line which cause cause when try to setText to InfLineLabel (line 191 in the py file).
File as below:
[myDockTest.zip](https://github.com/pyqtgraph/pyqtgraph/files/8599295/myDockTest.zip)

**Comment by mike9755** [comment]
Hi @j9ac9k 
Do you have some new comment on this issue? expecting your comments, thank you very much.

**Comment by pijyoi** [comment]
Browsing through your code, I see that you are calling pyqtgraph and Qt graphics functions in a separate thread from the main thread. That is not allowed. 

See:
https://github.com/pyqtgraph/pyqtgraph/discussions/2164

**Comment by pijyoi** [comment]
A minimal crashing example (tested on master and PySide6).
Holding an unneeded reference to `InfLineLabel` when its parent `InfiniteLine` has been cleared causes a crash.
It seems easy enough to avoid this crash, just don't instantiate `InfLineLabel` manually.

```python
import pyqtgraph as pg 
from pyqtgraph.Qt import QtWidgets

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        glw = pg.GraphicsLayoutWidget()
        self.plt = glw.addPlot()
        self.btn = QtWidgets.QPushButton('Test')
        self.btn.clicked.connect(self.onButtonClick)

        cw = QtWidgets.QWidget()
        layout=QtWidgets.QVBoxLayout()
        cw.setLayout(layout)
        layout.addWidget(glw)
        layout.addWidget(self.btn)
        self.setCentralWidget(cw)

        self.colors = 'rgb'
        self.cnt = 0

    def onButtonClick(self):
        self.plt.clear()
        color = self.colors[self.cnt]
        label = color.upper() * 3
        self.cnt = (self.cnt + 1) % len(self.colors)
        if 0:
            # working branch
            self.infline = pg.InfiniteLine(pos=0.5,pen=color,label=label)
        elif 0:
            # also working branch
            self.infline = pg.InfiniteLine(pos=0.5,pen=color)
            pg.InfLineLabel(self.infline, label)
        else:
            # crashing branch
            self.infline = pg.InfiniteLine(pos=0.5,pen=color)
            self.inflabel = pg.InfLineLabel(self.infline, label)
        self.plt.addItem(self.infline)

pg.mkQApp()
main = MainWindow()
main.show()
pg.exec()
```

**Comment by mike9755** [comment]
Hi @pijyoi 
Test again with your comment, the problem has gone after remove the thread which pyqtgraph and Qt graphics function was handled in main thread, also setText to the InfLineLabel not cause crash anymore, thank you very much.

**Comment by j9ac9k** [comment]
Actually looks like this issue can be closed out!
