### ISSUE TITLE
Opacity of the 3D line/scatter plotted using gl.GLLinePlotItem/gl.GLScatterPlotItem

### ISSUE THREAD

**Issue by zhangy76** [pyqtgraph/pyqtgraph#2295]
Hi,

I am wondering how to increase the opacity of the 3D line/scatter plotted using gl.GLLinePlotItem/gl.GLScatterPlotItem?

I just use the standard way to plot the 3D scatter or line as 
`
points = gl.GLScatterPlotItem(
                pos=points_pos,
                color=pg.glColor((255, 0, 0)),
                size=12
                )
            window.addItem(points)
`

**Comment by j9ac9k** [comment]
Hi @zhangy76 

you could try using `pg.glColor(255, 0, 0, 128)`, where the 4th parameter is the alpha value.

**Comment by zhangy76** [comment]
Hi,

Thank you so much for the quick reply! The results of using pg.glColor(255, 0, 0, 255) (255 is the maximal I think) is not good as well. I can still see transparency. Is this behaviour correct?

**Comment by ixjlyons** [comment]
See [setGLOptions](https://pyqtgraph.readthedocs.io/en/latest/3dgraphics/glgraphicsitem.html#pyqtgraph.opengl.GLGraphicsItem.GLGraphicsItem.setGLOptions). You can use `item.setGLOptions("translucent")` to get fully opaque points. The default for `GLScatterPlotItem` happens to be "additive" which, confusingly enough, maintains a somewhat translucent appearance even with max alpha.

`GLScatterPlotItem` and family also take `glOptions` as a keyword argument in their constructor (e.g. `GLScatterPlotItem(..., glOptions="translucent")`).

Documentation should be improved for `GLScatterPlotItem` and `GLLinePlotitem` to indicate that there's a `glOptions` keyword arg and its default value.

**Comment by zhangy76** [comment]
@ixjlyons Adding 'glOptions="translucent"' perfectly solve the problem. Thanks!
