### ISSUE TITLE
Options passed PenParameter are not applied

### ISSUE THREAD

**Issue by orangelynx** [pyqtgraph/pyqtgraph#2303]
### Short description
`pTypes.PenParameter(name="Line Style", width=5)` should initialize the wrapped pen with `width` of 5, but it remains at 1. Same applies for other style options.

### Tested environment(s)

 * PyQtGraph version: 0.12.4
 * Qt Python binding: PyQt6
 * Python version: 3.10
 * Installation method: venv / pip

**Comment by j9ac9k** [comment]
Thanks for the report @orangelynx, I'm going to tag @ntjess on this one, our resident parameter tree expert.
