### ISSUE TITLE
Set Axisitem's font size doesn't work

### ISSUE THREAD

**Issue by mike9755** [pyqtgraph/pyqtgraph#2321]
Hi, it doesn't work on setting Axisitem's font size, can someone helps? I try to set font size in expamles "ColorBarItem.py", add one line below setLabel of bottom axis:
`
p2.getAxis('bottom').setLabel('bottom axis label')
p2.getAxis('bottom').setStyle(tickTextWidth=15, tickTextHeight=9 )
`

**Comment by ixjlyons** [comment]
The `tickTextWidth`/`tickTextHeight` style params are only for space allocation. You can change the actual font used (and its size or anything else) with [`setTickFont`](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/axisitem.html#pyqtgraph.AxisItem.setTickFont) or [`setStyle(tickFont=font)`](https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/axisitem.html#pyqtgraph.AxisItem.setStyle).

**Comment by mike9755** [comment]
Hi @ixjlyons 
Thank you for quick response, it works.
