### ISSUE TITLE
warnOnException called for TypeError on drawPixmapFragments

### ISSUE THREAD

**Issue by dam5h** [pyqtgraph/pyqtgraph#233]
Hello,

I am getting the following issue as an "Ignored exception"
File "/usr/lib/python3.4/site-packages/pyqtgraph/widgets/GraphicsView.py", line 154, in paintEvent
    |      return QtGui.QGraphicsView.paintEvent(self, ev)
    |    File "/usr/lib/python3.4/site-packages/pyqtgraph/debug.py", line 92, in w
    |      printExc('Ignored exception:')
    |    ---- exception caught ---->
    |    File "/usr/lib/python3.4/site-packages/pyqtgraph/debug.py", line 90, in w
    |      func(_args, *_kwds)
    |    File "/usr/lib/python3.4/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 764, in paint
    |      p.drawPixmapFragments(data['targetRect'].tolist(), data['sourceRect'].tolist(), atlas)

TypeError: QPainter.OdrawPixmapFragments(list-of-QPainter.PixmapFragment, Pixmap, QPainter.PixmapFragmentHints hints=0): argument 2 has unexpected type 'list'

I am running PyQt4 and version 0.9 of pyqtgraph.  Please let me know if you've seen this before, I just need to silence it for now so will be altering the decroator function temporarily.
Thanks, Dave

**Comment by wean** [comment]
same warning

PyQt 4.11.4
pyqtgraph 0.9.10
python 2.7.10

**Comment by j9ac9k** [comment]
I think this was an issue with a binding changing the accepted type, regardless, I'm confident in saying this is no longer an issue, given we use `p.drawPixmapFragments` quite extensively now (and test accordingly).

Sorry it's taken so long for us to follow up!
