### ISSUE TITLE
GUI not redrawn after resize

### ISSUE THREAD

**Issue by tfeldmann** [pyqtgraph/pyqtgraph#234]
I embedded a GraphicsLayoutWidget into a QDialog.
When I resize my QDialog (with the mouse) both the plot and the rest of the GUI resizes fine during the resize, but when I release the mouse button only the plot is updated to the new size and the rest of the widgets in the GUI disappear.
This also happens with the pyqtgraph examples and the plot export dialog.

I'm using pyqtgraph 0.9.10, PySide 1.2.2, Python 3.5, Mac OS X 10.10.5. I remember it happened with Python 3.4, too.

**Comment by 2xB** [comment]
I could reproduce this.

### Code to reproduce

```python3
import sys
from PyQt5 import QtWidgets
import pyqtgraph as pg

app = pg.mkQApp()

w = pg.GraphicsLayoutWidget()
w.show()

vb = pg.ViewBox()
w.setCentralItem(vb)
grid = pg.GridItem()

vb.addItem(grid)

if __name__ == '__main__':
    sys.exit(app.exec_())
```

### Tested environment(s)

 * PyQtGraph version: 0.10.0 and on branch `develop`
 * Qt Python binding: PyQt5 5.13.0 Qt 5.13.0
 * Python version: 3.7.4
 * NumPy version: 1.17.0
 * Operating system: Manjaro KDE stable (Arch Linux)
 * Installation method: Dependencies via repositories and pip, PyQtGraph directly executed from source

**Comment by 2xB** [comment]
@tfeldmann It has been quite a while. Could you check if we are talking about the same bug? It seems like your bug is only happening after resizing, while for me I have problems both during and after resizing.

**Comment by tfeldmann** [comment]
I tried your example with with PySide2 and could not reproduce it.

**Comment by 2xB** [comment]
@tfeldmann If you still know roughly what you did: Can you then create a Minimal Working Example for your issue, so I can try to reproduce it?

**Comment by tfeldmann** [comment]
@2xB Your minimal example is roughly the same thing I did. I had the same trouble with the examples, too (`python3 -m pyqtgraph.examples`).
I just tested it in PySide2 and PyQt5 and everything works fine now...
