### ISSUE TITLE
Axes zoom area does not resize in 0.12.4

### ISSUE THREAD

**Issue by Seaspider1** [pyqtgraph/pyqtgraph#2345]
### Short description
When a plot is first generated with a given size, say `width ` and `height` in pixels, the entire axes areas on the left and bottom of the plot are zoomable. When the plot size is resized such that the plot is larger (e.g. the window is grabbed along an edge or corner and expanded), only the top `height` portion of the y-axes or the left `width` portion of the x-axis retain the ability to zoom the plot using the scroll wheel. The axes area outside (i.e. the lower portion of the y-axis or the right portion of the x-axis) are not zoomable. If hovering over the plot, not on an axes, there is no issue with zooming. Reverting to 0.12.3 fixes issue.

I was able to reproduce this in both custom plots and many of the pyqtgraph.example scripts.

### Tested environment(s)

 * PyQtGraph version: 0.12.4
 * Qt Python binding: PySide2 5.15.2.1 Qt 5.15.2
 * Python version: 3.7
 * NumPy version: 1.21.6
 * Operating system: Windows 10 Enterprise 21H2
 * Installation method: pip

**Comment by j9ac9k** [comment]
`git bisect` points to this commit as being the problematic one:       814de9c5fa472dd28167d2ba73ffab949d3a26ab

**Comment by j9ac9k** [comment]
Created #2357 that I think fixes this issue, if someone could verify that would be greatly appreciated.

**Comment by Seaspider1** [comment]
@j9ac9k I have confirmed that this fixes the issue. Well done!

**Comment by j9ac9k** [comment]
Thanks for checking @Seaspider1

I'm going to re-open the issue, and close it when the PR gets merged.
