### ISSUE TITLE
Lazy rectangle selection box contruction breaks subclassed ViewBoxes

### ISSUE THREAD

**Issue by markotoplak** [pyqtgraph/pyqtgraph#2352]
### Short description
#2168 introduced creating selection boxes lazily. This is, however, compatibility breaking for any classes that extend `ViewBox` and expect the attribute to behave as it did. For example, we use these in Orange here and I am sure this is not the only place we touch it:
https://github.com/biolab/orange3/blob/269d7fa75c0f36f69b318d925c080b3626d65837/Orange/widgets/visualize/utils/plotutils.py#L156

Should we work around the issue or are you perhaps planning on reverting this? Were there any substantial gains achieved by that particular optimization? Does anyone open thousands of viewboxes quickly?

**Comment by markotoplak** [comment]
@danielhrisca, did you need that particular optimization for your use case? Or did you just try to make the code a bit cleaner? If the latter, may I suggest reverting the PR for now?

I think these kind of compatibility-breaking changes are best done before new major releases.

**Comment by danielhrisca** [comment]
@markotoplak in my use case I was creating plot widgets with hundreds of curves, each on dedicated viewboz so the initial rectangle creation was wasting time on something that was not used

**Comment by markotoplak** [comment]
Daniel, an interesting approach. So you are like doing hundreds of viewboxes, one for each curve, right? Could you describe the context? I have never used more that ~10 viewboxes at the same time.

I have to admit I would also think of this a low-risk change. :) If we are the only users for whom this is a breaking change, we could work around it.

Perhaps a parameter in init could solve the same speedup in a backword-compatible way.

**Comment by danielhrisca** [comment]
Right now this PR is absolete for me because I've switched to using a single viewbox. 

The initial reason for using individual viwboxes for each curve was to have independent Y scrolling for each curve. The user would select the current curve from a qlistwidget and the scrolling would o ly apply for that curve.

**Comment by j9ac9k** [comment]
Sorry I've been absent here, I'm curious if there is a way we can maintain original and current functionality, with a warning being emitted with the original functionality.

@markotoplak is the issue that `self.rbScaleBox` can now be `None`?

**Comment by markotoplak** [comment]
@j9ac9k, yes, a class that extends ViewBox assumes that `self.rbScaleBox` is a `QGraphicsRectItem` after initialization and uses it independently of `ViewBox.RectMode`.

I raised an issue to notify of a breaking change. I do understand that you could judge our use case to be too exotic and will stick with it.

**Comment by j9ac9k** [comment]
> @j9ac9k, yes, a class that extends ViewBox assumes that `self.rbScaleBox` is a `QGraphicsRectItem` after initialization and uses it independently of `ViewBox.RectMode`.
> 
> I raised an issue to notify of a breaking change. I do understand that you could judge our use case to be too exotic and will stick with it.

I am sort of not great at these kinds of decisions so I'll try and get a consensus w/ other maintainers and report back.  Generally speaking, we want to avoid releasing breaking changes between versions w/o a deprecation warning phase.  

We appreciate you testing from the `master` branch and alerting us to this breaking change.

**Comment by danielhrisca** [comment]
I'm for not breaking other people's code. Since I was the only one using this optimization maybe you should just close the PR

**Comment by markotoplak** [comment]
>  but I'm scratching my head on how to go about emitting warnings in the correct fashion.

A possibility I see would be to rename the attribute, make it behave as it should, and use it with the new name everywhere in the library. And perhaps even make it private. :) Them, I'd make a property (effectively a pass-through) with the old name that complains on use (but on the first access also initializes it).
