### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by dingo9** [pyqtgraph/pyqtgraph#2372]
in pyqtgraph/pgcollections.py:149:22: 
```

    def __init__(self, *args, **kwargs):
        self.mutex = threading.RLock()
        list.__init__(self, *args, **kwargs)
        for k in self:
            self[k] = mkThreadsafe(self[k])
                     ^
```

should be 
```
            self[k] = makeThreadsafe(self[k])
```
 
in pyqtgraph/widget/DiffTreeWidget.py:126
```
    def _compare(self, a, b):
```

should be
```
    def _compare(self, info, expect):
```

**Comment by ksunden** [comment]
While I think you may be correct on both of these in some sense, I do not think either of these are actually worth addressing by applying the diff you suggest:

the first is in pgcollections which is deprecated and slated for wholesale removal in the near future anyway (and is not used internally at all, already)

The second is in a private (as indicated by the leading `_`, which traditionally means "don't use this except for internal use") method that is never called and should just be deleted.

**Comment by dingo9** [comment]
ok, thanks
