### ISSUE TITLE
Not plotting simple data set (Overflow issue?)

### ISSUE THREAD

**Issue by csnap001** [pyqtgraph/pyqtgraph#2377]
I'm attempting to plot two lines. One is the data spectrum and the other is the error spectrum. This typically works, but for a data set that I'm testing on it fails to plot. The data can be plotted with matplotlib.pyplot without issue, so I'm thinking this is a pyqtgraph issue. It is difficult to display the code to reproduce as I'm just using the plot function:

import pyqtgraph as pg
import numpy as np
x = np.arange(1100,1600,1)
y = [0, 3e70,2e70,...,0] #This is an array of large values except for the first and last element which is zero. Thought this was the #issue, but doesn't seem to matter if I remove these elements
err = np.arange(1e68,5e68,0.01e68) #This isn't exactly right, just an error spectrum at this scale
pg.plot(x,y,Name='Flux',stepMode=True)#Fails to plot when stepMode=False as well
pg.plot(x,err,Name='Error',stepMode=True)

### Expected behavior
Plotted curves

### Real behavior
Blank window with legend set and axis adjusted to the scale of the data

### Tested environment(s)

 * PyQtGraph version: 0.11.0
 * Qt Python binding: 'PyQt5 5.15.7 Qt 5.15.2'
 * Python version: 3.9.12
 * NumPy version: 1.21.5
 * Operating system: MacOS Monterey
 * Installation method: conda

### Additional context
I've created a GUI app for which this code is embedded. The exact code differs from what is above, but the same principle is being applied. The code I've written works on every other data set I've used. This is the first with numbers on the order of 1e70, so I suspect this is the issue, but I can't find a solution and it isn't an issue for matplotlib.pyplot. My apologies if I've made an obvious error somewhere.

**Comment by j9ac9k** [comment]
I couldn't run your example due to mismatched array sizes, making some slight adjustments to your example and it runs on the current master branch

```python
import pyqtgraph as pg
import numpy as np
# x = np.arange(1100,1600,5)
x = np.linspace(1100, 1600, 5)
y = [0, 3e70,2e70, 1e70 ,0] #This is an array of large values except for the first and last element which is zero. Thought this was the #issue, but doesn't seem to matter if I remove these elements
err = np.arange(1e68,5e68,0.01e68) #This isn't exactly right, just an error spectrum at this scale
pg.plot(x,y,Name='Flux',stepMode=False)#Fails to plot when stepMode=False as well
# pg.plot(x,err,Name='Error',stepMode=False)
pg.exec()
```

<img width="752" alt="image" src="https://user-images.githubusercontent.com/646398/193378506-93679791-352c-441d-8d17-42e15d772ab4.png">


This is a pretty old issue of pyqtgraph, I'm going to close this out, if you're still running into problems let me know.
