### ISSUE TITLE
when pack with pyinstaller, error: qt.qpa.xcb: could not connect to display

### ISSUE THREAD

**Issue by Neutree** [pyqtgraph/pyqtgraph#2402]
When I use github action to pack pyqtgraph with pyinstaller, error occurred:
```
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/opt/hostedtoolcache/Python/3.8.13/x64/bin/platforms" ...
loaded library "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```
> full log: https://github.com/Neutree/COMTool/runs/8050600195?check_suite_focus=true

And finally I resolved it by adding virtual display after I saw https://github.com/pyqtgraph/pyqtgraph/blob/bfb929fa1a04ed4f188540b0c7dfd4907c3a1b4d/.github/workflows/main.yml#L116 

```
xvfb-run pack command
```
> full ci script here: https://github.com/Neutree/COMTool/blob/739fbf35a70ec0067439a39183b6c40c60f01223/.github/workflows/pack_linux.yml#L43-L60

But I packed in my desktop's docker ubuntu20.04 container, no error occurred, I don't know why, it only occurrs in github action...

Is pyqtgpaph call some function related to show on screen when import the hidden imports(like:
```
"pyqtgraph.graphicsItems.PlotItem.plotConfigTemplate_pyqt5",
"pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyqt5",
"pyqtgraph.imageview.ImageViewTemplate_pyqt5",
```
)?

**Comment by j9ac9k** [comment]
Those template files should no longer exist with the current version of pyqtgraph, sometimes freezer applications would have trouble picking them up, especially if you didn't have a recent version of pyinstaller hooks library.

In case it helps, here is what we install on our CI.

https://github.com/pyqtgraph/pyqtgraph/blob/master/.github/workflows/main.yml#L184-L199

**Comment by j9ac9k** [comment]
This issue should no longer be problematic as we have done away w/ these templates.  I'm going to close this issue out.  If you are still having the issue, please create a new issue or comment here and I'll investigate/re-open.
