### ISSUE TITLE
OpenGL + Threading

### ISSUE THREAD

**Issue by rajkundu** [pyqtgraph/pyqtgraph#2427]
### PyQtGraph: OpenGL + Threading
Hello! I'm trying to make an application using `pyqtgraph` which "plays back" 3D data. That is, I have a short "recording" (5 sec @ 20 Hz) consisting of transformation matrices for 2 bodies over time. In order to play it back, I have tried creating a pyqtgraph OpenGL window as normal. Then, I run a separate thread, `update_fn`, which continuously sets the transforms of each object in the scene. Please see the code below.

I suppose my questions are pretty much:
1. Whether this is even expected to work, especially given knowledge of how `pyqtgraph.opengl` works
2. What the proper way to simultaneously render + update a scene is

Since Qt hijacks the main thread, I feel like this would be a common problem. So, if you have any general advice (doesn't have to be specific to `pyqtgraph.opengl`) on how to simultaneously render & update data with PyQtGraph, that would be great! Also, if I am doing something incorrectly or have missed something dumb, please forgive me. My first approach to this problem was multithreading, but I could very well be missing something obvious or have made a silly mistake.

Thank you very much for your help! Any advice is appreciated!

### Code (Relevant Excerpt)
```python
def update_fn(objs, transforms, sample_freq, loop):
	loop_count = 0
	frame_num = 0
	visible = [True for _ in range(len(objs))]
	anim_start = time.time()
	while True:
		start = time.time()
		frame_num = int((start - anim_start) * FPS)
		if frame_num >= transforms.shape[0]:
			if loop:
				frame_num = 0
				loop_count += 1
				print(f"Completed loop iteration #{loop_count} in {(time.time() - anim_start):.2f} sec")
				anim_start = start
			else:
				print(f"Playback finished")
				break

		for i, obj in enumerate(objs):
			T = transforms[frame_num][i]
			if np.any(np.isnan(T)):
				if visible[i]:
					obj.hide()
					visible[i] = False
			else:
				if not visible[i]:
					obj.show()
					visible[i] = True
				obj.setTransform(pg.Transform3D(T))

		end = time.time()
		if end - start > 1.0 / FPS:
			print(f"Warning: animation is falling behind realtime. Render took {(end - start) * 1000} msec when animation is {(sample_freq)} Hz/{(1000.0 / sample_freq)} msec/frame")
		time.sleep(0.020)

if __name__ == '__main__':
	# read in recorded transformations
	# ...

	# create gl.GLMeshItem objects from PLY files
	objs = create_objs(str(PLY_DIR / f"{tool['type']}.ply") for tool in tools.values())

	app = pg.mkQApp("NDI Playback 3D Viewer")
	w = gl.GLViewWidget()
	w.show()
	w.setWindowTitle("NDI Playback 3D Viewer")
	w.setCameraPosition(distance=500)

	g = gl.GLGridItem()
	g.setColor('gray')
	g.setSize(200, 200)
	g.setSpacing(10, 10)
	w.addItem(g)

	for obj in objs:
		w.addItem(obj)

	updater = threading.Thread(target=update_fn, args=(objs, transforms, FPS, LOOP), daemon=True)
	updater.start()

	app.exec()
```

If you would like to see the full code, I can provide it, but I didn't because I think it's more messy & distracting than important or helpful. Each object `T` is a 4x4 transformation matrix of 64-bit floats. Here is the output of `np.info(transforms)`:
```class:  ndarray
shape:  (100, 2, 4, 4)
strides:  (256, 128, 32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7fe96c8f6400
byteorder:  little
byteswap:  False
type: float64
```

### Expected behavior
The PyQtGraph OpenGL window should continue rendering the scene and the `updater` thread should continue setting the  scene's objects' transformations indefinitely.

### Real behavior
After a few loops (~30 sec?), the PyQtGraph OpenGL window freezes – the animation stops, and it no longer responds to input (i.e., mouse clicks).

### Tested environment(s)

 * PyQtGraph version: 0.12.4
 * Qt Python binding: PyQt6 6.3.0 Qt 6.3.0
 * Python version: 3.9.7
 * NumPy version: 1.21.4
 * Operating system: macOS 12.5
 * Installation method: `pip` from within a conda environment

**Comment by j9ac9k** [comment]
Some folks around here are more familiar w/ multi-threading and they may be able to give a better response.

Here is a sample of an application that I have where I use multi-threading

https://github.com/j9ac9k/barney/blob/main/src/barney/controllers/SubPlotControllers/SpectrogramController.py

In this file, you can see I subclass a `QThread`; in my subclassed `QThread`, I have a signal that emits the numpy array representing the data I want to plot.  Those calculations occur in the [`run`](https://github.com/j9ac9k/barney/blob/main/src/barney/controllers/SubPlotControllers/SpectrogramController.py#L60-L83) method.  

[I keep instances of my subclassed QThread and I discard it when the calculation finishes](https://github.com/j9ac9k/barney/blob/main/src/barney/controllers/SubPlotControllers/SpectrogramController.py#L109-L129).  When creating the instances, I connect up the signal that emits the numpy array representing the data I want to plot to a slot that runs in the main thread that handles the rendering.

Trying to handle rendering on the main thread is going to be problematic, and I would avoid doing that. 

On a side note, probably should make a more minimal example showing how to use the QThreads in such a way...

**Comment by pijyoi** [comment]
#2164 has one such example

**Comment by rajkundu** [comment]
@j9ac9k @pijyoi Thank you both very much for your extremely prompt and informative responses! I will definitely try using QThreads and only modify data from the main thread. I am very hopeful that this will fix the issue, and it makes perfect sense to my why it may currently be broken.

I'll close the issue as soon as I can test this (within the next few days), but you can also close it yourself if you'd like, and I can reopen it if using QThreads/signals/slots doesn't fix it for some reason. In any case, thank you both so much!

**Comment by rajkundu** [comment]
@pijyoi Okay, I think this is actually fixed! Also, I think that I may not have even needed to use QThreads. Does the following sound plausible/correct?

Previously, `update_fn` was implemented so that each time it was called, the current framenumber was calculated using the time elapsed since the animation's start. So, I connected `update_fn` to a `QTimer`. Now, it is triggered every _n_ milliseconds and calculates the current framenumber itself, then call setTransform() for each object in the scene – according to my understanding, all from the main Qt thread.

**Comment by pijyoi** [comment]
Indeed, all the included examples achieve their animation by the use of a QTimer.

The use of threading would only be useful if there is some cpu-heavy computation that is needed in order to calculate the next frame. Or if your frame data is somehow obtained via some blocking api.

**Comment by j9ac9k** [comment]
In all our current examples, we use `QTimer` instances to update plots as quickly as possible.  As @pijyoi said, moving to multiple threads is useful if there are tasks that take up so much CPU time they are causing inactivity in the main application.  In the example I linked above; the spectrogram calculation takes _just_ long enough that the GUI is frozen for a barely noticeable amount, and given that my example is interactive in nature, that can be pretty problematic for user experience.  

the openGL bit I don't have much guidance on.  Generally speaking, for 2D plots, we don't recommend using OpenGL unless you have a very specific reason for doing so.  We find our non-OpenGL implementation to be quite robust and performant.

I'm going to close out this issue unless you have another question @rajkundu 👍🏻

**Comment by rajkundu** [comment]
Wow - thank you both so much. I should have definitely checked out the examples before posting this issue. So sorry for wasting your time! I'm glad I can use pyqtgraph now that I understand how to properly set up threads; it all makes so much sense now. Thanks again!! 😁
