### ISSUE TITLE
pyside2-lupdate can not handle some file

### ISSUE THREAD

**Issue by cracy3m** [pyqtgraph/pyqtgraph#2430]
### Short description
pyqtgraph/graphicsItems/GradientEditorItem.py cause pyside2-lupdate exit without stderr message
pyqtgraph/graphicsItems/ViewBox/axisCtrlTemplate_pyside2.py can not generate translation file by pyside2-lupdate
### Code to reproduce
qt project file (reproduce.pro):
```
TRANSLATIONS = pyqtgraph.ts
SOURCE += pyqtgraph/graphicsItems/GradientEditorItem.py \
                    ...\ #other source file
```
`pyside2-lupdate reproduce.pro` , excuted, but got nothing

`pyside2-lupdate pyqtgraph/graphicsItems/ViewBox/axisCtrlTemplate_pyside2.py -ts pyqtgraph.ts` can not get translate info in axisCtrlTemplate_pyside2.py

### Expected behavior
pyqtgraph/graphicsItems/GradientEditorItem.py sould not break pyside2-lupdate work flow.
pyqtgraph/graphicsItems/ViewBox/axisCtrlTemplate_pyside2.py sould extra translate info string by pyside2-lupdate
### Real behavior
pyqtgraph/graphicsItems/GradientEditorItem.py  break the pyside2-lupdate work flow.
pyqtgraph/graphicsItems/ViewBox/axisCtrlTemplate_pyside2.py can not extra translate info string by pyside2-lupdate
```
An error occurred?
pyside2-lupdate has not stdout or stderr output
```

### Tested environment(s)

 * PyQtGraph version: 0.12.4
 * Qt Python binding: PySide2 5.15.2.1
 * Python version: 3.8
 * NumPy version: 1.21.2
 * Operating system: Windows 10, 64bit, 1809
 * Installation method: pip

### Additional context
Nope

**Comment by j9ac9k** [comment]
Hi @cracy3m 

I think we've done away w/ the axisCtrlTemplate_pyside2.py and moved them all into a generic one; but `GrandentEditorItem.py` being problematic is a head-scratcher.  Do you know what would cause that to happen?

I haven't worked w/ pyside2-lupdate before so I'm not sure what to even look for.  I guess first thing first, can you try with PySide6

I just tried the following file on pyside2 on pyqtgraph 0.13.1


This is my `issue_2430.pro`

```
TRANSLATIONS = pyqtgraph.ts
SOURCE += pyqtgraph/graphicsItems/GradientEditorItem.py 
```

Ran the following command

```
$ pyside2-lupdate issue_2430.pro
```

Which generated a file `pyqtgraph.ts` with the following content:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS><TS version="1.1">
</TS>
```

Is that what's expected?

**Comment by cracy3m** [comment]
Thanks reply, @j9ac9k

> I think we've done away w/ the axisCtrlTemplate_pyside2.py and moved them all into a generic one; but `GrandentEditorItem.py` being problematic is a head-scratcher. Do you know what would cause that to happen?

Personally, I think this problem cause by pyside2-lupdate, which cannot recognize tr() statements in .py script code with unicode prefix(for example, u'xxx' ), also can not process some statements in GrandentEditorItem.py like below.
```python
class Tick(QtWidgets.QGraphicsWidget):  ## NOTE: Making this a subclass of GraphicsObject instead results in
                                    ## activating this bug: https://bugreports.qt-project.org/browse/PYSIDE-86
``` 

> I guess first thing first, can you try with PySide6
PySide6 may work, but have not try It.

I suggest that the project should provide the generated .ts file for internationalization. It is quite complex to generate .ts file by pyqtgraph user for whole project ,  the project have different file for different Qt lib(use qtpy library like qtconsole may be a solution).Now,  I  just generate the . ts file of the project manually for what I need.

> Which generated a file `pyqtgraph.ts` with the following content:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <!DOCTYPE TS><TS version="1.1">
> </TS>
> ```
> 
> Is that what's expected?

Emm.. yes and no,  In my enviroment, no file will generate from the whole .pro file, so I just manual remove `GradientEditorItem.py` in `SOURCE += ` statement.
