### ISSUE TITLE
LinearRegionItem get curve data between selected region

### ISSUE THREAD

**Issue by djangosdk** [pyqtgraph/pyqtgraph#244]
REF: http://www.pyqtgraph.org/documentation/graphicsItems/linearregionitem.html#pyqtgraph.LinearRegionItem

I am new to pyqtGraph and using LinearRegionItem for selection. Is there a way i can get data for curves only for selection ?
For me getting data which lies between selection is important to process.

Any help of pointer in right direction will be helpful

```
from pyqtgraph.Qt import QtGui, QtCore
import numpy as np
import pyqtgraph as pg
#
app = QtGui.QApplication([])
#
win = pg.GraphicsWindow()
win.resize(1000, 600)
#
p1 = win.addPlot(title="Multiple curves")
p1.plot(np.random.normal(size=100), pen=(255, 0, 0), name="Red curve")
p1.plot(np.random.normal(size=110) + 5, pen=(0, 255, 0), name="Blue curve")
# LinearRegionItem
#
def updateRegion(window, viewRange):
    region = lr.getRegion()
    print region
#
lr = pg.LinearRegionItem([10, 40])
lr.setZValue(-10)
p1.addItem(lr)
p1.sigXRangeChanged.connect(updateRegion)
#
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()
```

**Comment by lesauxvi** [comment]
The forum might be a better place to get an answer (https://groups.google.com/forum/?fromgroups#!forum/pyqtgraph)... Could you please close this issue and ask your question on the forum?
