### ISSUE TITLE
How can I optimize rendering of +7000 polygons?

### ISSUE THREAD

**Issue by magicarm22** [pyqtgraph/pyqtgraph#2441]
### Short description
Hello! I wrote a program to draw dots, lines and polygons from 2d (QGIS) in 3d. I can draw all of this types of geometry, but when I tried to draw something big (with a lot of polygons), it works very slow. For example, I have a layer with 7026 polygons:

![image](https://user-images.githubusercontent.com/28513487/193055604-182fa0a3-9957-4da3-b6a8-2ad20165634d.png)

I spent near 10 seconds for drawing, and when I started to move camera, I spent near 1-2 seconds for redrawing image. I think, it is slow, and I want to optimize it. How can I do that? For example, the program tries to draw all polygons, but some of them are outside of view. Can I not to spend time for that polygons?

### Tested environment(s)

 * PyQtGraph version: 0.13.1
 * Qt Python binding: PySide6 6.3.1 Qt 6.3.1
 * Python version: Python 3.9
 * NumPy version: 1.20.2
 * Operating system: Windows 10
 * Installation method: pip

**Comment by j9ac9k** [comment]
Hi @magicarm22 

Our 3D capability isn't the most optimized due to its dependence on OpenGL and us maintainers knowing so little about it.  I would be happy to take a closer look, is there example code and a dataset you can share so I can replicate locally?

**Comment by ixjlyons** [comment]
How are you creating the polygons/mesh(es)? A single (or a few) large mesh items *should* work reasonably well up to 10k+ tris, but many small meshes will be slow.

As @j9ac9k alluded to, pyqtgraph's 3D system hasn't gotten a lot of attention recently and is somewhat dated. You might look at pyvista, which can integrate with Qt (https://qtdocs.pyvista.org/). It has a pretty heavy dependency on VTK, but that might work better if you need many simple items.

**Comment by magicarm22** [comment]
> How are you creating the polygons/mesh(es)? A single (or a few) large mesh items _should_ work reasonably well up to 10k+ tris, but many small meshes will be slow.
> 
> As @j9ac9k alluded to, pyqtgraph's 3D system hasn't gotten a lot of attention recently and is somewhat dated. You might look at pyvista, which can integrate with Qt (https://qtdocs.pyvista.org/). It has a pretty heavy dependency on VTK, but that might work better if you need many simple items.

Thanks, I worked with a lot of small meshes. Now I am concatenating all vertices and faces, and creating one big mesh. It works perfectly for me. Thanks!

**Comment by ixjlyons** [comment]
Great, glad to hear it.

**Comment by j9ac9k** [comment]
Glad to hear it! If anyone comes across this issue that knows how to deal w/ a series of small meshes in openGL and wants to contribute to pyqtgraph, we would love your input!
