### ISSUE TITLE
Pandas, Seaborn, Matplotlib support

### ISSUE THREAD

**Issue by ntjess** [pyqtgraph/pyqtgraph#2447]
Start by supporting the [basic plotting types](https://matplotlib.org/stable/plot_types/index.html) that already have pyqtgraph implementations:
- [ ] plot
- [ ] scatter
- [ ] step
- [ ] fill_between
- [ ] stackplot
- [ ] imshow
- [ ] pcolormesh
- [ ] contour

Stretch goals: Some new plot types
- [ ] violinplot

**Comment by do159hu** [comment]
Hi, what is this issue about? Only support or write some code using this implementations? Thanks

**Comment by ntjess** [comment]
There is an effort to allow pyqtgraph plotting through `pd.DataFrame(...).plot(...)` or `plt.plot(...)` syntax and the checkboxes represent standard matplotlib graphs that already have pyqtgraph implementations. It is a bit challenging to unify the API, so the development stalled since creating the issue. It's still open for discussion, though!

**Comment by j9ac9k** [comment]
Duplicate of #1677 ?  ;)

**Comment by ntjess** [comment]
Ah yes -- this initially was created from the roadmap but indeed could fit under the already-described issue. Closing for the reason.
