### ISSUE TITLE
row number of tableWidget before sorting

### ISSUE THREAD

**Issue by chanansh** [pyqtgraph/pyqtgraph#245]
So I have a `pg.TableWidget()` and the user sorted it. How do I get the row number before sorting so I will know what is the real row which was selected? I would like to avoid Model-View paradigm as it seems an overkill.
Thanks,
Hanan.

**Comment by j9ac9k** [comment]
Hi @chanansh 

Sorry you never got a response here; `pg.TableWidget` is an extension of `QTableWidget`, so for that kind of operation, I would look to what QTableWidget can do for you.

QTableWidget contains both the model and the view in one, if you do a sort on the view, my understanding is you do a sort on the model as well; so I would be surprised there is a way to get the pre-sort position of an item once it's been sorted, not unless you're willing to do some extra book-keeping yourself.
