### ISSUE TITLE
Plots look crushed along Y axis on Windows 10

### ISSUE THREAD

**Issue by matmr** [pyqtgraph/pyqtgraph#246]
After updating the system to windows 10 I noticed that figures are rendered in a flat line (example provided below). As soon as I move a particular figure (pan) it immediately renders ok (second picture).

<img width="501" alt="pyqtgraph_first" src="https://cloud.githubusercontent.com/assets/8112553/11165130/a8a9a99a-8b06-11e5-8b10-f0a66f737663.PNG">

<img width="502" alt="pyqtgraph_second" src="https://cloud.githubusercontent.com/assets/8112553/11165131/b0498a9e-8b06-11e5-9954-7d05270b8111.PNG">

**Comment by matmr** [comment]
This seems to be pyside/pyqt related. Closing ...

**Comment by Odoth** [comment]
Is there a workaround for this? I see it happening on my Windows 10 PC also, but also happening on Windows 7 in one case, though 2 other Windows 7 PCs I don't see it...

**Comment by lesauxvi** [comment]
Can you provide more information on your python set-up (python version and pyqt or pyside version) on your different machines?

**Comment by Odoth** [comment]
So it seems to be somehow a 32-bit vs 64-bit issue. On a Windows 7 PC I did separate installs of Python 2.7.11 both 64-bit and 32-bit. I installed latest PySide (1.2.4) and pyqtgraph(0.9.10) using pip to both 32-bit and 64-bit pythons. I see this issue with 64-bit but not with 32-bit.
matmr suggested it's a pyside/pyqt issue...that may be true, but I still need a workaround :) Or a fix is even better.

**Comment by matmr** [comment]
I believe it had something to do with the order of package installation and the source of the packages. In some cases (on my colleagues computer) it worked. That's why I didn't bother investigating further.  

It might be best to source all compiled libraries from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/) (Christoph Gohlke). I only ever used 64bit.

One good idea, probably, would be to go with PyQT 5. Which version are you using?

**Comment by lesauxvi** [comment]
Actually, my main machine is running under Linux (and I've never encountered your problem), but one of my machine runs Win 7. However, I never used pySide...

I always use (under Win7) Python(x,y) or WinPython as distribution. Can you check with WinPython for example?

**Comment by Odoth** [comment]
I tried with WinPython 64-bit on Win7 and didn't see the issue with the bundled Qt4 lib. I installed PySide 1.2.4 using pip to my WinPython and verified the issue happens when I set the examples app to  use PySide. I also downgraded on my WinPython install to PySide 1.2.2 from Gohlke's site as suggested by matmr and still saw the issue.

**Comment by matmr** [comment]
I'm not familiar with the WinPython package but I generally prefer installing each package by hand. Anaconda seems pretty solid though, maybe you should give it a try.

**Comment by cboulay** [comment]
I have a similar problem that may be relevant and informative.
Using Windows 10, x64, Python 2.7.10 [MSC v.1500 64 bit (AMD64)].

I'm doing real-time signal processing with graphs updating as new data come in. If I run my script from Windows or using PyCharm "Run" button, then the graphs update correctly and the axis labels update correctly (see Capture1.png below). If I run my script from PyCharm "Debug" button, then the graphs don't update, except for 1 or 2 pixels at the top of the y-axis (see Capture2.png). Note that the axis labels are not updating either.
![capture1](https://cloud.githubusercontent.com/assets/303797/14020224/9bb574d2-f1ac-11e5-8bfd-56ec2b2f4fd9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/303797/14020227/9f4b1f8e-f1ac-11e5-9522-a8b9cb969b71.PNG)

In OS X this does not happen. The graphs and axes update correctly whether running or debugging. 
(I have a maybe-separate problem in OS X where the widgets and non-updating graph elements disappear after a second. They reappear momentarily if I change screens then change back.)
