### ISSUE TITLE
ClipToView() range is not correct

### ISSUE THREAD

**Issue by Addy771** [pyqtgraph/pyqtgraph#247]
When zooming in on a plot with ClipToView(True) the data is clipped prematurely:
![cliptoview_true](https://cloud.githubusercontent.com/assets/11689983/11247158/bb2a19b2-8dcf-11e5-980c-2483ef72e595.png)

When ClipToView is set to False the data is normal:
![cliptoview_false](https://cloud.githubusercontent.com/assets/11689983/11247183/d1059d06-8dcf-11e5-880f-098811777e07.png)

**Comment by NilsNemitz** [comment]
The clip-to-view boundary logic has been revised multiple times since this report, most recently in  #1725 .
Wrong truncation of data should hopefully no longer happen. 

If anyone runs into new trouble with `clipToView`, please report a new issue!
