### ISSUE TITLE
Autoscale button missing

### ISSUE THREAD

**Issue by cjermain** [pyqtgraph/pyqtgraph#248]
I've switched to PySide 1.2.4 and Python 3.4 while using pyqtgraph 0.9.8+ and no longer see the autoscale "A" button on the lower left corner when I have changed the scale. I've also checked the `pyqtgraph.examples`. I didn't find it as a deprecated feature in the changelog. Is this a known PySide or Python 3 issue?

**Comment by Addy771** [comment]
Does it come back if you use showButtons()? http://www.pyqtgraph.org/documentation/graphicsItems/plotitem.html#pyqtgraph.PlotItem.showButtons

**Comment by cjermain** [comment]
@Addy771, thanks for the reference. It doesn't show up when I modify the `pyqtgraph.examples`, [PlotSpeedTest.py#L17](https://github.com/pyqtgraph/pyqtgraph/blob/develop/examples/PlotSpeedTest.py#L17), with the following:
```python
p. = pg.plot()
p.showButtons()
```
I guess the next step is to install PyQt4 and see if it shows by forcing the PyQt4 backend in the `pyqtgraph.examples`.

**Comment by Addy771** [comment]
That may work. I run PyQt5 and Python 3.4, and I had the "A" button working. I disabled it for my application though.

**Comment by cjermain** [comment]
I've confirmed that PyQt4 4.10.4 shows the autoscale button, while PySide 1.2.4 does not. Manually calling `plotItem.autoBtn.show` does not show it with PySide. All the correct methods seem to be called, so I think its a problem in the rendering or perhaps a PySide bug. Anyone else have this problem?
