### ISSUE TITLE
Crash when frequently updating graph including NaN and connect is set to finite

### ISSUE THREAD

**Issue by arendvp** [pyqtgraph/pyqtgraph#2486]
### Short description
In our product we show a graph with sensor data. This graph updates every second with up to 3600 samples per sensor. Our UI was crashing every now and then. When we changed the connect style from 'finite 'to the default one it doesn't crash anymore. This however draws the graph in a way that is not ideal to us.

### Code to reproduce
Our code is too big to easily extract a sample. I can however provide pseudo code which resembles our reproduction scenario.

* Create a graph
* Add 5 series with connect="finite"
* In a loop update the 5 series every second
** Use setData to set a newly created array with 3600 samples per sensor.
The crash is best reproducable if the array has a lot of NaN in the first part of the array and every update less NaNs are present. In real live this is the case where no historic sensor data is available and the sensor is just turned on. In the beginning the majority of the array is NaN and at the end there are some correct numbers. Every update there is 1 NaN less and 1 normal number more.

### Expected behavior
It shouldn't crash

### Real behavior
The application crashes. I attached a screenshot of a memory dump opened in Visual Studio showing the stacktrace of the crash.
![PyQtGraphCrash](https://user-images.githubusercontent.com/115632198/195334309-6ad1ed1b-d58a-41f6-a118-b78ff733a4e1.png)

### Tested environment(s)

 * PyQtGraph version: 0.12.3
 * Qt Python binding: PyQt5 5.15.4
 * Python version:  3.7.7
 * NumPy version: N/A
 * Operating system: Windows 10
 * Installation method: pip

Note: We also observed the crash on the combination when we were still using Python 2.7 with Qt4 and Python 3.7 with Qt4. I cannot be a 100% certain if it is the same crash.

**Comment by pijyoi** [comment]
Are you going to provide the equivalent runnable Python code of your pseudo code?

**Comment by ntjess** [comment]
Am I understanding the setup correctly? I created the code below based on your description but it doesn't seem to be crashing for me.

* How many sensors are there?
* Are you using `PlotDataItem`, `PlotCurveItem`, or something else?
* Are you using one curve per sensor, or one curve for all data?
* Does this error happen on the current version of pyqtgraph?

```python
import pyqtgraph as pg
import numpy as np

NUM_SENSORS = 100

pg.mkQApp()
pw = pg.PlotWidget()
pw.show()

sensor_data = np.full((NUM_SENSORS, 3600), np.nan)
curves = [pw.plot(i*1.1 + sensor_data[i]) for i in range(NUM_SENSORS)]

cur_idx = 0
def update():
    global cur_idx
    cur_idx = (cur_idx + 1) % sensor_data.shape[1]
    sensor_data[:, cur_idx] = np.random.rand(NUM_SENSORS)
    for i, curve in enumerate(curves):
        curve.setData(i*1.1 + sensor_data[i], connect="finite")

timer = pg.QtCore.QTimer()
timer.timeout.connect(update)
timer.start(500)

pg.exec()
```

**Comment by arendvp** [comment]
Thank you for creating the reproduction code. You hit the nail on the head, on my setup this is crashing on exactly the same spot. I have a Windows dump file but I cannot attach it, the file is too big, would this dump file help you? We are using virtual environments, may that be a factor?

I updated from 0.12.3 to 0.12.4 but it still crashes. What else can I do to help you reproduce?

**Comment by pijyoi** [comment]
Regarding your screenshot with the debugger showing the source code line where the exception happened, does that mean you compiled your own Qt libraries?

**Comment by arendvp** [comment]
No, I downloaded the symbol files from the Qt version I'm running. Qt is installed using pip.

**Comment by pijyoi** [comment]
Does the program still crash with NUM_SENSORS = 1?

Does the program still crash if you change the pen width to 2?

**Comment by pijyoi** [comment]
From your screenshot, I determined that you are running 32-bits Python. It does not crash on 64-bits. So that was important.

With Python 3.8.10 32-bits, the latest pip installable PyQt5, numpy, and pyqtgraph master, I was able to get a crash. It also crashes with PySide2.

I was also able to strip away usage of pyqtgraph and cause the crash.

**Comment by pijyoi** [comment]
Below is a pyqtgraph-free script that crashes on 32-bits Qt but not on 64-bits Qt.
Tested on Windows 11 64-bits, Python 3.8.10 32-bits and latest pip installable PyQt5 or PySide2.

The "access violation" crash seems to be triggered by constructing a `QPainterPath` (by deserialization) with many adjacent `MoveTo` commands to the same point. Such a path cannot be constructed with `moveTo()` method calls as Qt would simply merge them into a single `MoveTo` command. Other parameters in the script also seem significant.

In the script, no nans are used. Nans come into play only because pyqtgraph replaces nans with adjacent finite values. Thus, runs of nans will end up being runs of same-valued finite points.

Possible workarounds to the OP's crash:
1) switch to 64-bits Python
2) upgrade to pyqtgraph 0.13.1 and use `pg.setConfigOption('segmentedLineMode', 'on')`
    * this also requires upgrade to Python >= 3.8
3) stay on pyqtgraph 0.12.4 and change the pen width to something greater than 1.0
4) remove runs of nans with a single nan

```python
from PyQt5 import QtCore, QtGui, QtWidgets

import faulthandler
import platform
import random
import struct
import numpy as np

print(platform.python_build())
print(platform.python_compiler())

faulthandler.enable()
random.seed(0)

NUM_CURVES = 5
DATA_LEN = 3000     # making this large is important

# simplified arrayToQPath that only supports connect_array
def arrayToQPath(x, y, c):
    n = len(x)
    path = QtGui.QPainterPath()
    if n == 0:
        return path

    backstore = QtCore.QByteArray()
    backstore.resize(4 + n*20 + 8)      # contents uninitialized
    backstore.replace(0, 4, struct.pack('>i', n))
    # cStart, fillRule (Qt.FillRule.OddEvenFill)
    backstore.replace(4+n*20, 8, struct.pack('>ii', 0, 0))
    arr = np.frombuffer(backstore, dtype=[('c', '>i4'), ('x', '>f8'), ('y', '>f8')],
        count=n, offset=4)

    arr['x'] = x
    arr['y'] = y
    arr['c'][:1] = 0  # the first vertex has no previous vertex to connect
    arr['c'][1:] = c[:-1]

    ds = QtCore.QDataStream(backstore)
    ds >> path
    return path

app = QtWidgets.QApplication([])
view = QtWidgets.QGraphicsView()
view.resize(640, 480)
scene = QtWidgets.QGraphicsScene()
view.setScene(scene)
view.show()

curves = []
pen = QtGui.QPen(QtCore.Qt.GlobalColor.red)
for _ in range(NUM_CURVES):
    curve = QtWidgets.QGraphicsPathItem()
    curve.setPen(pen)
    scene.addItem(curve)
    curves.append(curve)

# apparently not starting from 0 is important to the crash
start_idx = 1
cur_idx = start_idx

# nans are not important to the crash
xdata = np.zeros(DATA_LEN)
ydata = np.zeros(DATA_LEN)
cdata = np.zeros(DATA_LEN, dtype=bool)

timer = QtCore.QTimer()

def update():
    global cur_idx
    view.setWindowTitle("{}".format(cur_idx))

    # every cycle, add one more connected element and duplicate it to the right
    cdata[cur_idx] = True
    xdata[cur_idx:] = cur_idx
    ydata[cur_idx:] = random.random()

    # duplicate the first connected element to the left
    if start_idx == cur_idx:
        xdata[:start_idx] = xdata[start_idx]
        ydata[:start_idx] = ydata[start_idx]

    for idx, curve in enumerate(curves):
        ydisp = 10 * (2 * idx + ydata)
        path = arrayToQPath(xdata, ydisp, cdata)
        curve.setPath(path)

    cur_idx = cur_idx + 1
    if cur_idx == DATA_LEN:
        app.exit()

timer.timeout.connect(update)
timer.start(0)

app.exec() if hasattr(app, 'exec') else app.exec_()
print('ran to completion')
```

**Comment by arendvp** [comment]
Thank you for the excellent help! It is really awesome that you were able to reproduce the problem and the pointers for the solution. We started on the 64-bit migration so that will solve the problem for us.
