### ISSUE TITLE
Is Qt > 4.7 A Hard Requirement

### ISSUE THREAD

**Issue by aarande** [pyqtgraph/pyqtgraph#251]
Hello and thank you for this great module! I am really wanting to use this in a work project however I have an issue. I need to make this work in a RHEL6 environment and that comes with Qt 4.6. I built PySide to work against this version but noticed when trying to use pyqtgraph it errors on import saying it needs Qt >=4.7. I did a test of commenting out this check and ran through some of the examples and things looked like they were working.

I was wondering is this a hard requirement or if PySide with Qt 4.6 would work ok? Are there any pitfalls or issues you can foresee? Again thanks for the package and would love to use it as it will save me a bunch of time.

**Comment by campagnola** [comment]
I have not tested against Qt 4.6 for many years. It's likely that pyqtgraph uses some features from 4.7+, but I am not sure which. I would recommend running as many of the examples as you can to see what does not work. You might get lucky, or you might find that the missing features are trivial to reimplement in python. Do let us know what you find!

**Comment by 2xB** [comment]
Currently the project officially supports PyQt 4.8+. Using older versions may still work for parts of the package, so it is still worth trying, although nothing is guaranteed to work then. Field reports are still welcome!
