### ISSUE TITLE
Draw Graph with Broken Axis

### ISSUE THREAD

**Issue by bilaljo** [pyqtgraph/pyqtgraph#2527]
Hello,

I would like to draw a graph with a broken axis like this here:

[Broken Graph](https://matplotlib.org/3.1.0/_images/sphx_glr_broken_axis_001.png)

How can I achieve this? I didn't find a hint in the documentation for this.

Thanks!

**Comment by j9ac9k** [comment]
Hi @bilaljo 

The only way I can think of doing this is to do two separate plots, one on top of the other, where the top plot has no x-axis shown, and the viewbox axis is in sync with the bottom plot.  Depending on the kind of interactivity you're wanting, you may run into other issues.

You can see plenty of examples of using layouts and synchronizing axes in our examples application.

**Comment by bilaljo** [comment]
Thanks!
