### ISSUE TITLE
isn't it time for an official release ?

### ISSUE THREAD

**Issue by stonebig** [pyqtgraph/pyqtgraph#253]
no official release with PyQt5 support yet

**Comment by lesauxvi** [comment]
The development version is currently PyQt5 compatible. You should use this version and wait for the 0.9.11 version that is coming.

**Comment by stonebig** [comment]
I do use a dev version of around april 2015, as I had issues after.

"pick a recent but proven stable dev. commit" is not an easy task.

**Comment by campagnola** [comment]
I despise regressions. If you have reported them, tag them with the 0.9.11 milestone so they'll be fixed before release.

I do agree we need another release soon. The PyQt5 issue plus a couple of critical bug fixes need to be available via pip.

**Comment by stonebig** [comment]
On today master on Python 3.4.4 Windows 7 64 Qt5.5.1, I have issues with:
- "Volumetric" test.
- "IsoSurface" test,

````
Using PyQt5 (default graphics system)
D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\sit
e-packages\pyqtgraph\examples\GLVolumeItem.py:44: RuntimeWarning: divide by zero
 encountered in log
  positive = np.log(np.clip(data, 0, data.max())**2)
D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\sit
e-packages\pyqtgraph\examples\GLVolumeItem.py:45: RuntimeWarning: divide by zero
 encountered in log
  negative = np.log(np.clip(-data, 0, -data.min())**2)
Fatal Python error: Segmentation fault

Current thread 0x000018a4 (most recent call first):
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64
\lib\site-packages\pyqtgraph\examples\GLVolumeItem.py", line 69 in <module>
Using PyQt5 (default graphics system)
Generating scalar field..
Generating isosurface..
Fatal Python error: Segmentation fault

Current thread 0x00000b4c (most recent call first):
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64
\lib\site-packages\pyqtgraph\examples\GLIsosurface.py", line 75 in <module>

````

**Comment by campagnola** [comment]
Shouldn't cause segmentation faults for old graphics cards. I think perhaps this isn't a regression so much as the addition of new unit tests that might never have worked for you. Can you try a git bisect to see when this started?

**Comment by stonebig** [comment]
I did open separates issues. I can't bissect but I can test a specific commit if you need me to (download, setup install, test).

**Comment by stonebig** [comment]
specific regression of this spring was https://github.com/pyqtgraph/pyqtgraph/issues/214

**Comment by 2xB** [comment]
There exists a release with PyQt5 support now and seemingly every other bug here is reported in separate issues. If I miss something, feel free to comment. Thanks for the feature request!
