### ISSUE TITLE
Plot window is blank and freezes (not responding) when launched in PyCharm's Python console or debugger

### ISSUE THREAD

**Issue by jackz314** [pyqtgraph/pyqtgraph#2530]
### Short description
The plot window is blank and freezes (not responding) when launched in PyCharm's Python console or debugger. 

### Code to reproduce
```python
import numpy as np
x = np.arange(1000)
y = np.random.normal(size=(3, 1000))
plotWidget = pg.plot(title="Three plot curves")
for i in range(3):
    plotWidget.plot(x, y[i], pen=(i,3))
```

### Expected behavior
Normal plot

### Real behavior
Unresponsive blank window
![image](https://user-images.githubusercontent.com/18280101/202795324-cf427649-3a4a-4085-9d28-b78a84a256c9.png)

### Tested environment(s)

 * PyQtGraph version: '0.13.1'
 * Qt Python binding: 'PyQt5 5.15.7 Qt 5.15.2'
 * Python version: 3.10.8
 * NumPy version: '1.23.4'
 * Operating system: Windows-10-10.0.19044-SP0
 * Installation method: pip

**Comment by ntjess** [comment]
You have to execute the gui event loop at the end of your script:

```python
import numpy as np
x = np.arange(1000)
y = np.random.normal(size=(3, 1000))
plotWidget = pg.plot(title="Three plot curves")
for i in range(3):
    plotWidget.plot(x, y[i], pen=(i,3))
pg.exec()
# ^^^ Add this line
```

Alternatively, if you're interactively debugging, you can also run `%gui qt` in the IPython console to unfreeze the window.

**Comment by jackz314** [comment]
Adding `pg.exec()` and `%gui qt% worked, thank you!
