### ISSUE TITLE
SpinBox _updateHeight has a type error

### ISSUE THREAD

**Issue by jaxankey** [pyqtgraph/pyqtgraph#2578]
PyQtGraph v0.11.0 and v0.12.3, in SpinBox.py line 577 should be

```
self.setMaximumHeight(int(1e6))
```

not

```
self.setMaximumHeight(1e6)
```

The existing line causes a type error when we set `opts['compactHeight'] = False`, because `1e6` is a float, not an int.

Currently my workaround is to keep `opts['compactHeight'] = True` but then I have to manually set the height of the number box to something more reasonable or else it looks janky and squished (a bug that was submitted some years ago).

Thanks so much!

**Comment by j9ac9k** [comment]
This was fixed in 41c8c245bda59d8760999effea6d2092b11f5353
