### ISSUE TITLE
no 'VideoTemplate_pyqt5' on PyQt5 on Windows

### ISSUE THREAD

**Issue by stonebig** [pyqtgraph/pyqtgraph#258]
testing on Windows Qt5.5.1/ PyQtgraph github of 20160102, I have the following error on the "Video Speed  test" :

```
Using PyQt5 (default graphics system)
Traceback (most recent call last):
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64
\lib\site-packages\pyqtgraph\examples\VideoSpeedTest.py", line 21, in <module>
    import VideoTemplate_pyqt5 as VideoTemplate
```

**Comment by 2xB** [comment]
This should be fixed through https://github.com/pyqtgraph/pyqtgraph/commit/e21d06b4c46a0fdbc873c3a37b3cb86132c3e35b as part of PR #383.

**Comment by j9ac9k** [comment]
@stonebig I'm going to close the issue, if it's still persistent let us know and we'll reopen.
