### ISSUE TITLE
Using dockarea for multiple OpenGL views

### ISSUE THREAD

**Issue by MarkGalperin** [pyqtgraph/pyqtgraph#2592]
### Short description

I want to use the docking feature and openGL to show multiple camera views of the same scene, but I don't know how to get all the views to update simultaneously. To try this out, I wrote a short script that uses three dock views to show different angles on the same scene. As I animated the scene, only one of the docks would update without interaction. Other docks would only update whenever I clicked/dragged them, and not as smoothly. If there is not a better way to do this, how can I force all docks to update simultaneously?

### Code to reproduce

My script does the following:
1. Creates three dock objects with one on the left, one on the top-right, one on the bottom-right
2. Creates three spheres (gl.MeshItem) and centers them at the points (2,0,0),(0,2,0), and (0,0,0) respectively.
3. Creates three view widgets (gl.GLViewWidget, one per dock) and assigns all three spheres to each view. 
4. Runs an update function (connected via QtCore.QTimer) to periodically update the position of two of the spheres, so that I can visualize changes to the scene.  

```python
import numpy as np
import pyqtgraph as pg
import pyqtgraph.opengl as gl
from pyqtgraph.dockarea.Dock import Dock
from pyqtgraph.dockarea.DockArea import DockArea
from pyqtgraph.Qt import QtWidgets, QtCore


## App and window
app = pg.mkQApp("multiple views")
win = QtWidgets.QMainWindow()
area = DockArea()
win.setCentralWidget(area)
win.resize(1000,500)
win.setWindowTitle('multiple views')

## Create docks
'''
Here I'll make three docks, each with its own view.
'''
d1 = Dock("dock 1")
d2 = Dock("dock 2")
d3 = Dock("dock 3")
area.addDock(d1,'left')
area.addDock(d2,'right')
area.addDock(d3,'bottom',d2)

## Create GL world of three spheres
# sphere 1
sphere1 = gl.MeshData.sphere(rows=10,cols=20)
colors1 = np.ones((sphere1.faceCount(), 4), dtype=float)
colors1[::2,0] = 0
colors1[:,1] = np.linspace(0, 1, colors1.shape[0])
sphere1.setFaceColors(colors1)
sphere1_mesh = gl.GLMeshItem(meshdata=sphere1,smooth=False)
sphere1_mesh.translate(2,0,0)

# sphere 2
sphere2 = gl.MeshData.sphere(rows=10,cols=20)
colors2 = np.random.random(size=(sphere2.faceCount(), 4))
colors2[:,3] = 0.3
colors2[100:] = 0.0
sphere2.setFaceColors(colors1)
sphere2_mesh = gl.GLMeshItem(meshdata=sphere2,smooth=False)
sphere2_mesh.translate(0,2,0)

# sphere 3
sphere3 = gl.MeshData.sphere(rows=10,cols=20)
colors3 = np.random.random(size=(sphere3.faceCount(), 4))
colors3[:,3] = 0.3
colors3[100:] = 0.0
sphere3.setFaceColors(colors1)
sphere3_mesh = gl.GLMeshItem(meshdata=sphere3,smooth=False)

# make an iterable of all items in the world
world_items = [sphere1_mesh,sphere2_mesh,sphere3_mesh]

## Create GL views...
v1 = gl.GLViewWidget()
v2 = gl.GLViewWidget()
v3 = gl.GLViewWidget()
v1.show()
v2.show()
v3.show()
#add to docks
d1.addWidget(v1)
d2.addWidget(v2)
d3.addWidget(v3)

for item in world_items:
    v1.addItem(item)
    v2.addItem(item)
    v3.addItem(item)


## animate the items
def update():
    sphere2_mesh.translate(0,0.01,0)
    sphere3_mesh.translate(0,0,0.01)
    

timer = QtCore.QTimer()
timer.timeout.connect(update)
timer.start(50)
    
win.show()

if __name__ == '__main__':
    pg.exec()
```

### Expected behavior

I hoped for all docks to simultaneously update, since they all hold references to the same GLMeshItem objects.

### Real behavior

 As I animated the scene, only one of the docks would update without interaction. Other docks would only update whenever I clicked/dragged them, and not as smoothly.

### Tested environment(s)

 * PyQtGraph version: 0.13.1
 * Qt Python binding: 'PyQt5 5.15.7 Qt 5.15.2'
 * Python version: 3.8.10
 * NumPy version: 1.23.5
 * Operating system: Ubuntu 20.04
 * Installation method: pip

**Comment by pijyoi** [comment]
The quick and dirty solution is to add calls to `v1.update()`, `v2.update()`, `v3.update()` in your `update()` routine.

The long answer is that each `GLGraphicsItem` only expects to be put in one `GLViewWidget`.
This is what `GLViewWidget.addItem` looks like:
```python
    def addItem(self, item):
        self.items.append(item)

        if self.isValid():
            item.initialize()
                
        item._setView(self)
        self.update()
```

Relevant methods from `GLGraphicsItem`
```python
    def _setView(self, v):
        self.__view = v
        
    def view(self):
        return self.__view

    def update(self):
        v = self.view()
        if v is None:
            return
        v.update()
```

**Comment by MarkGalperin** [comment]
This makes sense, thank you! So far your view.update() solution works just fine for my application, so I'll run with that for now.
