### ISSUE TITLE
How to set limit for zoom in time axis

### ISSUE THREAD

**Issue by Nishanth009** [pyqtgraph/pyqtgraph#2597]
Hi, I am using pg.DateAxisItem(orientation='bottom') for setting X axis as time axis. Currently it is possible to zoom(using mouse) to seconds level but I would like to limit zooming up to 1min or 3minute. Is it possible to achieve this. are there any methods available in DateAxisItem or setAxisItems

**Comment by ISMAILJAOUA11** [comment]
Hi there,

To set limits for zooming in on the time axis, you can use the setXRange method of the PlotWidget. Here's an example:

plot_widget.setXRange(start_time, end_time)

Replace 'start_time' and 'end_time' with the values of the time range that you want to limit the zoom to.

this example it can helps you 

Assume that the PlotWidget is named 'pw' and we want to set a zoom limit of 10 seconds
def update_time_axis_range():

 time_axis = pw.getAxis('bottom')
    x_range = time_axis.range
    if x_range[1] - x_range[0] > 10:
        new_range = (x_range[1] - 10, x_range[1])
        time_axis.setLimits(new_range)
pw.sigRangeChanged.connect(update_time_axis_range)

Hope this helps!

**Comment by j9ac9k** [comment]
Hi @Nishanth009 

Sorry for the late reply, but what you are looking for is [ViewBox.setLimits](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/viewbox.html#pyqtgraph.ViewBox.setLimits) specifically looking at `minXRange` option.  Sorry for the late response!
