### ISSUE TITLE
ImageItem displaying black image for an image with 16222*12028 pixels

### ISSUE THREAD

**Issue by sharon92** [pyqtgraph/pyqtgraph#2628]
### Short description

Plotting an image with very fine resolution shows just a black image. 

### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np

data = np.eye(20000)
imgItem = pg.ImageItem(data,levels,autoDownsample=False)

```

### Expected behavior
I expect it to take its time but still plot the image.

### Real behavior
It plots black Image.
![image](https://user-images.githubusercontent.com/51754340/221813033-6dcdd667-32b3-46af-80fb-1c3eded98d4a.png)

```
An error occurred?
Post the full traceback inside these 'code fences'!
```

### Tested environment(s)

 * PyQtGraph version: 0.13.1
 * Qt Python binding: PyQt5 5.15.9 Qt 5.15.2
 * Python version: 3.11.2
 * NumPy version: 1.24.2
 * Operating system: Windows 10
 * Installation method:  pip

**Comment by pijyoi** [comment]
seems to work fine for me
```python
import pyqtgraph as pg
import numpy as np

pg.mkQApp()
pw = pg.PlotWidget()
pw.show()
data = np.eye(20000, dtype=np.float32)
print(f"{data.shape}, {data.nbytes/1e9:.1f} GB")
imgItem = pg.ImageItem(data)
pw.addItem(imgItem)
pg.exec()
```

**Comment by sharon92** [comment]
@pijyoi your examples work on my system too.

I guess the problem comes from QtGraphicsView/QGraphicsScene or QImage. I am plotting inside Qt UI GraphicsView and this is what it shows me:
![image](https://user-images.githubusercontent.com/51754340/221836595-f79c8e31-03a4-49cd-ae01-3499fa86d92c.png)
Notice the histogram does show valid values.

In my testing it could only plot images with maximum of 8000*8000 pixels (raster values), so I guess I will have to break my image in chunks and plot.

**Comment by pijyoi** [comment]
Did you happen to have enabled OpenGL for QGraphicsView?
