### ISSUE TITLE
PlotWidget is crashing when calling close method with PySide2

### ISSUE THREAD

**Issue by mrawd** [pyqtgraph/pyqtgraph#2633]
I have an application that is using PlotWidget for displaying graphs. When widget is open and application is trying to close it on exit, it is crashing. Code is calling PlotWidget.close() and for some reason self.plotItem is already None and it crashes on that first line. Adding a check like this below, avoids the crash:

`    def close(self):`
`        if self.plotItem is not None:`
`            self.plotItem.close()`
`            self.plotItem = None`

Is this a know issue and what is the best way to get around this problem?
ps. using 64-bit python 3.9.9 here

_Originally posted by @mrawd in https://github.com/pyqtgraph/pyqtgraph/discussions/2630_

**Comment by pijyoi** [comment]
The following snippet ends normally on my system.
Could you provide a short runnable example that demonstrates your issue?
```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore

app = pg.mkQApp()
plt = pg.PlotWidget()
plt.plot([1,2,3])
plt.show()

def callback_last():
    print('last window closed')
app.lastWindowClosed.connect(callback_last)

cntdown = 5
def callback_close():
    global cntdown
    cntdown -= 1
    print(cntdown)
    if cntdown == 0:
        print('closing window')
        plt.close()
timer = QtCore.QTimer()
timer.timeout.connect(callback_close)
timer.start(1000)

pg.exec()
print('ended')
```

**Comment by mrawd** [comment]
![image](https://user-images.githubusercontent.com/17886932/222760893-a79379c9-c67e-49c5-95ff-8486932f80df.png)

**Comment by mrawd** [comment]
If I run this through debugger I could get more info on what is going on below:
![image](https://user-images.githubusercontent.com/17886932/222763186-c6be6304-9e3c-4a81-b8ed-7f0db2c37297.png)

Basically, above exceptions happen when PlotItem.close() method clears all the axes and assign axes to None on line 395

**Comment by mrawd** [comment]
After digging a bit deeper here I figured out what was the issue with this code. Here is the simple test code that reproduced the issue:
`
import sys
from PySide2.QtWidgets import QApplication, QMainWindow, QPushButton
from pyqtgraph import PlotWidget
import atexit


class MainWindow(QMainWindow):

    def __init__(self):
        super().__init__()
        self.pg = None
        self.button = QPushButton("Create QtGraph")
        self.setCentralWidget(self.button)

        self.button.pressed.connect(self.onButtonPressed)
        atexit.register(self.cleanup)

    def onButtonPressed(self):
        self.pg = PlotWidget()
        self.pg.show()

    def cleanup(self):
        if self.pg is not None:
            self.pg.close()

    def closeEvent(self, event):
        self.cleanup()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    app.exec_()
`
Reproduce it by starting the app, clicking on the button and than closing it.

What is happening there is that cleanup() code was executed twice. In the first pass, PlotWidget was successfully closed, but it also set the main object to None. When cleanup code was ran again, even though **pg** object looked valid it crashed because you cleaned it up underneath. 
If you want to keep that internal cleanup that is setting plotItem to None, you definitely need to check if that has already happened. The original code clip that I passed at first should be added there to avoid these issues in the future.

**Comment by mrawd** [comment]
I tried to fix this formatting of the code, but it just doesn't want to do the right thing there - sorry for that

**Comment by pijyoi** [comment]
You could fix your issue in two ways:
1) by setting `self.pg = None` after calling `self.pg.close()`.
2) not registering an `atexit` handler.

In my opinion, registering an `atexit` handler to a **method** of a widget is the wrong thing to do. A reference to the Python object is held and is kept alive until program exit.

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtWidgets
import atexit

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.pg = None
        self.button = QtWidgets.QPushButton("Create QtGraph")
        self.setCentralWidget(self.button)

        self.button.pressed.connect(self.onButtonPressed)
        atexit.register(self.cleanup)

    def onButtonPressed(self):
        self.pg = pg.PlotWidget()
        self.pg.show()

    def cleanup(self, note='unknown'):
        print('called by', note)
        if self.pg is not None:
            self.pg.close()
            self.pg = None

    def closeEvent(self, event):
        self.cleanup('closeEvent')

pg.mkQApp()
window = MainWindow()
window.show()
pg.exec()
```

**Comment by mrawd** [comment]
If code is internaly setting objects to None, it should be checking for state of those as well. 
This is just another widget object and you can call close() method on other widgets as many times as you wish. Fix is simple and safe and I strongly belive it should be there.
Thanks for help!

**Comment by j9ac9k** [comment]
Checking for states of objects like that if memory serves has been a source of segfaults, which we cannot safely catch.  I don't think there is anything here that pyqtgraph can realistically do here.
