### ISSUE TITLE
Hi, I suggest import the github docs of pyqtgraph to readthedocs.org

### ISSUE THREAD

**Issue by liubenyuan** [pyqtgraph/pyqtgraph#265]
To make it more publicity and make the docs more up-to-date.

BTW: can I do a Chinese translation to the docs of pyqtgraph ?

**Comment by liubenyuan** [comment]
I put my fork on readthedocs.org, http://pyqtgraph.readthedocs.org/

I do not know whether this violate the primary git repository of pyqtgraph, as in readthedocs, it only displays `pyqtgraph` in the url address.

**Comment by campagnola** [comment]
It would be better if it pointed to the main pyqtgraph repository. Is it possible for you to make this change, or would I have to do that?

**Comment by liubenyuan** [comment]
I pointed to the main repository.
