### ISSUE TITLE
Error in color displayed with ImageItem and ImageView

### ISSUE THREAD

**Issue by jmkerloch** [pyqtgraph/pyqtgraph#2651]
### Short description
I want to display a .png in pyqtgraph but the image produced doesn't seems to have a the proper color.

I think I'm missing something quite simple but I can figure out what it is. 

Here is the file used for test : ![avatar](https://user-images.githubusercontent.com/53606373/225309164-bc92807c-46b8-462d-b0f4-c7ef8486c48c.png) (named `avatar.png` in the code example)

### Code to reproduce

```python
import sys

import pyqtgraph as pg
import numpy as np

from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QHBoxLayout, QWidget, QSplitter


class MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)

        # Define central widget and add splitter
        layout = QHBoxLayout()
        self.setCentralWidget(QWidget())
        self.centralWidget().setLayout(layout)

        splitter = QSplitter(self)
        layout.addWidget(splitter)

        # Define used image
        img = QImage("avatar.png")
        imgArray = pg.imageToArray(img)

        # Create PlotWidget for ImageItem
        self.plot = pg.PlotWidget(name="Plot", title="test")
        self.plot.setBackground('white')
        imgitem = pg.ImageItem(imgArray)
        self.plot.addItem(imgitem)

        # Create label and set pixmap
        self.label = QLabel(self)
        self.label.setPixmap(QPixmap.fromImage(img))

        # Create ImageView
        self.img_view = pg.ImageView()
        self.img_view.setImage(imgArray)

        # Add to splitter
        splitter.addWidget(self.plot)
        splitter.addWidget(self.img_view)
        splitter.addWidget(self.label)

        self.showMaximized()


def main():
    app = QApplication(sys.argv)
    main_ = MainWindow()
    main_.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    print(f"{pg.__version__=}")
    print(f"{pg.Qt.VERSION_INFO=}")
    print(f"{np.__version__}")
    main()

```

### Expected behavior
I was expecting the image displayed in `self.img_view` and `pg.ImageItem` to be the same as the one displayed in `self.label`

### Real behavior

![image](https://user-images.githubusercontent.com/53606373/225309988-ef394c03-902f-4fc7-b507-a056ce2fefe8.png)

### Tested environment(s)

 * PyQtGraph version: 0.13.2
 * Qt Python binding: PyQt5 5.15.9 Qt 5.15.2
 * Python version: 3.10.6
 * NumPy version: 1.24.2
 * Operating system: Ubuntu 22.04
 * Installation method: pip

**Comment by pijyoi** [comment]
When you read a PNG using `QImage`, it usually gets stored internally in memory as RGB32 or ARGB32 format. 
However `ImageItem` actually expects the image (in this case) to be in RGBA8888 format.

**Comment by jmkerloch** [comment]
What I don't understand is that I'm passing a image with RGBA8888 format (image converted). And this only works with the conversion not if I keep the image.
But for me it's OK to close the issue since I found a way to use my image.

**Comment by pijyoi** [comment]
pg.imageToArray was not intended to be used to load a QImage into a pg.ImageItem.

It does happen that its implementation assumes 4-bytes per pixel, so when you pass in an RGBA8888 QImage, something useful comes out. 

What I am saying is that you are using undocumented/undefined functionality of imageToArray.

**Comment by jmkerloch** [comment]
Is there a recommanded way of loading an image file into a `pg.ImageItem` ? Should I use `numpy` ?
I'm in a 'restricted' environnement where I can't import all the python package that I want (a QGIS plugin), that's why I wanted to use Qt to load image.

**Comment by pijyoi** [comment]
Would Pillow be a package that is available to you? How is it that pyqtgraph is available to you?
```python
import pyqtgraph as pg
from PIL import Image
import numpy as np

pg.mkQApp()
pw = pg.PlotWidget()
pw.invertY(True)
imgitem = pg.ImageItem(axisOrder='row-major')
pw.addItem(imgitem)
pw.show()

img = Image.open('qimage.png')
arr = np.array(img)
imgitem.setImage(arr)

pg.exec()
```

**Comment by jmkerloch** [comment]
I have a trick to get some packages :wink: but I want to avoid dependency.

I will keep use of QImage with the proper conversion.

Many thanks for all the tips @pijyoi !

I'm closing the issue.
