### ISSUE TITLE
PlotItem leak since PySide6 6.5.0

### ISSUE THREAD

**Issue by pijyoi** [pyqtgraph/pyqtgraph#2672]
### Short description

Since PySide6 6.5.0, some objects within `PlotItem` will be leaked when `PlotItem` is destroyed.

This issue is a spinoff from #2665 as this issue is specific to PySide6 6.5.0.

### Code to reproduce

Additional `psutil` library is used to show memory growth.

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore
import psutil

app = pg.mkQApp()
timer = QtCore.QTimer()
proc = psutil.Process()

rss0 = proc.memory_info().rss

cnt = 0
def timer_cb():
    global cnt
    rss = proc.memory_info().rss
    print(f'{cnt}: {(rss - rss0)/1048576:.1f} MB')
    pg.PlotItem()
    cnt += 1
    if cnt > 100:
        timer.stop()
        app.exit()

timer.timeout.connect(timer_cb)
timer.start(0)
pg.exec()
```

### Expected behavior

Memory usage should stabilize.

### Real behavior

Memory usage continues to grow with each iteration.

### Tested environment(s)

 * PyQtGraph version: master 
 * Qt Python binding: PySide6 6.5.0 
 * Python version: Python 3.10.10
 * NumPy version: 1.24.2 
 * Operating system: Windows 11
 * Installation method: pip 

### Additional context
Doesn't occur for PySide2 5.12.2, PyQt5 5.15.9, PySide6 6.4.3, PyQt6 6.4.2

**Comment by pijyoi** [comment]
No leak for PyQt6 6.5.0 either.

**Comment by pijyoi** [comment]
Minimal pyqtgraph-free script that leaks on PySide >= 6.5.0
```python
from PySide6 import QtCore, QtWidgets
import psutil

class Leaker:
    def __init__(self):
        parent = None
        parent = QtWidgets.QWidget()    # this line seemingly makes PySide < 6.5.0 not leak
        wgt= QtWidgets.QSpinBox(parent)
        wgt.valueChanged.connect(self.mkChangeCallback(wgt))

    def mkChangeCallback(self, w):
        return lambda *args: self.widgetChanged(w, *args)
        
    def widgetChanged(self, w, *args):
        pass

app = QtWidgets.QApplication([])
timer = QtCore.QTimer()
proc = psutil.Process()

rss0 = proc.memory_info().rss

cnt = 0
def timer_cb():
    global cnt
    rss = proc.memory_info().rss
    print(f'{cnt}: {(rss - rss0)/1048576:.1f} MB')
    Leaker()
    cnt += 1
    if cnt > 500:
        timer.stop()
        app.exit()

timer.timeout.connect(timer_cb)
timer.start(0)
app.exec() if hasattr(app, 'exec') else app.exec_()
```

**Comment by j9ac9k** [comment]
Hi @adrianghc 

The difference is the reference to `self`.  We ran into this problem in another part of the library some eons ago and decided to just work around it at the time.  We should have reported upsteam them, sorry!

**Comment by adrianghc** [comment]
We believe we have now fixed this bug: https://bugreports.qt.io/browse/PYSIDE-2299 It will be part of the PySide 6.5.1 release. Thank you for your patience, and let us know if you continue to have problems.
