### ISSUE TITLE
How do I style pyqtgraph to make it look like matplotlib？

### ISSUE THREAD

**Issue by vincentguiling** [pyqtgraph/pyqtgraph#2673]
I tried setting the background color and foreground color. However, there is a big difference between pyqtgraph and matplotlib in colors and width of items, which is complex to modify them. Is there any method to set the default style of pyqtgraph to make it look like matplotlib?

**Comment by vincentguiling** [comment]
Thank you for your reply, and sorry to bother you

**Comment by j9ac9k** [comment]
Hardly a bother, it's good to know that this is a feature that is important to users.  The best way to help out with that is to review/comment on the PRs submitted, and test them out yourself.
