### ISSUE TITLE
TypeError: GraphicsWidgetAnchor.__init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Khanhlinhdang** [pyqtgraph/pyqtgraph#2680]
pyqtgraph.examples.customGraphicsItem, pyqtgraph.examples.customPlot and alot examples are not working.
it show error "TypeError: GraphicsWidgetAnchor.__init__() takes 1 positional argument but 2 were given"

**Comment by j9ac9k** [comment]
Duplicate of #2679 and #2674 and already fixed in #2662
