### ISSUE TITLE
This is not working in case parameterTree example

### ISSUE THREAD

**Issue by yashwanth7007** [pyqtgraph/pyqtgraph#2685]
https://github.com/pyqtgraph/pyqtgraph/blob/7642e18e1d1ff569b1ef6db844c09280fc5fcddf/pyqtgraph/examples/_buildParamTypes.py#L1

**Comment by yashwanth7007** [comment]
from pyqtgraph.examples._buildParamTypes import makeAllParamTypes
this works

python execution path can search files in pyqtgraph directory level and this helper file is in examples directory!

**Comment by ntjess** [comment]
`paramtreecfg` is only meant for running the `ParameterTree` example, and it seems to open for me:
```bash
python -m pyqtgraph.examples.parametertree
```

Can you post the command you are running (and which directory it is in) when you get errors?

**Comment by j9ac9k** [comment]
Closing due to being unable to replicate
