### ISSUE TITLE
GLScatterPlotItem broken on Xubuntu 13.10 + nouveau

### ISSUE THREAD

**Issue by campagnola** [pyqtgraph/pyqtgraph#27]
Seems to only affect when pxMode=False.
Details and screenshot here:
https://groups.google.com/forum/#!msg/pyqtgraph/sfnsbhXVSbU/zz9aLiJLOVoJ

**Comment by 2xB** [comment]
Cannot reproduce on Xubuntu 16.04 using pyqtgraph 0.10.0, Python 3.6.3 (Anaconda) and Qt 5.9.6.
