### ISSUE TITLE
Camera jumps on mouse drag in 3D plots

### ISSUE THREAD

**Issue by nvaytet** [pyqtgraph/pyqtgraph#2703]
### Short description

Taking any 3D example from the repository (e.g. the [surface example](https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/examples/GLSurfacePlot.py)), when using the left mouse click and drag to rotate the camera around the scene, the very first drag works as expected.

After that, if I click and start dragging again, the camera jumps to a (seemingly?) random point in the 3D space.

However, if I click and drag (the camera jumps a first time), and then release the mouse button, and make sure I do not move the mouse, and then click and drag again, the camera stays in the correct place.

### Code to reproduce

Use the surface plot example: https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/examples/GLSurfacePlot.py

### Tested environment(s)

 * PyQtGraph version: 0.13.3
 * Qt Python binding: PySide2 5.15.8 Qt 5.15.8
 * Python version: 3.10.9
 * NumPy version: 1.24.2
 * Operating system: Ubuntu 20.04
 * Installation method: conda (conda-forge)

**Comment by pijyoi** [comment]
Was fixed in #2698.
