### ISSUE TITLE
ScatterPlotItem is displayed with wrong values when `logmode` is set `True`

### ISSUE THREAD

**Issue by MasaakiU** [pyqtgraph/pyqtgraph#2725]
### Short description

ScatterPlotItem is displayed with wrong values when `logmode` was set `True`.

### Code to reproduce

```python
import pyqtgraph as pg
app = pg.mkQApp()
pw = pg.PlotWidget()
pw.show()

pdi = pg.PlotDataItem(pen=pg.mkPen({"color":"#000000", "width":2}))
pdi.setData([10, 20, 30], [10, 20, 30])
pw.addItem(pdi)

spi = pg.ScatterPlotItem(size=1, brush=pg.mkBrush(0, 0, 0, 127), pen=pg.mkPen({"color":"#000000", "width":10}))
spi.setData([10, 20, 30], [10, 20, 30])
pw.addItem(spi)

pw.setLogMode(True, False)
app.exec()
```

### Expected behavior

x values of ScatterPlotItem should be displayed as `10^1`, `2*10^1`, and `3*10^1`.

### Real behavior

x values of ScatterPlotItem was displayed as `10^10`, `10^20`, and `10^30`.
Without `pw.setLogMode(True, False)` line, there is no problem and the PlotDataItem and ScatterPlotItem in the above script is displayed with exactly the same location, but it goes wrong if the `logmode` is set `True`.
Of note, this happens regardless of x or y axis.

<img width="640" alt="Screenshot 2023-05-18 at 16 16 15" src="https://github.com/pyqtgraph/pyqtgraph/assets/51690596/f8c975fd-9ef4-4621-a810-4455b4a5f799">

### Tested environment(s)

 * PyQtGraph version: 0.13.3
 * Qt Python binding: PyQt6 6.4.2 Qt 6.4.2
 * Python version: 3.10.0
 * Operating system: macOS Ventura 13.0.1
 * Installation method: pip

### Notes

As far as I looked into the source code, apparently, `ScatterPlotItem` class does not have `setLogMode` method, that is why it displays with wrong values.

**Comment by pijyoi** [comment]
```python
import pyqtgraph as pg
app = pg.mkQApp()
pw = pg.PlotWidget()
pw.show()

pdi = pg.PlotDataItem(
    pen=pg.mkPen({"width":2}),
    symbolSize=1,
    symbolBrush=pg.mkBrush(0, 0, 0, 127),
    symbolPen=pg.mkPen({"width":10})
    )
pdi.setData([10, 20, 30], [10, 20, 30])
pw.addItem(pdi)

pw.setLogMode(True, False)
app.exec()
```

**Comment by MasaakiU** [comment]
Thanks.
Yeah, it's possible by using `PlotDataItem`,  but my point is that there's a bug in `ScatterPlotItem` and I am not looking for alternative ways.

Actually, all I need is scatter plot and the line plot is not required.
In that case, it seems more natural to use `ScatterPlotItem`, but there's a bug when it is used with the `logmode`.

Is `ScatterPlotItem` obsolete?
In that case, I can use `PlotDataItem` unconnecting all points by using `connect` kwargs.
Still, it's confusing that incomplete scripts are left.

**Comment by pijyoi** [comment]
I wouldn't call it a bug. Both `ScatterPlotItem` and `PlotCurveItem` are only concerned with drawing. The transformation is handled by 'PlotDataItem'. 

To disable line drawing, specify `pen=None`. (https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/plotdataitem.html)
```python
import pyqtgraph as pg
app = pg.mkQApp()
pw = pg.PlotWidget()
pw.show()

pdi = pg.PlotDataItem(
    pen=None,
    symbolSize=1,
    symbolBrush=pg.mkBrush(0, 0, 0, 127),
    symbolPen=pg.mkPen({"width":10})
    )
pdi.setData([10, 20, 30], [10, 20, 30])
pw.addItem(pdi)

pw.setLogMode(True, False)
app.exec()
```

**Comment by MasaakiU** [comment]
Ohh, I see, probably I did not understand the meaning of `PlotDataItem`.
I should have read the description of `PlotDataItem`, which clearly saying:

> While it is possible to use [PlotCurveItem](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/plotcurveitem.html#pyqtgraph.PlotCurveItem) or [ScatterPlotItem](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/scatterplotitem.html#pyqtgraph.ScatterPlotItem) individually, this is recommended only where performance is critical and the limited functionality of these classes is sufficient.

Thanks a lot, @pijyoi !
