### ISSUE TITLE
ModuleNotFoundError: No module named 'pyqtgraph.pgcollections'

### ISSUE THREAD

**Issue by mxa4646** [pyqtgraph/pyqtgraph#2729]
I am running someone's ancient code(maybe), and face the title ploblem. My pyqtgraph version is 0.13.3. I think maybe `pgcollections` has been deprecated in some version. So which version should I downgrade to?
Here is the log:

```
Traceback (most recent call last):
  File "fallDetection_main.py", line 12, in <module>
    from pyqtgraph.pgcollections import OrderedDict
ModuleNotFoundError: No module named 'pyqtgraph.pgcollections'
```

**Comment by ksunden** [comment]
It was deprecated in #1576 for 0.12 (so present, but will warn in that series) It was removed in 0.13.0
