### ISSUE TITLE
Failing travis

### ISSUE THREAD

**Issue by ericdill** [pyqtgraph/pyqtgraph#274]
If you restart travis, does master still fail on py2.7?  It seems like there is something strange going on with pytest and the failure probably has nothing to do with pyqtgraph.  

https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/105937939#L650

**Comment by ericdill** [comment]
cc @campagnola

**Comment by campagnola** [comment]
I have been seeing these a lot lately. Usually restarting the test does
correct it, but what a pain  :/

**Comment by 2xB** [comment]
Travis is currently working, although failing due to other issues reported here. Therefore this issue currently does not cover anything further.
If someone wishes to reopen this issue, e.g. regarding #895, please comment!
