### ISSUE TITLE
Feature Request: Dockarea - Restrict Drop Area

### ISSUE THREAD

**Issue by WilliamHuey** [pyqtgraph/pyqtgraph#2745]
The dockarea in pyqtgraph allows you to drag and drop into the four sides of the dockpanel for rearrangements. Is there a way to restrict the drop regions to the top and bottom position so that the vertical left and right side areas highlighted in red of the screenshot are forbidden for dropping?

![dockarea-limit-drop-areas-highlight](https://github.com/pyqtgraph/pyqtgraph/assets/1279060/3bf1ac17-c174-43b3-a79f-9c884914919f)

Thanks

**Comment by pijyoi** [comment]
A 'Dock' instance has a `DockDrop` member (https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/dockarea/Dock.py#L15)
and `DockDrop` has a `removeAllowedArea` method (https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/dockarea/DockDrop.py#L19)

**Comment by WilliamHuey** [comment]
Thanks pijyoi for the quick reply. Got it to work.
