### ISSUE TITLE
Enums missing in PyQt6 for QEvent Type and QTextCursor, MoveOperation, Move Mode

### ISSUE THREAD

**Issue by usysinct** [pyqtgraph/pyqtgraph#2754]
There appears to be missing enums. QEvent.KeyPress does not appear to exist. I can get this code to work by using the value 6.

    def eventFilter(self, obj, event):
        #if event.type() == QtCore.QEvent.KeyPress and obj is self._small_editor:
        if event.type() == QEvent.KeyPress and obj is self._small_editor: # QEvent::KeyPress = 6 https://doc.qt.io/qt-6/qevent.html
        # https://doc.qt.io/qtforpython-5/PySide2/QtCore/QEvent.html#PySide2.QtCore.PySide2.QtCore.QEvent.type
        # https://doc.qt.io/qtforpython-5/PySide2/QtGui/QKeyEvent.html#qkeyevent
            #if event.key() == QtCore.Qt.Key_Return and self._small_editor.hasFocus():
            if event.key() == Qt.Key.Key_Return and self._small_editor.hasFocus():
                print('Enter pressed on QTextEditor')
                self.cmd_parser(self._small_editor)
                return True
        return super().eventFilter(obj, event)

Also, I've tried replacement of QTextCursor.KeepAnchor and QTextCursor.STartOfLine with their integer values but get the following error.

cursor.movePosition(QTextCursor.StartOfLine, QTextCursor.KeepAnchor)

Traceback (most recent call last):
  File "E:\Design\VTOL_Twin_Rotor_Airfoil\3D_IMU_10DOF.py", line 532, in eventFilter
    self.cmd_parser(self._small_editor)
  File "E:\Design\VTOL_Twin_Rotor_Airfoil\3D_IMU_10DOF.py", line 512, in cmd_parser
    cursor.movePosition('3', QTextCursor_KeepAnchor)
TypeError: movePosition(self, op: QTextCursor.MoveOperation, mode: QTextCursor.MoveMode = QTextCursor.MoveAnchor, n: int = 1): argument 1 has unexpected type 'int'

# https://doc.qt.io/qt-6/qtextcursor.html#MoveOperation-enum
QTextCursor_StartOfLine = 3
QTextCursor_EndOfLine = 13
# https://doc.qt.io/qt-6/qtextcursor.html#MoveMode-enum
QTextCursor_MoveAnchor = 0
QTextCursor_KeepAnchor = 1
# https://doc.qt.io/qt-6/qevent.html#Type-enum
QEvent_KeyPress = 6
QEvent_KeyRelease = 7

**Comment by pijyoi** [comment]
```python
In [1]: from PyQt6 import QtCore, QtGui, QtWidgets

In [2]: QtCore.QEvent.Type.KeyPress
Out[2]: <Type.KeyPress: 6>

In [3]: QtGui.QTextCursor.MoveOperation.StartOfLine
Out[3]: <MoveOperation.StartOfLine: 3>

In [4]: QtGui.QTextCursor.MoveMode.KeepAnchor
Out[4]: <MoveMode.KeepAnchor: 1>
```

**Comment by usysinct** [comment]
Thanks. The API is very clear i.e. PySide2.QtGui.QTextCursor.SelectionType. I must have been tired to have ignored the obvious. ;-)
