### ISSUE TITLE
Issue with adding Widget to Pyside6 Layout

### ISSUE THREAD

**Issue by hendrikE** [pyqtgraph/pyqtgraph#2759]
Hey everyone,

I've encountered an issue with pyqtgraph, and I'm not sure if it is a bug or if I'm misusing pyqtgraph.
Below is a minimum working script of what I'm trying to do:

    import sys
    
    import numpy as np
    
    import PySide6
    import pyqtgraph as pg
    import pyqtgraph.opengl as gl
    
    from PySide6 import QtWidgets
    from PySide6.QtWidgets import QWidget, QHBoxLayout
    
    
    print(isinstance(gl.GLViewWidget, QWidget))
    
    
    class MainWidget(QWidget):
    
        def __init__(self):
            super().__init__()
    
            self.view = gl.GLViewWidget()
    
            self.layout = QHBoxLayout()
            self.layout.addItem(self.view)
    
            self.setLayout(self.layout)
    
    
    if __name__ == "__main__":
        app = QtWidgets.QApplication([])
    
        widget = MainWidget()
        widget.show()
    
        sys.exit(app.exec())

This produces the following error:

    False
    Traceback (most recent call last):
      File "C:\Users\USER\Desktop\TestQT\main.py", line 32, in <module>
        widget = MainWidget()
                 ^^^^^^^^^^^^
      File "C:\Users\USER\Desktop\TestQT\main.py", line 24, in __init__
        self.layout.addItem(self.view)
    TypeError: 'PySide6.QtWidgets.QBoxLayout.addItem' called with wrong argument types:
      PySide6.QtWidgets.QBoxLayout.addItem(GLViewWidget)
    Supported signatures:
      PySide6.QtWidgets.QBoxLayout.addItem(PySide6.QtWidgets.QLayoutItem)
    
    Process finished with exit code 1

From my understanding, the GLViewWidget should be an instance of QtWidget, but somehow it isn't and thus it can't be added to the layout. I tried around a lot, set up different virtual environments, made sure there is no other PyQt or PySide versions, checked during the initialization that in fact PySide6 is recognized and used as the correct version, but I still end up with this error.

My setup is:
Windows 11
Python 3.11.4 (also tested 3.10.3)
Pyside6 6.5.1.1
pyqtgraph 0.13.3
PyOpenGL 3.1.7

Grateful for any input, not sure what else to try.

Thanks!

**Comment by pijyoi** [comment]
```python
print(issubclass(gl.GLViewWidget, QWidget))
print(isinstance(self.view, QWidget))
self.layout.addWidget(self.view)
```

**Comment by hendrikE** [comment]
My bad, so the GLViewWidget object self.view is an instance of QWidget, which makes this just more confusing.

**Comment by hendrikE** [comment]
Sorry, I just realized the mix-up between addItem() and addWidget(), apparently I forgot how to read. It works now, thanks for the help!
