### ISSUE TITLE
Bug in slider parameter

### ISSUE THREAD

**Issue by MrBeee** [pyqtgraph/pyqtgraph#2786]
### Short description

Bug that precludes use of suffix in SliderParameter
### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np
from pyqtgraph.parametertree import (Parameter, ParameterTree, registerParameterType)

        ...
        colorParams = [
            dict(name='Color Settings', type='group', children=[
                dict(name='Opacity', type='slider', limits=[0,100], value = 60.0, suffix='%'),
            ]),
        ]
        self.parameters = pg.parametertree.Parameter.create(name='Analysis Settings', type='group', children=colorParams)
        ...
```

### Expected behavior

Slider should show a number 0 - 100, followed by a '%' suffix

### Real behavior

Application crashes, as it refers to a non-existing method
```
An error occurred?
Post the full traceback inside these 'code fences'!

AttributeError
'SliderParameterItem' object has no attribute '_updateLabel'
```

### Solution
 1. Please delete line 32, containing ``` self._updateLabel(self.slider.value())``` as this method does not exist
 2. After ```layout = QHBoxLayout()``` Please add a line containing ```layout.setContentsMargins(0, 0, 0, 0)```
 3. In doing so, the height of the slider item stays equal to the other items (=20), now there is a *bulge*

### Additional context
None

**Comment by MrBeee** [comment]
Thanks for fixing this !

@j9ac9k   Will three be a new pyqtgraph release anytime soon ?
I would like to stick to the official distribution, rather than using a development branch
This in view of others using my code, as well as pyqtgraph...

Cheers,
Bart

**Comment by j9ac9k** [comment]
Hi Bart,

Next release, not sure, probably not too far off, but I do have an upcoming vacation ... I need to address a regression in the SVG exporter I added.  My time with the library is very much feast or famine, recently been going through a famine period where it hasn't been getting the time/attention needed. I would anticipate no earlier than 3 weeks, but I'm awful at predicting these things, sorry!
