### ISSUE TITLE
Item selection buggy in zoomed-in ViewBox

### ISSUE THREAD

**Issue by loiblj** [pyqtgraph/pyqtgraph#279]
See [here](https://groups.google.com/forum/#!topic/pyqtgraph/VME5MiwGTjY)

I have QGraphicsItem objects where it is natural to set the flag ItemIgnoresTransformations and I also have ItemIsSelectable.  If such an object is added to a pyqtgraph viewbox then when you zoom in, the selection size seems to approximately reduce by the scale factor.  So if you zoom in far enough then you can only select the object by picking it right in the center.  Is this a "feature" or a "bug"?  If instead you scale up the boundingRect() by the zoom scale then it (sort of) works as expected.  I've attached some sample code (without the scaling done in boundingRect(), so this is the version where the selection doesn't work as I hoped it would).

**Comment by mliberty1** [comment]
See https://github.com/pyqtgraph/pyqtgraph/issues/1612#issuecomment-804041515 for a workaround.  This issue lies in Qt, not pyqtgraph, so the workaround is the best pyqtgraph-level approach.

I recommend closing this issue.

**Comment by j9ac9k** [comment]
Closing as a workaround by @mliberty1 was posted.
