### ISSUE TITLE
Qt returns wrong `AxisItem` width in tests

### ISSUE THREAD

**Issue by matenestor** [pyqtgraph/pyqtgraph#2816]
This is a minimal example of more complex code I am working on. I am trying to test if my right axes are getting correct widths set. However, in the tests it is not possible to change the width of an `AxisItem` object. As I write in the code comment, my right axis object serves only as a margin setter[1]. It needs to be dynamically changed according to a plot which is below and has two y-axes. I am keeping the right side area width in sync like that, so the bottom plot's curves don't get hidden when they reach the end. Like so: [2]

Both plots are embedded in `QMainWindow`. I am using an instance of a `QApplication` to `exec` the program, not pyqtgraph.

### Code to reproduce

```python
from pytest import approx
from pyqtgraph import PlotWidget, mkPen


def test_right_axis(qtbot):
    plot = PlotWidget()

    # the right axis serves only as a margin for the bottom axis,
    # so the right side is not at the very edge of plot
    plot.plotItem.getAxis("right").show()
    plot.plotItem.getAxis("right").style["showValues"] = False
    plot.plotItem.getAxis("right").setPen(mkPen(color="white"))

    with qtbot.waitExposed(plot):
        plot.show()

        plot.getAxis("left").setWidth(100)
        plot.getAxis("right").setWidth(100)

        # OK
        assert plot.getAxis("left").width() > 0
        # FAILS
        assert plot.getAxis("left").width() == approx(100)
        assert plot.getAxis("right").width() > 0
        assert plot.getAxis("right").width() == approx(100)
```

### Expected behavior

Immediate set of the axis' width, [3] so it is possible to get it back with `AxisItem.width()` in the tests.

The point [3] shows a solution if you want to pragmatic, so **my question now is**: what to _call_ or _emit_ in order to get the value with `AxisItem.width()` set by me with `AxisItem.setWidth()`, without a need to _call_ `plot.show()`?

### Real behavior

Waiting for Qt to update the width, so I am getting back the old width value.

### Additional context

[1]
While writing this issue I found `plot.getPlotItem().layout.setContentsMargins(1,1,100,1)`, which does the same. But then I have no way to get value of the margins, because `self.plot_mid.plot.getPlotItem().getContentsMargins()` return `(0, 0, 0, 0)`, because of some arcane Qt behavior :facepalm: 

[2] 
![image](https://github.com/pyqtgraph/pyqtgraph/assets/44382264/26f42a41-ac7e-45db-b8dc-b5a625972417)

[3] Now I realized I can use `AxisItem.fixedWidth`. That gets set immediately, so that can be a **solution**. However, I still wonder what in pyqtgraph causes the update in Qt that makes also `AxisItem.width()` return something else?

### Tested environment(s)

 * PyQtGraph version: 0.13.3
 * Qt Python binding: 6.5.1.1
 * Python version: 3.10
 * NumPy version: 1.24.2

**Comment by pijyoi** [comment]
inserting a `QApplication.instance().processEvents()` after your `setWidth()`s seems to make it work.

**Comment by matenestor** [comment]
Hm, yes, for the example I provided it works. In my program it doesn't even when I use it multiple times or set `maxtime`. There must be higher complexity, I guess...
Well, I wrote the tests without using GUI itself thanks to `AxisItem.fixedWidth`, `AxisItem.range` and modifying what `AxisItem.width()` returns. Thanks :slightly_smiling_face:

**Comment by j9ac9k** [comment]
In general, I recommend staying away from `QApplication.instance().processEvents()` it's been a continuous source of problematic behavior for us, and I'm trying to remove it from the library except in instances of the test suite.
