### ISSUE TITLE
Blurry scatter plot on high DPI monitor

### ISSUE THREAD

**Issue by kaktus018** [pyqtgraph/pyqtgraph#2854]
### Short description
I'm experiencing an issue with blurry scatter plots on high DPI monitors. The plots look fine on a HD screen, but with a resolution of 2560x1440 and the monitor scaling set to 125% in the Windows settings, the single points have blurry outlines.

### Code to reproduce
The following code makes two windows, one with pxMode=True and the other with pxMode=False and antialias=False.
```
import pyqtgraph as pg

plotWidget = pg.plot()
plotWidget.setBackground('w')
scatter = pg.ScatterPlotItem(size=10, symbol='o', pen=None, brush=pg.mkBrush((0,115,190)))
x = [1,2,3,4,5,6,7,8,9,10]
y = [5,4,3,2,1,6,7,8,9,10]
scatter.addPoints(x, y)
plotWidget.addItem(scatter)

plotWidget = pg.plot()
plotWidget.setBackground('w')
scatter = pg.ScatterPlotItem(size=0.5, pxMode=False, antialias=False, symbol='o', pen=None, brush=pg.mkBrush((0,115,190)))
scatter.addPoints(x, y)
plotWidget.addItem(scatter)
```
<img src="https://github.com/pyqtgraph/pyqtgraph/assets/26413439/ea51980e-dba8-4909-866a-e7084e395c52.png" width=50% height=50%>

The image to the right is with pxMode=False and does not have blurry points. However, I want to have the points properly scaled, which is not possible with pxMode=False (as far as I know). I suspect that the blurriness originates from antialiasing, which cannot be turned off when pxMode=True.

Any ideas?

### Tested environment(s)

 * PyQtGraph version: 0.13.3
 * Qt Python binding: PySide6 6.6.0 Qt 6.6.0
 * Python version: 3.11.4
 * NumPy version: 1.25.2
 * Operating system: Windows 10

**Comment by pijyoi** [comment]
I find that using `pxMode=True` (default True) together with `useCache=False` (default True) removes the blurriness.

**Comment by kaktus018** [comment]
Thanks for the remark! Indeed, the points look much better when using `useCache=False`.
