### ISSUE TITLE
InteractiveFunctions do not work with class methods

### ISSUE THREAD

**Issue by Antyos** [pyqtgraph/pyqtgraph#2925]
### Short description

The `InteractiveFunction` does not work when decorating class methods. This is because `InteractiveFunction` is missing `__get__()` method. A great (albeit technical) write up about why this is necessary can be found in the [blog](https://github.com/GrahamDumpleton/wrapt/blob/develop/blog/02-the-interaction-between-decorators-and-descriptors.md#wrappers-as-descriptors) for the Python library Wrapt.

The blog goes into much more detail, but here's a short excerpt about how to use decorators on class methods:

> ```python
> class bound_function_wrapper(object):
>     def __init__(self, wrapped):
>         self.wrapped = wrapped
>     def __call__(self, *args, **kwargs):
>         return self.wrapped(*args, **kwargs)
> 
> class function_wrapper(object):
>     def __init__(self, wrapped):
>         self.wrapped = wrapped
>     def __get__(self, instance, owner):
>         wrapped = self.wrapped.__get__( instance, owner)
>         return bound_function_wrapper(wrapped)
>     def __call__(self, *args, **kwargs):
>         return self.wrapped(*args, **kwargs)
> ```
>
> If the wrapper is applied to a normal function, the `__call__()` method of the wrapper is used. If the wrapper is applied to a method of a class, the `__get__()` method is called, which returns a new bound wrapper and the `__call__()` method of that is invoked instead. This allows our wrapper to be used around descriptors as it propagates the descriptor protocol.

Implementing a `__get__()` method to `InteractiveFunction` is still insufficient, however, because the parameters cached is not used if the method is called from elsewhere in the class.

### Code to reproduce

Here is example code. I have also added a sample `InteractiveMethod` (this should be part of `InteractiveFunction`'s default behavior though) which achieves partial desired functionality.

```python
import pyqtgraph as pg
from pyqtgraph.parametertree import (
    InteractiveFunction,
    Parameter,
    ParameterTree,
    RunOptions,
    interact,
)
from pyqtgraph.Qt.QtWidgets import QMessageBox


class object_proxy:
    def __init__(self, wrapped, **_):
        self.wrapped = wrapped
        try:
            self.__name__ = wrapped.__name__
        except AttributeError:
            pass

    @property
    def __class__(self):
        return self.wrapped.__class__

    def __getattr__(self, name):
        return getattr(self.wrapped, name)


class bound_function_wrapper(object_proxy):

    def __init__(self, wrapped):
        super(bound_function_wrapper, self).__init__(wrapped)

    def __call__(self, *args, **kwargs):
        return self.wrapped(*args, **kwargs)


class InteractiveMethod(InteractiveFunction):
    """Like an InteractiveFunction, but for methods instead of functions.
    i.e., allows a "self" parameter.
    """

    def __init__(self, function, *, closures=None, **extra):
        super().__init__(function, closures=closures, **extra)
        # Patch in "self" argument so it doesn't appear unbound
        if "self" not in self.extra:
            self.extra["self"] = None

    def __get__(self, instance, owner):
        wrapped = self.function.__get__(instance, owner)
        return bound_function_wrapper(wrapped)


@InteractiveFunction
def myfunc(a=5):
    QMessageBox.information(None, "myfunc()", f"{a =}")


class MyClass:
    def __init__(self, x=2):
        self.x = x

    @InteractiveFunction
    def my_bad_method(self, a=5):
        QMessageBox.information(None, "MyClass.my_bad_method", f"{a = }, {self.x = }")

    @InteractiveMethod
    def my_good_method(self, a=5):
        QMessageBox.information(None, "MyClass.my_good_method", f"{a = }, {self.x = }")

    def my_other_method(self):
        self.my_good_method()


# One line of code, no name/value duplication
my_instance = MyClass(x=2)
params = Parameter.create(name="params", type="group", children=[])
interact.interact(myfunc, parent=params)
interact.interact(my_instance.my_bad_method, parent=params)    # <-- This will fail
interact.interact(my_instance.my_good_method, parent=params)
interact.interact(my_instance.my_other_method, parent=params) 

app = pg.mkQApp()
tree = ParameterTree()
tree.setParameters(params)
tree.show()
pg.exec()
```

> Side note: Based on the [examples](https://pyqtgraph.readthedocs.io/en/latest/api_reference/parametertree/interactiveparameters.html#basic-use), shouldn't [this line in interactive.py](https://github.com/pyqtgraph/pyqtgraph/blob/261a32515fac2ffd5071801ef4b69720828b5142/pyqtgraph/parametertree/interactive.py#L625) be `interact = Interactor().interact` instead of `interact = Interactor()`?

### Expected behavior
Ideally, the program should not crash if the line marked with the comment `# <-- This will fail` is uncommented.

Setting that aside, clicking the "Run" button for the "my_good_method" parameter should run `my_instance.my_good_method()` with and display the message: `a=5, self.x=2`. If you change the parameter "a" in the parameter tree to another value, say `8`, clicking "Run" should now display `a=8, self.x=2`.

Assuming "a" is still `8`, if you click the "Run" button for "my_other_method", you should get another popup window that displays `a=8, self.x=2`.

### Real behavior
Again, I'll set aside `my_instance.my_bad_method()` causing issues. 

The call to `my_instance.my_good_method()` works as intended, however, the call to `my_instance.my_other_method()` does not use the actual value of "a". Even if "a" is set to `8`, it will still display the message `a=5, self.x=2`. If I were to guess, it has something to do with the `InteractiveFunction.parameterCache` not being copied to the `bound_function_wrapper`. I have reached my limit of my understanding of Python Descriptors and fully transparent wrappers to be able to explain much further, though.

[GrahamDumpleton/wrapt](https://github.com/GrahamDumpleton/wrapt) seems to do a good job of adding "proper" decorators that can be used on class methods, but I, 1. don't feel it is appropriate to be requesting adding a new dependency as a first-time contributor, and 2. would rather adapt the current syntax of `InteractiveFunction` to work if possible.

This is the traceback if `interact()` is called with `my_instance.my_bad_method`. I don't know if this is necessary since I (hopefully) was able to explain what the issue is, but it can't hurt to share it.

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python312\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\Andrew\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Andrew\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Andrew\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Andrew\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Andrew\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Andrew\.vscode\extensions\ms-python.debugpy-2024.0.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\Andrew\Documents\code\sandbox\foo.py", line 78, in <module>
    interact.interact(my_instance.my_bad_method, parent=params)
  File "c:\Users\Andrew\Documents\code\sandbox\.venv\Lib\site-packages\pyqtgraph\parametertree\interactive.py", line 381, in interact
    raise ValueError(
ValueError: Cannot interact with `InteractiveFunction(`<my_bad_method>`) at 0x234b962cf80` since it has required parameters ['self'] with no default or closure values provided.
```
</details>

#### Using the `InteractiveFunction` decorator with arguments

It is also not currently possible to pass arguments to `InteractiveFunction` when using it as a decorator. This is because it requires that `function` be passed as its first argument. This makes sense in the non-decorator case, but may be limiting for usage as a decorator.

I would like to propose the additional change that `function` is an optional argument, and if excluded, calling `InteractiveFunction` acts as a decorator. An (incomplete) implementation of this in my `InteractiveMethod` class looks something like:

```python
class InteractiveMethod(InteractiveFunction):
    """Like an InteractiveFunction, but for methods instead of functions.
    i.e., allows a "self" parameter.
    """

    def __init__(self, function=None, *, closures=None, **extra):
        super().__init__(function, closures=closures, **extra)
        # Patch in "self" argument so it doesn't appear unbound. If the function is
        # None, we'll patch "self" in later because doing it now will cause two "self"
        # parameters to be passed when we wrap the function for real.
        if "self" not in self.extra and function is not None:
            self.extra["self"] = None

    def __get__(self, instance, owner):
        wrapped = self.function.__get__(instance, owner)
        return bound_function_wrapper(wrapped)

	# NOTE: I don't think _wrap() properly wraps the function.
    @classmethod
    def _wrap(cls, instance, function):
        return cls(function=function, closures=instance.closures, **instance.extra)

    def __call__(self, *args, **kwargs):
        # Note we now have a possible "function" parameter in args[0]
        if self.function is None:
            function = args[0]
            return self._wrap(self, function)
        # Do we check that *args is empty now, or just discard it?
        return super().__call__(**kwargs)


class MyClass:
    def __init__(self, x=2):
        self.x = x

    # This is OK now: vv
    @InteractiveMethod()
    def bonus_method1(self, a=5):
        QMessageBox.information(None, "MyClass.bonus_method1", f"{a = }, {self.x = }")

    def get_value(self):
        return 10
	
	# This doesn't recognize the closures when it's called, but it would be cool if it did.
    @InteractiveMethod(closures={"a": lambda: 3, "b": get_value})
    def bonus_method(self, a=5, b=0):
        QMessageBox.information(
            None, "MyClass.bonus_method", f"{a = }, {b = }, {self.x = }"
        )
```

### Tested environment(s)

 * PyQtGraph version: 0.13.3
 * Qt Python binding: PyQt6 6.6.1 Qt 6.6.1
 * Python version: 3.12.1
 * NumPy version: 1.26.3
 * Operating system:  Windows 10
 * Installation method: Poetry

### Additional context
P.S. It seems that Pylance (and likely other type checkers) falsely recognize the `PARAM_UNSET` sentinel as the "valid" type for several arguments in functions in `interactor.py`. For example: `Interactor().interact(..., runOptions=RunOptions.ON_CHANGED)`, `runOptions` is considered to be of type `PARAM_UNSET`. I don't have the time to add type hints to _everything_, but would it be helpful if I drafted an incremental PR that adds some type hints in the `interactor.py` module, or is it not worth doing unless more is done at once?

**Comment by ntjess** [comment]
Thanks for the detailed writeup! A few of these concepts came up during the original design of `InteractiveFunction` (https://github.com/pyqtgraph/pyqtgraph/pull/2318#issuecomment-1214982886)

I thought a lot about how to manage class method decorators, and the added complexity seemed like a strong deterrent. Future maintainers would need significantly higher knowledge python class features than is used anywhere else in pyqtgraph. This burden is much lower if end users replace their own class objects with interactive functions on instantiating an object:

<details>

<summary>Example code</summary>

```python
import inspect
from pyqtgraph.parametertree import (
    interact,
    InteractiveFunction,
    ParameterTree,
    Parameter,
)
import pyqtgraph as pg


def register_me(**kwargs):
    def wrapper(func):
        func.__registration__ = kwargs
        return func

    return wrapper


class MyClass:
    def __init__(self, parent=None):
        self.group = parent or Parameter.create(name="params", type="group")
        for name, method in inspect.getmembers(self, inspect.ismethod):
            if (kwargs := getattr(method, "__registration__", None)) is not None:
                func = InteractiveFunction(method)
                setattr(self, name, func)
                interact(func, parent=self.group, **kwargs)

    @register_me(name="foo", age=20)
    def my_method(self, name="bar", age=10):
        print(f"{name=}, {age=}")


app = pg.mkQApp()
obj = MyClass()
tree = ParameterTree()
tree.setParameters(obj.group)
tree.show()
pg.exec()

```

</details>

Note how instead of identifying a `self` argument, creating object proxies, etc., we just check for whether this function must be registered and `setattr` during the object's `__init__`. You can extend this example with a second decorator that specifies keywords at the `InteractiveFunction` level, etc.

So, I'm inclined to avoid supporting `classmethod`-style interactive functions in favor of lightweight user-level decorators. It might be worth adding this illustration to the examples, though.

---
> Side note: Based on the [examples](https://pyqtgraph.readthedocs.io/en/latest/api_reference/parametertree/interactiveparameters.html#basic-use), shouldn't [this line in interactive.py](https://github.com/pyqtgraph/pyqtgraph/blob/261a32515fac2ffd5071801ef4b69720828b5142/pyqtgraph/parametertree/interactive.py#L625) be interact = Interactor().interact instead of interact = Interactor()?

`Interactor.__call__` is a synonym for `interact()`, so there's no difference in that usage. The benefit of the current usage is being able to set options on the interactor, which wouldn't be possible otherwise:
```python
# Able to call object methods
interact.setOpts(...)

@interact
def my_func(...): ...
```

**Comment by Antyos** [comment]
Thank you for your suggested implementation! There is a part of me that still wants that "one decorator" solution, but I think I agree with your decision that it is too complicated for future maintainers. I'm glad to know you put so much thought into the implementation.

It would definitely help to add this to the examples, as I banged my head against a wall for hours trying to figure out what I could possibly be doing wrong.

I have a bit of an over-obsession with type hints--I made a type definition for `ParametersOptions`, as well as type hints for the kwargs that are eventually passed to `interact`. It doesn't technically add anything "new" to the behavior in your implementation, but I find it helps with Pylance.

<details>
<summary>Example code (with type hints)</summary>

```python
import inspect
from typing import Any, Callable, NotRequired, Optional, Sequence, TypedDict

import pyqtgraph as pg
from pyqtgraph.parametertree import (
    InteractiveFunction,
    Parameter,
    ParameterTree,
    RunOptions,
    interact,
)
from pyqtgraph.parametertree.parameterTypes import GroupParameter


class ParameterOptions(TypedDict, total=False):
    name: NotRequired[str]
    value: NotRequired[Any]
    default: NotRequired[Any]
    type: NotRequired[str]
    readonly: NotRequired[bool]
    visible: NotRequired[bool]
    enabled: NotRequired[bool]
    renamable: NotRequired[bool]
    removable: NotRequired[bool]
    strictNaming: NotRequired[bool]
    expanded: NotRequired[bool]
    syncExpanded: NotRequired[bool]
    title: NotRequired[str]


def register_method(
    ignores: Optional[Sequence[str]] = None,
    runOptions: Optional[RunOptions | tuple[RunOptions, ...]] = None,  # Note: this would require RunOptions to become a StrEnum
    parent: Optional[GroupParameter] = None,
    titleFormat: Optional[str | Callable] = None,
    nest: Optional[bool] = None,
    runActionTemplate: Optional[dict] = None,
    existsOk: Optional[bool] = None,
    closures: Optional[dict[str, Callable[[], Any]]] = None,
    **overrides: Any | ParameterOptions,
):
    def wrapper[T](wrapped: T) -> T:
        kwargs = {
            "ignores": ignores,
            "runOptions": runOptions,
            "parent": parent,
            "titleFormat": titleFormat,
            "nest": nest,
            "runActionTemplate": runActionTemplate,
            "existsOk": existsOk,
            "closures": closures,
        }
        kwargs = {k: v for k, v in kwargs.items() if v is not None}
        kwargs.update(overrides)
        setattr(wrapped, "__register_method__", kwargs)
        return wrapped

    return wrapper


class MyClass:
    def __init__(self, parent=None):
        self.group = parent or Parameter.create(name="params", type="group")
        for name, method in inspect.getmembers(self, inspect.ismethod):
            if (kwargs := getattr(method, "__register_method__", None)) is not None:
                func = InteractiveFunction(method)
                setattr(self, name, func)
                interact(func, parent=self.group, **kwargs)

    @register_method(
        runOptions=(RunOptions.ON_CHANGED, RunOptions.ON_ACTION),
        name="foo",
        age={"type": "float", "value": 20, "step": 0.5},
    )
    def my_method(self, name="bar", age=10):
        print(f"{name=}, {age=}")


app = pg.mkQApp()
obj = MyClass()
tree = ParameterTree()
tree.setParameters(obj.group)
tree.show()
pg.exec()
```

</details>

Personally, I like defining the parameter properties (limits, string options, etc.) in the same place as the function definition so it is less likely for there to be a mismatch between `interactive` options and the function itself. The only downsides I see are that:
1. You cannot use keyword arguments used by `interact` 
2. It is less obvious what the sorting order the interactive functions appear in (it's alphabetical by function name)

Even though it's functionally simple, it might be nice to include something like the `register_method` decorator as part of the library to leverage the type hints without the user having to define all the keyword arguments. (Though at that point, wouldn't one decorator really be more convenient to the end user than two pieces of boiler plate? (_No! We went over this!_))

Part of me wants to suggest raising a `NotImplementedError` if `InteractiveFunction.__get__()` is called to make it clear to end users why it cannot be used to decorate methods and what to do instead. However, another part of me (which does not understand Descriptors very well) is terrified of that idea and has no idea what side effects that may cause.

---

Thanks for clearing the misconception I had about `interact`. My confusion arose from a similar issue to this one, but I think I will open a separate issue about that (there's an easy fix) for the sake of organization.

**Comment by Antyos** [comment]
After spending some more time with my `register_interact()` function, and it has made me realize that it may be beyond the scope of the library (but as we discussed, it could go as an example).

Should it be helpful to anyone in the future, here is my implementation:

<details>
<summary>`interactive_method.py`</summary>

```python
import inspect
from typing import Any, Callable, NotRequired, Optional, Sequence, TypedDict

from pyqtgraph.parametertree import InteractiveFunction, Interactor, RunOptions
from pyqtgraph.parametertree.parameterTypes import GroupParameter


class ParameterOptions(TypedDict, total=False):
    name: NotRequired[str]
    value: NotRequired[Any]
    default: NotRequired[Any]
    type: NotRequired[str]
    readonly: NotRequired[bool]
    visible: NotRequired[bool]
    enabled: NotRequired[bool]
    renamable: NotRequired[bool]
    removable: NotRequired[bool]
    strictNaming: NotRequired[bool]
    expanded: NotRequired[bool]
    syncExpanded: NotRequired[bool]
    title: NotRequired[str]


def sort_str_or_num(value):
    """Allow sorting by a string or a number. Coerces strings to numbers if possible."""
    try:
        num = float(value)
        return (0, num)
    except ValueError:
        return (1, value)


def register_interactive(
    ignores: Optional[Sequence[str]] = None,
    runOptions: Optional[RunOptions | Sequence[RunOptions]] = None,
    parent: Optional[GroupParameter] = None,
    titleFormat: Optional[str | Callable] = None,
    nest: Optional[bool] = None,
    runActionTemplate: Optional[dict] = None,
    existsOk: Optional[bool] = None,
    closures: Optional[dict[str, Callable[[], Any]]] = None,
    interactiveFunction: bool = False,
    order: Optional[float | str] = None,
    **overrides: Any | ParameterOptions,
):
    """Decorator to register a method as interactive.

    The class must inherit from InteractiveClass for the interactivity to work.

    Parameters
    ----------
    interactiveFunction : bool, default=False
        If True, the method will be registered as an InteractiveFunction
    order : float or str, optional
        If specified, the order in which the method will appear in the parameter tree.
        Defaults to the method name.

    See pyqtgraph.parametertree.Interactor for the rest of the parameters.
    """

    def wrapper[T](wrapped: T) -> T:
        if not interactiveFunction and closures is not None:
            raise ValueError("closures can only be used with interactive functions")
        kwargs = {
            "ignores": ignores,
            "runOptions": runOptions,
            "parent": parent,
            "titleFormat": titleFormat,
            "nest": nest,
            "runActionTemplate": runActionTemplate,
            "existsOk": existsOk,
            "closures": closures,
            # Past here are arguments custom to the registration decorator and must be
            # popped from kwargs in InteractiveClass before passing to interact()
            "order": order,
        }
        kwargs = {k: v for k, v in kwargs.items() if v is not None}
        kwargs.update(overrides)
        setattr(wrapped, "__interactive__", kwargs)
        if interactiveFunction == True:
            setattr(wrapped, "__register_interactive_function__", True)
        return wrapped

    return wrapper


class InteractiveClass:
    """Applies interactivity to methods that have been decorated with @register_interactive"""

    def __init__(self, *args, **kwargs):
        # Make sure we have a params_group and interactor
        if getattr(self, "params_group", None) is None:
            self.params_group = GroupParameter(name="Parameters")
        if getattr(self, "interactor", None) is None:
            self.interactor = Interactor(parent=self.params_group)
        elif getattr(self.interactor, "parent", None) is None:
            self.interactor.setOpts(parent=self.params_group)

        # Apply the interactive decorators
        interactive_functions = []
        for name, method in inspect.getmembers(self, inspect.ismethod):
            if getattr(method, "__register_interactive_function__", None) == True:
                func = InteractiveFunction(method)
                setattr(self, name, func)
            else:
                func = method
            # When converting method to InteractiveFunction, it loses the
            # __interactive__ attribute, so we need to check 'method' instead of 'func'
            if (kwargs := getattr(method, "__interactive__", None)) is not None:
                sort_key = kwargs.pop("order", name)
                interactive_functions.append((sort_key, func, kwargs))

        # Sort and add the interactive functions
        interactive_functions.sort(key=lambda x: sort_str_or_num(x[0]))
        for _, func, kwargs in interactive_functions:
            self.interactor(func, parent=self.param_group, **kwargs)  # type: ignore

```
</details>

<details>
<summary>`app.py`</summary>

```python
import pyqtgraph as pg
from pyqtgraph.parametertree import ParameterTree, RunOptions

from interactive_method import InteractiveClass, register_interactive


class MyClass(InteractiveClass):
    def __init__(self, parent=None):
        self.parent = parent
        super().__init__()

    @register_interactive(
        runOptions=(RunOptions.ON_CHANGED, RunOptions.ON_ACTION),
        interactiveFunction=True,
        order=2,
        name="foo",
        age={"type": "float", "value": 20, "step": 0.5},
    )
    def my_method(self, name="bar", age=10):
        print(f"{name=}, {age=}")

    @register_interactive(
        runOptions=RunOptions.ON_CHANGED,
        order=1,
        name="foo",
        val={"type": "float", "value": 35, "step": 0.5},
    )
    def abcde(self, name="bar", val=10):
        print(f"{name=}, {val=}")


app = pg.mkQApp()
obj = MyClass()
tree = ParameterTree()
tree.setParameters(obj.params_group)
tree.show()
pg.exec()
```

</details>
