### ISSUE TITLE
Pylance shows false error for direct call to `interact()`

### ISSUE THREAD

**Issue by Antyos** [pyqtgraph/pyqtgraph#2928]
I brought this up in #2925, but thought it would be better for the sake of organization to move it to its own issue.

## Short Description
Pylance will display an error message when calling `interact()` directly.

## Code to reproduce
From your example above, Pylance shows an error message:
```python
from pyqtgraph.parametertree import interact

def foo(a=5):
    print(a)

# ERROR:
interact(function=foo)
#        ^^^^^^^^^^^^ to parameter "self" of type "Interactor" in function "__call__"

# OK
interact.interact(function=foo)
```

## Behavior
Of course, there isn't actually an issue here during runtime. I think this has to do with `functools.wrap` not sufficiently wrapping the function signature in the definition of `Interact.__call__()`:

https://github.com/pyqtgraph/pyqtgraph/blob/261a32515fac2ffd5071801ef4b69720828b5142/pyqtgraph/parametertree/interactive.py#L406-L408

The fix seems to be simple, just replace the function definition with:

```python
class Interactor:
	# ...
	__call__ = interact
```

## Tested environment(s)
- PyQtGraph version: 0.13.3
- Qt Python binding: PyQt6 6.6.1 Qt 6.6.1
- Python version: 3.12.1
- NumPy version: 1.26.3
- Operating system: Windows 10
- Installation method: Poetry

**Comment by ntjess** [comment]
This is more of a problem with Pylance than with pyqtgraph (see https://github.com/microsoft/pylance-release/discussions/2716)

A problem with `__call__ = interact` is that when a class is overloaded, `__call__` will invoke the base class's method, not the subclass:
```python
class A:
    def my_method(self):
        print("A.my_method()")

    __call__ = my_method

class B(A):
    def my_method(self):
        print("B.my_method()")

b = B()
# Prints "A.my_method()", since __call__ still points to `A.my_method`
b()
```

**Comment by Antyos** [comment]
Ah, ok. I forgot about the inheritance issue. Thanks for clarifying!
