### ISSUE TITLE
Setting axisItems creates a phantom axis

### ISSUE THREAD

**Issue by jothalha** [pyqtgraph/pyqtgraph#295]
Creating a new PlotWidget with axis items draws an additional axis in the top left. Apparently this can be solved by removing 'parent=self' from 'axis = axisItems.get(k, AxisItem(orientation=k, parent=self))' in PlotItem.py. I'm using python 3.4.4 with PyQt4.11 on Windows 10.
![phantom_axis](https://cloud.githubusercontent.com/assets/15878282/13602772/f15e2c38-e538-11e5-8c7a-3391cb6e4591.JPG)

**Comment by lesauxvi** [comment]
This problem has already been identified and corrected in the 'develop' branch of PyQtGraph. Can you check and close this issue if this is the case?

**Comment by jothalha** [comment]
Sorry for troubling you guys, solved!
