### ISSUE TITLE
SyntaxWarnings

### ISSUE THREAD

**Issue by JulienPalard** [pyqtgraph/pyqtgraph#2962]
While running an `apt upgrade` I noticed:

```
/usr/lib/python3/dist-packages/pyqtgraph/examples/SpinBox.py:38: SyntaxWarning: invalid escape sequence '\$'
  regex='\$?(?P<number>(-?\d+(\.\d+)?)|(-?\.\d+))$')),
```

The `\$` should be written `\\$` or `r'\$'` since a few Python releases (same for all backslash escape that have no meanings). I don't have the time to search for other occurrences of this fact, but running the tests with `PYTHONDEVMODE=1` should help spotting them :)

**Comment by aaryamantriescode** [comment]
Hi i want to look into it
