### ISSUE TITLE
'DateAxisItem' object has no attribute 'fontMetrics'

### ISSUE THREAD

**Issue by Zhejing-Chin** [pyqtgraph/pyqtgraph#2966]
### Short description
I have a DateAxisItem and would like to adjust the zoomLevel with setZoomLevelForDensity but it hits the AttributeError: 'DateAxisItem' object has no attribute 'fontMetrics'. 

### Code to reproduce

```python
import pyqtgraph as pg
import numpy as np

class some_graph(pg.PlotWidget):
    def __init__(self, parent=None, background="default", plotItem=None, **kargs):
        super().__init__(parent, background, plotItem, **kargs)
        dateAxis = pg.DateAxisItem(orientation="bottom")
        self.plotItem.setAxisItems({"bottom": dateAxis})
        dateAxis.setZoomLevelForDensity(10)
```

### Real behavior

> site-packages\pyqtgraph\graphicsItems\DateAxisItem.py", line 311, in sizeOf
`return self.fontMetrics.boundingRect(text).width() + padding`

AttributeError: 'DateAxisItem' object has no attribute 'fontMetrics'

```
File "C:\Users____.py", line 18, in draw
    dateAxis.setZoomLevelForDensity(10)
  File "C:\Users\_\AppData\Local\pypoetry\Cache\virtualenvs\nUoyKD76-py3.9\lib\site-packages\pyqtgraph\graphicsItems\DateAxisItem.py", line 319, in setZoomLevelForDensity
    size = sizeOf(zoomLevel.exampleText)
  File "C:\Users\_\AppData\Local\pypoetry\Cache\virtualenvs\nUoyKD76-py3.9\lib\site-packages\pyqtgraph\graphicsItems\DateAxisItem.py", line 311, in sizeOf
    return self.fontMetrics.boundingRect(text).width() + padding
AttributeError: 'DateAxisItem' object has no attribute 'fontMetrics'
```

### Tested environment(s)

 * PyQtGraph version:  '0.13.3'
 * Qt Python binding:  'PyQt5 5.15.2 Qt 5.15.2'
 * Python version: Python 3.9.13
 * NumPy version:  '1.23.5'
 * Operating system: Win32
 * Installation method:  poetry add

**Comment by pijyoi** [comment]
From what I can understand from the code in `DateAxisItem` and `AxisItem`, `DateAxisItem::setZoomLevelForDensity` as implemented isn't meant to be called by the user.

`AxisItem::paint` -> `DateAxisItem::generateDrawSpecs` (*) -> `AxisItem::generateDrawSpecs` -> `DateAxisItem::tickValues` -> `DateAxisItem::setZoomLevelForDensity` (x)

(*) `self.fontMetrics` created here
(x) makes use of `self.fontMetrics`

**Comment by Zhejing-Chin** [comment]
That's interesting as based on the [documentation](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/dateaxisitem.html), we should be able to customize the zoomlevel with it. Or have you tried other methods to customize the zoom level to not be too fine grained?

**Comment by pijyoi** [comment]
The linked documentation says that to change the behaviour, one either:
1) overrides the setZoomLevelForDensity method, and/or
2) replaces the zoomLevels attribute

So the documentation is at least consistent in that it doesn't say that the user would call setZoomLevelForDensity.

It seems to me that either of methods above would require more than a passing understanding of the DateAxisItem code. (Which I don't)
