### ISSUE TITLE
Crash on Terminal Mouse Hover with non ASCII char

### ISSUE THREAD

**Issue by cdd1969** [pyqtgraph/pyqtgraph#297]
I am using pyqtgraph flowchart submodule. Whenever a node has a value with a non ASCII character (e.g. german letter) in its terminal, the method  `pyqtgraph.flowchart.Flowchart.FlowchartWidget.hoverOver()` causes a crash.

>   File "/usr/local/lib/python2.7/dist-packages/pyqtgraph/flowchart/Flowchart.py", line 921, in hoverOver
>     self.hoverText.setPlainText("%s.%s = %s" % (term.node().name(), term.name(), val))
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)

This fix works for me.

``` py
#self.hoverText.setPlainText("%s.%s = %s" % (term.node().name(), term.name(), val))
self.hoverText.setPlainText("{0}.{1} = {2}".format(term.node().name(), term.name(), val).decode('utf-8'))
```

**Comment by NilsNemitz** [comment]
With the switch to PYthon3 and native unicode support, this should no longer be an issue.
I can use German umlaut characters in a `setPlainText()` call in the  TextItem example.
Here are some to copy and paste for testing: ÄäÖöÜüß

**Comment by j9ac9k** [comment]
I'm going to close out this issue, as it shouldn't be a problem, if anything due to our python3 migration.  I know it's been a while @cdd1969 but if you're still able to create this issue, let us know and I'll reopen.
