### ISSUE TITLE
ConsoleWidget.write() function missing

### ISSUE THREAD

**Issue by ioneater** [pyqtgraph/pyqtgraph#2975]
Up to version 0.13.2 we could use the ConsoleWidget.write() function to write a string into the console.
I cannot find a reference to this function or a replacement in 0.13.4
What is the correct way to replace this functionality in 0.13.4?

**Comment by ftkovr9k** [comment]
Hello. Can I work on this?

**Comment by j9ac9k** [comment]
> Hello. Can I work on this?

Please do! Thanks for offering!

**Comment by ioneater** [comment]
Yes, thank you for looking into this!

**Comment by j9ac9k** [comment]
@ioneater 

Sorry for the late response.  Looks like that functionality got migrated to the `ReplWidget`, which can be accessed via `Console.repl`, so before it would be `Console.write(args)` but now it's `Console.repl.write(args)`

My apologies for breaking the public API in this way, I try to not let that happen, but it did in this case.

I'm going to close out the issue, but if you're having trouble still, let me know.

**Comment by ioneater** [comment]
> @ioneater
> 
> Sorry for the late response. Looks like that functionality got migrated to the `ReplWidget`, which can be accessed via `Console.repl`, so before it would be `Console.write(args)` but now it's `Console.repl.write(args)`
> 
> My apologies for breaking the public API in this way, I try to not let that happen, but it did in this case.
> 
> I'm going to close out the issue, but if you're having trouble still, let me know and I'll re-open.

@j9ac9k Thank you for clarifying. No worries. I am happy I can use the latest version now with this information.

**Comment by j9ac9k** [comment]
> > @ioneater
> > Sorry for the late response. Looks like that functionality got migrated to the `ReplWidget`, which can be accessed via `Console.repl`, so before it would be `Console.write(args)` but now it's `Console.repl.write(args)`
> > My apologies for breaking the public API in this way, I try to not let that happen, but it did in this case.
> > I'm going to close out the issue, but if you're having trouble still, let me know and I'll re-open.
> 
> @j9ac9k Thank you for clarifying. No worries. I am happy I can use the latest version now with this information.

Glad to hear that things are working again! Again, my apologies for the API breakage.
