### ISSUE TITLE
TypeError exception in ROI raiseContextMenu . QPoint being sent floats instead of ints

### ISSUE THREAD

**Issue by tjwilli58** [pyqtgraph/pyqtgraph#2983]
pyqtgraph version 0.12.4, python > 3.9:
pyqt 5.15.10 (conda) 

I have ROI in my GraphicsScene and added a context menu so I can remove it if desired, among other things. When I right-click on the ROI to get the context menu, I get

`
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(xpos: int, ypos: int): argument 1 has unexpected type 'float'
  QPoint(a0: QPoint): argument 1 has unexpected type 'float'
  debug.printExc("Error sending click event:")
`

This is similar to #1887.
Downgrading to python 3.9 fixes it for me in the meantime, or I can edit line 774 of ROI.py to change

`        menu.popup(QtCore.QPoint(pos.x(), pos.y()))
`

to 

`        menu.popup(QtCore.QPoint(int(pos.x()), int(pos.y())))
`

Thanks

**Comment by tjwilli58** [comment]
Running ROIExamples.py can demonstrate this.
right-click on ROI in w4 Layout.

**Comment by tjwilli58** [comment]
So I see that this is fixed in #2260. Can we get this MR in version 0.12.4?

**Comment by j9ac9k** [comment]
> So I see that this is fixed in #2260. Can we get this MR in version 0.12.4?
> 
> 

We don't have the maintainer resources/hours to back port to older versions and update multiple versions.

**Comment by tjwilli58** [comment]
Understood. When I tried to update to 0.13 another issue cropped up with my application. Addressing that was put on the back burner while I worked on other bugs with my own code. Looks like it's time to address it.
Thanks.

**Comment by tjwilli58** [comment]
And I'm not getting that error with 0.13 anymore anyway! I guess other edits fixed it.

**Comment by j9ac9k** [comment]
> And I'm not getting that error with 0.13 anymore anyway! I guess other edits fixed it.

🎊

**Comment by tjwilli58** [comment]
@j9ac9k , just to close this further. The problem I had was the change from some Qt things moving from QtGui to QtWidgets.

`class GeoPoints(QtGui.QGraphicsItemGroup)`

to

`class GeoPoints(QtWidgets.QGraphicsItemGroup)`

and so forth. Maybe this [commit](https://github.com/pyqtgraph/pyqtgraph/commit/bc6c7212a7ed1ebd4c9eab65929c920aecb01407): 

> deprecate all the QtWidgets being accessed through QtGui

 ?

**Comment by j9ac9k** [comment]
If you're using PyQtGraph's abstraction layer (pyqtgraph.Qt) that could certainly have given you problems. While accessible, we don't recommend its usage outside the library as it is nowhere near as complete as a library like QtPy.  That said, it's very convenient, maybe I should stick a warning somewhere in the docs about that.

**Comment by tjwilli58** [comment]
That's exactly what was going on. We fairly recently started to use QtPy, but there's a mix of that and pyqtgraph.Qt abstraction from when we first started using  pyqtgraph. We've only recently started to clean that up.

**Comment by j9ac9k** [comment]
The convenience of `pyqtgraph.Qt` is tough to resist for sure haha.

FWIW I've been considering doing away w/ our own abstraction layer and adding QtPy as a dependency.

**Comment by pijyoi** [comment]
> menu.popup(QtCore.QPoint(int(pos.x()), int(pos.y())))

A cleaner approach would be `menu.popup(pos.toPoint())`

**Comment by tjwilli58** [comment]
But as you mentioned in #2260, what if your cursor is on the right or bottom edge of your View? Wouldn't there be a danger of rounding taking the position outside of it?

**Comment by pijyoi** [comment]
What I meant at the time was:
The scope of the PR was to make things work with Python 3.10. To that end, the fix should probably just limit itself to syntactical fixes, and not make behavioral changes, no matter how small.

I don't think there's any issue in this case with pixels going out of bounds, since the consumer of that rounded point is just to get a hint of where to display the menu.
For cases where out of bounds does matter (e.g. locating a pixel value in a matrix), one would have to clip the rounded pixel anyway, regardless of the rounding mode.

Using `int` as the rounding mode is neither here nor there. It's rounding towards zero. So both -0.9 and 0.9 get rounded to zero.
