### ISSUE TITLE
FillBetweenItems overflows the area between the target curves

### ISSUE THREAD

**Issue by jeberger** [pyqtgraph/pyqtgraph#3022]
### Short description

`FillBetweenItems` overflows the area between the target curves

### Code to reproduce

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtWidgets

app = QtWidgets.QApplication ([])
win = pg.GraphicsLayoutWidget()
plot = win.addPlot (title = pg.Qt.VERSION_INFO)

xs = range (3)
lo = [  99, 89, 109 ]
hi = [ 101, 91, 111 ]

top = plot.plot (xs, hi, pen = (255, 255, 255, 255))
bot = plot.plot (xs, lo, pen = (255, 255, 255, 255))
fill = pg.FillBetweenItem (top, bot, (255, 255, 255, 75))
plot.addItem (fill)

win.show()
app.exec()
```

### Expected behavior

We should see two white lines with the area between them in gray, _and all the outside black._

### Real behavior

The gray area overflows above the top curve:

![bug](https://github.com/pyqtgraph/pyqtgraph/assets/930717/17985406-afc7-4ac9-baae-e39e8c6bcd16)

### Tested environment(s)

 * PyQtGraph version: 0.13.6
 * Qt Python binding:
    * PyQt6 6.7.0 Qt 6.7.0
    * PySide6 6.7.0 Qt 6.7.0
    * PyQt5 5.15.10 Qt 5.15.13
 * Python version: Python 3.12.3
 * Operating system: ArchLinux
 * Installation method: System package

**Comment by j9ac9k** [comment]
Version 0.13.7 was released to fix a regression with FillBetweenItem. Can you try upgrading to that?

**Comment by jeberger** [comment]
Version 0.13.7 works fine, thanks!

**Comment by j9ac9k** [comment]
Thanks for checking and reporting back!
