### ISSUE TITLE
Failed tests on travis are not being reported as failed...

### ISSUE THREAD

**Issue by ericdill** [pyqtgraph/pyqtgraph#303]
For example:
- https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/118923355#L541
- https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/118923352#L570
- https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/118923352#L672
- https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/118923352#L737
- https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/118923354#L654
- https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/118923354#L719
- https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/118923354#L818
- https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/118923355#L688
- https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/118960903#L745

Damn you travis and your false sense of security

**Comment by 2xB** [comment]
Thank you for the report! This was not a problem of Travis but of test_examples. It is fixed in #911.
