### ISSUE TITLE
Segfault when iterating on a transform-mapped Vector in a thread

### ISSUE THREAD

**Issue by outofculture** [pyqtgraph/pyqtgraph#3044]
### Short description
Take a Vector, map it with a transform, put it in a _threading_ Thread, iterate, and BOOM.

### Code to reproduce

```python
import pyqtgraph as pg
import threading


def do_it():
    xform = pg.SRTTransform3D()
    v = xform.map(pg.Vector((0, 0, 0)))
    tuple(v)


pg.mkQApp()
threading.Thread(target=do_it).start()
```

### Real behavior

`SIGSEGV`

### Tested environment(s)

 * PyQtGraph version: 0.13.8dev0
 * Qt Python binding: PyQt5 5.15.10 Qt 5.15.2
 * Python version: 3.11
 * NumPy version: 1.26.3
 * Operating system: linux
 * Installation method: git

### Additional context

Workaround: use a `QThread`, and this isn't an issue.

**Comment by j9ac9k** [comment]
the output of `map` is lazy, so likely the issue is something in the mapping method.

Let's try and narrow it down a bit, try:

```python
def do_it():
    xform = pg.SRTTransform3d()
    v = xform.map(QtGui.QVector3D(0, 0, 0))
    tuple(v)
```

**Comment by outofculture** [comment]
`QtGui.QVector3D` still segfaults. `np.array` does not.

**Comment by outofculture** [comment]
It still segfaults if I change vector to use `__next__` instead of yielding in the `__iter__`. It still segfaults with python 3.11.9 and pyqt 6.7.0.

**Comment by pijyoi** [comment]
This already segfaults, no threading needed.
```python
from PyQt6 import QtGui
import pyqtgraph as pg
m = QtGui.QMatrix4x4()
v0 = pg.Vector()
v1 = m.map(v0)
print(type(v0), type(v1)) # <class 'pyqtgraph.Vector.Vector'> <class 'PyQt6.QtGui.QVector3D'>
tuple(v1)
print('BYE')
```
The issue is that `QMatrix4x4` returns the base class `QVector3D` which doesn't support iteration, resulting in a crash in PyQt6.
https://github.com/pyqtgraph/pyqtgraph/blob/7b1510afc7509ed04e08425e630b58b41b6bef8f/pyqtgraph/Transform3D.py#L48

In PySide6, it results in an error:
`TypeError: 'PySide6.QtGui.QVector3D' object is not iterable`

**Comment by outofculture** [comment]
So spooky that the segfault _goes away_ when executed in a QThread; some peculiar memory arrangements to get that behavior.

What do y'all think, should `Transform3D.map` always return `type(obj)`? That's an easy change, but I don't know that my expectations are necessarily valid here. I can make that PR, if that makes sense.

**Comment by j9ac9k** [comment]
restricting `Transform3D.map(obj)`  to always return `type(obj)` is definitely where I would start, and that matches the `QMatrix4x4.map()` behavior as well.

I haven't had reason to use `Transform3D` at all in my work, but glancing at it, the types of the methods added are all over the place, so I would not only restrict it to return `type(obj)`, but I would likely restrict the accepted types of `obj` to the types accepted by  `QMatrix4x4`, and add `numpy.ndarray` and `Vector` as well.  I would do away w/ accepting list/tuples.

**Comment by j9ac9k** [comment]
also if you're changing `.map()` please consider adopting the python 3.10 match/case syntax.

**Comment by outofculture** [comment]
Sounds good. I tried, but match/case wasn't a good fit for this.

I would be sad to deprecate accepting list/tuple. I use them all the time (mostly for asking "what's my origin's position in some other coordinate system? e.g. `xform.map((0, 0, 0))"). I can move my less-restrictive typing into my project's codebase, but mapping a tuple is at least a sensible thing for a transform to do.
