### ISSUE TITLE
PlotItem with a custom ViewBox

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [pyqtgraph/pyqtgraph#3048]
I'm creating a custom ViewBox class (subclassing `pg.ViewBox`) and using it for `pg.PlotItem`. Reviewing the code, it appears that the viewbox parent must be set manually unlike the default viewbox. In other words, the

```python

view_box = MyViewBox()
plot_item = pg.PlotItem(viewBox=view_box)

assert plot_item==view_box.parent() # fails
```

While I can simply `view_box.setParent(plot_item)` after the `plot_item` is instantiated, it seems logical to do this internally. That is modify [Line 129-131](https://github.com/pyqtgraph/pyqtgraph/blob/7b1510afc7509ed04e08425e630b58b41b6bef8f/pyqtgraph/graphicsItems/PlotItem/PlotItem.py#L129) to:

```python
        if viewBox is None:
            viewBox = ViewBox(parent=self, enableMenu=enableMenu)
        else:
            viewBox.setParent(self)
        self.vb = viewBox
```

Is there a rationale against it? (I'm fairly new to the world of Qt.)

If this is a viable change, I can post a PR for this. Thanks.

Edit:
Never mind. The `view_box.parent()` is `None` even with the default code path.

**Comment by j9ac9k** [comment]
Hi @tikuma-lsuhsc 

What are you hoping to achieve by setting the parent in such a way? Broadly speaking, pyqtgraph's parent/child relationships are not always intuitive as pyqtgraph needs to maintain both python references to be avalable, as well as the internal Qt references to be available.

Every attempt is made to abstract this from the user, as having a problematic parent/child chain can result in segfaults and/or memory leaks.

Is there a specific reason you want the ViewBox parent to be the PlotItem?

**Comment by j9ac9k** [comment]
Subclassing ViewBox is totally fine, and passing it into a PlotItem like you did is the way to go.  I think it should set the parent/child relationships appropriately that way.

That said, would probably benefit from a test to ensure that's the case...

Anyway I'm going to close the issue as there seems to be no issue :)

**Comment by tikuma-lsuhsc** [comment]
Thank you for the confirmation!
