### ISSUE TITLE
how to setData() in bargraphItem

### ISSUE THREAD

**Issue by dindom999** [pyqtgraph/pyqtgraph#310]
I need to update bargraphItem every minute.
First I draw it :
`l11=pg.BarGraphItem(x=range(60), height=np.random.random(60), width=0.3, brush='r')`

Then when I update it:
`l11.setData(x=range(60),height=np.random.random(60)) `
excepttion comes out:
```
Traceback (most recent call last):
  File "./zil3.py", line 58, in update
    l11.setData(x=range(60),height=np.random.random(60))
TypeError: setData() takes no keyword arguments
```

Why is that ? Is it a bug?

**Comment by dindom999** [comment]
I found that there is not setData() after I read the source code "pyqtgraph/pyqtgraph/graphicsItems/BarGraphItem.py"
So I add one, and it work fine now.

**Comment by QuadCorei8085** [comment]
you could use "setOpts", and I saw a merge request which exactly does what "setOpts" do.
e.g.
bg = pg.BarGraphItem(...)
`bg.setOpts(y=np.random.normal(size=(1,10))[0]);`

**Comment by topherbuckley** [comment]
If you want to adjust the height of each bar, it would actually be `bg.setOpts(height=np.random.random(60));`  At least that is what I was looking for when I arrived here. I'm not sure what setting y does in the bargraphitem, but it wasn't useful for me.
