### ISSUE TITLE
The bottom axis label display incomplete in version 0.13.7

### ISSUE THREAD

**Issue by Knightly123** [pyqtgraph/pyqtgraph#3144]
the bottom axis label display incomplete when I upgrading pyqtgraph from 0.10.0 to 0.13.7.
![issue](https://github.com/user-attachments/assets/dcee53de-fb6a-463d-a423-9123c4b0ecd2)

I found below code changed in the AxisItem class, boundingRect function.
code in 0.13.7:
```
elif self.orientation == 'bottom':
    rect = rect.adjusted(-m, min(0,tl), m, 0)
```
code in 0.10.0 
```
elif self.orientation == 'bottom':
    rect = rect.adjusted(-15, min(0,tl), 15, 0)
```
It works well when I revert the fisrt arg to -15. is it an issue?

**Comment by pijyoi** [comment]
Looking at the library source code, you should be able to achieve that with `AxisItem.setStyle(hideOverlappingLabels=False)`

https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/axisitem.html#pyqtgraph.AxisItem.setStyle

**Comment by Knightly123** [comment]
> Looking at the library source code, you should be able to achieve that with `AxisItem.setStyle(hideOverlappingLabels=False)`
> thanks, it works.
> https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/axisitem.html#pyqtgraph.AxisItem.setStyle
