### ISSUE TITLE
background color of label in InfiniteLine 

### ISSUE THREAD

**Issue by rlegnain** [pyqtgraph/pyqtgraph#324]
I found an issue when I used InfiniteLine with label.
If I use pg.InfiniteLine.label.fill = pg.mkBrush(250, 250, 255),   The background will not change until I move the infiniteLine or the textItem.
Example: 

> > p = pg.plot()
> > Line = pg.InfiniteLine(pos=.8, angle=90, label="Test", labelOpts={'position': 0.1, 'color': (200, 0, 0), 'fill': (255, 255, 0), "border": "r",'movable': True})
> > p.addItem(Line)
> > Line.label.fill = pg.mkBrush(250, 250, 255)

**Comment by ixjlyons** [comment]
Sorry it took a while to get to this. I'm not able to reproduce this issue going back to when `labelOpts` was added as an argument. I'm kind of leaning toward this being an upstream (Qt) issue, but I'm not confident about that. Setting the `fill` brush of the underlying `TextItem` doesn't have an effect until the item's `paint()` method is called, and while that's not *triggered* by setting the `fill` attribute, I think it should happen automatically at some point. A potential workaround would be to call `Line.scene().update()`.

If you're still using pyqtgraph (and you're still seeing this problem), could you specify what OS you're using and which Qt backend (PyQt4/5, PySide(2))?
