### ISSUE TITLE
Bug with LegendItem drag

### ISSUE THREAD

**Issue by ombschervister** [pyqtgraph/pyqtgraph#332]
In master branch In examples/legend.py after dragging the legend around and releasing the mouse, next dragging attempt drags the plot instead of the legend.

![legend_bug](https://cloud.githubusercontent.com/assets/3264643/15014859/c577e0e4-1221-11e6-996f-3c98a1be454c.gif)

**Comment by lesauxvi** [comment]
I'm not able to reproduce the bug with the develop version of pyqtgraph (version of april 2016) both under linux and win7.

Can you also check on your side?

**Comment by ombschervister** [comment]
develop branch, last commit "670d63c Eric Dill on 03.05.2016 at 22:11":
error is reproduced.

The bug is appear, when this code running:
GraphicsScene.mousePressEvent

       if self.lastHoverEvent is not None:
                # If the mouse has moved since the last hover event, send a new one.
                # This can happen if a context menu is open while the mouse is moving.
                if ev.scenePos() != self.lastHoverEvent.scenePos():
                    self.sendHoverEvents(ev)

For reproduce the bug you should not move the mouse after first drag and before next.
Maybe you need to add print before sendHoverEvent.

**Comment by lesauxvi** [comment]
OK, with your guidelines, I'm able to reproduce it! My above comment should not be taken into account...

**Comment by j9ac9k** [comment]
@ombschervister Thanks for the issue with the gif and the associated PR!
