### ISSUE TITLE
Is that a bug on "row" and "col"

### ISSUE THREAD

**Issue by dindom999** [pyqtgraph/pyqtgraph#337]
I am trying to plot two rows,and they are 3:1
here is the code :
```
view = pg.GraphicsView()
layout_main = pg.GraphicsLayout(border=(100, 100, 100))
view.setCentralItem(layout_main)
view.showMaximized()

ax_kline =layout_main.addPlot(row=0, col=0,rowspan=3,colspan=1)
ax_kline.addItem(CandlestickItem(mydata[['open','close','high','low']].to_records()))
layout_main.nextRow()
ax_vol = layout_main.addPlot( row=3, col=0,rowspan=1,colspan=1)
```
But it show 1:1
![image](https://cloud.githubusercontent.com/assets/5274818/15183286/f47f833c-17c2-11e6-8aed-054d9fed4f7b.png)

**Comment by ixjlyons** [comment]
[This post on the mailing list](https://groups.google.com/forum/#!searchin/pyqtgraph/graphicslayout/pyqtgraph/RJjtJea9KFc/EhqG734-37sJ) is relevant. Also, see the [QGraphicsGridLayout docs](http://doc.qt.io/qt-4.8/qgraphicsgridlayout.html#setRowStretchFactor) for more.

As far as I can tell, it's not straightforward to specify the exact weights for items in the layout and maintain them with resizing. A simple, though imperfect, solution would be:

```python
layout_main.layout.setRowStretchFactor(0, 3)
```

Full working example:

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtGui

app = QtGui.QApplication([])
win = QtGui.QMainWindow()

layout_widget = pg.GraphicsLayoutWidget()
win.setCentralWidget(layout_widget)

p1 = layout_widget.addPlot()
p1.addItem(pg.PlotDataItem([1, 2, 3, 4], [5, 18, 1, 6]))

layout.nextRow()

p2 = layout_widget.addPlot()
p2.addItem(pg.PlotDataItem([1, 2, 3, 4], [4, 21, 76, 2]))

# ci attr is the "central item," which is a GraphicsLayout
layout_widget.ci.layout.setRowStretchFactor(0, 3)

win.show()
app.exec_()
```

**Comment by dindom999** [comment]
It works great!Thanks!
