### ISSUE TITLE
Will there be new release with PyQt5 support?

### ISSUE THREAD

**Issue by xmikos** [pyqtgraph/pyqtgraph#341]
Hello, I am developing [QSpectrumAnalyzer](https://github.com/xmikos/qspectrumanalyzer) which uses this great library. But last version of PyQtGraph is really really old (2014) and there is no support for PyQt5, so I am stuck with PyQt4. But support for Qt 4 has ended, we really should move on.

I know there seems to be support for PyQt5 in git master branch, but I don't want users to install library from git. Can you please make new release available on [PyPI](https://pypi.python.org/pypi)?

Or is this project now completely dead? That would be really pity :-(

**Comment by Addy771** [comment]
Could you include the pyqtgraph library in your own code and distribute it that way? I'm doing this for a project of mine using pyqt5.

**Comment by xmikos** [comment]
Yes, I can include it as a git submodule, but I really don't think this is good solution. There should be a new release.

**Comment by liubenyuan** [comment]
@xmikos I like your QSpectrumAnalyzer and my own projects are mainly build on top (modified) of qspectrumanalyzer.

You can now set `PYQTGRAPH_QT_LIB` to `PyQt5` and using the git version of this module.

**Comment by j9ac9k** [comment]
pyqtgraph supports PyQt5 as of version 0.10.0; we're working on getting PySide2 support in the next official version (0.11.0) however we're patching up our test suite and other issues first.  In the meantime, you can install pyqtgraph directly from the develop branch

```
pip install git+https://github.com/pyqtgraph/pyqtgraph.git@develop
```
