### ISSUE TITLE
Add support for PySide2

### ISSUE THREAD

**Issue by dustingooding** [pyqtgraph/pyqtgraph#342]
With the latest from Qt saying that PySide will be [officially supported](https://groups.google.com/d/msg/pyside-dev/pqwzngAGLWE/kXUpXBhILAAJ) and that https://github.com/PySide/pyside2 is the base for that support, pytgraph support of PySide2 seems reasonable.

**Comment by campagnola** [comment]
I'd love to have this for the 0.11 release (0.10 is almost done; no more additions allowed there).
Anyone want to give it a shot? pyqtgraph/Qt.py is where we manage all the various differences between PyQt/PySide/4/5.

**Comment by maxpeng** [comment]
I have tried pyside2 and pygraph develop branch with some modifications, I can run most of the examples.

I will upload my works when time is available.

**Comment by maxpeng** [comment]
I already created a pull request - [modifications to support pyside2 by maxpeng · Pull Request #376 · pyqtgraph/pyqtgraph](https://github.com/pyqtgraph/pyqtgraph/pull/376).

**Comment by kamikaze** [comment]
Please make a new release on PyPI, otherwise we still can't use it with PySide2. And with Python 3.7, because there is only PySide2 that supports it.

**Comment by Proxoso** [comment]
I request this too.
When you try to replicate the example from the  [pyqt crash course](http://www.pyqtgraph.org/documentation/qtcrashcourse.html) it would look something like this in PySide2:
```
from PySide2 import QtWidgets, QtCore, QtGui, QtCharts
import sys
import pyqtgraph as pg

if __name__ == '__main__':

    app = QtWidgets.QApplication(sys.argv)
    w = QtWidgets.QWidget()

    ## Create some widgets to be placed inside
    btn = QtWidgets.QPushButton('press me')
    text = QtWidgets.QLineEdit('enter text')
    listw = QtWidgets.QListWidget()
    plot = pg.PlotWidget() # this line causes the error

    ## Create a grid layout to manage the widgets size and position
    layout = QtWidgets.QGridLayout()
    w.setLayout(layout)

    ## Add widgets to the layout in their proper positions
    layout.addWidget(btn, 0, 0)   # button goes in upper-left
    layout.addWidget(text, 1, 0)   # text edit goes in middle-left
    layout.addWidget(listw, 2, 0)  # list widget goes in bottom-left
    # layout.addWidget(plot, 0, 1, 3, 1)  # plot goes on right side, spanning 3 rows

    ## Display the widget as a new window
    w.show()
    win = pg.GraphicsLayoutWidget()

    app.exec_()
```
This error will be thrown:
> QWidget: Must construct a QApplication before a  QPaintDevice
Using it with PySide or PyQt works without any problems.

**Comment by j9ac9k** [comment]
We're working on this, in the meantime you can install pyqtgraph from the development branch directly (it's how I've been using pyqtgraph with pyside2).

**Comment by jcyrss** [comment]
When will the stable release supporting pyside2 be avaliable on PYPI?

**Comment by j9ac9k** [comment]
Hi @jcyrss we're talking internally about doing an RC release soon (we're all volunteers that work off-the-clock on this project, so soon is really a matter of when we have time).

For the time being, you can install from the `develop` branch directly via pip by running

```
pip install git+https://github.com/pyqtgraph/pyqtgraph@develop
```

or alternative if you're using a `requirements.txt`  file you have to specify a commit, but the entry would be something like

```
git+https://github.com/pyqtgraph/pyqtgraph.git@db483f8ec22a0d53bd0e71fac69b0045a96c6637#egg=pyqtgraph
```

**Comment by kamikaze** [comment]
Guys, I can upload your package to pypi if it's hard

ср, 11 дек. 2019 г., 18:18 Ogi Moore <notifications@github.com>:
