### ISSUE TITLE
Group-type Parameter doesn't hide

### ISSUE THREAD

**Issue by aziesemer** [pyqtgraph/pyqtgraph#346]
I think that it is missing a call to the same method in the super class (as happens with the other Parameter types):
# Call base class to hide/show group-type parameter item

def optsChanged_Fix(self, param, opts):
    ParameterItem.optsChanged(self, param, opts)
    if 'addList' in opts:
        self.updateAddList()

GroupParameterItem.optsChanged = optsChanged_Fix

**Comment by lidstrom83** [comment]
PR #328 will fix this.

**Comment by 2xB** [comment]
This should be fixed via https://github.com/pyqtgraph/pyqtgraph/commit/65e9052580fe93130738549dc374621efdc126fa, which is very similar to the referenced pull request. If possible, it would of course be great if you could test the current `develop` branch.
