### ISSUE TITLE
UnsupportedOperation: IOStream has no fileno.

### ISSUE THREAD

**Issue by genliu777** [pyqtgraph/pyqtgraph#353]
in Jupyter QtConsole, i just want to import examples.

import pyqtgraph.examples

and it fails: 

---

UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-1-abb779932323> in <module>()
----> 1 import pyqtgraph.examples

C:\Anaconda3_64\lib\site-packages\pyqtgraph\examples__init__.py in <module>()
----> 1 from .**main** import run

C:\Anaconda3_64\lib\site-packages\pyqtgraph\examples__main__.py in <module>()
      7     **package** = "examples"
      8 
----> 9 from . import initExample
     10 from pyqtgraph.Qt import QtCore, QtGui, USE_PYSIDE
     11 import pyqtgraph as pg

C:\Anaconda3_64\lib\site-packages\pyqtgraph\examples\initExample.py in <module>()
     38 try:
     39     import faulthandler
---> 40     faulthandler.enable()
     41 except ImportError:
     42     pass

C:\Anaconda3_64\lib\site-packages\ipykernel\iostream.py in fileno(self)
    203 
    204     def fileno(self):
--> 205         raise UnsupportedOperation("IOStream has no fileno.")
    206 
    207     def write(self, string):

UnsupportedOperation: IOStream has no fileno.

**Comment by j9ac9k** [comment]
I couldn't replicate

![image](https://user-images.githubusercontent.com/646398/60299819-771e0e00-98e2-11e9-8916-43a162266cf0.png)


If you can reproduce this with the current develop branch of the library let us know and we'll reopen and investigate further.
