### ISSUE TITLE
Test warnings with NumPy 1.11

### ISSUE THREAD

**Issue by QuLogic** [pyqtgraph/pyqtgraph#354]
Using the latest `develop`, `test_nan_image` in `pyqtgraph/imageview/tests/test_imageview.py` produces the following exception, though it seems to be ignored:

``` pytb
Traceback (most recent call last):
  File ".../pyqtgraph/graphicsItems/HistogramLUTItem.py", line 195, in imageChanged
    h = self.imageItem().getHistogram()
  File ".../pyqtgraph/graphicsItems/ImageItem.py", line 398, in getHistogram
    hist = np.histogram(stepData, **kwds)
  File ".../numpy/lib/function_base.py", line 505, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.
```

Sometimes, though not always, the following warnings are printed:

```
.../pyqtgraph/functions.py:1011: RuntimeWarning: divide by zero encountered in double_scalars
  data = rescaleData(data, scale/(maxVal-minVal), minVal, dtype=dtype)
.../pyqtgraph/functions.py:870: RuntimeWarning: invalid value encountered in multiply
  d2 *= scale
```

**Comment by 2xB** [comment]
Currently, the CI pipelines shows that this test is no longer failing. If you still manage to reproduce this, feel free to leave a comment or open a new issue.

**Comment by j9ac9k** [comment]
We still get those warnings; #926 and #927 (on numpy 1.16.4), If i recognized this issue, I would have followed up here.
