### ISSUE TITLE
pyqtgraph.image window suppressed at least with ipython 5.0.0

### ISSUE THREAD

**Issue by wolfgang-noichl** [pyqtgraph/pyqtgraph#362]
Example:

``` python
import numpy as np
import pyqtgraph as pg

pg.image(np.random.rand(100,100,100))
```

Either the window **is not shown at all**, or it's not interactive (seems configuration dependent).
CTRL+D (and not quitting!) makes the window appear normally.

That's the case for both release 0.9.10 and the most recent dev branch, commit 670d63cdf443d667eece3b203083692588f41693.

**Comment by petermoran** [comment]
I noticed this issue.  Try setting IPython to use the qt gui event loop, e.g. from the command line:

ipython --TerminalIPythonApp.gui='qt'

Or you can set it for your profile.

**Comment by j9ac9k** [comment]
Issue here is that there is no QEventLoop running, if you look at any of the examples, you will notice that a QApplication instance is started by calling the `exec_()` method.
