### ISSUE TITLE
how to embed pyqtgraph into webbrowser such as ie or chrome?

### ISSUE THREAD

**Issue by genliu777** [pyqtgraph/pyqtgraph#364]
as the title mentioned, i want to embed pyqtgraph in chrome, and i install pyqt5 in my toplap.

**Comment by onlyjus** [comment]
Why do you want to embed pyqtgraph in chrome?

If you are looking for a python plotting library that works in the browser, try bokeh: http://bokeh.pydata.org/en/latest/

**Comment by ixjlyons** [comment]
pyqtgraph is specifically for creating desktop applications, so this is out of scope for the library. As noted above, there are better options for plotting in the browser.
