### ISSUE TITLE
Composite graphs

### ISSUE THREAD

**Issue by brupelo** [pyqtgraph/pyqtgraph#365]
I was thinking to use pyqtgraph for one tool using opengl+shaders, before doing that i'd like to know whether it's possible to compose graphs in a similar way to Blender or Coral recursively and exposing certain inputs and outputs ?

Btw, is there any pyqt project out there using pyqtgraph to manage and process nodes like Nuke software?

Thank you.

**Comment by 2xB** [comment]
Yes, that exists. It is called `Flowchart`. I do not have an overview of software that uses it - you might look into the flowchart example in the `examples` folder to see it in action!

**Comment by 2xB** [comment]
If you have further comments, just add them here or in a new issue!
