### ISSUE TITLE
Is it time for official 0.9.11?

### ISSUE THREAD

**Issue by talkaminker** [pyqtgraph/pyqtgraph#377]
The Qt5 support is by far the most needed  (especially now that the newer Spyder version doesn't work on qt4 anymore)
Thanks!

**Comment by bjxpolarbear** [comment]
I agree, I would love to see that coming in short.

**Comment by stonebig** [comment]
@talkaminker , where did you read that Spyder-3.0.0 would not support Qt4 ?

**Comment by talkaminker** [comment]
currently updating spyder using conda will update qt to qt 5.  pyqtgraph prevents this update (in conda). this may be only a conda thing (i didn't try it with pip)
In any case, the spyder issue is beside the point. We will all love to see a new official release with qt5 support and all the new goods and bugfixes that come with it.

**Comment by lxkain** [comment]
+1

**Comment by campagnola** [comment]
It is time! The next version will be 0.10. At this point I am just working
on the scripts for building release packages.

**Comment by lxkain** [comment]
That's really exciting & thank you!!!

**Comment by flutefreak7** [comment]
I know it's a minor fix, but I'm really looking forward to a stable pyqtgraph release that includes the fix for the VisibleDeprecationWarning's that numpy churns out with the current code (for non-integer slice indices).  Really looking forward to this update!  Go Luke!

**Comment by campagnola** [comment]
Preliminary release packages for 0.10.0 are up at
http://pyqtgraph.org/downloads/0.10.0/
Try 'em out, let me know if there are any major issues. If everything is
good I'll push up to pypi in a few days.


Luke

**Comment by YoshiharaYusuke** [comment]
There is no problem the 0.10.0. for my environment(win10), because i just only use PlotWidget and regionItem.
Incidentally... please merge my pull request #382(it was #379).

**Comment by lxkain** [comment]
I installed this on Debian from the .tgz. I ran most of the examples and everything worked great with just Qt5 installed. Thank you so much!

**Comment by mivade** [comment]
I ran through most of the examples in OS X with PyQt5 and saw no obvious issues. I'd say it's ready for a realease on PyPI!

**Comment by peendebak** [comment]
Installed under Ubuntu 16.04 (python 3) and it works fine.

**Comment by giulioungaretti** [comment]
Time to close this @campagnola , thanks for the new release ! 

https://github.com/pyqtgraph/pyqtgraph/releases/tag/pyqtgraph-0.10.0

**Comment by sscherfke** [comment]
There are still some issues with PyQt5, see pull request #361
