### ISSUE TITLE
Setting the order of GraphicsItems in PlotWidget

### ISSUE THREAD

**Issue by balashev** [pyqtgraph/pyqtgraph#380]
Is it possible to change the order of GraphicsItems in the PlotWidget?

I just want to plot selected Graphics Item in front of other Items in PlotWidget.

**Comment by NilsNemitz** [comment]
For future reference, and for those who may come across this in a Google search:
GraphicsItems typically support 
`item.setZValue()`
Assigning a higher z-value will cause items to draw on top of other items, that is
```python
item1.setZValue(3)
item2.setZValue(2)
```
will cause item1 to draw over item2, independent of the order they were originally assigned.
