### ISSUE TITLE
API documentation is broken

### ISSUE THREAD

**Issue by mivade** [pyqtgraph/pyqtgraph#387]
The latest documentation on readthedocs lists many classes under the "API Reference" section, however they all appear to have no generated documentation apart from the class name.

**Comment by mivade** [comment]
For now, the [documentation for the previous release](http://www.pyqtgraph.org/documentation/apireference.html) works as a reference.

**Comment by ixjlyons** [comment]
This is because PyQt/PySide isn't installed on the Read the Docs server. The only reasonable solution as far as I can tell is to use a [conda environment](https://read-the-docs.readthedocs.io/en/latest/conda.html#conda-support).

**Comment by campagnola** [comment]
Thanks Mike!
I actually don't have access to pyqtgraph.readthedocs.io. For now, I have
reverted to using pyqtgraph.org to host the documentation.

**Comment by mivade** [comment]
This looks to have been resolved!
