### ISSUE TITLE
wheelEvent broken in RemoteGraphicsView with pyqt5

### ISSUE THREAD

**Issue by michelp** [pyqtgraph/pyqtgraph#426]
This can be reproduced with the example/RemoteGraphicsView.py demo.  Just run and try and move the mouse wheel.  It throws:

Traceback (most recent call last):
  File "/home/michel/dev/pyqtgraph/pyqtgraph/widgets/RemoteGraphicsView.py", line 115, in wheelEvent
    self._view.wheelEvent(ev.pos(), ev.globalPos(), ev.delta(), int(ev.buttons()), int(ev.modifiers()), int(ev.orientation()), _callSync='off')
AttributeError: 'QWheelEvent' object has no attribute 'delta'

It appears that .delta() has become qt4Delta and .orientation() has become qt4Orientation.

**Comment by mrdawson** [comment]
+1
`.delta()` is deprecated in Qt5 and has been replaced by `.angleDelta()` and `.pixelDelta()`
`.orientation()` is also deprecated and appears to have no direct replacement
