### ISSUE TITLE
BUG# detection of requirements

### ISSUE THREAD

**Issue by pedromorgan** [pyqtgraph/pyqtgraph#43]
In my case against 
## kubuntu linux 

after apt-get install scipy
pyopengl failed when I try to run 3d
## Windows

After git submodule against my application, failed to find numpy and scipy..
and eventually installed from . ? (cant remember)

I think we need to alert users where to download these externals.. maybe
and dependancies.. even if it means calling vbs, or popping up a single html page..
- GL / pyopengl could be disabled if not present..
- the others are fatal..

**Comment by ixjlyons** [comment]
I think the situation regarding installing pyqtgraph's dependencies has improved (e.g. with wheels and conda) since this issue was raised. Closing in a cleanup sweep of some old issues.
