### ISSUE TITLE
Calling a SpinBox-Parameter's hide()/show() raises a TypeError in version 0.10.0

### ISSUE THREAD

**Issue by honkomonk** [pyqtgraph/pyqtgraph#430]
Hi,

I stumbled accross a bug when calling the hide()/show() function of a SpinBox Parameter in a ParameterTree. With PyQtGraph version 0.10.0 my code produces the following error, while it worked fine in version 0.9.10 ...
> Traceback (most recent call last):
>   File "D:\...\python\pyqtgraph\pyqtgraph\parametertree\parameterTypes.py", line 284, in optsChanged
>     self.widget.setOpts(**opts)
>   File "D:\...\python\pyqtgraph\pyqtgraph\widgets\SpinBox.py", line 160, in setOpts
>     raise TypeError("Invalid keyword argument '%s'." % k)
> TypeError: Invalid keyword argument 'visible'.

From a quick look at the code I guess the keyword 'visible' is missing in the default options of the widget. In version 0.10.0 new code was added in SpinBox.py just before line 160 that checks if a config option is among the default keywords. I haven't checked all types of widgets, but apparently the bug only affects the int/float spinbox widgets.

Here's a minimum working example:
```
# -*- coding: utf-8 -*-
"""Minimum working example for a bug in pyqtgraph's parametertree. Calling a ParameterItems hide()/show() raises a TypeError in version 0.10.0."""

import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui
from pyqtgraph.parametertree import Parameter, ParameterTree

app = QtGui.QApplication([])

params = [
    {'name': 'Dummy', 'type': 'int', 'value': 10},
    {'name': 'Show', 'type': 'action'},
    {'name': 'Hide', 'type': 'action'},
]

## Create tree of Parameter objects
p = Parameter.create(name='params', type='group', children=params)
t = ParameterTree()
t.setParameters(p, showTop=False)

p.param('Show').sigActivated.connect(lambda: p.param('Dummy').show())
p.param('Hide').sigActivated.connect(lambda: p.param('Dummy').hide())

win = QtGui.QMainWindow()
win.setCentralWidget(t)
win.show()

## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()

```

Keep up the good work!

**Comment by 2xB** [comment]
Thank you for the report! This is fixed in the upcoming version 0.11.0 (and currently on the `develop` branch) via commit 65e9052580fe93130738549dc374621efdc126fa.
