### ISSUE TITLE
Crash when canceling export

### ISSUE THREAD

**Issue by mgrady3** [pyqtgraph/pyqtgraph#432]
OS X, Python 3.6 via Anaconda, PyQt 5.6 via Anaconda, pyqtgraph 0.10 via pip

When displaying an image via imageView and selecting "Export" from the "Menu" button, if you click cancel to cancel the export of the image, python crashes with the following error:

Traceback (most recent call last):
  File "/Users/Maxwell/Anaconda/envs/pls-pyqtg/lib/python3.6/site-packages/pyqtgraph/imageview/ImageView.py", line 737, in exportClicked
    self.export(fileName)
  File "/Users/Maxwell/Anaconda/envs/pls-pyqtg/lib/python3.6/site-packages/pyqtgraph/imageview/ImageView.py", line 731, in export
    self.imageItem.save(fileName)
  File "/Users/Maxwell/Anaconda/envs/pls-pyqtg/lib/python3.6/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 430, in save
    self.qimage.save(fileName, *args)
TypeError: arguments did not match any overloaded call:
  save(self, str, format: str = None, quality: int = -1): argument 1 has unexpected type 'tuple'
  save(self, QIODevice, format: str = None, quality: int = -1): argument 1 has unexpected type 'tuple'
Abort trap: 6

[Minimal Example](https://gist.github.com/mgrady3/ee502090c135553af4f1028086bec999)

Here is a link for a minimal working example which creates a QWidget, embeds an imageView from pyqtgraph, creates a numpy array of random values, then displays the image.

The error can be reproduced by clicking Menu then Export then clicking the Cancel button when the Export dialog appears.

The error appears to be related to not handling the situation when the cancel button is selected. 
The method exportClicked() in imageview.py gets a filename from the Qt Dialog QFileDialog.getSaveFileName() method and then checks if the filename is blank. If the file name is blank the entire process is canceled. However, my guess here is that in PyQt5, the output from getSaveFileName() has been chanced to be a tuple instead of a string. This is in line with certain methods like getOpenFileName(). The output from getOpenFileName(), in PyQt5, was changed to output a tuple of two items, the first being a string with the file name, and the second being the file type filter that was active when selecting the file (All files, '.txt', '.jpg', etc ...).

**Comment by mgrady3** [comment]
The following edit of the method exportClicked() in file ImageView.py fixed the problem for me. (Tested on OS X.11 and Ubuntu 16.04)

def exportClicked(self):
        fileName = QtGui.QFileDialog.getSaveFileName()
        # if fileName == '':
        #    return
        if type(fileName) == tuple:
            try:
                fileName = fileName[0]
            except IndexError:
                # empty tuple -> return
                return
        elif fileName == '':
                # This was the old check for "Cancel" scenario
                return
            pass
        self.export(fileName)

**Comment by 2xB** [comment]
Thank you for the report! This will be fixed in the upcoming 0.11.0 version, pretty similarly to your suggestion with commit 3fd56eb195b10e209c3c00376b37408328fce58f (currently on branch `develop`)!
