### ISSUE TITLE
BUG: PyQt5 svg

### ISSUE THREAD

**Issue by sem-geologist** [pyqtgraph/pyqtgraph#434]
*When exporting figure to svg with PyQt5 I experience that Y axis in plots gets wrongly placed, while PyQt4 gets ok svg.
* If there is many plots (like first example in pyqtgraph.examples) PyQt4 svg export sucess, PyQt5 crash.

Also in both Qt4 and Qt5 there is no bounding box in produced svg, can something be done about that?

system: debian testing, PyQt and Qt 5.7

**Comment by zhliu0124** [comment]
I got a very similar axes-shifting problem while exporting SVG files:
[](https://stackoverflow.com/questions/45517995/pyqtgraph-exporting-svg-messy-shifting/45530829#45530829)

**Comment by sem-geologist** [comment]
I hope #641 fixes this issue.

**Comment by sem-geologist** [comment]
#641 had fixed the issue, I am closing it.
