### ISSUE TITLE
Axis values

### ISSUE THREAD

**Issue by marijazupunski** [pyqtgraph/pyqtgraph#449]
After zooming in/out a lot, numbers of axis values are so big that axis is moved. Calling auto scale after that do not restart axis position
In attachment there are  images that show use cases.

![moved axis](https://cloud.githubusercontent.com/assets/14001200/23157423/6ebb02d2-f81b-11e6-9217-b08b2af12dee.PNG)

![after autoscaling](https://cloud.githubusercontent.com/assets/14001200/23157463/a96b61c4-f81b-11e6-8379-0dbb32febae8.PNG)

**Comment by lesauxvi** [comment]
PR #403 proposes a fix to solve that problem.

Vincent
