### ISSUE TITLE
kiloseconds

### ISSUE THREAD

**Issue by Kamik423** [pyqtgraph/pyqtgraph#451]
is there a way to automatically use minutes and hours, not kilo seconds?

**Comment by 2xB** [comment]
No, there isn't. I think this is somewhat out of scope for a scientific plotting library. If there is an interesting approach to include such a feature, of course a pull request would be interesting - but I think this had to be something reusable for other custom tick types so we do not have too much code floating around something that is in our case an edge case.

If you would like to monkey-patch or extend pyqtgraph for yourself, overwriting `generateDrawSpecs` of AxisItem would be the way to go, especially https://github.com/pyqtgraph/pyqtgraph/blob/132f417f7267605dc5dee9ea78f0112a23d0f1fd/pyqtgraph/graphicsItems/AxisItem.py#L880 .

**Comment by j9ac9k** [comment]
@Kamik423 We would definitely welcome and review a pull request with this feature.   If implementing in your own application, you would need to subclass `AxisItem` and likely edit the function that governs what strings are displayed.  The line you will likely want to edit is here:

https://github.com/pyqtgraph/pyqtgraph/blob/132f417f7267605dc5dee9ea78f0112a23d0f1fd/pyqtgraph/graphicsItems/AxisItem.py#L843

There is more talk of improving the styling of the plotting library, which I agree with but I'm also cautious of.  I think it may be worth considering allowing for passing of an optional custom string mapping function.  But given that isn't what you were asking for specifically, that's likely worth it's own issue, and I'm going to close this one out.
