### ISSUE TITLE
detach QtProcess

### ISSUE THREAD

**Issue by peendebak** [pyqtgraph/pyqtgraph#460]
When working with a `QtProcess`, is there a way to detach the process from the main process (so that the remote process continues running when the main process is closed)?

**Comment by j9ac9k** [comment]
Hi @peendebak 

We don't use `QProcess` anywhere in this library, so we're not well prepared to answer this question, this would be a better question for a Qt forum/group.   In short, I don't know, but I would suspect any QProcess that is started would likely be a child-process of the main process, so I would be surprised if there was a way to have it keep going if the main process starts.
