### ISSUE TITLE
set LinearRegionItem color?

### ISSUE THREAD

**Issue by 4ever911** [pyqtgraph/pyqtgraph#462]
Cannot set line color when creating LinearRegionItem. Have to do something dirty like below:

rsi = pg.LinearRegionItem([30,70], orientation=pg.LinearRegionItem.Horizontal, movable=False)

rsi.lines[0].setPen('w')
rsi.lines[1].setPen('w')

**Comment by 2xB** [comment]
This feature was implemented in https://github.com/pyqtgraph/pyqtgraph/commit/98cdc65049a8b61169982bb7add833f923979bf4, is currently available on branch `develop` and will be part of pyqtgraph 0.11!
