### ISSUE TITLE
when exporting the params width and heigth are floats instead of int

### ISSUE THREAD

**Issue by jjgsherwood** [pyqtgraph/pyqtgraph#464]
When exporting large images, with Image export, two things go wrong:
-  the scaling ratio uses floats and put the height and width in params back as floats
- during __init__ the params height and width are made as floats.

I solved it with the following code:

```
from pyqtgraph.exporters.ImageExporter import ImageExporter,Exporter
from pyqtgraph.parametertree import Parameter

def widthChanged(self):
    sr = self.getSourceRect()
    ar = float(sr.height()) / sr.width()
    self.params.param('height').setValue(int(self.params['width'] * ar), blockSignal=self.heightChanged)
        
def heightChanged(self):
    sr = self.getSourceRect()
    ar = float(sr.width()) / sr.height()
    self.params.param('width').setValue(int(self.params['height'] * ar), blockSignal=self.widthChanged)

def New__init__(self, item):
    Exporter.__init__(self, item)
    tr = self.getTargetRect()
    if isinstance(item, pg.Qt.QtGui.QGraphicsItem):
        scene = item.scene()
    else:
        scene = item
    bgbrush = scene.views()[0].backgroundBrush()
    bg = bgbrush.color()
    if bgbrush.style() == pg.Qt.QtCore.Qt.NoBrush:
        bg.setAlpha(0)
            
    self.params = Parameter(name='params', type='group', children=[
        {'name': 'width', 'type': 'int', 'value': int(tr.width()), 'limits': (0, None)},
        {'name': 'height', 'type': 'int', 'value': int(tr.height()), 'limits': (0, None)},
        {'name': 'antialias', 'type': 'bool', 'value': True},
        {'name': 'background', 'type': 'color', 'value': bg},
    ])
    self.params.param('width').sigValueChanged.connect(self.widthChanged)
    self.params.param('height').sigValueChanged.connect(self.heightChanged)
        
ImageExporter.heightChanged = heightChanged
ImageExporter.widthChanged = widthChanged
ImageExporter.__init__ = New__init__
```

**Comment by CPrescher** [comment]
I had the same error, but i think it can more easily fixed by using:
 
in the export function...

`bg = np.empty((int(self.params['width']), int(self.params['height']), 4), dtype=np.ubyte)`

**Comment by jjgsherwood** [comment]
That is true but I write an application for other users so I needed something that would fix the problem without changing pyqtgraph itself. It is almost the same amount as my code then and I though my code would be less likely to change when pyqtgraph release a new update. But otherwise indeed it is easier to just change in pyqtgraph only that line

**Comment by mihtjel** [comment]
Since line 67 in the files (ImageExporter.py) assigns width and height to w and h, I figured a sensible change was to fix those to be ints, and use them:

```
w, h = int(self.params['width']), int(self.params['height'])
if w == 0 or h == 0:
    raise Exception("Cannot export image with size=0 (requested export size is %dx%d)" % (w,h))
bg = np.empty((w, h, 4), dtype=np.ubyte)
```

**Comment by dorpvom** [comment]
Hi,
I had the same issue but through a third party library that uses pyqtgraph.
Looking at the code I thought about a more general fix:
As the Parameters class seems to store the type of a each parameter, isn't it possible to ensure the correct type whenever the setValue() method is called?
Maybe I'm off on that one though ^^

**Comment by QuLogic** [comment]
@mihtjel That change is part of #356.

**Comment by campagnola** [comment]
I believe this is fixed in the `develop` branch; please reopen if I misunderstood the issue.
