### ISSUE TITLE
Image (NumPy array) data not released when closing plot windows (memory leak?)

### ISSUE THREAD

**Issue by nanoant** [pyqtgraph/pyqtgraph#466]
Long story short, pyqtgraph is not releasing NumPy array variables once they are used by some plots.

Run following commands line by line and observe your memory usage (eg. in task manager):
```python
import numpy
import pyqtgraph
a=numpy.ones((128,1024,1024)) #<- 1GB now used by python
del a                         #<- memory released python now is using just few MBs
a=numpy.ones((128,1024,1024)) #<- 1GB now used again by python
pyqtgraph.image(a) # opens a window
pyqtgraph.QtGui.QGuiApplication.exec() # just run Qt event loop, so we can close the window
# now close the plot window
del a #<- python still uses 1GB, even I have just released NumPy array
pyqtgraph.cleanup() #<- no effect, still 1GB used
import gc
gc.collect() #<- absolutely no efffect, still 1GB used
```
Is there any reason that this memory is not collected and pyqtgraph is keeping references to non-accessible plot objects?

**Comment by nanoant** [comment]
Some update on this issue. pyqtgraph seems to track imageViews in `images` global. However clearing this global does not release underlying memory:
```python
pyqtgraph.images.clear() #<- no effect memory not released
```
But if we instead of the command above, assign some 1x1 image to existing images, then most (but not all) memory is reclaimed.
```python
for iw in pyqtgraph.images:
  iw.setImage(numpy.zeros((1,1))) #<- dummy 1x1 image
  iw.parent().close()
```
So it means altogether that pyqtgraph (or Qt?) keeps a reference to `pyqtgraph.graphicsWindows.ImageWindow` even it is no longer accessible by user of `pyqtgraph`, which means that's a memory leak.

Altogether I think that `pyqtgraph` should not keep any strong references, and release memories once the windows are closed and there's no explicit reference to the window or other `pyqtgraph` object in the user's code.

**Comment by j9ac9k** [comment]
Since merging #468 we can close this issue out.
