### ISSUE TITLE
Image item step size is float leading to crash

### ISSUE THREAD

**Issue by DavidLP** [pyqtgraph/pyqtgraph#469]
**Description**
When the `getHistogram` function is called with std. parameters the step size is calculated [here](https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/graphicsItems/ImageItem.py#L453). The
calculated step size is a `float` leading to a crash:
``` bash
Traceback (most recent call last):
  File ".../test_online_monitor.py", line 168, in test_receiver
    data_received_2.append(receiver.position_img.getHistogram())
  File ".../python2.7/site-packages/pyqtgraph/graphicsItems/ImageItem.py", line 354, in getHistogram
    stepData = self.image[::step[0], ::step[1]]
TypeError: slice indices must be integers or None or have an __index__ method
```

**Solution**
Cast the step size to int [here](https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/graphicsItems/ImageItem.py#L453), like:
``` python
if step == 'auto':
  step = (np.ceil(self.image.shape[0] / targetImageSize).astype(np.int),
          np.ceil(self.image.shape[1] / targetImageSize).astype(np.int))
```

**Comment by QuLogic** [comment]
I don't understand; there's an `int()` in the code that you linked already.

**Comment by DavidLP** [comment]
True, was added 2 years ago. I do not know what happened when I reported this issue 2 months ago. I will close and reopen if needed. Thank you.
