### ISSUE TITLE
[CI-fail] LabelItem _sizeHint AttributeError

### ISSUE THREAD

**Issue by dam5h** [pyqtgraph/pyqtgraph#472]
Upon moving to PyQt5 in our application I am now seeing this error on one of the tests in the test suite.

```
________________________________________________________________________________
  File "c:\python36-x64\lib\site-packages\pyqtgraph\graphicsItems\LabelItem.py", line 130, in sizeHint
    if hint not in self._sizeHint:
AttributeError: 'LabelItem' object has no attribute '_sizeHint'
________________________________________________________________________________
Qt exceptions in virtual methods:
________________________________________________________________________________
  File "c:\python36-x64\lib\site-packages\pyqtgraph\graphicsItems\LabelItem.py", line 130, in sizeHint
    if hint not in self._sizeHint:
AttributeError: 'LabelItem' object has no attribute '_sizeHint'
________________________________________________________________________________
Qt exceptions in virtual methods:
________________________________________________________________________________
  File "c:\python36-x64\lib\site-packages\pyqtgraph\graphicsItems\LabelItem.py", line 130, in sizeHint
    if hint not in self._sizeHint:
AttributeError: 'LabelItem' object has no attribute '_sizeHint'
__________________________________________________________________________
```
Clearly LabelItem has a dictionary called `self._sizeHint` from looking at the source.  I am thinking this could have to do with shutdown and the order with which Qt is destroying widgets (LabelItem never gets parent passed in) but I am not yet sure.  Does anyone have any ideas on debugging this?

Thanks,
Dave

**Comment by j9ac9k** [comment]
Was looking over our newly implemented CI system and saw this error there; we should likely try and patch this guy up shortly.

**Comment by j9ac9k** [comment]
While I see this error in CI, looking over the code I don't see how this is generated.

Anyone on a Windows machine able to reproduce locally?

**Comment by j9ac9k** [comment]
Wonder if this is related to #884

**Comment by Dschoni** [comment]
I tried reproducing on both python2 and python3 with pyqt5 and could not reproduce locally. @j9ac9k could you point me to a CI log, that shows that error, so I can try and setup the exact same environment locally?

**Comment by j9ac9k** [comment]
I actually meant to follow up on this yesterday, I think this issue was inadvertently fixed sometime in the last few weeks as I haven't seen this failure in the CI recently.

**Comment by Dschoni** [comment]
Close this for now, as right now the error cannot be reproduced.
