### ISSUE TITLE
Kernel dies unexpectedly when trying to import pyqtgraph

### ISSUE THREAD

**Issue by shubhamsharma1609** [pyqtgraph/pyqtgraph#480]
I am using Python 3.5 in spyder (Anaconda 3) and successfully installed the pyqtgraph but whenever I am trying to import through import pyqtgraph as pg ,the kernel dies unexpectedly everytime. I am using Qt4. Kindly help.

**Comment by j9ac9k** [comment]
There's not nearly enough information.  If you can reproduce, please open a new issue with OS version, pyqtgraph version, qt-bindings version, as well as any kind of console output
