### ISSUE TITLE
Parameter 'pos' of GLViewWidget.setCameraPosition() is ignored

### ISSUE THREAD

**Issue by cklb** [pyqtgraph/pyqtgraph#481]
It seems like the mentioned method ignores its first argument `pos` .

As you can see in:
https://github.com/pyqtgraph/pyqtgraph/blob/5195d9dd6308caee87e043e859e7e553b9887453/pyqtgraph/opengl/GLViewWidget.py#L224
all other arguments are handled correctly.

Adding:
```
if pos is not None:
      self.opts['center'] = pos
```
fixes the behavior for me.

If the solution is really that simple, I'm gladly opening a PR for this.

**Comment by ParisNeo** [comment]
Thanks, this work for me too.
I don't want to mess around with the pyqtgraph library so I added a workaround function in my project:
`
def setCameraPosition(w, pos=None, distance=None, elevation=None, azimuth=None):
    if pos is not None:
        w.opts['center'] = pos
    if distance is not None:
        w.opts['distance'] = distance
    if elevation is not None:
        w.opts['elevation'] = elevation
    if azimuth is not None:
        w.opts['azimuth'] = azimuth
    w.update()       
`

**Comment by j9ac9k** [comment]
Closing due to the merging of #770
