### ISSUE TITLE
candlestick plot

### ISSUE THREAD

**Issue by cresg820** [pyqtgraph/pyqtgraph#483]
I've googling by i can't figure out if is possibile to plot a candlestick graph or not?

**Comment by genliu777** [comment]
it can, and it does well!!

**Comment by fcorrea** [comment]
Trivial and done already:

https://github.com/pyqtgraph/pyqtgraph/blob/develop/examples/customGraphicsItem.py

**Comment by ixjlyons** [comment]
Closing per the comments above.

**Comment by dgabriele** [comment]
The author of the example should use actual `"""` doc strings rather than a bunch of inline comments ;)

**Comment by sam-the-programmer** [comment]
Could this not be added to the docs?

**Comment by j9ac9k** [comment]
> Could this not be added to the docs?

a PR would definitely be considered here; maintainers are a bit overloaded so it's unlikely this would be implemented by the maintainers any time soon.   We are considering a documentation overhaul, where something like this would get incorporated, but AFAIK there isn't any kind of WIP on this effort as of right now.

**Comment by ixjlyons** [comment]
I have a branch with a mostly-working sphinx-gallery that I really ought to get back to and finish up...

Also I'd just point out the examples have always been a big component of pyqtgraph's documentation despite not actually being integrated with the sphinx docs (yet).

**Comment by j9ac9k** [comment]
> I have a branch with a mostly-working sphinx-gallery that I really ought to get back to and finish up...
> 
> Also I'd just point out the examples have always been a big component of pyqtgraph's documentation despite not actually being integrated with the sphinx docs (yet).

Is this something you would like help with?  If you have it on a branch on your fork and want me to take a look, let me know.
