### ISSUE TITLE
incorrect axis ticks

### ISSUE THREAD

**Issue by peendebak** [pyqtgraph/pyqtgraph#489]
When creating a simple plot the axis are labelled fine when I put the window on my normal monitor (e.g. the x-axis runs from 0 to 9):

```
import numpy as np
import pyqtgraph as pg
app=pg.mkQApp()

win = pg.GraphicsWindow(title="Basic plotting examples")
win.setGeometry(2400,40,1200,500)
p1 = win.addPlot(title="Basic array plotting", x=np.arange(10), y=np.arange(10)+np.random.normal(size=10))
```
If I move the plot window to my laptop monitor (which has zooming by 150% by default) the axis labels change, the x-axis runs from 0 to about 6). A screenshot of the window created by the code above is here:

https://snag.gy/d1kfD6.jpg

**Comment by kyleuckert** [comment]
This issue looks to be related to this stackoverflow question, which may provide more information:

https://stackoverflow.com/questions/45108069/pyqtgraph-axes-not-displaying-correctly

**Comment by sapphire008** [comment]
The solution provided by the stackoverflow question does not solve the problem. The external monitor may now display the axes correctly, but the native monitor no longer does.

**Comment by hi2010** [comment]
Altough this thread is a little bit old, if some body needs a workaround and finds this label:
for me using
`# Query DPI Awareness (Windows 10 and 8)`
`awareness = ctypes.c_int()`
`# errorCode = ctypes.windll.shcore.GetProcessDpiAwareness(0, ctypes.byref(awareness))`
`# print(awareness.value)`
`# Set DPI Awareness  (Windows 10 and 8)`
`errorCode = ctypes.windll.shcore.SetProcessDpiAwareness(1)`
`# errorCode = ctypes.windll.shcore.GetProcessDpiAwareness(0, ctypes.byref(awareness))`
`# print(awareness.value)`
`# the argument is the awareness level, which can be 0, 1 or 2:`
`# for 1-to-1 pixel control I seem to need it to be non-zero (I'm using level 2)`

Before the creation of the QApplication did help creating plots without the offset on the second screen.

Sources:
https://stackoverflow.com/questions/45108069/pyqtgraph-axes-not-displaying-correctly
https://stackoverflow.com/questions/44398075/can-dpi-scaling-be-enabled-disabled-programmatically-on-a-per-session-basis

**Comment by j9ac9k** [comment]
I'm going to close this issue out as the bulk of hidpi issues have been resolved.  The ctypes issue shown here is only applicable to windows so I'd be reluctant to introduce that given that with the current  versions of Qt, hidpi on windows "just works" (at least as far as I'm aware).
