### ISSUE TITLE
Parameter.opts keeps stale data about children

### ISSUE THREAD

**Issue by polwel** [pyqtgraph/pyqtgraph#493]
We can initialize a `Parameter` like so:

```python
Parameter.create( ..., children=[...])
```
This way, a key called `'children'` ends up in the `opts` of the newly created parameter. It is never updated though, as children are added, renamed or deleted. Eventually it causes trouble when `Parameter.storeState` is called, as some code paths of that function store the stale `opts['children']`, rather than generate it dynamically.

AFAICT, `opts['children']` is needed only when initializing the `Parameter`. After that it only contains redundant (and potentially stale) information. I thus suggest not to keep `opts['children']` around beyond the `Parameter.__init__` function. Just `del opts['children']` after use, e.g. in `Parameter.py:183`.

I will submit a PR shortly.

**Comment by campagnola** [comment]
Thanks @polwel!
