### ISSUE TITLE
Retina display 3D issue

### ISSUE THREAD

**Issue by edbarnard** [pyqtgraph/pyqtgraph#497]
When opening a 3D example on a Mac with a Retina (HiDPI) display, the scene is only rendered in the bottom left quadrant of the window.

<img width="591" alt="screen shot 2017-06-09 at 10 19 47 am" src="https://user-images.githubusercontent.com/6744917/26986652-54c5a4ea-4cfd-11e7-89ae-ae855d020a9f.png">

Anaconda environment includes:

numpy                     1.11.3                   py35_0  
pyopengl                  3.1.1a1             np111py35_0  
pyqt                      5.6.0                    py35_1  
pyqtgraph                 0.10.0+gaf4c673           <pip>
scipy                     0.19.0              np111py35_0

**Comment by mshunshin** [comment]
I have reported the same in issue #422 with a fix. I just haven't made a pull request for it.

**Comment by msollami** [comment]
I'm seeing this bug again on Macos 10.13.6 with Anaconda and Python 3.6.
