### ISSUE TITLE
Graphs don't refresh properly with some versions of python

### ISSUE THREAD

**Issue by spikeynick** [pyqtgraph/pyqtgraph#499]
I had pyqtgraph installed on Windows using Python 2.7 32bit and it worked great.  I need to use 64bit for a project.  When I use python2.7 64bit it the scroll wheel zoom doesn't work at all.  Zooming the individual axes with right click, kind of works.  If you drag the right mouse button nothing seems to happen, but then if you pan with a left mouse click the graph updates.  
I upgraded to Python 3.6 64bit and pyqtgraph works great.  However due to other packages I can't use 3.6, so I changed to 3.5.  Pyqtgraph in python 3.5 64 bit has the same wonky behavior as the Python 2.7 64 bit.

I was able to reproduce this on two different machines

**Comment by j9ac9k** [comment]
Hi @spikeynick 

Sorry nobody followed up with you.  I'm going to close this out as I haven't seen the behavior you've described, but if you're still having an issue, if you can post an example that I can attempt to reproduce that would be helpful.
