### ISSUE TITLE
Unicode calls when saving and loading flowcharts fail on Python 3

### ISSUE THREAD

**Issue by npyoung** [pyqtgraph/pyqtgraph#512]
[`Flowchart.saveFile`](https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/flowchart/Flowchart.py#L538) and [`Flowchart.loadFile`](https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/flowchart/Flowchart.py#L517) both contain raw calls to `unicode` that have not been updated to use the python 2/3 compatibility library. These calls should be replaced by [`python2_3.asUnicode`](https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/python2_3.py#L6).

`FlowchartCtrlWidget` has similar issues in its `fileSaved` and `setCurrentFile` methods too.

**Comment by npyoung** [comment]
#513 fixes this issue.

**Comment by harwoodr** [comment]
We've done the fix manually in our environment - but will this pull request be merged in any time soon?
