### ISSUE TITLE
PlotWidget.__getattr__ raises wrong exception type - but this has a simple fix

### ISSUE THREAD

**Issue by vladimir-kraus** [pyqtgraph/pyqtgraph#525]
`hasattr(widget, "some_non_existing_attribute")` raises `NameError` instead of returning `False` for instances of `PlotWidget`. I think that `PlotWidget.__getattr__` (in PlotWidget.py) should raise `AttributeError` instead of `NameError`, which would be converted correctly to `False` by `hasattr`. I believe the same holds for `TabWindow.__getattr__` (in graphicsWindows.py).

**Comment by ixjlyons** [comment]
This was partially fixed by https://github.com/pyqtgraph/pyqtgraph/commit/52754d48594f713092a7e6b55a6fdcb046f76be6

`TabWindow.__getattr__` still raises a `NameError` so that should be fixed. I believe that's the only one remaining.
