### ISSUE TITLE
Retrieve configuration properties from a pickle file

### ISSUE THREAD

**Issue by oscarPrades** [pyqtgraph/pyqtgraph#531]
When i try to recover the properties of a curve (self.opts) which come from a pickle file, i get this error:

File "/usr/lib/python2.7/site-packages/pyqtgraph/debug.py", line 91, in w
    |      func(*args, **kwds)
    |    File "/usr/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 430, in paint
    |      path = self.getPath()
    |    File "/usr/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 412, in getPath
    |      self.path = self.generatePath(*self.getData())
    |    File "/usr/lib/python2.7/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 401, in generatePath
    |      path = fn.arrayToQPath(x, y, connect=self.opts['connect'])
    |    File "/usr/lib/python2.7/site-packages/pyqtgraph/functions.py", line 1391, in arrayToQPath
    |      raise Exception('connect argument must be "all", "pairs", "finite", or array')
    |  Exception: connect argument must be "all", "pairs", "finite", or array

I think this comes from a eq(a,b) function in the script functions.py.

**Comment by 2xB** [comment]
Could you perhaps provide a minimal working example that produces this error?

**Comment by j9ac9k** [comment]
Generally, Qt objects are not pickle-able; Going to close this issue out w/o more to go on.
