### ISSUE TITLE
PlotCurveItem "fillLevel" working as intended?

### ISSUE THREAD

**Issue by sandba66er** [pyqtgraph/pyqtgraph#539]
pg.plot(x,y)
pg.plot(out[0], out[1], fillBrush=pg.mkBrush(255, 0, 0, 90), fillLevel = 2, pen = 'r')

gives me:

![brokenfill1](https://user-images.githubusercontent.com/31360819/29737536-5a437b32-89c4-11e7-83e7-d35d6701431e.png)

where the 2nd curve is a b-spline.

pg.plot(x,y, fillLevel=2, fillBrush=pg.mkBrush(255, 0, 0, 90), pen=pg.mkPen(style=QtCore.Qt.DotLine))
pg.plot(out[0], out[1], pen = 'r')

also gives:

![brokenfill2](https://user-images.githubusercontent.com/31360819/29737572-f792f9a8-89c4-11e7-8b38-d4c87a6a627c.png)

so it's not just the b-spline causing the behavior.

Is this how it's supposed to work?  I'm trying to fill only under the curve up to x=2.  I could use fillbetween, but then I have to add code to figure a new curve where the index of the b-spline evaluates to 2 and add another "curve" from x=0 to x=2.

**Comment by sandba66er** [comment]
#Here is the workaround:

fillval = 1.88 #fill up to this value under curve

curve_index = min(enumerate(out[0]), key=lambda x: abs(x[1]-fillval))

ci = curve_index[0]

pdi3 = pg.PlotCurveItem([0,out[0][ci]],[0,0])
pdi4 = pg.PlotCurveItem(out[0][:ci+1], out[1][:ci+1], pen = 'r')

print(out[0][ci-1],out[0][ci],out[0][ci+1])

fbtwn = pg.FillBetweenItem(pdi3, pdi4, brush=pg.mkBrush(255, 0, 0, 90))
pItem.addItem(fbtwn)

![fillworkaround](https://user-images.githubusercontent.com/31360819/29738334-1eb631ac-89d5-11e7-8e3d-cc6de9429e2b.png)

**Comment by 2xB** [comment]
`fillLevel` has the documentation `Fill the area between the curve and fillLevel` (http://www.pyqtgraph.org/documentation/graphicsItems/plotdataitem.html#pyqtgraph.PlotDataItem.__init__). Therefore, you observed the intended behaviour. Using `FillBetweenItem` is a totally legitimate approach to this!

**Comment by j9ac9k** [comment]
Just to add to this, I'm not seeing a fill level argument that specifies a x-limit.

As an alternative workaround, you could plot a second line, that overlaps with the first, but only goes up to x=2; and set the `fillBrush` on that line instead.
