### ISSUE TITLE
Update the brush of individual SpotItem objects fast

### ISSUE THREAD

**Issue by georgedimitriadis** [pyqtgraph/pyqtgraph#540]
Hello Luke,

I am creating a ScatterPlotItem with hundreds of thousands of points (up to 1M). They are color and shape coded according to certain groups (a few hundred of them). I have made my own ROI extensions so that I can use different ROIs to select the data on the scatter plot. Given the size of the data set I am quite happy with the way pyqtgraph updates the selection and also zooms in and out and pans the view.

But I have one more need that right now is way to slow to implement. I need to be able to change the brush of the SpotItem points that I have selected with my ROI. I have tried the setBrush function at the level of the ScatterPlotItem (passing a list of brushes for all spots on the plot) and of course for anything more than 50k spots or so the update of the brushes is too slow. 

So I tried to access the individual SpotItem objects I was interested in changing and found how to do this:
points = scatter_item.points()
new_brush = pg.mkBrush(255, 255, 255, 255)
for i in range(number_of_points):
    if i in currently_selected:
        points[i].setBrush(new_brush)

I was hoping that this would update only the small number of points I select (usually fewer than a few thousands) and would be much faster. I realize though that this is not the case. Again the update depends on the total number of points I am showing and takes minutes to update for my full plot even if I have selected just a few hundred of points. Is there any way to update the brush of only a few points in a ScatterPlotItem that is not depended on the total number of points visible?

Thanks

**Comment by j9ac9k** [comment]
Fixed with #1420
