### ISSUE TITLE
playRate not observed in response to space bar

### ISSUE THREAD

**Issue by bensondaled** [pyqtgraph/pyqtgraph#549]
The ability to play an image using ImageView allows custom frame rates for playback, using 

`image_view.play(rate)`

However, if the image is played using the spacebar, the default frame rate is hard-coded as 

`fps = (self.getProcessedImage().shape[0]-1) / (self.tVals[-1] - self.tVals[0])`

This points to a more general design flaw in which the `playRate` class variable is used both to track the desired frame rate and the current state of play; i.e. it is set to the desired frame rate while the movie plays, and set to 0 to indicate to the event loop that playback should not occur.

In order to allow for consistent user-specified playback frame rates with interactive control, perhaps another class variable should be introduced, such as `fps`, independent of `playRate` (which can continue to serve as an internal flag for the playback loop).

**Comment by j9ac9k** [comment]
Resolved with the merging of #551
