### ISSUE TITLE
Crashes when closing pyqtgraph

### ISSUE THREAD

**Issue by fabioz** [pyqtgraph/pyqtgraph#55]
Ok, this is mostly to report my findings...

It seems it's pretty common for pyqtgraph to have crashes (not necessarily only on teardown, but also when some widget is not used and is about to be collected).

The only way I found to get over this is making sure that GraphicsView.close() and ViewBox.close() are always called -- so, maybe some warning in the application exit saying that close() wasn't properly called could be added?

My guess on why this happens is because there seem to be cycles in the application (i.e.: a scene has a reference to some item and that item in turn references the scene), this way, when python does a collect (when none of this objects are used anymore), it'll detect a cycle, yet it can't know for sure which is the correct order for the deletion -- and if it guesses wrong and deletes in the wrong order, qt can try to access an item which was already deleted on the teardown (i.e.: if the scene is deleted before a child).

So, the close() fixes this because we manually decide to delete and remove references to children in the parent -- although a real solution would be not having those cycles in the first place (but it'd need some changes on the basic structure -- I'm not familiar enough with the code to do that, so, I'm not providing a patch for this... but I think it'd the only way to fix the random crashes that can happen when using pyqtgraph when some pyqtgraph widget is not used anymore -- besides calling close() manually, in which case this should probably be made more explicit in the documentation. Also, fixing that should fix the need for the atexit.register issues).

As a separate note, you can use:
shiboken.isValid(o) and sip.isdeleted(o) to check if an object is still alive -- I saw some places in the code which catch a RuntimeError, but I think checking before is nicer :)

**Comment by j9ac9k** [comment]
Going to close out this issue as we don't have a reproducible example to work from.
