### ISSUE TITLE
There is an issues when I use Pycharm's "External Tools"

### ISSUE THREAD

**Issue by greedyhao** [pyqtgraph/pyqtgraph#554]
I've added **pyuic** to **External Tools**,but it didn't work.**Pyuic** can only work on shell.

This is **pyuic** on PyCharm.
![](https://user-images.githubusercontent.com/25771942/30363825-3b709a08-9894-11e7-9f74-a632293c2928.png)
This is **pyuic** on Shell.
![](https://user-images.githubusercontent.com/25771942/30363838-40b6ba1a-9894-11e7-9b99-08c84390622d.png)

I've searching on Google for a long time,but get nothing.Can anybody do me a favour?

**Comment by honkomonk** [comment]
The error message in Python says that your Python installation is missing PyQt5. However, as it's working in the shell, it's likely that you've more than one Python environment on the system and the one you're referencing to in your "External tools" setup is missing PyQt5.

Enter "where python.exe" in your shell. It will tell you which Python installation it  uses. IT's probably a different one as in PyCharm. Change your tool setting to that path or install PyQt5 in the other installation.
