### ISSUE TITLE
memory leak upon multiple ViewBox.linkView() calls

### ISSUE THREAD

**Issue by jaxankey** [pyqtgraph/pyqtgraph#556]
I noticed that repeatedly linking and unlinking views (with linkView()) consume memory. Here is simplified code to reproduce the issue:

```
import pyqtgraph

p1 = pyqtgraph.PlotWidget()
p2 = pyqtgraph.PlotWidget()

v1 = p1.plotItem.getViewBox()
v2 = p2.plotItem.getViewBox()

while True:
    v1.linkView(v1.XAxis, v2)
    v1.linkView(v1.XAxis, None)
```

Note the RAM will grow at a level of ~1 MB / sec with this code, whether I include the last line or not. I suspect a connection / signal / slot is not getting fully deleted.

This happens on Linux and Windows, Anaconda python 2.7 and 3.6, with pyqtgraph v0.10.0, and Qt5 underneath.

My workaround is to check the value of linkedView() prior to linking, and then only modify things if something actually needs changing. In my case, this confines the leak to only a few situations. However, this can be a serious problem if a program is dynamically changing the number of plots and rapidly plotting data (e.g. as in my lab).

Cheers,
Jack

**Comment by j9ac9k** [comment]
this might be a case where the connection call in viewbox.linkView method should have the Qt.UniqueConnection parameter passed along would be of benefit.

**Comment by j9ac9k** [comment]
Can replicate this issue on 0.12.2 still with PyQt5 5.12, but I cannot with PySide2 5.15; I suspect this is a Qt issue that was fixed upstream, so I'm going to close this issue out.  For the record, this is the code I ran.

```
import pyqtgraph

app = pyqtgraph.mkQApp()

p1 = pyqtgraph.PlotWidget()
p2 = pyqtgraph.PlotWidget()

v1 = p1.plotItem.getViewBox()
v2 = p2.plotItem.getViewBox()

while True:
    v1.linkView(v1.XAxis, v2)
    v1.linkView(v1.XAxis, None)

if __name__ == "__main__":
    pg.exec()
```

Also I'm not sure there is anything pyqtgraph could have done, given we disconnect the signal already.

Thanks for reporting @jaxankey sorry it's taken us so long to follow up.

**Comment by jaxankey** [comment]
When I run this code on my system from ipython (in Spyder), the memory accumulates still, as it did before. The original code I submitted just causes a kernel restart.

Linux Mint 20.1
Miniconda
pyqtgraph 0.12.2
PyQt 5.2.10
Python 3.9
Spyder 5.0.5
numpy 1.21.0

Perhaps this should stay open? @j9ac9k

**Comment by j9ac9k** [comment]
Hi @jaxankey I think you got a binding version wrong, I'm not sure pyqtgraph has ever supported Qt 5.2 (didn't know you could still get it).

My advice here would be to upgrade to a Qt binding of 5.15, which if you're stuck w/ conda distributions of bindings, I know that's not feasible at the moment (but folks are working on Qt 5.15 bindings for conda-forge).

I let the sample code run for over an hour on PySide2 5.15, and memory usage remained constant, so I'm confident in saying this is an upstream issue.

**Comment by jaxankey** [comment]
Sorry that was pasted from another thread with the same error. It's 5.12.10
________________________________
