### ISSUE TITLE
Ready-to-use colormaps for ImageItems etc.

### ISSUE THREAD

**Issue by drs251** [pyqtgraph/pyqtgraph#561]
IMO it would be nice to have a handful of pre-defined colormaps in pyqtgraph for ImageItem or elsewhere, instead of having to use grayscale or manually defining your own. One source of good quality colormaps is of course matplotlib. I use the following code to get the new perceptually uniform colormaps viridis, magma, plasma and inferno - it will not import all colormaps, but perhaps this could serve as a starting point.

```python
import maplotlib.pyplot as plt
import pyqtgraph as pg

def generatePgColormap(cm_name):
    pltMap = plt.get_cmap(cm_name)
    colors = pltMap.colors
    colors = [c + [1.] for c in colors]
    positions = np.linspace(0, 1, len(colors))
    pgMap = pg.ColorMap(positions, colors)
    return pgMap
```

**Comment by HashSplat** [comment]
I found that you can basically use matplotlib's colormaps for ImageItems.

```python
import numpy as np
import pyqtgraph

from matplotlib import cm

from PySide import QtGui

QtGui.QApplication([])

colormap = cm.get_cmap("nipy_spectral")  # cm.get_cmap("CMRmap")
colormap._init()
lut = (colormap._lut * 255).view(np.ndarray)

glw = pyqtgraph.GraphicsLayoutWidget()
glw.show()

p = glw.addPlot(0, 0)

img = pyqtgraph.ImageItem()
p.addItem(img)
img.setLookupTable(lut)

# dummy data
d = np.random.random_sample((1000, 1000))

img.updateImage(image=d, levels=(0, 1))

QtGui.qApp.exec_()
```

**Comment by drs251** [comment]
@HashSplat That's a neat hack, I'll have to remember that. By the way, do you know if it's possible to add a color bar to an `ImageItem`?

Anyway, what I was trying to suggest is that pyqtgraph should come with a couple of included colormaps. So instead of going through the details of how to make new `ColorMap` objects or lookup tables, people could simply say something like this:
 ```python
import pyqtgraph as pg
img = pg.ImageItem()
map = pg.colormaps.Viridis()   # for example
img.setLookupTable(map.getLookupTable())
```
Since I guess one does not want to add matplotlib as a dependency, one could go ahead and copy and paste the color values for the new viridis-and-friends maps from matplotlib's source and convert them to `ColorMap` objects  like in my first post. The other matplotlib color maps could be a bigger challenge, since they are generated by functions.

**Comment by feketeimre** [comment]
You could also use some of the built in colormaps from the gradient editor.

```python
import pyqtgraph as pg
from pyqtgraph.graphicsItems.GradientEditorItem import Gradients

#list the available colormaps
print Gradients.keys()

#pick one to turn into an actual colormap
spectrumColormap =  pg.ColorMap(*zip(*Gradients["spectrum"]["ticks"]))

#create colormaps from the builtins
for k,v in Gradients.iteritems():
    pos, color = zip(*v["ticks"])
    cmap =  pg.ColorMap(pos, color)
```

**Comment by honkomonk** [comment]
A while ago I wrote a converter for Matplotlib colormaps that might help here. I needed some colormaps from MPL in ImageViews. I converted them into the format `GradientEditorItem` uses internally and monkey-patched them into the menu of the gradient editor. Link: [mpl_cmaps_in_ImageView.py](https://github.com/honkomonk/pyqtgraph_sandbox/blob/master/mpl_cmaps_in_ImageView.py)

There is no dependency on matplotlib itself. It just traverses the datastructure of matplotlib's colormaps and it should work for all flavors (defined by a function, list of RGB values, list of color ranges). If a gradient is defined by color ranges between tickmarks, these can be edited in the gradient editor. However, a list of RGB tuples (like 'Viridis') shows up as 255 tickmarks.

I hacked together a small demo to use it with `ColorMap()` and an `ImageItem` : 
[mpl_cmaps_in_ImageItem.py](https://github.com/honkomonk/pyqtgraph_sandbox/blob/master/mpl_cmaps_in_ImageItem.py)

So you can just use it to convert colormaps on the fly (as showed above):
```python
...
 # Convert a matplotlib colormap into a list of (tickmark, (r,g,b)) tuples
pos, rgba_colors = zip(*cmapToColormap(matplotlib.cm.cubehelix))
# Set the colormap
pgColormap =  pyqtgraph.ColorMap(pos, rgba_colors)
imageitem.setLookupTable(pgColormap.getLookupTable())
...
```
or export the colormaps and include them into pyqtgraph like **feketeimre** showed.

When I wrote this pyqtgraph had no `ColorMap()` class. But now it could be a convenient `util` function or an alternative constructor for `ColorMap` objects (e.g. `ColorMap.from_mpl(cm.jet)`)?

**Comment by j9ac9k** [comment]
This should be implemented via #1424

**Comment by NilsNemitz** [comment]
Thanks to @honkomonk for figuring out the ridiculous number of formats that Matplotlib uses to describe its colormaps. That has been very helpful in building an importer for the ColorMap loader we have now!

**Comment by honkomonk** [comment]
You're welcome. Thanks for including it into PyQtGraph!

Hmm .... I just had a look at the code and a few remarks. I'll post it in #1424
