### ISSUE TITLE
How to setup columns width

### ISSUE THREAD

**Issue by Nedo93** [pyqtgraph/pyqtgraph#572]
Sorry if this is the wrong place to ask something like this.
Hi guys, this library is fantastic but I can't find a way to setup columns width properly.

![cattura](https://user-images.githubusercontent.com/24442367/30782741-6a96470e-a138-11e7-919e-64b4518b9635.PNG)

I would like something like this but currently to setup column's width I have to insert an element (a label here with a string long enough to achieve the width).
I'm sure that there is a better method to properly setup the width but I can't find a working method on the Internet

Thank you in advance if you can answer me.

Here is the code:

```python
app = QtGui.QApplication([])

# Window init
win = pg.GraphicsWindow(border=True)
win.showMaximized()
win.setWindowTitle('MeteoStation Graph')

# Enable antialiasing for prettier plots
pg.setConfigOptions(antialias=True)

t = "TEST: " + str(159873864824758969862456347656857111111111111)
r = "JIBJGRBKGLJRBG"

win.addLabel(t, row=0, col=0)
win.addLabel(t, row=0, col=2)
win.addLabel(r, row=1, col=0)

# Graphs plot
stringaxis = pg.AxisItem(orientation='bottom')
stringaxis.setTicks([xdict.items()])
p1 = win.addPlot(row=0, col=1, title="Temperature", axisItems={'bottom': stringaxis})
p1.plot(list(xdict.keys()), newlistY, pen={'color': (255, 0, 0), 'width': 2})
p1.setYRange(-10, 40)
p1.setXRange(0, 15)
p1.showGrid(x=True, y=True)

stringaxis = pg.AxisItem(orientation='bottom')
stringaxis.setTicks([xdict.items()])
p2 = win.addPlot(row=1, col=1, title="Humidty", axisItems={'bottom': stringaxis})
p2.plot(list(xdict.keys()), humlistY, pen={'color': (0, 255, 255), 'width': 2})
p2.setYRange(0, 60)
p2.setXRange(0, 15)
p2.showGrid(x=True, y=True)

stringaxis = pg.AxisItem(orientation='bottom')
stringaxis.setTicks([xdict.items()])
p3 = win.addPlot(row=2, col=1, title="Humidty", axisItems={'bottom': stringaxis})
p3.plot(list(xdict.keys()), humlistY, pen={'color': (0, 255, 0), 'width': 2})
p3.setYRange(32, 36)
p3.setXRange(0, 15)
p3.showGrid(x=True, y=True)

# Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()
```

**Comment by kuriankattukaren** [comment]
Hi,

Could you try:
>> win.addLabel(t, row=0, col=0, colspan = 1)
>> win.addLabel(t, `row=0,` col=2, colspan = 1)
>> win.addLabel(r, row=1, col=0, colspan = 1)


Cheers,
Kurian Kattukaren

**Comment by kuriankattukaren** [comment]
I've modified your code slightly as I don't have your xdict and newlistY and humlistY values. By adding colspan = 1 to the addLabels I get a well aligned label.

`from PyQt4 import QtGui
import pyqtgraph as pg

app = QtGui.QApplication([])

# Window init
win = pg.GraphicsWindow(border=True)
win.showMaximized()
win.setWindowTitle('MeteoStation Graph')

# Enable antialiasing for prettier plots
pg.setConfigOptions(antialias=True)

t = "TEST: " + str(159873864824758969862456347656857111111111111)
r = "JIBJGRBKGLJRBG"

t = "TEST: "
win.addLabel(t, row=0, col=0, colspan=1)
win.addLabel(t, row=0, col=2, colspan=1)
win.addLabel(r, row=1, col=0, colspan=1)

# Graphs plot
xdict = {1 : 10, 2:20, 3:30, 4:40, 5:50, 6:60, 7:70, 8:80, 9:90, 10:100}
stringaxis = pg.AxisItem(orientation='bottom')
stringaxis.setTicks([xdict.items()])
p1 = win.addPlot(row=0, col=1, title="Temperature", axisItems={'bottom': stringaxis})
p1.plot(list(xdict.keys()), list(xdict.values()), pen={'color': (255, 0, 0), 'width': 2})
p1.setYRange(-10, 40)
p1.setXRange(0, 15)
p1.showGrid(x=True, y=True)

stringaxis = pg.AxisItem(orientation='bottom')
stringaxis.setTicks([xdict.items()])
p2 = win.addPlot(row=1, col=1, title="Humidty", axisItems={'bottom': stringaxis})
p2.plot(list(xdict.keys()), list(xdict.values()), pen={'color': (0, 255, 255), 'width': 2})
p2.setYRange(0, 60)
p2.setXRange(0, 15)
p2.showGrid(x=True, y=True)

stringaxis = pg.AxisItem(orientation='bottom')
stringaxis.setTicks([xdict.items()])
p3 = win.addPlot(row=2, col=1, title="Humidty", axisItems={'bottom': stringaxis})
p3.plot(list(xdict.keys()), list(xdict.values()), pen={'color': (0, 255, 0), 'width': 2})
p3.setYRange(32, 36)
p3.setXRange(0, 15)
p3.showGrid(x=True, y=True)

# Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()`

![image](https://user-images.githubusercontent.com/7378439/30786927-6abb013e-a17e-11e7-9485-0ef64d75e66d.png)

**Comment by Nedo93** [comment]
Hi, thank you for your answer but this is not exactly what I wanted to achieve. I would like to set a fixed width for the right column (for example 350px or 2/5 of the whole page width). I don't really understand what that colspan is doing but even changing his value I can't achieve the precise width that I would.

**Comment by SusyWusy** [comment]
Hello :)
I'm not sure if it is the right thread to add my issue.
But in this shown graph by Nedo93 I saw, that the x-Axis is in a perfect scale. I need the same for my program. How can I do this, that the x-Axis is in two lines or how can I set a step size for it?
I use pyqtgraph and this is my code for the axis settings:

`
y_array = []
        for i in range(len(t_method)):
            y_array.append(i)  
            
        x_array = []
        for i in range(len(i_time)):
            x_array.append(i_time[i])
         
        y = y_array
        x = t_method
        
        my_xticks = i_time
        xdict = dict(enumerate(my_xticks))
        
        my_yticks = [0] + methodINtype
        ydict = dict(enumerate(my_yticks))
        
        plt.showGrid(y=True)
        
        plt.setLabel('left', 'Methods')
        plt.getAxis('left').setTicks([ydict.items()])
        y_min = methodINtype.index(min(methodINtype))
        y_max = methodINtype.index(max(methodINtype))
        plt.setYRange(y_min, y_max+2)
        
        plt.setLabel('bottom', 'Time', units='hh:mm:ss')
        plt.getAxis('bottom').setTicks([xdict.items()])
`

![example](https://user-images.githubusercontent.com/32490454/31134723-43102f24-a863-11e7-87bd-d2e831f58bee.PNG)

In the picture you can see the mess. It is a string with time content: 

dict_items([(0, ''), (1, '08:35:10.25'), (2, '08:35:10.25').....

**Comment by Nedo93** [comment]
Try to use

plt.setXRange(begin_of_your_desired_visualization_interval, end_of_your_desired_visualization_interval)

For example if you want to visualize on x axes an interval ofcoordinates from 1 to 10, set these values in the function.

**Comment by SusyWusy** [comment]
Thanks for the fast response!
Yes it works in this way, that I can see the string clearly. But the problem is, it cuts the plot.
For example I'll do this:

plt.setXRange(1, 5)

I'll get this:
![example2](https://user-images.githubusercontent.com/32490454/31143693-5c2472ca-a87e-11e7-99f1-3e8c08546e24.PNG)

And this are just test datas...the real data are much more.
So is there any possibility to put a step size to the xrange function? I didn't find something.

**Comment by Nedo93** [comment]
You are asking about showing the whole graph without the overlay of coordinates on X axys? In this case I don't know how to achieve that.

**Comment by SusyWusy** [comment]
Yes, this it what I want :)
Or I mean with step size to show just every tenth value for example.
I'm searching for days for it...

**Comment by Nedo93** [comment]
Can't help you with that then, sorry :(

**Comment by SusyWusy** [comment]
No problem! Thanks a lot for your help :)

**Comment by 2xB** [comment]
@Nedo93 To the first issue: GraphicsWindow is just a convenience wrapper that does not provide the customization depth you can reach when directly using Qt. So I'd suggest that you do not add plots to a GraphicsWindow, but PlotWidgets to a QGridLayout. An example with buttons is shown here: https://stackoverflow.com/questions/47943676/pyqt5-how-to-fix-the-width-height-to-specific-column-row-in-qgridlayout

**Comment by j9ac9k** [comment]
yeah, you can access that through `win.layout.layout.setColumnFixedWidth(col: int, width; int)`

**Comment by 2xB** [comment]
@SusyWusy To your issue: The solution is using `plt.getAxis('bottom').setTickSpacing(...)` or `plt.getAxis('bottom').setTicks(...)`. Therefore you have to get the axis item of your x axis
