### ISSUE TITLE
Need a few spaces between LegendItem symbols and their names

### ISSUE THREAD

**Issue by Felix-neko** [pyqtgraph/pyqtgraph#578]
When I add a legend to a plot, the legend marks (for example, scatter plot marks) are too close to the names i wrote to them. Cannot you fix it?

https://imgur.com/a/uqJPg — here is it.

P.S. Your library is really cool, it's much better than slow matplotlib = )

**Comment by gdotmueller** [comment]
i had the same problem and i think i found the bug. it is a bug in **legenditem.py line 112 & 113**.
that is in **method updateSize()**.
The same bug also moves the text further away from the symbol each time a legend row is appended!

my Fix:
instead of **sample.height()** and **sample.width()** it should be:
**sample.boundingRect().height()** & **sample.boundingRect().width()**

```
    def updateSize(self):
        if self.size is not None:
            return
            
        height = 0
        width = 0
        #print("-------")
        for sample, label in self.items:
            height += max(sample.boundingRect().height(), label.height()) + 3
            width = max(width, sample.boundingRect().width()+label.width())
            #print(width, height)
        #print width, height
        self.setGeometry(0, 0, width+25, height)
```

i think it was intented to use the boundingRect but it was forgotten to use it here!
when i make these changes it works flawlessy!!

**Comment by FalkMusick** [comment]
Thanks for the tip gdotmueller! 
Additionaly, the legend text should be 'left' aligned instead of the default 'center'.
````
def addItem(self, item, name):
        #label = LabelItem(name)
        label = LabelItem(name, justify='left')
        if isinstance(item, ItemSample):
            sample = item
        else:
            sample = ItemSample(item)        
        row = self.layout.rowCount()
        self.items.append((sample, label))
        self.layout.addItem(sample, row, 0)
        self.layout.addItem(label, row, 1)
        self.updateSize()`

Best Regards
Falk

**Comment by tomer2141** [comment]
I was able to fix it by adding horizontalSpacing for the LegendItem layout
`GraphicsWidget.__init__(self)
        GraphicsWidgetAnchor.__init__(self)
        self.setFlag(self.ItemIgnoresTransformations)
        self.layout = QtGui.QGraphicsGridLayout()
        self.layout.setHorizontalSpacing(15) # custom space between the legend shape and label
        self.setLayout(self.layout)
        self.items = []
        self.size = size
        self.offset = offset
        if size is not None:
            self.setGeometry(QtCore.QRectF(0, 0, self.size[0], self.size[1]))`

and adding justify to the LabelItem

`label = LabelItem(name, justify='left') # important
        label.setText(name, size='12pt', color='000000') # change the legend label style
        if isinstance(item, ItemSample):
            sample = item
        else:
            sample = ItemSample(item)        
        row = self.layout.rowCount()
        self.items.append((sample, label))
        self.layout.addItem(sample, row, 0)
        self.layout.addItem(label, row, 1)
        self.updateSize()`
