### ISSUE TITLE
Can't use pyqtgraph in ipython from anaconda due to 'use_jedi' config option

### ISSUE THREAD

**Issue by Dschoni** [pyqtgraph/pyqtgraph#604]
I have installed anaconda and use pyqtgraph inside spyder in ipython.

The version I use are:

pyqt   5.6.0
pyqtgraph 0.10.0
qt 5.6.2
python 2.7.14
numpy 1.13.3

In a minimal test I do

```
import numpy as np
import pyqtgraph as pg

pg.image(np.eye(3))
```

The pyqtgraph image opens but shows only black. Force quitting gives the error message:

`<pyqtgraph.graphicsWindows.ImageWindow at 0x7f6391f33f28>/home/gu32hej/anaconda2/lib/python2.7/site-packages/traitlets/config/configurable.py:84: UserWarning: Config option `use_jedi` not recognized by `IPCompleter`.
  self.config = config`

**Comment by j9ac9k** [comment]
Can you still reproduce this issue?  I think you need to have a `QApplication` instance going first.

**Comment by j9ac9k** [comment]
I didn't get that same error, but something similar, could this be because the qeventloop wasn't started?

**Comment by Dschoni** [comment]
It's fixed in all (recent) spyder versions. In some cases, it helps to manually change spyder's graphics backend from automatic to e.g. Qt5. New Spyder versions won't support python2 nor QT4, so I considered that issue closed for now.
