### ISSUE TITLE
PyQtGraph-core is outdated

### ISSUE THREAD

**Issue by pavel-kirienko** [pyqtgraph/pyqtgraph#617]
First things first, *PyQtGraph rocks*. I am using it in several projects, mostly for real-time data visualization purposes. Two of the projects embed PyQtGraph as a git submodule through https://github.com/pyqtgraph/pyqtgraph-core.

The problem with the core repo is that it hasn't been updated in ages (last commit almost 3 years ago, latest release 0.9.10). Is it not maintained anymore? Is it still a good idea to use it as a submodule? If not, what is the current best practice? I don't want to depend on the PIP package because it complicates dependency management and distribution.

Thanks!

**Comment by j9ac9k** [comment]
Sort of resolved with #1636 

There is little benefit for attempting to keep pyqtgraph-core up to date when with a small change to projects, the main repository can be used (without installing it via pip).  The documentation change in #1636 details how to do that.

While I was initially thinking we would update pyqtgraph-core, the addition of some supplemental functionality (colormaps being the first to come to mind) make the question of if something should be included with pyqtgraph-core or not not as obvious (you can make a case for both ways).

I hope this change will work out for you @pavel-kirienko if you need some assistance, let us know.
