### ISSUE TITLE
LegendItem formatting

### ISSUE THREAD

**Issue by falkkyburz** [pyqtgraph/pyqtgraph#625]
Hi pyqtgraph contributers, 

As one can examine in the examples, the legend-formatting is not very good. Two issues:
1. Width of sample isn't set/configured correctly.
2. Label text is center justified.

Fix for 2. is easy: Just add justify='left' parameter to LabelItem instantiation call.
The first problem has somehow to do with Qt's way of determining width. Since size is hardcoded anyways, you could use self.setFixedWidth(20) in the constructor of the ItemSample class.

I am no GUI expert!

Before/After of the two modifications is shown below:
![capture](https://user-images.githubusercontent.com/30900572/35569847-a10e3ee6-05cd-11e8-8998-2af9e11e438d.PNG) ![capture](https://user-images.githubusercontent.com/30900572/35569760-55db5558-05cd-11e8-87c7-9ea2b6057b80.PNG)

This is also discussed in #578

**Comment by NilsNemitz** [comment]
I think this should have been fixed in #958.
If anybody is still seeing this issue, please let us know!

**Comment by j9ac9k** [comment]
I think this was indeed solved, if you can still recreate the issue, let us know @falkkyburz and I'll re-open.  Sorry fro the long-time to follow up.
