### ISSUE TITLE
pyqtgraph not showing figures in Spyder IDE

### ISSUE THREAD

**Issue by wang1943** [pyqtgraph/pyqtgraph#640]
I have installed anaconda2 and use pyqtgraph inside spyder in ipython. Everything was great until I upgrade the anaconda version and spyder version recently. After upgrade, the script I have still run but interactive 2D and 3D figures plotted by pyqtgraph just don't show up at all.

However, if I run the script in command line mode outside spyder, it runs smoothly as previously. Could anyone help me figure out what's going on? Thank you!

The version I use are:

spyder 3.2.8
pyqt 5.6.0
pyqtgraph 0.10.0
qt 5.6.2
python 2.7

**Comment by talkaminker** [comment]
This is not a pyqtgraph problem. In spyder. go to Tools->Preferences->Ipython Console->Graphics.
In graphics backend change to Qt5. click OK
restart spyder.

**Comment by jmoraispk** [comment]
Or run this in the console: %gui qt5
