### ISSUE TITLE
Python3 and slices

### ISSUE THREAD

**Issue by vascotenner** [pyqtgraph/pyqtgraph#650]
In python3 slicing is only possible with integers. The division operator has been changed. Due to this, multiple bug arise, including #534, #622 .

A solution of this problem is discussed here.
https://stackoverflow.com/questions/12888320/python-3-getting-typeerror-slices-must-be-integers-but-they-are-i-believe/49431082#49431082

Someone should walk through the code to convert all slicing things.

**Comment by campagnola** [comment]
Hi @vascotenner, many of these bugs are already fixed in the latest `develop` branch (including the two you referenced). If you can find any other specific examples, please reopen and let us know.
