### ISSUE TITLE
TableWidget's save method in pyqt5 gives an  error

### ISSUE THREAD

**Issue by APophale** [pyqtgraph/pyqtgraph#652]
Whenever I try to save TableWidget data, it throws the following error:
`TypeError: expected str, bytes or os.PathLike object, not tuple`

I think the problem is, in pyqt5 return value for `QtGui.QFileDialog.getSaveFileName` is a tuple of the filename and the selected filter not a single string which is assumed right now.

```
def save(self, data):
        fileName = QtGui.QFileDialog.getSaveFileName(self, "Save As..", "", "Tab-separated values (*.tsv)")
        if fileName == '':
            return
        open(fileName, 'w').write(data)
```

**Comment by j9ac9k** [comment]
Looks like this was fixed with 3fd56eb195b10e209c3c00376b37408328fce58f

Thanks for the issue.
