### ISSUE TITLE
How to do overpainting with GLViewWidget?

### ISSUE THREAD

**Issue by traveller59** [pyqtgraph/pyqtgraph#662]
## Environment
* pyqtgraph 0.10.0
* Ubuntu 16.04
## Problems
I have add following code to paintGL:
```Python
        painter = QPainter(self)
        painter.setRenderHint(QPainter.Antialiasing)
        painter.drawText(10, 10, 'test')
        painter.end()
```
These code works well with official pyqt hellogl example, but don't work with pyqtgraph.

**Comment by NilsNemitz** [comment]
Dear @traveller59 , I hope you have figured this all out by now.

In principle, the QPainter should be able to draw over the contents of GLViewWidget.
But it is not simple to switch the painter between the OpenGL "native mode" and the normal Qt behavior. I found this as a possible starting point:
https://stackoverflow.com/questions/39171120/qopenglwidget-qpainterdrawrect-only-draws-four-arrows?noredirect=1&lq=1

Within PyQtGraph, only graphicsItems/PlotCurveItem.py seems to implements this kind of mode switching, so you might want to look at that, too.

On the other hand, the issues might be as simple as needing to set a visible pen, or that the view may be scaled such that your coordinates 10,10 are be off-screen.

Please let us know if you have a problem specifically with the PyQtGraph use of OpenGl!

**Comment by j9ac9k** [comment]
I think we can close this, citing #1892 as a solution here.  Thanks @pijyoi for creating the example!
