### ISSUE TITLE
compatibility for upcoming PySide2-5.11 preview

### ISSUE THREAD

**Issue by stonebig** [pyqtgraph/pyqtgraph#680]
After 2 years of brewing, PySide2-5.11 will reach preview status in may 2018, with:
- full support per the Qt Company,
- full API support at release time of Qt versions.

Would it be possible to have PySide2 compatibility for that may 2018 milestone ?
(QtPy, vendored or not,  being a possible intermediate layer)

see http://blog.qt.io/blog/category/qt-for-python/

for PySide2 bug tracker, see https://wiki.qt.io/Qt_for_Python

**Comment by stonebig** [comment]
curent status is that PySIde2 is not recognized:

````
C:\.....\python-3.6.5.amd64\lib\site-packages\pyqtgraph\Qt.py in <module>()
     42 
     43 if QT_LIB is None:
---> 44     raise Exception("PyQtGraph requires one of PyQt4, PyQt5 or PySide; none of these packages could be imported.")
     45 
     46 

Exception: PyQtGraph requires one of PyQt4, PyQt5 or PySide; none of these packages could be imported.
````

**Comment by campagnola** [comment]
PR in progress: https://github.com/pyqtgraph/pyqtgraph/pull/635

**Comment by stonebig** [comment]
ok, so it's a duplicate
