### ISSUE TITLE
How to plot a thumbnail on a part of the pyqtgraph.plot layout 

### ISSUE THREAD

**Issue by ankith0073** [pyqtgraph/pyqtgraph#694]
Hi, 

   I am trying to visualize data coming out of a sensor and plotting it in 2d cartesian coordinates.

I want to visualize this data as coming from a robot centered at (0,0). To do this i want a display a thumbnail of robot at (0,0) and update the plot with sensor readings. 

Could you please tell how i can plot the thumbnail of the robot ? 

P.S right now i am using  

**p6.robot= p6.plot([0], [0], pen=None, symbolSize=20, **symbol="t1"**, symbolBrush=(255, 0, 0))**

I want to replace the triangle obtained using symbol = t1 with the thumbnail of the robot . 

Any help regarding this would be greatly appreciated!

Thanks and regards
Ankith Manjunath

**Comment by NilsNemitz** [comment]
Dear @ankith0073 , sorry for the slow reply.

In case it is still useful to you, or to anybody who finds this issue in a Google search:

While you could probably draw an ImageItem at a specified position, the simplest adjustment to the code you are now using would be to define a custom symbol to better indicate your robot.

As described in
https://pyqtgraph.readthedocs.io/en/latest/graphicsItems/scatterplotitem.html
the `symbol=` argument can be any QPainterPath.

Take a look at how the current symbols are defined in graphicsItems/ScatterPlotItem.py .
Let us know if you have further questions!

**Comment by j9ac9k** [comment]
In addition to defining your own QPainterPath, we _started_ rolling out minimal support for icons that can be embedded

See: https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/icons/__init__.py#L75-L79

Right now it's limited to icons in the icons directory; but future variants will likely be expanded to support more generic variants.
