### ISSUE TITLE
Spinbox.validate not compatible with PyQt + Python3

### ISSUE THREAD

**Issue by polwel** [pyqtgraph/pyqtgraph#697]
`Spinbox.fixup` expects its argument to be a `QString`. This is not the case in Python3, where PyQt replaced `QString` by native `str`.

`Spinbox.validate` does correctly implement both APIs, but `Spinbox.fixup` does not.

More info at http://pyqt.sourceforge.net/Docs/PyQt4/python_v3.html#qvalidator.

The issue concerns the dev branch. The current release (0.10) is not affected.

**Comment by j9ac9k** [comment]
Closing as a PR was merged addressing this issue.
