### ISSUE TITLE
Image Exporter needs numpy API fix

### ISSUE THREAD

**Issue by flutefreak7** [pyqtgraph/pyqtgraph#703]
https://github.com/pyqtgraph/pyqtgraph/blob/develop/pyqtgraph/exporters/ImageExporter.py#L71

The following line:

    bg = np.empty((self.params['height'], self.params['width'], 4), dtype=np.ubyte)

Should now be:

     bg = np.empty((int(self.params['width']), int(self.params['height']), 4), dtype=np.ubyte)

This should be addressed under https://github.com/pyqtgraph/pyqtgraph/pull/273 but apparently was missed?

Perhaps there's a test that also needs to exist to catch this if it hasn't been caught before now.

**Comment by campagnola** [comment]
@flutefreak7 IIRC the change in #273 was to ensure that integer-type parameters would coerce their output to int, so it is not necessary to do that here. Have you tested against the latest in the `develop` branch? The last pip release does not have this fix. (it's definitely time for a new release)

**Comment by flutefreak7** [comment]
All I know is that np.empty wants integers and self.params['width'] is giving it a float in 0.10.  I haven't tried the develop branch, but (incorrectly?) came to the conclusion that it hadn't been fixed since the offending line was unchanged.  I suppose if self.params['width'] returns `int` in `develop`, then that would be all good.  I'm new to this... so I might want to pip install from a git branch I think...
