### ISSUE TITLE
Getting an error when clicking on ScatterPlotItem...

### ISSUE THREAD

**Issue by SpacelySpaceSprockets** [pyqtgraph/pyqtgraph#704]
I'm trying to use the sigPointsClicked signal in a PlotDataItem, and its failing with the error

> File "/home/myhome/anaconda3/envs/python3/lib/python3.6/site-packages/pyqtgraph/graphicsItems/ScatterPlotItem.py", line 817, in pointsAt
>     |      s2x = s2y = ss * 0.5
>     |  TypeError: can't multiply sequence by non-int of type 'float'
>     |==============================<<

running Python 3.6.4 and pyqtgraph version 0.10.0

**Comment by ixjlyons** [comment]
Sorry for taking so long to get to this. Do you happen to still have an example you could share? Also Py{Qt,Side} version could be helpful too. If you've moved on, feel free to unsubscribe from notifications so you don't get noise while I investigate and leave some notes here.

Here's an example that seems to work for me:

```python
import numpy as np
import pyqtgraph as pg

app = pg.mkQApp()

plt = pg.plot()
pdi = plt.plotItem.plot(*np.random.randn(2, 10), symbol='o')
pdi.sigPointsClicked.connect(lambda points: print(points))

app.exec_()
```

**Comment by SpacelySpaceSprockets** [comment]
your example works for me, but I still get the error in my application.  I'll try to get an example that reproduces it 

I would like to add that the value transmitted through the sigPointsClicked is the reference to the plotDataItem clicked on.  That can be useful, but I think more useful would be if it transmitted some sort of reference to the point clicked on, and thus be able to extract, for example, the x,y coordinates of that point.

**Comment by ixjlyons** [comment]
Both the `PlotDataItem` and a list of the clicked-on `SpotItem` objects are emitted. I think what is probably happening is your callback function (slot) takes a single argument so only the first argument is passed. I think this is just how PyQt/PySide deals with method overloading in the C++ Qt API. For example:

```python
import numpy as np
import pyqtgraph as pg

app = pg.mkQApp()

def rx(plotdataitem, points_clicked):
    print(points_clicked[0].pos())

plt = pg.plot()
pdi = plt.plotItem.plot(*np.random.randn(2, 10), symbol='o')
pdi.sigPointsClicked.connect(rx)

app.exec_()
```

Regarding the error: that is the same error you'd get if you tried `[1, 2, 3] * 0.5`, so somehow the `SpotItem.size` is returning a sequence. I haven't come up with a way to cause that without causing other errors to come up yet.

**Comment by SpacelySpaceSprockets** [comment]
ah, i see that now... somehow missed that in the documentation.  Thanks

**Comment by ixjlyons** [comment]
Going to close this as resolved. Feel free to re-open or create a new issue if you come across any other problems.
