### ISSUE TITLE
PySide QImage workaround should only be used where bug is present

### ISSUE THREAD

**Issue by campagnola** [pyqtgraph/pyqtgraph#724]
The current workaround would probably cause a segfault if the upstream bug is fixed.
Reference: https://github.com/pyqtgraph/pyqtgraph/commit/f6819dda28e9f725215efb5f198257a43b827d38#commitcomment-29552713

**Comment by pijyoi** [comment]
Note that upstream bug is reported to have been fixed on 20180921:
https://bugreports.qt.io/browse/PYSIDE-140

**Comment by j9ac9k** [comment]
@campagnola is there a chance that this is causing the segfaults we're seeing on PySide2 5.12 right now?

**Comment by j9ac9k** [comment]
I think at this point, PySide2 5.12 is the oldest version of PySide2 we test/support, and we should remove the workaround.  With PySide2 5.15 now released, there have been two LTS releases since the version that had this bug.

**Comment by campagnola** [comment]
I support removing this code.
