### ISSUE TITLE
GraphicsWindow freezes when opened

### ISSUE THREAD

**Issue by user-na** [pyqtgraph/pyqtgraph#728]
Calling any Graphics window will open a blank window which freezes. For example when doing this:
```
import pyqtgraph as pg
import numpy as np

arr=np.random.randint(500,1000,(5,1000,1000))
pg.show(arr)
```

System:
- Windows 7
- Anaconda 3 64bit
  - python 3.6.6
  - pyqt 5.9.2
  - pyqtgraph 0.10.0

pyqtgraph installed via 

> conda install -c anaconda pyqtgraph 

I also observed this behavior also on a freshly installed Win10 maschine with anaconda 3.

After a great guess from @campagnola ([here](https://groups.google.com/forum/?fromgroups#!topic/pyqtgraph/st47vIRff1c)) it turned out that obviously the `QApplication.exec_()` is never called. So this modified version will run without any issues:

```
from PyQt5.QtWidgets import QApplication
import pyqtgraph as pg
import numpy as np
import sys

arr=np.random.randint(500,1000,(5,1000,1000))
pg.show(arr)

app = QApplication.instance()
if app is None:
    app = QApplication(sys.argv)
else:
    print('QApplication instance already exists: %s' % str(app))
app.exec_()
```

I am wondering what changed, as I had pyqtgraph running in my old python 2 enviornment without the need to explicitly call the `exec_()` method.

**Comment by jongra** [comment]
Hello @user-na,
I recently had the same problem.
For me the solution was to call the `exec_()` method of the application stored in pyqtgraph.
```python
import pyqtgraph as pg
import numpy as np
arr=np.random.randint(500,1000,(5,1000,1000))
pg.show(arr)
pg.QAPP.exec_()
```
should do the job.

**Comment by orena1** [comment]
> ```python
> import pyqtgraph as pg
> import numpy as np
> arr=np.random.randint(500,1000,(5,1000,1000))
> pg.show(arr)
> pg.QAPP.exec_()
> ```

This actually does not work:
```python
In [1]: import pyqtgraph as pg 
   ...: import numpy as np 
   ...: arr=np.random.randint(500,1000,(5,1000,1000)) 
   ...: pg.show(arr) 
   ...: pg.QAPP.exec_()                                                                                                                                                                                                                                                                                        
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-231a3179797e> in <module>
      3 arr=np.random.randint(500,1000,(5,1000,1000))
      4 pg.show(arr)
----> 5 pg.QAPP.exec_()

AttributeError: 'NoneType' object has no attribute 'exec_'
```

**Comment by NilsNemitz** [comment]
Dear @orena1 ,

I am not entirely sure what the current best practice is.
But 
```python
import pyqtgraph as pg
import numpy as np
arr=np.random.randint(500,1000,(5,1000,1000))
pg.show(arr)
```
works for me in interactive mode.

In a script, using pg.mkQApp() in the final call makes the window show up:
```python
import pyqtgraph as pg
import numpy as np
arr=np.random.randint(500,1000,(5,1000,1000))
pg.show(arr)
pg.mkQApp().exec_()
```
Does that work for you?

**Comment by j9ac9k** [comment]
Unless you have your own instance of QApplication already running, we recommend 

```python
app = pg.mkQApp()  # this will return 

# your code

app.exec_()
```

or as @NilsNemitz suggested using `pg.mkQApp().exec_()`

I'm going to close out this issue, as I'm fairly sure either suggestion here should work.  If you're still running into issues, let us know and we'll re-open.  Sorry it's taken so long to follow up.
