### ISSUE TITLE
PyQT 5.11.2 possible issue

### ISSUE THREAD

**Issue by apiszcz** [pyqtgraph/pyqtgraph#729]
Python 3.5, pyqtgraph 0.10, PyQt 5.11.2
```
    import pyqtgraph as pg
  File "lib\pyqtgraph\__init__.py", line 13, in <module>
    from .Qt import QtGui
  File "lib\pyqtgraph\Qt.py", line 153, in <module>
    from PyQt5 import QtGui, QtCore, QtWidgets, uic
ValueError: PyCapsule_GetPointer called with incorrect name
```

**Comment by stonebig** [comment]
did you try with curent github master source ? Pyside suport has been merges may 25th, but is not yet on an official release . https://github.com/pyqtgraph/pyqtgraph/pull/635

**Comment by campagnola** [comment]
This looks like a PyQt bug. If you just run the last line from python (without pyqtgraph), do you get the same result?
```from PyQt5 import QtGui, QtCore, QtWidgets, uic```

**Comment by apiszcz** [comment]
Apparently my sip.pyd was not the latest, retesting with latest sip and 5.11.2 same test works.
