### ISSUE TITLE
CSV export broken

### ISSUE THREAD

**Issue by jack77er** [pyqtgraph/pyqtgraph#734]
When trying to export the plot values to a CSV file I'm getting the following error:

> Traceback (most recent call last):
>   File "C:\Users\XXX\AppData\Roaming\Python\Python36\site-packages\pyqtgraph\exporters\Exporter.py", line 77, in fileSaveFinished
>     self.export(fileName=fileName, **self.fileDialog.opts)
>   File "C:\Users\XXX\AppData\Roaming\Python\Python36\site-packages\pyqtgraph\exporters\CSVExporter.py", line 44, in export
>     name = c.name().replace('"', '""') + '_'
> AttributeError: 'builtin_function_or_method' object has no attribute 'replace'
> Press any key to continue . . .
I have the problem with the last stable version (0.10.0) and the current git checkout.
Any ideas?

**Comment by jack77er** [comment]
Ok I found the error:
I've given the plot a reference to a QLineEdit but not the actual text field string value. Maybe there should be a cast to a string or a try-catch block?!

**Comment by j9ac9k** [comment]
I don't think we're try and cast a `QLineEdit` object into a string, in part due to `QLineEdit` already providing a method to get the text.  If it was a string-like object we would reconsider.  Thanks for following up your issue with the cause.
