### ISSUE TITLE
ViewBox: "UnboundLocalError: local variable 'mask' referenced before assignment"

### ISSUE THREAD

**Issue by Braendle** [pyqtgraph/pyqtgraph#736]
https://github.com/pyqtgraph/pyqtgraph/blob/585390e16ebbc7eb993c78216cc88e439c5bfe60/pyqtgraph/graphicsItems/ViewBox/ViewBox.py#L1128

**Comment by campagnola** [comment]
Thanks for the report @Braendle !

**Comment by stonebig** [comment]
pyqtgraph-0.10.1 release soon ?

**Comment by campagnola** [comment]
@stonebig this bug was introduced very recently; it should not affect 0.10 users. 
That said, it is clearly past time for a new release. Do you want to volunteer some time?

**Comment by stonebig** [comment]
well, every 2 month I compile Pyqtgraph-master as wheel, and incorporate it in WinPython, assuming that it's better than last release. Why does it take so long to cut an official release ?

**Comment by campagnola** [comment]
The major roadblocks are testing on multiple platforms and building packages. I am thinking about dropping the latter part because there are now other people building most of the packages that I used to build.
