### ISSUE TITLE
ImageView: No such signal ViewBox::destroyed(*)

### ISSUE THREAD

**Issue by zhujun98** [pyqtgraph/pyqtgraph#741]
Hi, when I ran examples/ImageView.py, I got the following error message

Using PyQt5 (default graphics system)
QObject::connect: No such signal ViewBox::destroyed(*)
Traceback (most recent call last):
  File "/home/zhujun/da-repo/pyqtgraph/examples/ImageView.py", line 28, in <module>
    imv = pg.ImageView()
  File "/home/zhujun/da-repo/pyqtgraph/pyqtgraph/imageview/ImageView.py", line 210, in __init__
    self.ui.roiPlot.registerPlot(self.name + '_ROI')
  File "/home/zhujun/da-repo/pyqtgraph/pyqtgraph/graphicsItems/PlotItem/PlotItem.py", line 363, in registerPlot
    self.vb.register(name)
  File "/home/zhujun/da-repo/pyqtgraph/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 235, in register
    self.destroyed.connect(lambda: ViewBox.forgetView(sid, name) if (ViewBox is not None and 'sid' in locals() and 'name' in locals()) else None)
TypeError: connect() failed between (QObject*) and unislot()
QObject::disconnect: No such signal ViewBox::destroyed(*)
QObject::disconnect: No such signal ViewBox::destroyed(*)
QObject::disconnect: No such signal ViewBox::destroyed(*)

I am using Python3.6 in Ubuntu16.04

Could you give me some hint? Thank you!

**Comment by j9ac9k** [comment]
Hi @zhujun98 sorry we're getting back to you so long after you created this issue.  Can you replicate this failure if you install/run from the `develop` branch?  You can install the develop branch directly by running

```
pip install git+https://github.com/pyqtgraph/pyqtgraph.git@develop
```

**Comment by j9ac9k** [comment]
I'm going to close the issue, as that test is part of our CI runs now, and we haven't seen this fault.  If you can replicate this off the current development branch, let us know and we'll reopen.

Thanks
