### ISSUE TITLE
Development API changes are leaking into documentation of stable release

### ISSUE THREAD

**Issue by albertogomcas** [pyqtgraph/pyqtgraph#745]
For example, the documentation for 0.10.0 (released in Nov 2016) of LinearRegionItem http://pyqtgraph.org/documentation/graphicsItems/linearregionitem.html includes details about pen, swapMode... which were integrated in Sept 2017, so of course they don't work with 0.10.0

**Comment by albertogomcas** [comment]
Related issue https://github.com/pyqtgraph/pyqtgraph/pull/684

**Comment by aldanor** [comment]
... and some items can't be found at all, like `BarGraphItem`

**Comment by ixjlyons** [comment]
Docs are now built with readthedocs. [latest](https://pyqtgraph.readthedocs.io/en/latest/) will be up to date with the `develop` branch and we will have separate versions for releases, starting with 0.11.0.
