### ISSUE TITLE
HDF5Exporter: throws error when curves aren't the same length

### ISSUE THREAD

**Issue by jdchristesen** [pyqtgraph/pyqtgraph#747]
When trying to save data from a graph as an hdf5 file, the HDF5Exporter throws and error when you have multiple curves with differing lengths. This looks to be because the numpy.array(data).astype('double') can't handle lists with different lengths. Below is a traceback from the error. This occurs when trying to save data from the "Multiple curves" graph in the "Basic Plotting" example.

````
Traceback (most recent call last):
  File "/home/jchrist/PycharmProjects/lib/python3.5/site-packages/pyqtgraph/exporters/Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "/home/jchrist/PycharmProjects/lib/python3.5/site-packages/pyqtgraph/exporters/HDF5Exporter.py", line 55, in export
    fdata = numpy.array(data).astype('double')
ValueError: setting an array element with a sequence.
````

**Comment by campagnola** [comment]
Agreed; this was originally written with the intent of supporting only equal-length plots. For plots of different length, you would have to store each plot in its own dataset. Probably not too difficult to add an exporter option for that?
