### ISSUE TITLE
Scalebar setParentItem not setting parent item if it is a GraphicsWidget such as a ViewBox

### ISSUE THREAD

**Issue by adamananos** [pyqtgraph/pyqtgraph#753]
I have been trying to get the example ScaleBar.py to work, however, I continually run into the error of not being able to set the parent item of the viewbox item, the error returned exception being : cannot anchor; parent is not set. I am able to set the parent of a scalebar item to a GraphicsObject item such as imageItem. Furthermore, trying to set the parent of any GraphicsObject item to a GraphicsWidget item fails. 
I have tested this with (anaconda) python 2.7 pyqtgraph 0.10.0 PySide 1.2.1 
as well as (anaconda) python 3.4 pyqtgraph 0.10.0 PySide 1.2.4

**Comment by campagnola** [comment]
This sounds like a PySide bug that I reported a while back:
https://bugreports.qt.io/browse/PYSIDE-86
I thing using PyQt or a more recent version of PySide should fix this.

**Comment by adamananos** [comment]
Thanks for the info. 
I have tested this using the following combinations

Python 2.7
pyqtgraph 0.10.0  
PyQt5 5.6
result - receive the same error. 

Python 3.4 
pyqtgraph 0.10.0 
PyQt4 4.11.4 
result - scalebar works

Python 2.7.14
pyqtgraph 0.10.0 
PyQt4 4.11.4 
result - scalebar works

I didnt try a more recent version of PySide
Not sure why PyQt5 and Python 2.7 didnt work.

**Comment by j9ac9k** [comment]
@adamananos Since you posted this issue, you can install PySide2 via pip; while the last stable release of pyqtgraph doesn't support PySide2, the current develop branch can run it fairly effectively.

Would you mind seeing if you can still get this error with PySide2 installed via pip?

**Comment by j9ac9k** [comment]
I'm going to close out this issue as I cannot replicate it.  If you can still replicate the issue please post a code example and we'll look into it further 👍🏻
