### ISSUE TITLE
axis and glyph scaling issue with Multiple DPI monitors

### ISSUE THREAD

**Issue by dvincentwest** [pyqtgraph/pyqtgraph#756]
I am happy to check this out, but I don't really know where to start.

I am running Windows10, Anaconda x64, python 3.6.6, and the below images were created using the latest git version of pyqtgraph, and PyQt5.9

I have two monitors, one at 1080p (set to 100% scaling) and the other at 4K (set to 150% scaling), and when switching between the two monitors windows will attempt to adjust their scaling accordingly.  Some applications do this better than others, and this may in fact be an issue in Qt, but in case we can address it in the pyqtgraph code, that would probably be good.

The first image is on the 1080p monitor and the second is just from moving the window over to the 4K monitor.  The problem is most easily seen in the gray plots in the upper left and lower right.  You can see that the scatter clouds are centered at 0,0 in the 1080p plots, but are shifted to lower x and higher y coordinates in the 4k 150% plots.  This is the major issue because it means the plots aren't accurate in presenting the coordinates of the data.

Weirdly, it also seems that some of the glyphs are shrinking while others are growing when the dpi change happens

Lastly, I can confirm that if I switch the 1st monitor to 150% scaling before starting python, this issue does not happen.  It is only an issue when switching from a monitor at one dpi setting to a different one

## 1080p, 100% Scaling
![image](https://user-images.githubusercontent.com/9872343/45054816-b88fb500-b053-11e8-8262-745200e2f31b.png)

## 4K, 150% Scaling
![image](https://user-images.githubusercontent.com/9872343/45054831-bf1e2c80-b053-11e8-8346-ddcb7a435162.png)

**Comment by cosminpolifronie** [comment]
I'm having the same problem. Description can be found here.
https://github.com/unitbvcv/image_processing_framework/issues/14

I am trying to fix this in pyqtgraph, but I cannot find the place where the grid is getting drawn. Can anybody help with that?

**Comment by j9ac9k** [comment]
@dvincentwest thanks so much for the screen shots, they really illustrate what's happening, only machine I have with a 4k monitor is a laptop I only periodically use and don't have a development environment setup; but I'll try and reproduce the issue there.

@cosminpolifronie if you're still trying to solve this issue, could you see if you can recreate it when installing from the develop branch?

**Comment by cosminpolifronie** [comment]
@j9ac9k Yup, I can still recreate it using pyqtgraph-0.11.0.dev0+g78df356

**Comment by j9ac9k** [comment]
Thanks for reporting back, I'll look into it in the next day or so hopefully

**Comment by j9ac9k** [comment]
@cosminpolifronie Thanks again for putting the effort to re-verify.  It might be a bit before you get to it, if you're waiting for this, and have a few minutes, could you try inserting the following lines

```python
        QtGui.QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
        if hasattr(QtWidgets.QStyleFactory, "AA_UseHighDpiPixmaps"):
            QtGui.QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
```

right before this line here:

https://github.com/pyqtgraph/pyqtgraph/blob/78df356c74ea9596c085a149654d18f4f2f524e9/pyqtgraph/Qt.py#L336

If you're not comfortable editing the source of the library that's fine, I'll get to it.

**Comment by cosminpolifronie** [comment]
I have added the lines you suggested, but the bug is not fixed (I've tried to add them before the `if` on line 335, that didn't help either). I don't think it has to do only with Qt scaling, something is weird in the backend as well.

Look at the following video: https://youtu.be/X4ltNIjDuz4
Second screen only: https://youtu.be/uViX3zOAXIo

The first screen that I'm opening the app in is the main screen with 125% scaling (2560x1440), and the second one has 100% scaling (1920x1080). You can see that when I'm dragging the plot on the second screen, the background grid moves at a different speed. That shouldn't happen.

**Comment by j9ac9k** [comment]
Thanks for the videos highlighting this issue I completely understand the problem; I've assigned myself some issues and I have some PRs to review first, but I'll poke around with this...  Do you have any suggestions on how we can make a test that will actually fail for this issue?

**Comment by cosminpolifronie** [comment]
Can this be automatically tested, as it is a display error? Do we have any means to probe into the actual displayed elements (as in pixels, maybe)?

**Comment by j9ac9k** [comment]
If I was to characterize this, I would say that during a drag event, the mouse does not remain at the same coordinates within the view.

First step is definitely to make a test that simulates a mouse drag event (there are other tests in the test suite that do this) and we can show that the mouse position within the view did not remain the same.  What I don't know how to do in the test suite is to capture the monitor scaling that's occurring.

**Comment by cosminpolifronie** [comment]
I don't have any kind of experience with testing, so I'll have to learn to be helpful. Tomorrow I'll have my last exam before I finish university, and after that I could look into it.

It could take a while, but I'm willing to learn.

**Comment by j9ac9k** [comment]
> I don't understand. Are we talking about the same issue?

In your video, when you click on drag, the mouse stays in the same position, relative to the grid on the right monitor, but on the left monitor the mouse position moves in relation to the grid.  Is that not the issue you're describing?

**Comment by cosminpolifronie** [comment]
Oooh, I didn't look at it this way. Yes, it is one problem, but there are others: the plot is badly represented in height (it's shifted downwards), and the plot and the grid move out of sync (they move at different speeds, the grid stays sychronized to the mouse movement while the grid does not and "floats"). Basically, when you move the plot, the `x` and `y` values change as you move the plot, they don't stay linked to their corresponding values on the grid.

**Comment by Kheirlb** [comment]
I'm experiencing a similar bug. Any new news on how to fix it?

**Comment by j9ac9k** [comment]
@cosminpolifronie @Kheirlb 

An item in the changelog for Qt 5.13.1 caught my attention that may be relevant:

```
****************************************************************************
*                                  QtGui                                   *
****************************************************************************

 - [QTBUG-73231] QWindow::mapToGlobal()/mapFromGlobal() now handle windows
   spanning screens correctly.
```

I would be eager to get an update on this issue if either of you install either PySide2 5.13.1 or PyQt 5.13.1 and report back.

Thanks

**Comment by cosminpolifronie** [comment]
Sadly the bug is still there with PyQt 5.13.1 😢.

**Comment by james0807** [comment]
I'm seeing something similar (I think), viewing a plot on a 4k display with 250% scaling, the line in the plot seems to become discontinuous? I'll try to upload a screenshot soon.

**Comment by Schneider1** [comment]
I have the same problem and here's what I see:

- This is independent of 4K resolution, it appears when you have two screens with different scaling (even if the resolution is the same)
- On the main screen, the view is always correct, the problem only occurs on the extended screen
- When you drag the window between the screens, you see that the axis size and labels change as soon as the center of the windows is on the extended screen; the rest (data and titlebar etc.) stay at the same size
- The axes still show the correct range, but are just smaller than the data 
![125screen](https://user-images.githubusercontent.com/14293012/78654243-8e077d00-78c4-11ea-96e0-9c47bf9618d5.PNG)
![100screen](https://user-images.githubusercontent.com/14293012/78654244-8f38aa00-78c4-11ea-8497-d22e0735da83.png)
The first image shows the situation on the main screen (125% scaling), the second image shows the extended screen (100% scaling)

Code snippet
```python
import numpy as np
import pyqtgraph as pg

data = np.random.normal(size=1000)
pg.plot(data, title="test")
pg.QtGui.QApplication.exec_()
```

**Comment by andybarry** [comment]
I was able to fix this issue by adding:

```
QApplication.setAttribute(QtCore.Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
```
after the imports in your example.

Here's a relevant mailing list post: https://lists.qt-project.org/pipermail/development/2019-September/037434.html


Working example:
```
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5 import QtCore

import numpy as np
import pyqtgraph as pg

QApplication.setAttribute(QtCore.Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)

data = np.random.normal(size=1000)
pg.plot(data, title="test")
pg.QtGui.QApplication.exec_()
```

**Comment by j9ac9k** [comment]
@andybarry Thank you so much for sharing!  

If I'm reading it  right, this was introduced in Qt 5.14, so this will only work on newer versions of Qt, but I see no reason not to add this to `pg.mkQApp()` with an if check for Qt version.

**Comment by luiztauffer** [comment]
@andybarry solution makes my app blurry and fonts too small... has anyone managed to find a solution for this?

**Comment by j9ac9k** [comment]
@luiztauffer I've self-assigned hidpi issues as I have a windows laptop w/ a hidpi monitor and an external non-hidpi display I can test on.  I'm not sure when I'm going to get to it, or if I'm going to be able to find a solution.  My first priority is working on the PR backlog (we're down to 30-something from 180 a year ago!).  

That said, this matplotlib issue may be of relevance, they identified a fix, but I think it requires Qt 5.15+

https://github.com/matplotlib/matplotlib/issues/17440

If you implement their fix, please do report back!

**Comment by andybarry** [comment]
Another option: https://stackoverflow.com/a/48431398/730138

**Comment by Androwei** [comment]
I had the same problem (Windows 10 , display scale to 125%, Python3.7, pyqtgraph 0.11, PySide2 5.15.1). 
I try to use QApplication.setAttribute(QtCore.Qt.AA_Use96Dpi) option, it don't work on every monitor(works fine on external). 

After I found this document, it mentions that "Sets the high-DPI scale factor rounding policy for the application. The policy decides how non-integer scale factors (such as Windows 150%) are handled, for applications that have AA_EnableHighDpiScaling enabled."

So I set the option : QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
It works fine for me.

https://doc.qt.io/qtforpython/PySide2/QtGui/QGuiApplication.html#PySide2.QtGui.PySide2.QtGui.QGuiApplication.highDpiScaleFactorRoundingPolicy

**Comment by j9ac9k** [comment]
> def make_dpi_aware():
>     if int(platform.release()) >= 8:
>         ctypes.windll.shcore.SetProcessDpiAwareness(True)

I'm working on #1509 and I tried implementing this, but this seemed to make text in the example app blurry (on Qt 5.12)... lots of  combinations to try out over here still...

**Comment by RitterD** [comment]
for PySide2 with Qt-Version 5.15 I was able to fix this by adding the following two lines **before** app = QApplication(sys.argv)

`QApplication.setHighDpiScaleFactorRoundingPolicy(Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)`

I hope I can help some ppl out with that.
With setAttribute as @andybarry suggested it wasnt possible for me and after the windll manipulation the app became blurry

**Comment by ozankececioglu** [comment]
Thanks for sharing @RitterD, this also fixes our long standing issue here. Cheers!

**Comment by karahanyilmazer** [comment]
By combining [this code](https://github.com/pyqtgraph/pyqtgraph/issues/756#issuecomment-705930693) and [this](https://github.com/matplotlib/matplotlib/issues/12221#issuecomment-440744946) I get good-looking plots with a multi-dpi setting with different scalings. But the solution is very lengthy to include in the beginning of every script. I would very much appreciate a proper fix.

```
import ctypes
import platform
import sys
import matplotlib.pyplot as plt
from IPython import get_ipython

if int(platform.release()) >= 8:
    ctypes.windll.shcore.SetProcessDpiAwareness(True)
        
if get_ipython() is not None:
    get_ipython().run_line_magic('matplotlib', 'qt')

if plt.get_backend() == 'Qt5Agg':
    from matplotlib.backends.qt_compat import QtWidgets
    qApp = QtWidgets.QApplication(sys.argv)
    plt.matplotlib.rcParams['figure.dpi'] = qApp.desktop().physicalDpiX()
```

**Comment by HoWeBrz** [comment]
@karahanyilmazer  I can confirm, that this workaround works for me and I get proper scaling with non-100% dpi-scaling.
