### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by vilim** [pyqtgraph/pyqtgraph#775]
@campagnola thank you for developing this invaluable package! Would it be possible to release a newer version on PyPI soon? There are very many things fixed since the last release in 2016, some preventing crashes in a package we have been developing (https://github.com/portugueslab/stytra) and it would be great if all the dependencies could be automatically installed by pip (apparently specifying URL repository dependencies with setup.py is not possible).

**Comment by erakli** [comment]
By the way, I see many PR that haven't been merged. pyqtgraph is great lib, but it also lacks from unmaintained documentation. Recently, I found that I used very  old version has been stored in pyqtgraph-core repo.

New release and some maintenance is highly desirable!

**Comment by campagnola** [comment]
100% agree. We actually have some folks at DOE helping out with the next release right now!

**Comment by termim** [comment]
Is there any way to help?

**Comment by jrast** [comment]
Any news on this?

**Comment by mrvx666** [comment]
I want new release too.

**Comment by jmdejong** [comment]
I agree. The issue with the retina displays makes it hard to use this for mac computers.
Maybe make a version 0.10.1 that just has these bug fixes?

**Comment by j9ac9k** [comment]
Development of this library has just picked up dramatically, aim is to get the test suite passing on all supported configurations and then release the next stable release.  

@jmdejong Doing a patch to 0.10 is not in the cards right now unfortunately; but I don't think the next stable release is too far off.  Easiest way to help is to make a PR addressing any of the issues tagged with [CI-fail].

**Comment by klotzt-draeger** [comment]
i would also really like to see a release to master! the library is of great use to use but using it from develop is troublesome...

**Comment by takluyver** [comment]
If anyone's looking to help with those issues, there are currently three [CI-fail] issue open:

- #967: intermittent segfault with Python 3.7 on Mac
- #895: a segfault on Linux that's hard to reproduce
- #881: a CI issue on Python 2.7 Linux & Mac

**Comment by ksunden** [comment]
We have now released 0.11.0rc0 to [pypi](https://pypi.org/project/pyqtgraph/0.11.0rc0/).
