### ISSUE TITLE
PyQtGraph Crashes Python: Help Required!

### ISSUE THREAD

**Issue by rudrathegreat** [pyqtgraph/pyqtgraph#779]
I am experimenting with this simple gist -

https://gist.github.com/Overdrivr/ed140520493e5d0f248d

But when I run it, a pop-up window comes up with the following message - 

```
Python has stopped working. A problem cause the program to stop working correctly. Please close the program
```

A Little Help would be Great!

**Comment by ixjlyons** [comment]
I'm not able to reproduce the crash you're seeing. Some information that would be helpful in determining what's going on:

- pyqtgraph version
- How you installed pyqtgraph (conda, pip, system package manager)
- Your OS
- How you're running the code (e.g. `python Plot.py`, `%run Plot.py` from ipython, etc.)

**Comment by campagnola** [comment]
The linked gist does not implement an event loop, so I guess the program is exiting as soon as you run it, and the error you see is unrelated (often we see errors during Qt teardown as python exits).

If you're using PyQt, you can just run the script from an interactive shell:
```
python -i pg_gist.py
```
Otherwise, add to the end of the file:
```
QtGui.QApplication.exec_()
```

**Comment by rudrathegreat** [comment]
I am using a Windows System, using command `python Plot.py` and installed PyQtGraph using pip.

I will let you know the PyQtGraph version shortly

**Comment by ixjlyons** [comment]
The script *does* run the event loop in the `start()` method (https://gist.github.com/Overdrivr/ed140520493e5d0f248d#file-plot-py-L26), so I'm not really sure what the problem could be.

Python 2 or Python 3?

Also, if possible, try using the latest `develop` branch of pyqtgraph.

**Comment by rudrathegreat** [comment]
Python 3

**Comment by rudrathegreat** [comment]
I'll try

**Comment by j9ac9k** [comment]
Haven't had an update to this issue in a few months, so will close due to being unable to reproduce.  @rudrathegreat if you're able to reproduce this issue still, let me know and I'll reopen.
