### ISSUE TITLE
Matplotlib exporter iteritems() error

### ISSUE THREAD

**Issue by PenkoMlakar** [pyqtgraph/pyqtgraph#783]
Pyqtgraph version 0.10.0 (python3) 'Plot to matplotlib' exporter contains a bug left from the python2 days:

    $ File "<...>/.local/lib/python3.6/site-packages/pyqtgraph/exporters/Matplotlib.py", line 46, in cleanAxes
    for loc, spine in ax.spines.iteritems():
    $ AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

The error occurs because the 'iteritems' was removed from python3:
https://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems

So the fix is simple:
pyqtgraph/exporters/Matplotlib.py, line 46, change 'iteritems()' to 'items()'. 

This can be done manually but it would be nice if the library itself had this fixed.

**Comment by ojob** [comment]
Seems this is a duplicate of #574

**Comment by PenkoMlakar** [comment]
True. It seems it was already fixed while I've used the non-fixed pyqtgraph version.

I am closing this issue.
