### ISSUE TITLE
3D plot goes in bottom left side of window 

### ISSUE THREAD

**Issue by Eyshika** [pyqtgraph/pyqtgraph#785]
Hello! I am trying to do 3D plotting using Pyqtgraph in Python. here is the simple code I ran:
```
 import pyqtgraph as pg
    import pyqtgraph.opengl as gl
   app=pg.QtGui.QApplication(sys.argv)
   view=gl.GLViewWidget()  
   view.setGeometry(50, 50, 600, 500)
    view.opts['distance'] = 40
    view.setWindowTitle('pyqtgraph example')
    view.show() 
    gx = gl.GLGridItem()
    gx.rotate(90, 0, 1, 0)
    gx.translate(-10, 0, 0)
    view.addItem(gx)
    gy = gl.GLGridItem()
    gy.rotate(90, 1, 0, 0)
    
    gy.translate(0, -10, 0)
    view.addItem(gy)
    gz = gl.GLGridItem()
    gz.translate(0, 0, -10)
    view.addItem(gz)
    app.exec_()
```
I installed PyQt5 and OPengl using pip
I am running it in MAC in Visual Code

**Problem:** The output always displays on bottom left side of window when checked on system screen, but displays in middle of window when checked on monitor screen.. What could be the reason ? What are the changes I can or I should do in the code ? Here is the output attached to better explain the issue.
<img width="600" alt="screen shot 2018-11-14 at 9 36 38 am" src="https://user-images.githubusercontent.com/25290579/48501254-b2574b00-e7f1-11e8-8746-1bbfff72de09.png">
@campagnola @lesauxvi @gpoulin @ericdill

**Comment by daranday** [comment]
+1 Reproducing on Mac High Sierra as well.

**Comment by ixjlyons** [comment]
An issue very similar to this showed up on the mailing list recently. Could you try [installing from the latest development version](https://github.com/pyqtgraph/pyqtgraph#installation-methods)? There may still be some OpenGL issues with high DPI displays but I think this specific problem has been fixed (but not released yet).

**Comment by j9ac9k** [comment]
Just ran the code attached above (had to add `import sys`) off of the current `develop` branch on macOS mojave and got the following result

![image](https://user-images.githubusercontent.com/646398/60200101-4793d680-97fa-11e9-85d5-363bce183728.png)

I would say that this issue has likely been addressed; and will be incorporated in the next release.  If you can still duplicate this issue from the develop branch, let us know and we'll reopen.
