### ISSUE TITLE
Axis shifted with multiple Windows 10 displays with different zoom settings

### ISSUE THREAD

**Issue by paulgavrikov** [pyqtgraph/pyqtgraph#795]
Hi,
I have the following display setup: Notebook (1080p, 125% zoom) and 2x external displays (1080p, 100% zoom). If I launch any graph on my notebook it looks just fine but when dragging the window to any of the external displays the x/y axis drift.
Setting my notebook to 100% solves this issue.

**Comment by j9ac9k** [comment]
i know it's been a while since you opened this issue, but could you provide some screenshots, as well as what version of pyqtgraph and qt-bindings you're using?

**Comment by j9ac9k** [comment]
I think this is a duplicate of #756 so I'm going to close this out and refer to that, if you don't feel that issue is the same, let us know and we'll reopen!
