### ISSUE TITLE
Secondary window issue on PlotWidget

### ISSUE THREAD

**Issue by dhabbyc** [pyqtgraph/pyqtgraph#796]
Hello,

 I have a PlotWidget instance embedded on pyqt5 application.

 The problem arises when a secondary screen is plugged into the computer (setting it as a "extension" of the main screen). When the appplication window is moved to the secondary screen (no matter if the resolution is the same as the main screen) the plot goes haywire:

![mono2](https://user-images.githubusercontent.com/45916589/50054094-251f5300-011d-11e9-8b54-5e28f9bfa83f.png)

But on the main screen looks like this:

![mono1](https://user-images.githubusercontent.com/45916589/50054098-35373280-011d-11e9-9f1e-36929d72b6f2.png)

Obviuosly, the subsequent plots get affected.

Is this a bug or I'm doing something wrong.

 I'm using Python 3.6.5, pyside2 5.11.2 and pyqtgraph 0.11.0.dev0+g41d2bc0.

Cheers,

**Comment by j9ac9k** [comment]
Hi @dhabbyc 

I routinely use multiple windows and have not encountered this problem.  If you can provide an example code (or reference one of the built-in examples), and still have this issue with the current release, let me know and I'll reopen.
