### ISSUE TITLE
Mouse Movement Bug

### ISSUE THREAD

**Issue by zanderman** [pyqtgraph/pyqtgraph#799]
Hello,

I am new to PyQtGraph and have encountered a small issue. I'm using the latest development version of PyQtGraph with **PySide2** and developing on **macOS**.

When moving the mouse while running any of the examples, or my own plots for that matter, I get the following exception:

`
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 365, in mouseMoveEvent
    delta = Point(ev.pos() - self.lastMousePos)
TypeError: 'PySide2.QtCore.QPoint.__sub__' called with wrong argument types:
  PySide2.QtCore.QPoint.__sub__(Point)
Supported signatures:
  PySide2.QtCore.QPoint.__sub__(PySide2.QtCore.QPoint)
`

I've looked into the code a bit and as the exception suggests the mouse event point and the last mouse position point are two different classes. I can cast the mouse event point to a `pyqtgraph.Point' to make the subtraction work, but this is only a temporary fix.

Is this a known issue with the current development version, or is there something I'm doing incorrectly on my end?

Cheers

**Comment by ixjlyons** [comment]
I believe #797 is intended to fix this issue.

**Comment by rangeli** [comment]
I too experienced this exact issue with PySide2 and the development PyQtGraph on Linux.

**Comment by j9ac9k** [comment]
This should have been fixed with https://github.com/pyqtgraph/pyqtgraph/pull/824 . Feel free to comment if that's not the case.
