### ISSUE TITLE
hpw to toggle plot visible?

### ISSUE THREAD

**Issue by retsyo** [pyqtgraph/pyqtgraph#802]
for example, there are 2D and 3D plot for both curve in theory and measure. 
```python
curve2D_1 = pg.PlotWidget().plot(x=x1, y=y1)
curve3D_1 = gl.GLLinePlotItem(pts1)

curve2D_2 = pg.PlotWidget().plot(x=x2, y=y2)
curve3D_2 = gl.GLLinePlotItem(pts2)


curve2D_1.setVisible(drawCurveInTheory)
curve3D_1.setVisible(drawCurveInTheory)

curve2D_2.setVisible(drawCurveInMeausured)
curve3D_2.setVisible(drawCurveInMeausured)
     
```

How to toggle to show except for 
```python
if setInvisible:
     saveData()
     setDataToNull()
else:
    setDataToSaved()
```

**Comment by ixjlyons** [comment]
For opengl items, `GLGraphicsItem` (the parent class) provides [`setVisible`](https://pyqtgraph.readthedocs.io/en/latest/3dgraphics/glgraphicsitem.html#pyqtgraph.opengl.GLGraphicsItem.GLGraphicsItem.setVisible) as well as `show`/`hide`.

Similarly for 2D items like `PlotCurveItem`, `ScatterPlotItem`, etc.  the great-grandparent class `QGraphicsItem` provides [`setVisible`](https://doc.qt.io/qt-5/qgraphicsitem.html#setVisible) and `show`/`hide`.
