### ISSUE TITLE
Selecting flowchart input or output nodes in Flowchart widget gives KeyError

### ISSUE THREAD

**Issue by christuart** [pyqtgraph/pyqtgraph#808]
The Flowchart widget has a flowchart visualisation and a tree view. The input and output nodes are in the visualisation within FlowchartWidget but not the tree of FlowchartCtrlWidget. When the user clicks on the input or output node to select it in the FlowchartWidget, an attempt it made to highlight it in the FlowchartCtrlWidget. This results in a KeyError, and therefore stops the data on those nodes being displayed in the FlowchartWidget.

To reproduce, run the Flowchart example: _examples/Flowchart.py_. Click Flowchart in the first window, and then click on the input or output node in the flow chart of the second window. A KeyError is raised.

**Comment by 2xB** [comment]
I can reproduce this using the latest version from branch `develop`. Did you manage to fix this?

**Comment by christuart** [comment]
Yes, there's a pull request open for it #809. I just updated the the flowchart-808 branch on christuart/pyqtgraph to confirm it still merges fine with develop.

**Comment by 2xB** [comment]
Great, thank you! Might you add "Fixes #808." to your first comment on #809? That automatically links this issue and the Pull Request.

**Comment by christuart** [comment]
Great, thanks for the hint.
