### ISSUE TITLE
multiplotwidget curve color with pen

### ISSUE THREAD

**Issue by ghost** [pyqtgraph/pyqtgraph#812]
When using multiplotwidget, it is not possible to pass a pen to the plot method.
This crashes:
pw = MultiPlotWidget()
pw.plot(metaarray,, pen=pg.mkPen('b', width=0.00001))

So there is no way to customize the color of the curves.

**Comment by angulartist** [comment]
https://github.com/pyqtgraph/pyqtgraph/pull/1324

**Comment by ixjlyons** [comment]
Implemented with #1324
