### ISSUE TITLE
PlotCurveItem.paintGL uses wrong type in glDrawArrays

### ISSUE THREAD

**Issue by Dennis-van-Gils** [pyqtgraph/pyqtgraph#819]
https://github.com/pyqtgraph/pyqtgraph/blob/2e69b9c5e6bd8008c2d7e9f384b9c9b32ff2f5a7/pyqtgraph/graphicsItems/PlotCurveItem.py#L566

Easy fix:
Line 566 should read:
gl.glDrawArrays(gl.GL_LINE_STRIP, 0, int(pos.size / pos.shape[-1]))
instead of:
gl.glDrawArrays(gl.GL_LINE_STRIP, 0, pos.size / pos.shape[-1])

**Comment by ixjlyons** [comment]
Fixed by #1044
