### ISSUE TITLE
Typo in checkSceneChange method of ViewBox?

### ISSUE THREAD

**Issue by andalpha** [pyqtgraph/pyqtgraph#820]
https://github.com/pyqtgraph/pyqtgraph/blob/9aaae8d5dc86d5373d297f5763ab65d8043afcdb/pyqtgraph/graphicsItems/ViewBox/ViewBox.py#L277

ViewBox has an attribute called `_lastScene`, but it doesn't seem to have one called `lastScene`.

So I suggest replacing line 277,
`if self._lastScene is not None and hasattr(self.lastScene, 'sigPrepareForPaint')`,
with
`if self._lastScene is not None and hasattr(self._lastScene, 'sigPrepareForPaint')`.

**Comment by j9ac9k** [comment]
Thanks for identifying this issue, I submitted a PR and will see if someone else has any issues.
