### ISSUE TITLE
AxisItem: text space is not reduced when tick labels get smaller

### ISSUE THREAD

**Issue by andalpha** [pyqtgraph/pyqtgraph#821]
By default, the text space needed for tick labels is automatically increased upon zoom when the labels get longer (e.g. when showing more digits). When zooming back to normal size, though, the space reserved for tick labels stays large. This can result in a huge gap between the axis label and the tick labels.

The issue occurs because the `textWidth` and `textHeight` properties of AxisItem can never decrease.
To see this, let's have a look at the method `_updateMaxTextSize`:
https://github.com/pyqtgraph/pyqtgraph/blob/2e69b9c5e6bd8008c2d7e9f384b9c9b32ff2f5a7/pyqtgraph/graphicsItems/AxisItem.py#L290-L307
With line 295, `mx = max(self.textWidth, x)`, and line 297, `self.textWidth = mx`, we observe that `self.textWidth` is set to the maximum of itself and `x`. So `self.textWidth` can only increase.

In fact, the code should be modified as follows:
Line 295 should be deleted (as the maximum is not needed here).
Line 296 should be replaced by `if x > self.textWidth or x < self.textWidth - 10:`.
Line 297 should be replaced by `self.textWidth = x`.

The same modifications should be done in line 302, 303 and 304 for `self.textHeight`.

**Comment by vadmu** [comment]
I was surprised to see this feature in all examples. If I scroll any plot I can get very long tick labels. Scrolling back results in an empty space between the y-axis and the border. In my case when using a PlotWidget these two lines helped:

`pw.getAxis('left').textWidth = 0`
`pw.getAxis('left')._updateWidth()`

**Comment by andalpha** [comment]
Thanks for your feedback, vadmu! Indeed, your code cures the issue.

To get down to its root, I solved it by re-implementing the AxisItem class using the modifications specified at the end of my OP. The modified AxisItem can then be used in a PlotWidget by

`PlotWidget(axisItems={"bottom": ModifiedAxisItem(orientation="bottom"), "left": ModifiedAxisItem(orientation="left")})`

As this problem concerns _all_ pyqtgraph applications, I'm quite surprised, too, that it hasn't been addressed yet.

**Comment by andalpha** [comment]
There is a pull request now:
[https://github.com/pyqtgraph/pyqtgraph/pull/838](url)
