### ISSUE TITLE
very slow feed-back

### ISSUE THREAD

**Issue by danielhrisca** [pyqtgraph/pyqtgraph#822]
there are many opened issues and PR's, many without any feed-back from the core devs.

It's sad that such a well known and used package stagnates like this.

**Comment by ussserrr** [comment]
I think it's not so fair to claim a lot from such open-source project. And if we take this message https://groups.google.com/d/msg/pyqtgraph/FroKuuar_EM/WIQbnnVgEQAJ it is stated that the work is slowly but surely is going on.

**Comment by danielhrisca** [comment]
I don't mean to be disrespectful. I just wish state of the repo would better reflect the message from the google group

**Comment by j9ac9k** [comment]
This project has largely been developed by one individual who has been taking a step back, for reasons I could only guess.  There are few people that can really contribute to the level that Luke can, so some of us that have volunteered to contribute as best we can have to come to terms with the fact that willingness along won't cut it.

2 of the 3 participants of this issue, including the author are now contributors.  A number of other people (including myself) have started contributing.  In recent weeks numerous advancements have been made to try and assist with giving confidence that a given PR won't break something.

* As of #880 there is a tox configuration that develops can run tests on a variety of configurations locally.
* As of #903 we have a robust CI system (only passing on 5/18 builds currently, but we're getting there)
* If you click on the [insights button](https://github.com/pyqtgraph/pyqtgraph/pulse) on the top, you can see the activity to the repo has picked up.

I think things are going in the right direction, but it's going to be slow going.  We have a huge backlog of issues/PRs, test suite that is broken, and a desire to get the next stable release out that supports pyside2 5.12.  Most of the contributors to this library, myself especially, are not that familiar with it, so at least in my case, I am very cautious on what I give feedback or do code reviews.  Once the test suite starts passing, we can start being more aggressive with merging PRs, but until then we have to be cautious.

Anyway if you (and by you, I mean anyone reading this issue) want to contribute to the library, email campagnola know (not tagging him to keep his github notifications down) and he'll invite you to the slack group.  Even if you don't have much experience, we can use help with testing, documentation, issue/PR management, etc, so please come volunteer if you are at all interested.

@danielhrisca I'm going to close this issue; I think we're doing a lot of the right things, but it will take a while for new contributors to get comfortable enough to review code from other PRs as they're coming in.
