### ISSUE TITLE
Using flowchart nodes without flowchart causes python to seg fault

### ISSUE THREAD

**Issue by syamajala** [pyqtgraph/pyqtgraph#828]
I tried using a flowchart node outside of the flowchart and it no longer seems to work.
It looks like the python process is seg faulting. 
Here is the code:
`
import pyqtgraph
from pyqtgraph.flowchart.library import LIBRARY

node = LIBRARY.getNodeType("RemovePeriodic")
node('remove_periodic')
`

Below is a stack trace in gdb:
`
#0  0x00007ffff675c0f2 in QGuiApplication::palette() () from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5        
#1  0x00007ffff1866d98 in QApplication::palette(char const*) ()
   from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5                                                         
#2  0x00007ffff1a2c964 in QWidgetTextControlPrivate::setContent(Qt::TextFormat, QString const&, QTextDocument*) ()                                       
   from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5                                                         
#3  0x00007ffff1a2f7d2 in QWidgetTextControlPrivate::init(Qt::TextFormat, QString const&, QTextDocument*) ()                                             
   from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5                                                         
#4  0x00007ffff1a2f862 in QWidgetTextControl::QWidgetTextControl(QObject*) ()                                                                            
   from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5                                                         
#5  0x00007ffff1b2b1e7 in QGraphicsTextItemPrivate::textControl() const ()
   from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5                                                         
#6  0x00007ffff1b2b3ad in QGraphicsTextItem::setPlainText(QString const&) ()
   from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5                                                         
#7  0x00007ffff1b32b10 in QGraphicsTextItem::QGraphicsTextItem(QString const&, QGraphicsItem*) ()                                                        
   from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5                                                         
#8  0x00007ffff21902d9 in sipQGraphicsTextItem::sipQGraphicsTextItem(QString const&, QGraphicsItem*) ()                                                  
   from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/QtWidgets.so                                                                      
#9  0x00007ffff21904b1 in init_type_QGraphicsTextItem () from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/QtWidgets.so                
#10 0x00007ffff2beed34 in sipSimpleWrapper_init () from /home/seshu/.virtualenvs/ami/lib/python3.7/site-packages/PyQt5/sip.so                            
#11 0x00007ffff7baf3ac in _PyObject_FastCallKeywords () from /usr/lib/libpython3.7m.so.1.0                                                               
#12 0x00007ffff7bfacca in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.7m.so.1.0                                                                 
#13 0x00007ffff7b3dc0b in _PyFunction_FastCallDict () from /usr/lib/libpython3.7m.so.1.0                                                                 
#14 0x00007ffff7b4d908 in _PyObject_Call_Prepend () from /usr/lib/libpython3.7m.so.1.0                                                                   
#15 0x00007ffff7b9ba73 in ?? () from /usr/lib/libpython3.7m.so.1.0
#16 0x00007ffff7baf3ac in _PyObject_FastCallKeywords () from /usr/lib/libpython3.7m.so.1.0                                                               
#17 0x00007ffff7bfa5e7 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.7m.so.1.0                                                                 
#18 0x00007ffff7b832eb in _PyFunction_FastCallKeywords () from /usr/lib/libpython3.7m.so.1.0                                                             
#19 0x00007ffff7bfa2b3 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.7m.so.1.0                                                                 
#20 0x00007ffff7b3cb99 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.7m.so.1.0                                                                 
#21 0x00007ffff7b3ddec in _PyFunction_FastCallDict () from /usr/lib/libpython3.7m.so.1.0                                                                 
#22 0x00007ffff7b4d908 in _PyObject_Call_Prepend () from /usr/lib/libpython3.7m.so.1.0                                                                   
#23 0x00007ffff7b9ba73 in ?? () from /usr/lib/libpython3.7m.so.1.0
#24 0x00007ffff7baf204 in ?? () from /usr/lib/libpython3.7m.so.1.0
#25 0x00007ffff7b3e33b in PyObject_Call () from /usr/lib/libpython3.7m.so.1.0                                                                            
#26 0x00007ffff7bf743c in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.7m.so.1.0                                                                 
#27 0x00007ffff7b3cb99 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.7m.so.1.0                                                                 
#28 0x00007ffff7b3ddec in _PyFunction_FastCallDict () from /usr/lib/libpython3.7m.so.1.0                                                                 
#29 0x00007ffff7b4d908 in _PyObject_Call_Prepend () from /usr/lib/libpython3.7m.so.1.0                                                                   
#30 0x00007ffff7b3e33b in PyObject_Call () from /usr/lib/libpython3.7m.so.1.0                                                                            
#31 0x00007ffff7bf743c in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.7m.so.1.0                                                                 
#32 0x00007ffff7b3cb99 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.7m.so.1.0                                                                 
#33 0x00007ffff7b83492 in _PyFunction_FastCallKeywords () from /usr/lib/libpython3.7m.so.1.0                                                             
#34 0x00007ffff7bf6b7d in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.7m.so.1.0                                                                 
#35 0x00007ffff7b3cb99 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.7m.so.1.0                                                                 
#36 0x00007ffff7b3ddec in _PyFunction_FastCallDict () from /usr/lib/libpython3.7m.so.1.0                                                                 
#37 0x00007ffff7b4d908 in _PyObject_Call_Prepend () from /usr/lib/libpython3.7m.so.1.0                                                                   
#38 0x00007ffff7b9ba73 in ?? () from /usr/lib/libpython3.7m.so.1.0
#39 0x00007ffff7baf3ac in _PyObject_FastCallKeywords () from /usr/lib/libpython3.7m.so.1.0                                                               
#40 0x00007ffff7bfa5e7 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.7m.so.1.0                                                                 
#41 0x00007ffff7b3cb99 in _PyEval_EvalCodeWithName () from /usr/lib/libpython3.7m.so.1.0                                                                 
#42 0x00007ffff7b3dab4 in PyEval_EvalCodeEx () from /usr/lib/libpython3.7m.so.1.0                                                                        
#43 0x00007ffff7b3dadc in PyEval_EvalCode () from /usr/lib/libpython3.7m.so.1.0                                                                          
#44 0x00007ffff7c67c94 in ?? () from /usr/lib/libpython3.7m.so.1.0
#45 0x00007ffff7c698be in PyRun_FileExFlags () from /usr/lib/libpython3.7m.so.1.0                                                                        
#46 0x00007ffff7c6ac75 in PyRun_SimpleFileExFlags () from /usr/lib/libpython3.7m.so.1.0                                                                  
#47 0x00007ffff7c6ceb7 in ?? () from /usr/lib/libpython3.7m.so.1.0
#48 0x00007ffff7c6d0fc in _Py_UnixMain () from /usr/lib/libpython3.7m.so.1.0
#49 0x00007ffff7dcb223 in __libc_start_main () from /usr/lib/libc.so.6
#50 0x000055555555505e in _start ()
`

**Comment by syamajala** [comment]
This is a user error. You have to create a QApplication and QMainWindow before you try to create a node instance. I had assumed I could create the node instance first then the application and window.

**Comment by flutefreak7** [comment]
I think it's true that you can create QObjects and even widgets without a problem, but if you try to paint them or interact with QApplication in any way you get errors. Glancing through the stack trace it looks like the object was trying to determine it's pallete in order to format a text widget and the palette is related to painting and trickles down from the QApplication and that caused the error.
