### ISSUE TITLE
PySide2 official release

### ISSUE THREAD

**Issue by benjaminirving** [pyqtgraph/pyqtgraph#829]
Be great to have a release that officially supports PySide2. Pyqtgraph is great but this is a stumbling block for the Quantiphyse (https://github.com/ibme-qubic/quantiphyse) team that have just released there code. I'm no longer involved but keen to test Quantiphyse on more recent distributions.

**Comment by dolorsitatem** [comment]
I second that PySide2 support would be great.  However, I don't second "Pyqtgraph isn't great".  I appreciate the work you've put into PyQtGraph and appreciate that you decided to free it under an MIT license for all of us to use, even those of us who are ungrateful for your efforts and kindness...

**Comment by benjaminirving** [comment]
@dolorsitatem, I apologies for the trailing 'n'. This was typed quite quickly and gave the wrong impression. 

I was trying to say that Pyqtgraph is great but it would really help to have a release with PySide2 support.

**Comment by campagnola** [comment]
No worries, Benjamin. I want to see that release as well. We had a few
people volunteer to prepare the next release, but they seem to have run out
of spare time.
If anyone wants to help out, pop in to pyqtgraph.slack.com!

**Comment by ksunden** [comment]
If there is anything I can do to help out, let me know (Don't see a way to request a slack invite to discuss over there).

**Comment by ixjlyons** [comment]
@ksunden see https://github.com/pyqtgraph/pyqtgraph/issues/238#issuecomment-489177286

**Comment by j9ac9k** [comment]
Going to close this issue as a clean-up effort, but PySide2 support is front and center for the next stable release of pyqtgraph.

**Comment by ksunden** [comment]
We have now released 0.11.0rc0 to [pypi](https://pypi.org/project/pyqtgraph/0.11.0rc0/).
