### ISSUE TITLE
Future warning with image size >1e6

### ISSUE THREAD

**Issue by grm84** [pyqtgraph/pyqtgraph#842]
`ImageView.py, line 588, in quickMinMax`
`  data = data[sl]`

`FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use arr[tuple(seq)] instead of `arr[seq]`. In the future this will be interpreted as an array index, arr[np.array(seq)], which will result either in an error or a different result.
Aborted (core dumped)
`

I'm using pyqtgraph 0.10.0, python 3.7.2 and numpy 1.15.4

**Comment by ksunden** [comment]
Closed by #875
