### ISSUE TITLE
How to rotate Xtick 

### ISSUE THREAD

**Issue by qiujian3328103** [pyqtgraph/pyqtgraph#843]
Is there a way to rotate the Xtick text value in PyQtGraph? I tried to get the axis and rotate the label but the entire x-axis rotated. 
from pyqtgraph import GraphicsLayoutWidget
View = GraphicsLayoutWidget()
window = View.addPlot()
Xtick = window.getAxis('bottom')
Ytick = window.getAxis('left')
Xtick.label.rotate(45)

**Comment by 2xB** [comment]
It is currently not possible to rotate tick labels. You might be interested in issue #322, which developed into a feature request including example code on how to modify PyQtGraph to support this feature.

**Comment by 2xB** [comment]
If you have further comments on this, feel free to leave one here or in a new issue!
