### ISSUE TITLE
application not responding

### ISSUE THREAD

**Issue by xlgforever** [pyqtgraph/pyqtgraph#844]
when i run the examples in this page"http://www.pyqtgraph.org/documentation/plotting.html":
```
import pyqtgraph as pg
import numpy as np
x = np.random.normal(size=1000)
y = np.random.normal(size=1000)
pg.plot(x, y, pen=None, symbol='o') 
```
then it show a window but have not responding. 
![the no responding window](https://user-images.githubusercontent.com/40095259/54729289-b3442300-4bbd-11e9-9a5c-7852e6eaeaec.png)
besides, when i kill the window,, the python kernel will be forced shutdown. 

and when i import the pyqtgraph module, it shows : FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.from ._conv import register_converters as _register_converters".

**Comment by campagnola** [comment]
Are you using jupyter notebook?  See `%gui qt` here: https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-gui

**Comment by xlgforever** [comment]
> Are you using jupyter notebook? See `%gui qt` here: https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-gui

yes, thanks for your answer! it works well now!

**Comment by ibrahimLearning** [comment]
> Are you using jupyter notebook? See `%gui qt` here: https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-gui

What about in spyder?

**Comment by Nikfr** [comment]
I have the same problem in Spider under Windows 10
