### ISSUE TITLE
How to disable the right button function

### ISSUE THREAD

**Issue by weike32** [pyqtgraph/pyqtgraph#849]

**Comment by ixjlyons** [comment]
Are you referring to the context menu that comes up with you right click on a plot? If so, I believe this is what you're looking for: http://www.pyqtgraph.org/documentation/graphicsItems/plotitem.html#pyqtgraph.PlotItem.setMenuEnabled

**Comment by weike32** [comment]
> 你是指你在右键点击情节时出现的上下文菜单吗？如果是这样，我相信这就是你要找的东西：[http](http://www.pyqtgraph.org/documentation/graphicsItems/plotitem.html#pyqtgraph.PlotItem.setMenuEnabled)：[//www.pyqtgraph.org/documentation/graphicsItems/plotitem.html#pyqtgraph.PlotItem.setMenuEnabled](http://www.pyqtgraph.org/documentation/graphicsItems/plotitem.html#pyqtgraph.PlotItem.setMenuEnabled)

Thank you, but this API is limited and needs to call pyqtgraph.ViewBox. Here is my example, can you help me see how to call this api。



import pyqtgraph as pg
import array
import random
app = pg. mkQApp()
data = array.array('d')
N = 200
win = pg.GraphicsWindow()
win.setWindowTitle(u'Real-time curve display')
win.resize(1000, 600)
# p = pg.ViewBox()
# plot.showAxis('right')
# plot.setMenuEnabled(False)
# plot.scene().addItem(p)
# plot.getAxis('right').linkToView(p)
# p.setXLink(plot)
# plot.viewBoxes.append(p)
# Callback = functools.partial(self.updateViews, plot)
# plot.getViewBox().sigStateChanged.connect(Callback)
p = win.addPlot()
p.showGrid(x=True, y=True)
p.setRange(xRange=[0, N-1], yRange=[0,260], padding=0)
p.setLabels(left='Real-time temperature/℃', bottom='time/0.1s', title='Real-time temperature curve')
curve = p.plot(pen='y')
def plotData():
    tmp = random.randint(5, 8)*20
    data.append(tmp)
    print(tmp)
    curve.setData(data)

timer = pg.QtCore.QTimer()
timer.timeout.connect(plotData)
timer.start(100)
app.exec_()

**Comment by ixjlyons** [comment]
Sorry, I don't quite get what you're asking now. Is this still a question of how to disable the context menu or how to use `ViewBox`? If the former, the object `p` is a `PlotItem` so you can add `p.setMenuEnabled(False)`. In the latter case, maybe this example would be helpful: https://github.com/pyqtgraph/pyqtgraph/blob/develop/examples/ViewBox.py

A `ViewBox` object is created for you when the `PlotItem` is created. It can be retrieved with [`getViewBox`](http://www.pyqtgraph.org/documentation/graphicsItems/plotitem.html#pyqtgraph.PlotItem.getViewBox). If you need to create your own `ViewBox`, you can pass it to `addPlot` like `win.addPlot(viewBox=viewBox)`.

**Comment by weike32** [comment]
Hello @ixjlyons
i try to this 

from PyQt5 import QtCore, QtGui, QtWidgets

class graph_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_3.setSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 2, 2, 1, 2)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 4)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 1, 1, 4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_7.setText(_translate("Form", "分析"))
        self.label.setText(_translate("Form", "图形分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "折线图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))

and the Demo 
import sys
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QDialog, QApplication, QWidget
from qtpy import QtWidgets
import pyqtgraph as pg

from graph1.graphAnalysis import graph_Form


class CustomViewBox(pg.ViewBox):
    def __init__(self, *args, **kwds):
        pg.ViewBox.__init__(self, *args, **kwds)
        self.RectMode = 3
        self.setMouseMode(self.RectMode)

    def mouseClickEvent(self, ev):
        if ev.button() == pg.QtCore.Qt.RightButton:
            self.autoRange()

    def mouseDragEvent(self, ev):
        pg.ViewBox.mouseDragEvent(self, ev)

    def wheelEvent(self,ev):
        ev.ignore()


class graphAnalysis(QDialog,graph_Form):
    def __init__(self):
        super(graphAnalysis, self).__init__()
        self.setupUi(self)
        self.pushButton_7.clicked.connect(self.test)
        self.tabWidget.clear()
    def handleChanged(self,item,column):
        count = item.childCount()
        if item.checkState(column) == Qt.Checked:
            for index in range(count):
                item.child(index).setCheckState(0,Qt.Checked)
        if item.checkState(column) == Qt.Unchecked:
            for index in range(count):
                item.child(index).setCheckState(0,Qt.Unchecked)
    def test(self):


        tab1 = QtWidgets.QWidget()
        scrollArea = QtWidgets.QScrollArea(tab1)
        scrollArea.setMinimumSize(650,550)
        scrollArea.setWidgetResizable(True)

        labelsContainer = QWidget()
        labelsContainer.setMinimumSize(0,1500)
        scrollArea.setWidget(labelsContainer)
        layout = QtWidgets.QVBoxLayout(labelsContainer)

        time = ['2019-04-20 08:09:00', '2019-04-20 08:09:00', '2019-04-20 08:09:00', '2019-04-20 08:09:00']
        value = [1.2, 2, 1, 4]
        xdict = dict(enumerate(time))
        ticks = [list(zip(range(4), tuple(time)))]

        vb = CustomViewBox()

        plt = pg.PlotWidget(title="Basic array plotting",viewBox=vb)
        plt.resize(500, 500)
        plt.setBackground(background=None)
        plt.plot(list(xdict.keys()), value)
        plt.getPlotItem().getAxis("bottom").setTicks(ticks)


        temp = QtWidgets.QWidget()
        temp.setMinimumSize(600,300)
        temp.setMaximumSize(600,300)
        layout1 = QtWidgets.QVBoxLayout(temp)
        layout1.addWidget(plt)
        layout.addWidget(temp)


        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        layout.addItem(spacerItem)
        self.tabWidget.addTab(tab1, '12')

if __name__ =="__main__":
    app = QApplication(sys.argv)
    w = graphAnalysis()
    w.show()
    sys.exit(app.exec_())

this  class CustomViewBox forbid the RightButton, However, there is a problem with the scroll wheel. When the mouse is on the coordinate axis, the sliding wheel will throw the following problem.

Traceback (most recent call last):
  File "F:\Anaconda3\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py", line 1062, in wheelEvent
    self.linkedView().wheelEvent(ev, axis=0)
TypeError: wheelEvent() got an unexpected keyword argument 'axis'

**Comment by ixjlyons** [comment]
Going to close this as it's been a couple months and I think the original question has been answered.. If you're still having trouble, feel free to re-open this issue or make another one.
