### ISSUE TITLE
how to change size (height and width) of graph in a ScrollArea

### ISSUE THREAD

**Issue by weike32** [pyqtgraph/pyqtgraph#853]
i want to change size, but , i do not find any API.
my question like this link
https://stackoverflow.com/questions/22893564/pyqtgraph-how-to-change-size-height-and-width-of-graph-in-a-scrollarea

**Comment by TinToSer** [comment]
when we use addPlot() then bydefault it will capture whole width but when we use addViewBox() then some portion is left

**Comment by 2xB** [comment]
@weike32 Does any of the comments on stackoverflow or here answer your question?

**Comment by weike32** [comment]
@2xB Think for you attention to this question , and this question is solved. thinks for every help

**Comment by j9ac9k** [comment]
@weike32 would you mind posting your solution, in case someone with the same issue comes across this page in google, or we decide to implement a "better" implementation within the library.

Thanks.

**Comment by weike32** [comment]
@j9ac9k The example is very simple, but it reflects my solution

This link is my solution：
https://github.com/PyQt5/PyQt/blob/master/PyQtGraph/testGraphAnalysis.py

looking forward "better" implementation within the library.

**Comment by j9ac9k** [comment]
thanks for sharing
