### ISSUE TITLE
Wrong `Point` type to QPoint.__sub__ ?

### ISSUE THREAD

**Issue by goodboy** [pyqtgraph/pyqtgraph#858]
I just booted up the [`BarGraphItem`](https://github.com/pyqtgraph/pyqtgraph/blob/develop/examples/BarGraphItem.py) example and see this error as I move the mouse around:

```python
Traceback (most recent call last):
  File "/home/goodboy/repos/pyqtgraph/pyqtgraph/widgets/GraphicsView.py", line 365, in mouseMoveEvent
    delta = Point(ev.pos() - self.lastMousePos)
TypeError: 'PySide2.QtCore.QPoint.__sub__' called with wrong argument types:
  PySide2.QtCore.QPoint.__sub__(Point)
Supported signatures:
  PySide2.QtCore.QPoint.__sub__(PySide2.QtCore.QPoint)
```

Backend version:

```python
In [3]: PySide2.__version__                                                                                     
Out[3]: '5.12.3'
```

If it's a simple fix I'm happy to make a PR :+1:

**Comment by ixjlyons** [comment]
Duplicate of #799. Proposed fix at #797. Unfortunately, the project has been pretty quiet for a while now, so there's not really a timeline for when it might be merged (and released).

**Comment by goodboy** [comment]
Shoot. Thanks for the heads up @ixjlyons.

>the project has been pretty quiet for a while now

Is this because all the work has been moved to `vispy`?
If that project is where I should be focusing instead it'd be good to know.
The thing is I was hoping to leverage some built in charting features of Qt, namely candlesticks.

**Comment by ixjlyons** [comment]
As far as I know, no. The two projects have overlapping but still distinct sets of goals. I haven't really kept up with vispy progress though so I'm not sure how it's evolved. Depending on your needs, though, it could be worth the switch.

There has been some recent effort to get pyqtgraph back on track with a new release and possibly more maintainers. I've asked about getting involved so we'll see how it goes.

**Comment by ixjlyons** [comment]
Also, see https://github.com/pyqtgraph/pyqtgraph/issues/238#issuecomment-297804881

**Comment by goodboy** [comment]
Thanks @ixjlyons if I get around to what I'm hoping then I might be interested in becoming more serious contributor eventually.
