### ISSUE TITLE
pyqtgraph should not inject basestring (or other python2 builtins) in the python3 builtins namespace

### ISSUE THREAD

**Issue by anntzer** [pyqtgraph/pyqtgraph#86]
For the better or, mostly, the worse, setuptools' pkg_resources uses the presence of `basestring` in the builtins namespace to check for Python2 vs. Python3.  While this is a poor approach, this leads to issues when trying to import pkg_resources after pyqtgraph in Python3:

```
$ ipython3 -c "import pyqtgraph, pkg_resources"                     [14-08-04 0:23:44]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-90f3ed1b6919> in <module>()
----> 1 import pyqtgraph, pkg_resources

/usr/lib/python3.4/site-packages/pkg_resources.py in <module>()
     48     basestring
     49     next = lambda o: o.next()
---> 50     from cStringIO import StringIO as BytesIO
     51 except NameError:
     52     basestring = str

ImportError: No module named 'cStringIO'
```

(note that the reference to `basestring` does not raise a NameError despite being run in Python3.)

The other functions injected, `cmp` and `xrange`, could arguably also lead to similar problems.

I filed a bug for pkg_resources too but ultimately any kind of builtins manipulation is vulnerable to such issues.

**Comment by 2xB** [comment]
This should be fixed as of pyqtgraph 0.10.0 via https://github.com/pyqtgraph/pyqtgraph/commit/0976991efda1825d8f92b2462ded613bcadef188 . Thank you for reporting!
