### ISSUE TITLE
ErrorBarItem with no data crashes PlotWidget.addItem

### ISSUE THREAD

**Issue by jaxankey** [pyqtgraph/pyqtgraph#860]
pyqtgraph v0.10.0 installed via conda on windows or linux (same behavior)

Hello,

To get fast plot updates, I currently add a `PlotCurveItem` to a `PlotWidget` once (via `addItem()`), then keep updating the `PlotCurveItem`'s data with `setData()`. This allows me to initially specify no data, which is helpful when I initially build the GUI.

I now wish to do the same with an `ErrorBarItem`, but it will crash unless the data when the ErrorBarItem is created: for example,

```
import pyqtgraph as pg
import numpy     as np

x = np.array([1,2,3,4,5])
y = np.array([1,2,1,3,1])
e = np.array([1,0.1,0.5,0.1,3])

plt = pg.plot()
err = pg.ErrorBarItem(x=x, y=y, top=e, bottom=e)
cur = pg.PlotCurveItem(x=x, y=y)
plt.addItem(err)
plt.addItem(cur)
```
works just fine, but
```
import pyqtgraph as pg
import numpy     as np

x = np.array([1,2,3,4,5])
y = np.array([1,2,1,3,1])
e = np.array([1,0.1,0.5,0.1,3])

plt = pg.plot()
err = pg.ErrorBarItem() #x=x, y=y, top=e, bottom=e)
cur = pg.PlotCurveItem(x=x, y=y)
plt.addItem(err)
plt.addItem(cur)
```
raises the following exception:
```
  File "/home/jack/Anaconda3/lib/python3.7/site-packages/pyqtgraph/graphicsItems/ErrorBarItem.py", line 147, in boundingRect
    return self.path.boundingRect()

AttributeError: 'NoneType' object has no attribute 'boundingRect'
```

As a hack, it is possible to simply set some dummy x and y data with top=0 and bottom=0.

Cheers,
Jack

**Comment by ixjlyons** [comment]
Should be fixed now
