### ISSUE TITLE
Synchronize multiple pg.ImageView objects

### ISSUE THREAD

**Issue by maxstrobel** [pyqtgraph/pyqtgraph#862]
Hello,

I encountered some difficulties two synchronize two (or more) pg.ImageView objects:

```python
import numpy as np
import pyqtgraph as pg


pg.mkQApp()
imv1 = pg.ImageView()
imv1.show()
imv1.setImage(np.random.random((100,8,8)))

imv2 = pg.ImageView()
imv2.show()
imv2.setImage(np.random.random((100,8,8)))

imv2.sigTimeChanged.connect(imv1.setCurrentIndex)
imv1.sigTimeChanged.connect(imv2.setCurrentIndex)
```

Both image views are synchronized when I set the position of the time axis via the mouse. However if I use keys, e.g. <space> for <play>, only the selected pg.ImageView is reacting. I found a small workaround, but I wonder, if this is the intended usage?

```python
import numpy as np
import pyqtgraph as pg

class PatchedImageView(pg.ImageView):
    def jumpFrames(self, n):
        super().jumpFrames(n)
        _, time = self.timeIndex(self.timeLine)
        self.sigTimeChanged.emit(self.currentIndex, time)


pg.mkQApp()
imv1 = PatchedImageView()
imv1.show()
imv1.setImage(np.random.random((100,8,8)))

imv2 = PatchedImageView()
imv2.show()
imv2.setImage(np.random.random((100,8,8)))

imv2.sigTimeChanged.connect(imv1.setCurrentIndex)
imv1.sigTimeChanged.connect(imv2.setCurrentIndex)
```

**Comment by 2xB** [comment]
Thank you for the report! Could you please verify that Pull Request #1016 fixes the issue?

**Comment by maxstrobel** [comment]
@2xB, yes, your fix seems to fix the issue. I tried the above example and everything worked as intended. I let the issue open until the pull request is merged.

Thank you!
