### ISSUE TITLE
ImageItem max size 

### ISSUE THREAD

**Issue by adamananos** [pyqtgraph/pyqtgraph#863]
Hello, 

I am finding that the largest size array that can be rendered in an ImageItem is 2^29. 
For example, take this modified version of the example imageAnalysis.py code:
```python3
#### -*- coding: utf-8 -*-
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui
import numpy as np

#### Interpret image data as row-major instead of col-major
pg.setConfigOptions(imageAxisOrder='row-major')

pg.mkQApp()
win = pg.GraphicsLayoutWidget()
win.setWindowTitle('pyqtgraph example: Image Analysis')

#### A plot area (ViewBox + axes) for displaying the image
p1 = win.addPlot()

#### Item for displaying image data
img = pg.ImageItem()
p1.addItem(img)

#### Custom ROI for selecting an image region
roi = pg.ROI([-8, 14], [600, 500])
roi.addScaleHandle([0.5, 1], [0.5, 0.5])
roi.addScaleHandle([0, 0.5], [0.5, 0.5])
p1.addItem(roi)
roi.setZValue(10)  # make sure ROI is drawn above image

### Contrast/color control
hist = pg.HistogramLUTItem()
hist.setImageItem(img)
win.addItem(hist)

### Another plot area for displaying ROI data
win.nextRow()
p2 = win.addPlot(colspan=2)
p2.setMaximumHeight(250)
win.resize(800, 800)
win.show()

### Generate image data
data = np.random.normal(size=(23170, 23170))
data[2000:8000, 2000:8000] += 3.
img.setImage(data)
hist.setLevels(data.min(), data.max())

### set position and scale of image
img.scale(0.2, 0.2)
img.translate(-50, 0)

### zoom to fit imageo
p1.autoRange()  

### Callbacks for handling user interaction
def updatePlot():
    global img, roi, data, p2
    selected = roi.getArrayRegion(data, img)
    p2.plot(selected.mean(axis=0), clear=True)

roi.sigRegionChanged.connect(updatePlot)
updatePlot()

### Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()_
```
Which produces
![image](https://user-images.githubusercontent.com/22941100/57467872-5b3aac00-7251-11e9-8a74-a86828c55e3b.png)

## Now change the size of the data to be rendered to (size = 23171,23170)
Which produces
![image](https://user-images.githubusercontent.com/22941100/57468025-ae146380-7251-11e9-9332-ace56a192cca.png)

The data is no longer rendered, but it is accessible to the ROI object. 

Is this a known limitation, and if so, is there a good workaround. Is there a good way to break up and display large arrays that will still allow control over their LUTs using a HistogramLUTItem.

Thanks for any help.

**Comment by pijyoi** [comment]
Given that ImageItem uses an QImage under the hood, the size limitation would be related to QImage's maximum size. 

Qt 5.9 QImage has a method byteCount() -> int, so that limits the maximum byte size to be 2^31 - 1. Since ImageItem renders a RGBA image, that reduces your maximum image size by a factor of 4.

Qt 5.12 QImage has a method sizeInBytes() -> qsizetype, so possibly the maximum size has been bumped to 2^63-1 on 64-bit systems. 

Which version of Qt were you using?

**Comment by adamananos** [comment]
Hello pijyoi, 

I was using: 
python 2.7.14
pyqt 4.11.4
pyqtgraph 0.10.0
qt 4.8.7

with: 
python 3.9.1
pyqt 5.12.3
pyqtgraph 0.11.1
qt 5.12.9

you are correct in that the limit is no longer a problem.

**Comment by j9ac9k** [comment]
> I did not try to test the maximum size as the rendering was quite slow.

If you have a Windows or Linux machine with an NVIDIA GPU, you can install CuPy and pyqtgraph will use that to assist with rendering, which can have a great deal of improvement on large images.

**Comment by j9ac9k** [comment]
I think we can close this out, @adamananos let us know if you have any further questions.
