### ISSUE TITLE
Wrong auto-scale when using FillBetweenItem

### ISSUE THREAD

**Issue by jeberger** [pyqtgraph/pyqtgraph#874]
# Summary of the issue

When the plot includes a `FillBetweenItem`, the axes no longer auto-scale properly.

# Steps to reproduce

```py
import pyqtgraph as pg
from pyqtgraph.Qt import QtGui, QtCore

app = QtGui.QApplication ([])

xs = range (3)
lo = [  99, 89, 109 ]
hi = [ 101, 91, 111 ]

win = pg.GraphicsWindow()

plot = win.addPlot (title = "No fill")
plot.setLogMode (x = False, y = True)
plot.plot (x = xs, y = lo)
plot.plot (x = xs, y = hi)

plot = win.addPlot (title = "With fill")
plot.setLogMode (x = False, y = True)
lp = plot.plot (x = xs, y = lo)
hp = plot.plot (x = xs, y = hi)
plot.addItem (pg.FillBetweenItem (lp, hp))

app.exec_()
```

# Expected result

We should see two mostly identical plots side by side.

# Actual result

The right-hand plot appears zoomed out.

# Notes

I've enabled log-scale on the Y axis because it makes the problem more visible, but the issue is present even with linear scale.

# Versions

Python: 2.7.16
PyQtGraph: 0.10.0

**Comment by 2xB** [comment]
@jeberger I could not reproduce a difference between executing your example with and without adding the FillBetweenItem. For me, it does not appear zoomed-out. Could you please provide a screenshot?
Which operating system are you using?
What is the output of `pyqtgraph.Qt.VERSION_INFO`?

**Comment by jeberger** [comment]
Here it is: `PyQt4 4.12.3 Qt 4.8.7`

**Comment by jeberger** [comment]
Here's a screenshot showing what I mean:

![Screenshot](http://jeberger.free.fr/public/pyqtgraph_issue874.png)

I would expect both graphs to look like the left one.

**Comment by frodo4fingers** [comment]
...any progress on this issue? o.O

**Comment by 2xB** [comment]
@frodo4fingers I personally did not follow this further, as I could not reproduce it locally with PyQt5, so if you are interested to work on this, feel free to do so!

To help whomever wants to work on this: What is your output of `pyqtgraph.Qt.VERSION_INFO`? And which version of PyQtGraph are you using?

**Comment by j9ac9k** [comment]
So, ugh, 5 years later... (so sorry for the very late response) I'm not able to replicate this issue.  From the discussion earlier, there are hints this may have been a Qt specific issue, which wouldn't surprise me.  I checked with a current PySide6 binding and a PyQt5 binding on macOS and this worked just fine.

I'm going to close out the issue, but if it can still be replicated with the currently supported bindings, I'll reopen.

For documentation sake, here is the test code I ran:

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtGui, QtCore

app = pg.mkQApp()

xs = range (3)
lo = [  99, 89, 109 ]
hi = [ 101, 91, 111 ]

win = pg.GraphicsLayoutWidget()

plot = win.addPlot (title = "No fill")
plot.setLogMode (x = False, y = True)
plot.plot (x = xs, y = lo)
plot.plot (x = xs, y = hi)

plot = win.addPlot (title = "With fill")
plot.setLogMode (x = False, y = True)
lp = plot.plot (x = xs, y = lo)
hp = plot.plot (x = xs, y = hi)
plot.addItem (pg.FillBetweenItem (lp, hp))


win.show()

if __name__ == "__main__":
	pg.exec()
```
