### ISSUE TITLE
Store images of failed tests

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#878]
When analyzing a test failure, it would be useful to know what the window/display was actually showing.  This is troublesome on head-less systems such as CI services, as we have no direct access to the display, and thus cannot see what things looked like.

A good way to handle this is to use our CI `artifacts` capability, where we generate a file, that is effectively a screenshot, and make that file available for review at a later time.

Here are some links to documentation for making use of artifacts for our CI systems:

[Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
[Travis CI](https://docs.travis-ci.com/user/uploading-artifacts/)

**Comment by 2xB** [comment]
Are you maybe speaking of https://github.com/pyqtgraph/pyqtgraph/blob/3d3d0a24590a59097b6906d34b7a43d54305368d/pyqtgraph/tests/image_testing.py#L284?

That already uploads failed tests to data.pyqtgraph.org, links are posted in the test logs, e.g. on Travis:
https://travis-ci.org/pyqtgraph/pyqtgraph/jobs/536018688#L1418

**Comment by 2xB** [comment]
(Line 1418 in the exemplary Travis log - the link anchor does not work)

**Comment by j9ac9k** [comment]
Good catch, I was relaying what we were discussing with @campagnola on slack here... regardless, we probably don't want to send this data off to `data.pyqtgraph.org` but ideally hold it with the test logs if possible (not sure Travis or Azure pipelines will let us do that though)

**Comment by campagnola** [comment]
Huh! I have no memory of implementing this :D

In any case, +1 for having azure serve up the test images instead of data.pyqtgraph.org.

**Comment by campagnola** [comment]
@2xB if you'd like to join us on slack, please message me at luke.campagnola@gmail.com

**Comment by j9ac9k** [comment]
Looks like azure-pipelines has just the thing for storing screenshots, logs, etc:

https://docs.microsoft.com/en-us/azure/devops/test/collect-screenshots-and-video?view=azure-devops

**Comment by hhslepicka** [comment]
@j9ac9k You could make a fixture for the tests to always take a screenshot and dump it to a particular folder.
Saving a folder with Azure is trivial with the `Publish Build Artifacts task` https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops

You can even save the logs, core dumps & etc in the same... call it test output or so and upload...
I believe that you can hold up to 30 days of artifacts... there is an option that you can configure at the Pipeline setup for retention.

**Comment by j9ac9k** [comment]
This is implemented with #903
