### ISSUE TITLE
[CI-fail] python3.7 issues deprecation warning for collections.abc

### ISSUE THREAD

**Issue by RobertHenry6bev** [pyqtgraph/pyqtgraph#885]
running python3.7 on

https://github.com/pyqtgraph/pyqtgraph/blob/20c74954a5a18ee37958383e0d4e5c4769bd98e5/pyqtgraph/pgcollections.py#L329
generates a warning message 
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

See https://docs.python.org/3/library/collections.abc.html

**Comment by ixjlyons** [comment]
For some reason, I don't actually see a warning when I import from the `pgcollections` module with Python 3.7.3, but I do if I try to use `collections.Sequence` myself:

```
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import Sequence
__main__:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
>>> from pyqtgraph.pgcollections import ProtectedList
>>>
```

Even stranger:

```
Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyqtgraph.pgcollections import ProtectedList
>>> from collections import Sequence
>>>
```

pyqtgraph must have an import side effect I haven't come across before. Regardless, I submitted a PR that fixes this (and a couple other uses of ABCs from `collections`) in a backwards compatible way.
