### ISSUE TITLE
GraphicsWindow parameters not documented

### ISSUE THREAD

**Issue by sguillia** [pyqtgraph/pyqtgraph#916]
`GraphicsWindow.__init__` accepts the following parameters:
- title
- size
- Those of [`GraphicsLayout`](http://www.pyqtgraph.org/documentation/graphicsItems/graphicslayout.html)

The two first ones seem to be undocumented.

Source code is here:
https://github.com/pyqtgraph/pyqtgraph/blob/a838e0267fc7480d01f2ce73e051c0a3835cb33b/pyqtgraph/graphicsWindows.py#L24

A code example of `GraphicsWindow` is here:
http://www.pyqtgraph.org/documentation/how_to_use.html

As a new pyqtgraph user, I was expecting to find GraphicsWindow in this list:
http://www.pyqtgraph.org/documentation/graphicsItems/index.html

Are GraphicsWindow title and size documented anywhere?

Thank you

**Comment by j9ac9k** [comment]
@sguillia no doubt our documentation has come out of date; I must admit that with my own uses of pyqtgraph, I often look at the source code and make my way from there; which is not the way it should be.

If you want to make a PR we'll look it over, but updating documentation will probably be one of the last steps we do before the next stable release.

**Comment by ixjlyons** [comment]
`GraphicsWindow` is now included in the API reference: https://pyqtgraph.readthedocs.io/en/latest/graphicswindow.html

Although the arguments are still not documented, the class is deprecated and there's a notice to use `GraphicsLayoutWidget` instead. Its arguments *are* documented: https://pyqtgraph.readthedocs.io/en/latest/widgets/graphicslayoutwidget.html
