### ISSUE TITLE
[proposal] Make legend more customizable

### ISSUE THREAD

**Issue by SamSchott** [pyqtgraph/pyqtgraph#923]
This may be a starting point afc50388f1fa359ea0af52faeb5d4f1264d515f9:

- Give options for legend frame and background colors instead of hard-coded values.
- Reduce spacing for more compact legend
- Give separate option `labelTextColor`.
- New method to clear all legend items.
- New methods to get and change `offset` relative to the legend's parent.
- Horizontal instead of tilted lines for legend pictures (also fixes #578).

An example of how the modified legend will look like from [keithleygui](https://github.com/OE-FET/keithleygui): 

![keithleygui screenshot](https://github.com/OE-FET/keithleygui/blob/master/screenshots/KeithleyGUI.png?raw=true)

**Comment by 2xB** [comment]
Part of your suggestions are already implemented in Pull Request #64, if you have time, trying it out and reviewing it would be great!
Also: Thanks for this interesting proposal!

**Comment by SamSchott** [comment]
I had not seen that, but it does seem to overlap. I'll look into it.

**Comment by SamSchott** [comment]
I just tested the changes from #64. I especially like the proposed way of controlling the legend layout and added them to my own branch [here](https://doc.qt.io/qt-5/qgraphicsgridlayout.html#rowCount). 

Two issues that I have with #64:

- Instead of adding a boolean parameter `box` to control if a box is drawn, I still prefer actually choosing a pen and brush for the legend (and possibly setting them to `None`). Especially when choosing a white background in the general settings, having a black legend by default seems to be a bad idea.

- Some of the proposed changes regarding the insertion and removal of items seem to address problems that do not exist (anymore?). Or maybe I am missing something...

**Comment by 2xB** [comment]
Btw. issue #579 also asks for customizable background color.

**Comment by SamSchott** [comment]
I agree with #579. I have opened a pull request now (#958) which defaults to having a transparent background, but one could possibly also default to using the global background color (i.e., black or white). In any case, there should be an option for the user to customize this without needing to subclass `LegendItem`.

**Comment by SamSchott** [comment]
Any updates on this?

**Comment by j9ac9k** [comment]
Hi @SamSchott sorry it's taken us so long to get to this.  I just merged #958 thank you for your contribution.  I'm going to go through other relevant issues and PRs and close them as well to try and tidy things up.
