### ISSUE TITLE
[CI-Warning] Divide by zero encountered in double_scalars

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#926]
Our CI generates the following output:

```
pyqtgraph/functions.py:1108
  /home/vsts/work/1/s/pyqtgraph/functions.py:1108: RuntimeWarning: divide by zero encountered in double_scalars
    data = rescaleData(data, scale/(maxVal-minVal), minVal, dtype=dtype)
```

While the CI system doesn't show it (it should), i think this error occurs during the `test_nan_image` and you can recreate this warning by running `pytest . -sv -k "test_nan_image"`

**Comment by ixjlyons** [comment]
Resolved by #955
