### ISSUE TITLE
GraphicsWindow may be garbage collected too early

### ISSUE THREAD

**Issue by 2xB** [pyqtgraph/pyqtgraph#936]
Consider the following code:

```python3
import pyqtgraph as pg

def plot():
    pg.GraphicsWindow()

plot()

pg.QtGui.QApplication.exec_()
```
I would expect a GraphicsWindow to show up, but it does not. It does when preventing garbage collection:

```python3
import pyqtgraph as pg

def plot():
    return pg.GraphicsWindow()

a = plot()

pg.QtGui.QApplication.exec_()
```

So there is an issue with garbage collection of GraphicsWindows.

**Comment by flutefreak7** [comment]
I've come to expect this behavior with Qt... I even sometimes keep a module-level list outside of any functions to hold any persistent windows, that way I don't have to always return them. This is less problematic when using classes where you typically make UI objects an instance attribute of the class, so the reference lives as long as the instance does.

**Comment by j9ac9k** [comment]
Right, this is a byproduct of the Qt event loop, I'm reluctant to try and manipulate how the garbage collector does things, as if stopped doing its thing, it would create far more massive head aches.

I would certainly entertain any suggested solutions though.

**Comment by ixjlyons** [comment]
Example to show this isn't specific to `GraphicsWindow` or pyqtgraph:

```python
from PyQt5 import QtWidgets

app = QtWidgets.QApplication([])

def make_window():
    win = QtWidgets.QMainWindow()
    win.show()
    return win # comment out to compare

win = make_window()
app.exec_()
```

**Comment by 2xB** [comment]
Thank you for the remarks, you have a good point. So we could of course store references to open widgets in arrays, but as pyqtgraph is intended to extend Qts Widget zoo, using the common PyQt behaviour seems reasonable enough to not call it a bug.

The linked pull request shows a RuntimeWarning if visible GraphicsViews are garbage collected, so users can quickly understand the problem.
