### ISSUE TITLE
[CI-fail] macOS all GL-related examples fail on Python 2.7/Qt4

### ISSUE THREAD

**Issue by j9ac9k** [pyqtgraph/pyqtgraph#939]
on macOS, the following examples fail when running on Python 2.7/Qt4

```
GLImageItem.py
GLVolumeItem.py
GLIsosurface.py
GLLinePlotItem.py
GLScatterPlotItem.py
GLshaders.py
GLMeshItem.py
GLSurfacePlot.py
```

These failures can be reproduced locally using `tox`, and while I have tested more configurations than the CI build, the failures only occur when when using Qt4 bindings with a Python 2.7 environment.

**Comment by j9ac9k** [comment]
Saw this stackoverflow post, it may help mandate using OpenGL 3.2 on macOS (instead of 2.1)

https://stackoverflow.com/questions/19658745/why-is-my-opengl-version-always-2-1-on-mac-os-x

**Comment by j9ac9k** [comment]
Looks like vispy folks ran into the same issue (no postedd fix unfortunately)

https://github.com/vispy/vispy/issues/1290

**Comment by j9ac9k** [comment]
After talking w/ some of the `vispy` folks, they decided not to fix due to deprecating Py2/Qt4 support so this became a non-issue for them.

Should we consider skipping these tests on our CI system, and adding something in the documentation about not supporting that configuration?

**Comment by campagnola** [comment]
Fine by me! I think this has been going on for a long time, so it's unlikely that we're "abandoning" many OSX users by declining to chase this bug further. Maybe add a table of known working / broken configurations in the README?

**Comment by j9ac9k** [comment]
> Fine by me! I think this has been going on for a long time, so it's unlikely that we're "abandoning" many OSX users by declining to chase this bug further. Maybe add a table of known working / broken configurations in the README?

We sort of have that already (by the chart of tested configurations); what we don't explicitly talk about is OpenGL stuff... as you point out, this is nothing new.

I should also add (probably not directly related to this issue) that when I upped the azure pipeline version to macOS 10.14, some of the openGL tests were causing segmentation faults; you can see this build log:

https://dev.azure.com/j9ac9k/pyqtgraph-fork/_build/results?buildId=214

**Comment by j9ac9k** [comment]
Made a PR:  https://github.com/pyqtgraph/pyqtgraph/pull/966

**Comment by j9ac9k** [comment]
Closing with the merging of #966
