### ISSUE TITLE
Enable `autoProxy` by default in multiprocess

### ISSUE THREAD

**Issue by campagnola** [pyqtgraph/pyqtgraph#97]
This would simplify many situations (but possibly break others, so implement with care). See:
http://stackoverflow.com/questions/25691748/pyqtgraph-remotegraphicsview-and-connecting-signals/25693270#25693270

**Comment by Dschoni** [comment]
@campagnola Do you have anything particular in mind, that could be broken by setting `autoProxy` as a default?

**Comment by campagnola** [comment]
It just changes the default behavior, which is bound to break something. I'd rather just leave it as-is.
