### ISSUE TITLE
GL examples not drawn on CI

### ISSUE THREAD

**Issue by 2xB** [pyqtgraph/pyqtgraph#983]
### Short description
For the OpenGL examples, seemingly no image is drawn on platforms other than Linux and - randomly - Mac.

### Code to reproduce
This commit raises a RuntimeError every time `GLViewWidget.paintGL` is called: https://github.com/pyqtgraph/pyqtgraph/pull/982/commits/f253f3ba056efdad8260340e159c1fd392c9cb3e It therefore allows to investigate when `paintGL` was run.

### Expected behavior
All environments in the CI should fail as for all environments the `GLViewWidget` should be drawn

### Real behavior
Only the Linux environments fail: https://github.com/pyqtgraph/pyqtgraph/runs/161985164

### Tested environment(s)

 * Azure CI

### Additional context
This was noticed as part of investigations to #967.

**Comment by j9ac9k** [comment]
A good suggestion might be to try and grab a screenshot.  If you save to the location of `$SCREENSHOT_DIR` then the screenshot will be uploaded as an artifact that you can review later.

**Comment by j9ac9k** [comment]
if PR #1131 is merged, this issue can be closed out I believe (along with #982)

While testing the new macOS image (10.15) on azure pipelines, I have not run into this issue.

**Comment by j9ac9k** [comment]
Since we merged #1131 we can close this one out!
