### ISSUE TITLE
Add Axis features (labels, ticks, values) to a GLViewWidget with GLAxisItem?

### ISSUE THREAD

**Issue by luiztauffer** [pyqtgraph/pyqtgraph#984]
I want to add axis features such as labels, ticks and values to a 3D scene created with the GLViewWidget module. The GLAxisItem option can only control the length of the axes.
I've extended GLAxisItem to change the axis color, but can't see the way to include these other features. It would be perfect if they didn't change size with zooming.

Here's an example:
```python
from pyqtgraph.Qt import QtCore, QtGui
import pyqtgraph.opengl as gl
import pyqtgraph as pg
import OpenGL.GL as ogl
import numpy as np

class Custom3DAxis(gl.GLAxisItem):
    """Class defined to extend 'gl.GLAxisItem'."""
    def __init__(self, color=(0,0,0,.6)):
        gl.GLAxisItem.__init__(self)
        self.c = color

    def paint(self):
        self.setupGLState()
        if self.antialias:
            ogl.glEnable(ogl.GL_LINE_SMOOTH)
            ogl.glHint(ogl.GL_LINE_SMOOTH_HINT, ogl.GL_NICEST)
        ogl.glBegin(ogl.GL_LINES)

        x,y,z = self.size()
        ogl.glColor4f(self.c[0], self.c[1], self.c[2], self.c[3]) 
        ogl.glVertex3f(0, 0, 0)
        ogl.glVertex3f(0, 0, z)

        ogl.glColor4f(self.c[0], self.c[1], self.c[2], self.c[3])
        ogl.glVertex3f(0, 0, 0)
        ogl.glVertex3f(0, y, 0)

        ogl.glColor4f(self.c[0], self.c[1], self.c[2], self.c[3])
        ogl.glVertex3f(0, 0, 0)
        ogl.glVertex3f(x, 0, 0)
        ogl.glEnd()


app = QtGui.QApplication([])
fig1 = gl.GLViewWidget()
background_color = app.palette().color(QtGui.QPalette.Background)
fig1.setBackgroundColor(background_color)

n = 51
y = np.linspace(-10,10,n)
x = np.linspace(-10,10,100)
for i in range(n):
    yi = np.array([y[i]]*100)
    d = (x**2 + yi**2)**0.5
    z = 10 * np.cos(d) / (d+1)
    pts = np.vstack([x,yi,z]).transpose()
    plt = gl.GLLinePlotItem(pos=pts, color=pg.glColor((i,n*1.3)), width=(i+1)/10., antialias=True)
    fig1.addItem(plt)

axis = Custom3DAxis(color=(0.2,0.2,0.2,.6))
axis.setSize(x=12, y=12, z=12)
fig1.addItem(axis)
fig1.opts['distance'] = 40
fig1.show()

if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()
```

Is this feature anywhere in your roadmap horizon? Or else, how would you suggest me to go about and create these myself?
Thank you for pyqtgraph, I really love the package and am using it a lot these days!

**Comment by luiztauffer** [comment]
I found a workaround and posted it [here](https://stackoverflow.com/questions/56890547/how-to-add-axis-features-labels-ticks-values-to-a-3d-plot-with-glviewwidget), in case anyone needs to do it before a proper extension comes.

**Comment by j9ac9k** [comment]
@luiztauffer we're talking internally about deprecating the openGL components of pyqtgraph in future versions (0.11 (which will be released soon) will have the openGL components), and attempt to integrate vispy in its place.  Because of the upcoming deprecation, I doubt we'll integrate something like this ourselves; but if a PR was submitted for this feature, we would certainly look it over.

**Comment by luiztauffer** [comment]
well, if it will be deprecated anyway, I don't see the point of working on a PR. Well, at least a partial solution is available for anyone who might be in need of it! I'll close the issue.
