### ISSUE TITLE
HistogramLUTItem should support multiple orientations

### ISSUE THREAD

**Issue by bks** [pyqtgraph/pyqtgraph#99]
Right now, `HistogramLUTItem` really only makes sense to put on the right edge of a layout. It would be really nice if `HistogramLUTItem.__init__()` took an orientation parameter (i.e., `'left'`, `'right'`, `'top'`, `'bottom'`; default to `'right'`) that made it have a layout appropriate for docking to that side of an image.

My use case is that my images are short and wide; I'd really like to put the histogram beneath them to
more efficiently use screen space.

**Comment by mysterylektro** [comment]
I am running into this need as well.
