### ISSUE TITLE
pyqtGraph meet invalid enumerant GLError on Raspberry pi 4

### ISSUE THREAD

**Issue by pointcloudAI** [pyqtgraph/pyqtgraph#993]
### Short description
All pyqtgraph.examples related 3D meet GLError on Raspberry pi 4

### Code to reproduce

```python
import PySide2
import pyqtgraph.examples
pyqtgraph.examples.run()
```

### Expected behavior

The Scatter Plot example can run normally.

### Real behavior
Meet 1280 GLError .
```
qt5ct: using qt5ct plugin
Using PySide2 (default graphics system)
qt5ct: using qt5ct plugin
b'OpenGL ES 3.0 Mesa 19.1.0-devel'
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 60, in addItem
    item.initializeGL()
  File "/home/pi/.local/lib/python3.7/site-packages/pyqtgraph/opengl/items/GLScatterPlotItem.py", line 72, in initializeGL
    glEnable(GL_TEXTURE_2D)
  File "/home/pi/.local/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/pi/.local/lib/python3.7/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1280,
	description = b'invalid enumerant',
	baseOperation = glEnable,
	cArguments = (GL_TEXTURE_2D,)
)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/pyqtgraph/examples/GLScatterPlotItem.py", line 46, in <module>
    w.addItem(sp1)
  File "/home/pi/.local/lib/python3.7/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 62, in addItem
    self.checkOpenGLVersion('Error while adding item %s to GLViewWidget.' % str(item))
  File "/home/pi/.local/lib/python3.7/site-packages/pyqtgraph/opengl/GLViewWidget.py", line 431, in checkOpenGLVersion
    if int(ver.split('.')[0]) < 2:
TypeError: a bytes-like object is required, not 'str'
```

### Tested environment(s)

 * PyQtGraph version:  0.11.0.dev0+gad7453c
 * Qt Python binding:  PySide2 5.11.2 Qt 5.11.3
 * Python version:  3.7.3
 * NumPy version:  N/A
 * Operating system:   Raspbian Buster with desktop (Debian Buster for Raspberry pi 4)
 * Installation method: 
pip3 install git+https://github.com/pyqtgraph/pyqtgraph@develop

### Additional context

pi@raspberrypi:~ $ glxinfo | grep -i opengl
OpenGL vendor string: Broadcom
OpenGL renderer string: V3D 4.2
OpenGL version string: 2.1 Mesa 19.1.0-devel
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 19.1.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

Raspbian Buster has now been released and Pyside2 can be installed using:
$apt-get install python3-pyside2.qt3dcore python3-pyside2.qt3dinput python3-pyside2.qt3dlogic python3-pyside2.qt3drender python3-pyside2.qtcharts python3-pyside2.qtconcurrent python3-pyside2.qtcore python3-pyside2.qtgui python3-pyside2.qthelp python3-pyside2.qtlocation python3-pyside2.qtmultimedia python3-pyside2.qtmultimediawidgets python3-pyside2.qtnetwork python3-pyside2.qtopengl python3-pyside2.qtpositioning python3-pyside2.qtprintsupport python3-pyside2.qtqml python3-pyside2.qtquick python3-pyside2.qtquickwidgets python3-pyside2.qtscript python3-pyside2.qtscripttools python3-pyside2.qtsensors python3-pyside2.qtsql python3-pyside2.qtsvg python3-pyside2.qttest python3-pyside2.qttexttospeech python3-pyside2.qtuitools python3-pyside2.qtwebchannel python3-pyside2.qtwebsockets python3-pyside2.qtwidgets python3-pyside2.qtx11extras python3-pyside2.qtxml python3-pyside2.qtxmlpatterns python3-pyside2uic

**Comment by pointcloudAI** [comment]
glEnable and glDisable are still present in GLES 2, but a lot of boolean states are deprecated or even removed (for instance, GL_TEXTURE_2D or GL_ALPHA_TEST).

According to the manual page, the following boolean states can still be enabled or disabled using these functions:

GL_BLEND
GL_CULL_FACE
GL_DEPTH_TEST
GL_DITHER
GL_POLYGON_OFFSET_FILL
GL_SAMPLE_ALPHA_TO_COVERAGE
GL_SAMPLE_COVERAGE
GL_SCISSOR_TEST
GL_STENCIL_TEST

**Comment by pointcloudAI** [comment]
For pyqtgraph.opengl.GLViewWidget   , How to set it to use  OPENGL 2.1  to replace  OpenGL ES 3.0?

**Comment by 2xB** [comment]
> glEnable and glDisable are still present in GLES 2 [...]

This is a quote from https://gamedev.stackexchange.com/a/20660.

(Just a note for the sake of context)

**Comment by 2xB** [comment]
Further information: PyQtGraph uses PyOpenGL and Qts QtOpenGl module. I am not aware of any possibility to constrain those libraries to using a specific OpenGL version. If someone knows or finds out more, it would be great to know!

**Comment by j9ac9k** [comment]
I'm going to close this issue as I think a fix here is outside the scope of pyqtgraph, and in-line with pyopengl library.  If you feel the issue should remain open for whatever reason feel free to post.

**Comment by Aknifejackzhmolong** [comment]
Is it resolve? I meet the same problem!!
